Using MAPPING_STR=20202020, VERSION_DIR=v4
Running /platform/source/s01/v4/m20202020/m20202020_q10_t0.sh
Running /platform/source/s01/v4/m20202020/m20202020_q11_t0.sh
0% [Working]            Hit:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease
0% [Working]0% [Waiting for headers]                        Hit:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease
                        0% [Working]0% [Waiting for headers]                        Hit:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease
                        0% [Working]0% [Waiting for headers]                        Hit:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease
                        0% [Working]20% [Working]             Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Building dependency tree... 0%Building dependency tree... 0%Building dependency tree... 50%Building dependency tree... 50%Building dependency tree       
Reading state information... 0%Reading state information... 0%Reading state information... Done
python3 is already the newest version (3.8.2-0ubuntu2).
python3 set to manually installed.
python3-pip is already the newest version (20.0.2-5ubuntu1.10).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: direct-redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct-redis) (3.4.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4/m20202020/m20202020_q12_t0.sh
/platform/source/s01/v4/m20202020/m20202020_q12_t0.sh: line 5: sudo: command not found
/platform/source/s01/v4/m20202020/m20202020_q12_t0.sh: line 6: sudo: command not found
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4/m20202020/m20202020_q13_t0.sh
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4/m20202020/m20202020_q14_t0.sh
Running /platform/source/s01/v4/m20202020/m20202020_q15_t0.sh
/platform/source/s01/v4/m20202020/m20202020_q15_t0.sh: line 5: sudo: command not found
/platform/source/s01/v4/m20202020/m20202020_q15_t0.sh: line 8: sudo: command not found
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Running /platform/source/s01/v4/m20202020/m20202020_q16_t0.sh
0% [Working]            Hit:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease
0% [Working]0% [Waiting for headers]                        Hit:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease
                        0% [Working]0% [Waiting for headers]                        Hit:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease
                        0% [Working]0% [Waiting for headers]                        Hit:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease
                        0% [Working]20% [Working]             Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Building dependency tree... 0%Building dependency tree... 0%Building dependency tree... 50%Building dependency tree... 50%Building dependency tree       
Reading state information... 0%Reading state information... 0%Reading state information... Done
python3 is already the newest version (3.8.2-0ubuntu2).
python3-pip is already the newest version (20.0.2-5ubuntu1.10).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: redis in /usr/local/lib/python3.8/dist-packages (3.4.1)
Requirement already satisfied: direct-redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4/m20202020/m20202020_q17_t0.sh
0% [Working]            Hit:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease
0% [Working]0% [Waiting for headers]                        Hit:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease
                        0% [Working]0% [Waiting for headers]                        Hit:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease
0% [Waiting for headers]0% [Waiting for headers]                        Hit:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease
                        0% [Working]20% [Working]             Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Building dependency tree... 0%Building dependency tree... 0%Building dependency tree... 50%Building dependency tree... 50%Building dependency tree       
Reading state information... 0%Reading state information... 0%Reading state information... Done
python3 is already the newest version (3.8.2-0ubuntu2).
python3-pip is already the newest version (20.0.2-5ubuntu1.10).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: redis in /usr/local/lib/python3.8/dist-packages (3.4.1)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4/m20202020/m20202020_q18_t0.sh
/platform/source/s01/v4/m20202020/m20202020_q18_t0.sh: line 5: sudo: command not found
/platform/source/s01/v4/m20202020/m20202020_q18_t0.sh: line 8: sudo: command not found
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: direct-redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct-redis) (3.4.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4/m20202020/m20202020_q19_t0.sh
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: redis in /usr/local/lib/python3.8/dist-packages (3.4.1)
Requirement already satisfied: direct-redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4/m20202020/m20202020_q1_t0.sh
/platform/source/s01/v4/m20202020/m20202020_q1_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4/m20202020/m20202020_q1_t0.sh: line 7: sudo: command not found
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Running /platform/source/s01/v4/m20202020/m20202020_q20_t0.sh
/platform/source/s01/v4/m20202020/m20202020_q20_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4/m20202020/m20202020_q20_t0.sh: line 7: sudo: command not found
Collecting pip
  Downloading pip-23.3.1-py3-none-any.whl (2.1 MB)
[?25l[K     |▏                               | 10 kB 12.3 MB/s eta 0:00:01[K     |▎                               | 20 kB 7.4 MB/s eta 0:00:01[K     |▌                               | 30 kB 10.9 MB/s eta 0:00:01[K     |▋                               | 40 kB 4.4 MB/s eta 0:00:01[K     |▊                               | 51 kB 4.7 MB/s eta 0:00:01[K     |█                               | 61 kB 5.6 MB/s eta 0:00:01[K     |█                               | 71 kB 5.3 MB/s eta 0:00:01[K     |█▎                              | 81 kB 6.0 MB/s eta 0:00:01[K     |█▍                              | 92 kB 6.2 MB/s eta 0:00:01[K     |█▌                              | 102 kB 6.7 MB/s eta 0:00:01[K     |█▊                              | 112 kB 6.7 MB/s eta 0:00:01[K     |█▉                              | 122 kB 6.7 MB/s eta 0:00:01[K     |██                              | 133 kB 6.7 MB/s eta 0:00:01[K     |██▏                             | 143 kB 6.7 MB/s eta 0:00:01[K     |██▎                             | 153 kB 6.7 MB/s eta 0:00:01[K     |██▌                             | 163 kB 6.7 MB/s eta 0:00:01[K     |██▋                             | 174 kB 6.7 MB/s eta 0:00:01[K     |██▉                             | 184 kB 6.7 MB/s eta 0:00:01[K     |███                             | 194 kB 6.7 MB/s eta 0:00:01[K     |███                             | 204 kB 6.7 MB/s eta 0:00:01[K     |███▎                            | 215 kB 6.7 MB/s eta 0:00:01[K     |███▍                            | 225 kB 6.7 MB/s eta 0:00:01[K     |███▋                            | 235 kB 6.7 MB/s eta 0:00:01[K     |███▊                            | 245 kB 6.7 MB/s eta 0:00:01[K     |███▉                            | 256 kB 6.7 MB/s eta 0:00:01[K     |████                            | 266 kB 6.7 MB/s eta 0:00:01[K     |████▏                           | 276 kB 6.7 MB/s eta 0:00:01[K     |████▍                           | 286 kB 6.7 MB/s eta 0:00:01[K     |████▌                           | 296 kB 6.7 MB/s eta 0:00:01[K     |████▋                           | 307 kB 6.7 MB/s eta 0:00:01[K     |████▉                           | 317 kB 6.7 MB/s eta 0:00:01[K     |█████                           | 327 kB 6.7 MB/s eta 0:00:01[K     |█████▏                          | 337 kB 6.7 MB/s eta 0:00:01[K     |█████▎                          | 348 kB 6.7 MB/s eta 0:00:01[K     |█████▍                          | 358 kB 6.7 MB/s eta 0:00:01[K     |█████▋                          | 368 kB 6.7 MB/s eta 0:00:01[K     |█████▊                          | 378 kB 6.7 MB/s eta 0:00:01[K     |██████                          | 389 kB 6.7 MB/s eta 0:00:01[K     |██████                          | 399 kB 6.7 MB/s eta 0:00:01[K     |██████▏                         | 409 kB 6.7 MB/s eta 0:00:01[K     |██████▍                         | 419 kB 6.7 MB/s eta 0:00:01[K     |██████▌                         | 430 kB 6.7 MB/s eta 0:00:01[K     |██████▊                         | 440 kB 6.7 MB/s eta 0:00:01[K     |██████▉                         | 450 kB 6.7 MB/s eta 0:00:01[K     |███████                         | 460 kB 6.7 MB/s eta 0:00:01[K     |███████▏                        | 471 kB 6.7 MB/s eta 0:00:01[K     |███████▎                        | 481 kB 6.7 MB/s eta 0:00:01[K     |███████▌                        | 491 kB 6.7 MB/s eta 0:00:01[K     |███████▋                        | 501 kB 6.7 MB/s eta 0:00:01[K     |███████▊                        | 512 kB 6.7 MB/s eta 0:00:01[K     |████████                        | 522 kB 6.7 MB/s eta 0:00:01[K     |████████                        | 532 kB 6.7 MB/s eta 0:00:01[K     |████████▎                       | 542 kB 6.7 MB/s eta 0:00:01[K     |████████▍                       | 552 kB 6.7 MB/s eta 0:00:01[K     |████████▌                       | 563 kB 6.7 MB/s eta 0:00:01[K     |████████▊                       | 573 kB 6.7 MB/s eta 0:00:01[K     |████████▉                       | 583 kB 6.7 MB/s eta 0:00:01[K     |█████████                       | 593 kB 6.7 MB/s eta 0:00:01[K     |█████████▏                      | 604 kB 6.7 MB/s eta 0:00:01[K     |█████████▎                      | 614 kB 6.7 MB/s eta 0:00:01[K     |█████████▌                      | 624 kB 6.7 MB/s eta 0:00:01[K     |█████████▋                      | 634 kB 6.7 MB/s eta 0:00:01[K     |█████████▉                      | 645 kB 6.7 MB/s eta 0:00:01[K     |██████████                      | 655 kB 6.7 MB/s eta 0:00:01[K     |██████████                      | 665 kB 6.7 MB/s eta 0:00:01[K     |██████████▎                     | 675 kB 6.7 MB/s eta 0:00:01[K     |██████████▍                     | 686 kB 6.7 MB/s eta 0:00:01[K     |██████████▋                     | 696 kB 6.7 MB/s eta 0:00:01[K     |██████████▊                     | 706 kB 6.7 MB/s eta 0:00:01[K     |██████████▉                     | 716 kB 6.7 MB/s eta 0:00:01[K     |███████████                     | 727 kB 6.7 MB/s eta 0:00:01[K     |███████████▏                    | 737 kB 6.7 MB/s eta 0:00:01[K     |███████████▍                    | 747 kB 6.7 MB/s eta 0:00:01[K     |███████████▌                    | 757 kB 6.7 MB/s eta 0:00:01[K     |███████████▋                    | 768 kB 6.7 MB/s eta 0:00:01[K     |███████████▉                    | 778 kB 6.7 MB/s eta 0:00:01[K     |████████████                    | 788 kB 6.7 MB/s eta 0:00:01[K     |████████████▏                   | 798 kB 6.7 MB/s eta 0:00:01[K     |████████████▎                   | 808 kB 6.7 MB/s eta 0:00:01[K     |████████████▍                   | 819 kB 6.7 MB/s eta 0:00:01[K     |████████████▋                   | 829 kB 6.7 MB/s eta 0:00:01[K     |████████████▊                   | 839 kB 6.7 MB/s eta 0:00:01[K     |█████████████                   | 849 kB 6.7 MB/s eta 0:00:01[K     |█████████████                   | 860 kB 6.7 MB/s eta 0:00:01[K     |█████████████▏                  | 870 kB 6.7 MB/s eta 0:00:01[K     |█████████████▍                  | 880 kB 6.7 MB/s eta 0:00:01[K     |█████████████▌                  | 890 kB 6.7 MB/s eta 0:00:01[K     |█████████████▊                  | 901 kB 6.7 MB/s eta 0:00:01[K     |█████████████▉                  | 911 kB 6.7 MB/s eta 0:00:01[K     |██████████████                  | 921 kB 6.7 MB/s eta 0:00:01[K     |██████████████▏                 | 931 kB 6.7 MB/s eta 0:00:01[K     |██████████████▎                 | 942 kB 6.7 MB/s eta 0:00:01[K     |██████████████▌                 | 952 kB 6.7 MB/s eta 0:00:01[K     |██████████████▋                 | 962 kB 6.7 MB/s eta 0:00:01[K     |██████████████▊                 | 972 kB 6.7 MB/s eta 0:00:01[K     |███████████████                 | 983 kB 6.7 MB/s eta 0:00:01[K     |███████████████                 | 993 kB 6.7 MB/s eta 0:00:01[K     |███████████████▎                | 1.0 MB 6.7 MB/s eta 0:00:01[K     |███████████████▍                | 1.0 MB 6.7 MB/s eta 0:00:01[K     |███████████████▌                | 1.0 MB 6.7 MB/s eta 0:00:01[K     |███████████████▊                | 1.0 MB 6.7 MB/s eta 0:00:01[K     |███████████████▉                | 1.0 MB 6.7 MB/s eta 0:00:01[K     |████████████████                | 1.1 MB 6.7 MB/s eta 0:00:01[K     |████████████████▏               | 1.1 MB 6.7 MB/s eta 0:00:01[K     |████████████████▎               | 1.1 MB 6.7 MB/s eta 0:00:01[K     |████████████████▌               | 1.1 MB 6.7 MB/s eta 0:00:01[K     |████████████████▋               | 1.1 MB 6.7 MB/s eta 0:00:01[K     |████████████████▉               | 1.1 MB 6.7 MB/s eta 0:00:01[K     |█████████████████               | 1.1 MB 6.7 MB/s eta 0:00:01[K     |█████████████████               | 1.1 MB 6.7 MB/s eta 0:00:01[K     |█████████████████▎              | 1.1 MB 6.7 MB/s eta 0:00:01[K     |█████████████████▍              | 1.1 MB 6.7 MB/s eta 0:00:01[K     |█████████████████▋              | 1.2 MB 6.7 MB/s eta 0:00:01[K     |█████████████████▊              | 1.2 MB 6.7 MB/s eta 0:00:01[K     |█████████████████▉              | 1.2 MB 6.7 MB/s eta 0:00:01[K     |██████████████████              | 1.2 MB 6.7 MB/s eta 0:00:01[K     |██████████████████▏             | 1.2 MB 6.7 MB/s eta 0:00:01[K     |██████████████████▍             | 1.2 MB 6.7 MB/s eta 0:00:01[K     |██████████████████▌             | 1.2 MB 6.7 MB/s eta 0:00:01[K     |██████████████████▋             | 1.2 MB 6.7 MB/s eta 0:00:01[K     |██████████████████▉             | 1.2 MB 6.7 MB/s eta 0:00:01[K     |███████████████████             | 1.2 MB 6.7 MB/s eta 0:00:01[K     |███████████████████▏            | 1.3 MB 6.7 MB/s eta 0:00:01[K     |███████████████████▎            | 1.3 MB 6.7 MB/s eta 0:00:01[K     |███████████████████▍            | 1.3 MB 6.7 MB/s eta 0:00:01[K     |███████████████████▋            | 1.3 MB 6.7 MB/s eta 0:00:01[K     |███████████████████▊            | 1.3 MB 6.7 MB/s eta 0:00:01[K     |████████████████████            | 1.3 MB 6.7 MB/s eta 0:00:01[K     |████████████████████            | 1.3 MB 6.7 MB/s eta 0:00:01[K     |████████████████████▏           | 1.3 MB 6.7 MB/s eta 0:00:01[K     |████████████████████▍           | 1.3 MB 6.7 MB/s eta 0:00:01[K     |████████████████████▌           | 1.4 MB 6.7 MB/s eta 0:00:01[K     |████████████████████▊           | 1.4 MB 6.7 MB/s eta 0:00:01[K     |████████████████████▉           | 1.4 MB 6.7 MB/s eta 0:00:01[K     |█████████████████████           | 1.4 MB 6.7 MB/s eta 0:00:01[K     |█████████████████████▏          | 1.4 MB 6.7 MB/s eta 0:00:01[K     |█████████████████████▎          | 1.4 MB 6.7 MB/s eta 0:00:01[K     |█████████████████████▌          | 1.4 MB 6.7 MB/s eta 0:00:01[K     |█████████████████████▋          | 1.4 MB 6.7 MB/s eta 0:00:01[K     |█████████████████████▊          | 1.4 MB 6.7 MB/s eta 0:00:01[K     |██████████████████████          | 1.4 MB 6.7 MB/s eta 0:00:01[K     |██████████████████████          | 1.5 MB 6.7 MB/s eta 0:00:01[K     |██████████████████████▎         | 1.5 MB 6.7 MB/s eta 0:00:01[K     |██████████████████████▍         | 1.5 MB 6.7 MB/s eta 0:00:01[K     |██████████████████████▌         | 1.5 MB 6.7 MB/s eta 0:00:01[K     |██████████████████████▊         | 1.5 MB 6.7 MB/s eta 0:00:01[K     |██████████████████████▉         | 1.5 MB 6.7 MB/s eta 0:00:01[K     |███████████████████████         | 1.5 MB 6.7 MB/s eta 0:00:01[K     |███████████████████████▏        | 1.5 MB 6.7 MB/s eta 0:00:01[K     |███████████████████████▎        | 1.5 MB 6.7 MB/s eta 0:00:01[K     |███████████████████████▌        | 1.5 MB 6.7 MB/s eta 0:00:01[K     |███████████████████████▋        | 1.6 MB 6.7 MB/s eta 0:00:01[K     |███████████████████████▉        | 1.6 MB 6.7 MB/s eta 0:00:01[K     |████████████████████████        | 1.6 MB 6.7 MB/s eta 0:00:01[K     |████████████████████████        | 1.6 MB 6.7 MB/s eta 0:00:01[K     |████████████████████████▎       | 1.6 MB 6.7 MB/s eta 0:00:01[K     |████████████████████████▍       | 1.6 MB 6.7 MB/s eta 0:00:01[K     |████████████████████████▋       | 1.6 MB 6.7 MB/s eta 0:00:01[K     |████████████████████████▊       | 1.6 MB 6.7 MB/s eta 0:00:01[K     |████████████████████████▉       | 1.6 MB 6.7 MB/s eta 0:00:01[K     |█████████████████████████       | 1.6 MB 6.7 MB/s eta 0:00:01[K     |█████████████████████████▏      | 1.7 MB 6.7 MB/s eta 0:00:01[K     |█████████████████████████▍      | 1.7 MB 6.7 MB/s eta 0:00:01[K     |█████████████████████████▌      | 1.7 MB 6.7 MB/s eta 0:00:01[K     |█████████████████████████▋      | 1.7 MB 6.7 MB/s eta 0:00:01[K     |█████████████████████████▉      | 1.7 MB 6.7 MB/s eta 0:00:01[K     |██████████████████████████      | 1.7 MB 6.7 MB/s eta 0:00:01[K     |██████████████████████████▏     | 1.7 MB 6.7 MB/s eta 0:00:01[K     |██████████████████████████▎     | 1.7 MB 6.7 MB/s eta 0:00:01[K     |██████████████████████████▍     | 1.7 MB 6.7 MB/s eta 0:00:01[K     |██████████████████████████▋     | 1.8 MB 6.7 MB/s eta 0:00:01[K     |██████████████████████████▊     | 1.8 MB 6.7 MB/s eta 0:00:01[K     |███████████████████████████     | 1.8 MB 6.7 MB/s eta 0:00:01[K     |███████████████████████████     | 1.8 MB 6.7 MB/s eta 0:00:01[K     |███████████████████████████▏    | 1.8 MB 6.7 MB/s eta 0:00:01[K     |███████████████████████████▍    | 1.8 MB 6.7 MB/s eta 0:00:01[K     |███████████████████████████▌    | 1.8 MB 6.7 MB/s eta 0:00:01[K     |███████████████████████████▊    | 1.8 MB 6.7 MB/s eta 0:00:01[K     |███████████████████████████▉    | 1.8 MB 6.7 MB/s eta 0:00:01[K     |████████████████████████████    | 1.8 MB 6.7 MB/s eta 0:00:01[K     |████████████████████████████▏   | 1.9 MB 6.7 MB/s eta 0:00:01[K     |████████████████████████████▎   | 1.9 MB 6.7 MB/s eta 0:00:01[K     |████████████████████████████▌   | 1.9 MB 6.7 MB/s eta 0:00:01[K     |████████████████████████████▋   | 1.9 MB 6.7 MB/s eta 0:00:01[K     |████████████████████████████▊   | 1.9 MB 6.7 MB/s eta 0:00:01[K     |█████████████████████████████   | 1.9 MB 6.7 MB/s eta 0:00:01[K     |█████████████████████████████   | 1.9 MB 6.7 MB/s eta 0:00:01[K     |█████████████████████████████▎  | 1.9 MB 6.7 MB/s eta 0:00:01[K     |█████████████████████████████▍  | 1.9 MB 6.7 MB/s eta 0:00:01[K     |█████████████████████████████▌  | 1.9 MB 6.7 MB/s eta 0:00:01[K     |█████████████████████████████▊  | 2.0 MB 6.7 MB/s eta 0:00:01[K     |█████████████████████████████▉  | 2.0 MB 6.7 MB/s eta 0:00:01[K     |██████████████████████████████  | 2.0 MB 6.7 MB/s eta 0:00:01[K     |██████████████████████████████▏ | 2.0 MB 6.7 MB/s eta 0:00:01[K     |██████████████████████████████▎ | 2.0 MB 6.7 MB/s eta 0:00:01[K     |██████████████████████████████▌ | 2.0 MB 6.7 MB/s eta 0:00:01[K     |██████████████████████████████▋ | 2.0 MB 6.7 MB/s eta 0:00:01[K     |██████████████████████████████▉ | 2.0 MB 6.7 MB/s eta 0:00:01[K     |███████████████████████████████ | 2.0 MB 6.7 MB/s eta 0:00:01[K     |███████████████████████████████ | 2.0 MB 6.7 MB/s eta 0:00:01[K     |███████████████████████████████▎| 2.1 MB 6.7 MB/s eta 0:00:01[K     |███████████████████████████████▍| 2.1 MB 6.7 MB/s eta 0:00:01[K     |███████████████████████████████▋| 2.1 MB 6.7 MB/s eta 0:00:01[K     |███████████████████████████████▊| 2.1 MB 6.7 MB/s eta 0:00:01[K     |███████████████████████████████▉| 2.1 MB 6.7 MB/s eta 0:00:01[K     |████████████████████████████████| 2.1 MB 6.7 MB/s 
[?25hInstalling collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.0.2
    Not uninstalling pip at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'pip'. No files were found to uninstall.
Successfully installed pip-23.3.1
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: redis in /usr/local/lib/python3.8/dist-packages (3.4.1)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4/m20202020/m20202020_q21_t0.sh
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRequirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRequirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRunning /platform/source/s01/v4/m20202020/m20202020_q22_t0.sh
/platform/source/s01/v4/m20202020/m20202020_q22_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4/m20202020/m20202020_q22_t0.sh: line 7: sudo: command not found
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: direct-redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct-redis) (3.4.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRunning /platform/source/s01/v4/m20202020/m20202020_q2_t0.sh
/platform/source/s01/v4/m20202020/m20202020_q2_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4/m20202020/m20202020_q2_t0.sh: line 7: sudo: command not found
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mCollecting git+https://github.com/RedisLabs/direct_redis.git
  Cloning https://github.com/RedisLabs/direct_redis.git to /tmp/pip-req-build-n07xsxj0
[31m  ERROR: Error [Errno 2] No such file or directory: 'git' while executing command git version[0m[31m
[0m[31mERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?[0m[31m
[0mRunning /platform/source/s01/v4/m20202020/m20202020_q3_t0.sh
/platform/source/s01/v4/m20202020/m20202020_q3_t0.sh: line 3: sudo: command not found
/platform/source/s01/v4/m20202020/m20202020_q3_t0.sh: line 6: sudo: command not found
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRequirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRequirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRunning /platform/source/s01/v4/m20202020/m20202020_q4_t0.sh
/platform/source/s01/v4/m20202020/m20202020_q4_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4/m20202020/m20202020_q4_t0.sh: line 5: sudo: command not found
/platform/source/s01/v4/m20202020/m20202020_q4_t0.sh: line 8: sudo: command not found
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: direct-redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct-redis) (3.4.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRunning /platform/source/s01/v4/m20202020/m20202020_q5_t0.sh
/platform/source/s01/v4/m20202020/m20202020_q5_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4/m20202020/m20202020_q5_t0.sh: line 7: sudo: command not found
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRunning /platform/source/s01/v4/m20202020/m20202020_q6_t0.sh
0% [Working]            Hit:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease
0% [Working]0% [Waiting for headers]                        Hit:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease
                        0% [Working]0% [Waiting for headers]                        Hit:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease
                        0% [Working]0% [Waiting for headers]                        Hit:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease
                        0% [Working]20% [Working]             Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Building dependency tree... 0%Building dependency tree... 0%Building dependency tree... 50%Building dependency tree... 50%Building dependency tree       
Reading state information... 0%Reading state information... 0%Reading state information... Done
python3 is already the newest version (3.8.2-0ubuntu2).
python3-pip is already the newest version (20.0.2-5ubuntu1.10).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRunning /platform/source/s01/v4/m20202020/m20202020_q7_t0.sh
Running /platform/source/s01/v4/m20202020/m20202020_q8_t0.sh
/platform/source/s01/v4/m20202020/m20202020_q8_t0.sh: line 6: sudo: command not found
/platform/source/s01/v4/m20202020/m20202020_q8_t0.sh: line 9: sudo: command not found
/platform/source/s01/v4/m20202020/m20202020_q8_t0.sh: line 12: sudo: command not found
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: redis in /usr/local/lib/python3.8/dist-packages (3.4.1)
Collecting msgpack-python
  Downloading msgpack-python-0.5.6.tar.gz (138 kB)
[?25l     [90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━[0m [32m0.0/139.0 kB[0m [31m?[0m eta [36m-:--:--[0m[2K     [90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━[0m [32m139.0/139.0 kB[0m [31m6.4 MB/s[0m eta [36m0:00:00[0m
[?25h  Preparing metadata (setup.py) ... [?25l- done
[?25hRequirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Building wheels for collected packages: msgpack-python
  Building wheel for msgpack-python (setup.py) ... [?25l- \ | / - done
[?25h  Created wheel for msgpack-python: filename=msgpack_python-0.5.6-cp38-cp38-linux_aarch64.whl size=446758 sha256=2502648889acf8705593ab623037c4ddd228ffce34a5e8363439c5188c952ddf
  Stored in directory: /root/.cache/pip/wheels/03/7f/e7/8ec405fe5220fe1401be3dfa943f6e1f10b525f54f68d75e0a
Successfully built msgpack-python
Installing collected packages: msgpack-python
Successfully installed msgpack-python-0.5.6
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRunning /platform/source/s01/v4/m20202020/m20202020_q9_t0.sh
0% [Working]            Hit:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease
0% [Working]0% [Waiting for headers]                        Hit:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease
                        0% [Working]0% [Waiting for headers]                        Hit:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease
                        0% [Working]0% [Waiting for headers]                        Hit:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease
                        0% [Working]20% [Working]             Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Building dependency tree... 0%Building dependency tree... 0%Building dependency tree... 50%Building dependency tree... 50%Building dependency tree       
Reading state information... 0%Reading state information... 0%Reading state information... Done
python3-dev is already the newest version (3.8.2-0ubuntu2).
python3-dev set to manually installed.
build-essential is already the newest version (12.8ubuntu1.1).
build-essential set to manually installed.
The following additional packages will be installed:
  libmysqlclient-dev libmysqlclient21 libssl-dev
Suggested packages:
  libssl-doc
The following NEW packages will be installed:
  default-libmysqlclient-dev libmysqlclient-dev libmysqlclient21 libssl-dev
0 upgraded, 4 newly installed, 0 to remove and 0 not upgraded.
Need to get 4321 kB of archives.
After this operation, 25.1 MB of additional disk space will be used.
0% [Working]            Get:1 http://ports.ubuntu.com/ubuntu-ports focal-updates/main arm64 libmysqlclient21 arm64 8.0.35-0ubuntu0.20.04.1 [1256 kB]
0% [1 libmysqlclient21 11.4 kB/1256 kB 1%]8% [1 libmysqlclient21 440 kB/1256 kB 35%]                                          28% [Working]             Get:2 http://ports.ubuntu.com/ubuntu-ports focal-updates/main arm64 libssl-dev arm64 1.1.1f-1ubuntu2.20 [1460 kB]
28% [2 libssl-dev 2641 B/1460 kB 0%]                                    60% [Waiting for headers]                         Get:3 http://ports.ubuntu.com/ubuntu-ports focal-updates/main arm64 libmysqlclient-dev arm64 8.0.35-0ubuntu0.20.04.1 [1601 kB]
61% [3 libmysqlclient-dev 35.5 kB/1601 kB 2%]                                             95% [Waiting for headers]                         Get:4 http://ports.ubuntu.com/ubuntu-ports focal/main arm64 default-libmysqlclient-dev arm64 1.0.5ubuntu2 [3932 B]
                         100% [Working]              Fetched 4321 kB in 1s (3805 kB/s)
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package libmysqlclient21:arm64.
(Reading database ... (Reading database ... 5%(Reading database ... 10%(Reading database ... 15%(Reading database ... 20%(Reading database ... 25%(Reading database ... 30%(Reading database ... 35%(Reading database ... 40%(Reading database ... 45%(Reading database ... 50%(Reading database ... 55%(Reading database ... 60%(Reading database ... 65%(Reading database ... 70%(Reading database ... 75%(Reading database ... 80%(Reading database ... 85%(Reading database ... 90%(Reading database ... 95%(Reading database ... 100%(Reading database ... 14446 files and directories currently installed.)
Preparing to unpack .../libmysqlclient21_8.0.35-0ubuntu0.20.04.1_arm64.deb ...
Unpacking libmysqlclient21:arm64 (8.0.35-0ubuntu0.20.04.1) ...
Selecting previously unselected package libssl-dev:arm64.
Preparing to unpack .../libssl-dev_1.1.1f-1ubuntu2.20_arm64.deb ...
Unpacking libssl-dev:arm64 (1.1.1f-1ubuntu2.20) ...
Selecting previously unselected package libmysqlclient-dev.
Preparing to unpack .../libmysqlclient-dev_8.0.35-0ubuntu0.20.04.1_arm64.deb ...
Unpacking libmysqlclient-dev (8.0.35-0ubuntu0.20.04.1) ...
Selecting previously unselected package default-libmysqlclient-dev:arm64.
Preparing to unpack .../default-libmysqlclient-dev_1.0.5ubuntu2_arm64.deb ...
Unpacking default-libmysqlclient-dev:arm64 (1.0.5ubuntu2) ...
Setting up libmysqlclient21:arm64 (8.0.35-0ubuntu0.20.04.1) ...
Setting up libssl-dev:arm64 (1.1.1f-1ubuntu2.20) ...
Setting up libmysqlclient-dev (8.0.35-0ubuntu0.20.04.1) ...
Setting up default-libmysqlclient-dev:arm64 (1.0.5ubuntu2) ...
Processing triggers for libc-bin (2.31-0ubuntu9.12) ...
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Collecting sqlalchemy
  Downloading SQLAlchemy-2.0.23-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata (9.6 kB)
Requirement already satisfied: direct-redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: msgpack-python in /usr/local/lib/python3.8/dist-packages (0.5.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: typing-extensions>=4.2.0 in /usr/local/lib/python3.8/dist-packages (from sqlalchemy) (4.8.0)
Collecting greenlet!=0.4.17 (from sqlalchemy)
  Downloading greenlet-3.0.1-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata (3.7 kB)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct-redis) (3.4.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Downloading SQLAlchemy-2.0.23-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (3.1 MB)
[?25l   [90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━[0m [32m0.0/3.1 MB[0m [31m?[0m eta [36m-:--:--[0m[2K   [91m━━━━[0m[90m╺[0m[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━[0m [32m0.3/3.1 MB[0m [31m9.4 MB/s[0m eta [36m0:00:01[0m[2K   [91m━━━━━━━━━━━━━━━━━━━━━━━[0m[91m╸[0m[90m━━━━━━━━━━━━━━━━[0m [32m1.8/3.1 MB[0m [31m26.5 MB/s[0m eta [36m0:00:01[0m[2K   [91m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━[0m[90m╺[0m [32m3.0/3.1 MB[0m [31m28.5 MB/s[0m eta [36m0:00:01[0m[2K   [90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━[0m [32m3.1/3.1 MB[0m [31m26.6 MB/s[0m eta [36m0:00:00[0m
[?25hDownloading greenlet-3.0.1-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (654 kB)
[?25l   [90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━[0m [32m0.0/654.9 kB[0m [31m?[0m eta [36m-:--:--[0m[2K   [90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━[0m [32m654.9/654.9 kB[0m [31m43.6 MB/s[0m eta [36m0:00:00[0m
[?25hInstalling collected packages: greenlet, sqlalchemy
Successfully installed greenlet-3.0.1 sqlalchemy-2.0.23
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mpython /dbknitter/dbknitter/grader.py /platform/source/s01/v4/m20202020/m20202020_q10_t0.py /platform/output/s01/v4/m20202020/m20202020_q10_t0.csv /platform/expected/s01/q10.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4/m20202020/m20202020_q10_t0.py", line 44, in <module>
    orders_df = pd.DataFrame(eval(redis.get('orders')))
TypeError: eval() arg 1 must be a string, bytes or code object
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4/m20202020/m20202020_q11_t0.py /platform/output/s01/v4/m20202020/m20202020_q11_t0.csv /platform/expected/s01/q11.csv
/platform/source/s01/v4/m20202020/m20202020_q11_t0.py:11: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  supplier_df = pd.read_sql(supplier_query, mysql_conn)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/sql.py", line 2202, in execute
    cur.execute(sql, *args)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 822, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'tpch.nation' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/platform/source/s01/v4/m20202020/m20202020_q11_t0.py", line 11, in <module>
    supplier_df = pd.read_sql(supplier_query, mysql_conn)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/sql.py", line 635, in read_sql
    return pandas_sql.read_query(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/sql.py", line 2266, in read_query
    cursor = self.execute(sql, params)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/sql.py", line 2214, in execute
    raise ex from exc
pandas.errors.DatabaseError: Execution failed on sql 'SELECT * FROM supplier WHERE S_NATIONKEY IN (SELECT N_NATIONKEY FROM nation WHERE N_NAME = 'GERMANY')': (1146, "Table 'tpch.nation' doesn't exist")
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4/m20202020/m20202020_q12_t0.py /platform/output/s01/v4/m20202020/m20202020_q12_t0.csv /platform/expected/s01/q12.csv
/platform/source/s01/v4/m20202020/m20202020_q12_t0.py:28: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  lineitem_df = pd.read_sql(mysql_query, mysql_connection)
Traceback (most recent call last):
  File "/platform/source/s01/v4/m20202020/m20202020_q12_t0.py", line 35, in <module>
    orders_df = pd.DataFrame(eval(redis_connection.get('orders')))
TypeError: eval() arg 1 must be a string, bytes or code object
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4/m20202020/m20202020_q13_t0.py /platform/output/s01/v4/m20202020/m20202020_q13_t0.csv /platform/expected/s01/q13.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4/m20202020/m20202020_q13_t0.py", line 27, in <module>
    df_orders = pd.read_json(orders_data)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4/m20202020/m20202020_q14_t0.py /platform/output/s01/v4/m20202020/m20202020_q14_t0.csv /platform/expected/s01/q14.csv
/platform/source/s01/v4/m20202020/m20202020_q14_t0.py:10: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
Exception ignored in: <function Redis.__del__ at 0xffff907c0af0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/redis/client.py", line 862, in __del__
    self.close()
  File "/usr/local/lib/python3.8/dist-packages/redis/client.py", line 865, in close
    conn = self.connection
AttributeError: 'DirectRedis' object has no attribute 'connection'
Traceback (most recent call last):
  File "/platform/source/s01/v4/m20202020/m20202020_q14_t0.py", line 63, in <module>
    part_df = get_redis_data('part', redis_conn)
  File "/platform/source/s01/v4/m20202020/m20202020_q14_t0.py", line 20, in get_redis_data
    client = DirectRedis(**connection_params)
TypeError: __init__() got an unexpected keyword argument 'hostname'
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4/m20202020/m20202020_q15_t0.py /platform/output/s01/v4/m20202020/m20202020_q15_t0.csv /platform/expected/s01/q15.csv
Query executed successfully. Results are saved in 'query_output.csv'.
>>> Expected ((1, 5))
               S_ADDRESS              S_NAME          S_PHONE  S_SUPPKEY  TOTAL_REVENUE
0  8mhrffG7D2WJBSQbOGstQ  Supplier#000000677  23-290-639-3315        677   1.614410e+06

>>> Actual ((1, 5))
               S_ADDRESS              S_NAME          S_PHONE  S_SUPPKEY  TOTAL_REVENUE
0  8mhrffG7D2WJBSQbOGstQ  Supplier#000000677  23-290-639-3315        677   1.614410e+06

Score.success
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4/m20202020/m20202020_q16_t0.py /platform/output/s01/v4/m20202020/m20202020_q16_t0.csv /platform/expected/s01/q16.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4/m20202020/m20202020_q16_t0.py", line 29, in <module>
    part_df = pd.read_msgpack(redis_client.get('part'))
AttributeError: module 'pandas' has no attribute 'read_msgpack'
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4/m20202020/m20202020_q17_t0.py /platform/output/s01/v4/m20202020/m20202020_q17_t0.csv /platform/expected/s01/q17.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4/m20202020/m20202020_q17_t0.py", line 27, in <module>
    part_details = pd.read_json(redis_conn.get('part'))
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4/m20202020/m20202020_q18_t0.py /platform/output/s01/v4/m20202020/m20202020_q18_t0.csv /platform/expected/s01/q18.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4/m20202020/m20202020_q18_t0.py", line 53, in <module>
    df_orders = get_redis_df('orders', redis_hostname, redis_port, redis_db_number)
  File "/platform/source/s01/v4/m20202020/m20202020_q18_t0.py", line 18, in get_redis_df
    df = pd.read_json(redis_connection.get(key).decode('utf-8'))
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'decode'
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4/m20202020/m20202020_q19_t0.py /platform/output/s01/v4/m20202020/m20202020_q19_t0.csv /platform/expected/s01/q19.csv
/platform/source/s01/v4/m20202020/m20202020_q19_t0.py:23: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  lineitem_df = pd.read_sql(mysql_query, con=mysql_conn)
Traceback (most recent call last):
  File "/platform/source/s01/v4/m20202020/m20202020_q19_t0.py", line 28, in <module>
    part_df = pd.read_json(redis_conn.get('part'))
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4/m20202020/m20202020_q1_t0.py /platform/output/s01/v4/m20202020/m20202020_q1_t0.csv /platform/expected/s01/q1.csv
>>> Expected ((4, 10))
   AVG_DISC     AVG_PRICE    AVG_QTY  COUNT_ORDER L_LINESTATUS L_RETURNFLAG  SUM_BASE_PRICE    SUM_CHARGE  SUM_DISC_PRICE  SUM_QTY
0  0.050145  36002.123829  25.537587       147790            F            A    5.320754e+09  5.256751e+09    5.054096e+09  3774200
1  0.049394  35521.326916  25.300664         3765            F            N    1.337378e+08  1.322863e+08    1.271324e+08    95257
2  0.050096  36000.924688  25.545538       292000            O            N    1.051227e+10  1.038558e+10    9.986238e+09  7459297
3  0.049989  35994.029214  25.525944       148301            F            R    5.337951e+09  5.274406e+09    5.071819e+09  3785523

>>> Actual ((4, 10))
   AVG_DISC     AVG_PRICE    AVG_QTY  COUNT_ORDER L_LINESTATUS L_RETURNFLAG  SUM_BASE_PRICE    SUM_CHARGE  SUM_DISC_PRICE    SUM_QTY
0  0.050145  36002.123829  25.537587       147790            F            A    5.320754e+09  5.256751e+09    5.054096e+09  3774200.0
1  0.049394  35521.326916  25.300664         3765            F            N    1.337378e+08  1.322863e+08    1.271324e+08    95257.0
2  0.050096  36000.924688  25.545538       292000            O            N    1.051227e+10  1.038558e+10    9.986238e+09  7459297.0
3  0.049989  35994.029214  25.525944       148301            F            R    5.337951e+09  5.274406e+09    5.071819e+09  3785523.0

Head row similarity: 0.992412746585736
Score.success_approx
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4/m20202020/m20202020_q20_t0.py /platform/output/s01/v4/m20202020/m20202020_q20_t0.csv /platform/expected/s01/q20.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4/m20202020/m20202020_q20_t0.py", line 38, in <module>
    df_nation = read_from_redis('nation')
  File "/platform/source/s01/v4/m20202020/m20202020_q20_t0.py", line 17, in read_from_redis
    if df_bytes:
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/generic.py", line 1466, in __nonzero__
    raise ValueError(
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4/m20202020/m20202020_q21_t0.py /platform/output/s01/v4/m20202020/m20202020_q21_t0.csv /platform/expected/s01/q21.csv
/platform/source/s01/v4/m20202020/m20202020_q21_t0.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  supplier_df = pd.read_sql('SELECT * FROM supplier', mysql_conn)
/platform/source/s01/v4/m20202020/m20202020_q21_t0.py:16: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  lineitem_df = pd.read_sql('SELECT * FROM lineitem', mysql_conn)
Traceback (most recent call last):
  File "/platform/source/s01/v4/m20202020/m20202020_q21_t0.py", line 23, in <module>
    nation_df = pd.read_json(redis_conn.get('nation').decode('utf-8'))
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'decode'
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4/m20202020/m20202020_q22_t0.py /platform/output/s01/v4/m20202020/m20202020_q22_t0.csv /platform/expected/s01/q22.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4/m20202020/m20202020_q22_t0.py", line 47, in <module>
    orders_df = pd.read_json(orders_str, orient='table')
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4/m20202020/m20202020_q2_t0.py /platform/output/s01/v4/m20202020/m20202020_q2_t0.csv /platform/expected/s01/q2.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4/m20202020/m20202020_q2_t0.py", line 38, in <module>
    cursor.execute(mysql_query)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 822, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'tpch.nation' doesn't exist")
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4/m20202020/m20202020_q3_t0.py /platform/output/s01/v4/m20202020/m20202020_q3_t0.csv /platform/expected/s01/q3.csv
/platform/source/s01/v4/m20202020/m20202020_q3_t0.py:29: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  customer_df = pd.read_sql(mysql_query_customer, mysql_conn)
/platform/source/s01/v4/m20202020/m20202020_q3_t0.py:30: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  lineitem_df = pd.read_sql(mysql_query_lineitem, mysql_conn)
Query result written to query_output.csv
>>> Expected ((1216, 4))
      L_ORDERKEY O_ORDERDATE  O_SHIPPRIORITY      REVENUE
0         223140  1995-03-14               0  355369.0698
1         584291  1995-02-21               0  354494.7318
2         405063  1995-03-03               0  353125.4577
3         573861  1995-03-09               0  351238.2770
4         554757  1995-03-14               0  349181.7426
...          ...         ...             ...          ...
1211      152096  1995-01-25               0    1113.2000
1212      521728  1994-12-14               0    1013.7761
1213      445159  1994-12-06               0     949.6260
1214      598597  1994-12-03               0     939.0182
1215      135490  1994-12-20               0     934.9592

[1216 rows x 4 columns]

>>> Actual ((1216, 4))
      L_ORDERKEY O_ORDERDATE  O_SHIPPRIORITY      REVENUE
0         223140  1995-03-14               0  355369.0698
1         584291  1995-02-21               0  354494.7318
2         405063  1995-03-03               0  353125.4577
3         573861  1995-03-09               0  351238.2770
4         554757  1995-03-14               0  349181.7426
...          ...         ...             ...          ...
1211      152096  1995-01-25               0    1113.2000
1212      521728  1994-12-14               0    1013.7761
1213      445159  1994-12-06               0     949.6260
1214      598597  1994-12-03               0     939.0182
1215      135490  1994-12-20               0     934.9592

[1216 rows x 4 columns]

Head row similarity: 1.0
Score.success_approx
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4/m20202020/m20202020_q4_t0.py /platform/output/s01/v4/m20202020/m20202020_q4_t0.csv /platform/expected/s01/q4.csv
/platform/source/s01/v4/m20202020/m20202020_q4_t0.py:20: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  lineitems = pd.read_sql(mysql_query, mysql_connection)
Traceback (most recent call last):
  File "/platform/source/s01/v4/m20202020/m20202020_q4_t0.py", line 30, in <module>
    orders_df = pd.read_json(orders_df_str)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4/m20202020/m20202020_q5_t0.py /platform/output/s01/v4/m20202020/m20202020_q5_t0.csv /platform/expected/s01/q5.csv
/platform/source/s01/v4/m20202020/m20202020_q5_t0.py:12: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)
Traceback (most recent call last):
  File "/platform/source/s01/v4/m20202020/m20202020_q5_t0.py", line 64, in <module>
    (df_joined['O_ORDERDATE'] >= datetime.date(1990, 1, 1)) & 
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/ops/common.py", line 81, in new_method
    return method(self, other)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/arraylike.py", line 60, in __ge__
    return self._cmp_method(other, operator.ge)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/series.py", line 6096, in _cmp_method
    res_values = ops.comparison_op(lvalues, rvalues, op)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/ops/array_ops.py", line 293, in comparison_op
    res_values = comp_method_OBJECT_ARRAY(op, lvalues, rvalues)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/ops/array_ops.py", line 82, in comp_method_OBJECT_ARRAY
    result = libops.scalar_compare(x.ravel(), y, op)
  File "pandas/_libs/ops.pyx", line 107, in pandas._libs.ops.scalar_compare
TypeError: '>=' not supported between instances of 'str' and 'datetime.date'
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4/m20202020/m20202020_q6_t0.py /platform/output/s01/v4/m20202020/m20202020_q6_t0.csv /platform/expected/s01/q6.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4/m20202020/m20202020_q6_t0.py", line 41, in <module>
    connection.close()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 409, in close
    raise err.Error("Already closed")
pymysql.err.Error: Already closed
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4/m20202020/m20202020_q7_t0.py /platform/output/s01/v4/m20202020/m20202020_q7_t0.csv /platform/expected/s01/q7.csv
/platform/source/s01/v4/m20202020/m20202020_q7_t0.py:33: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_mysql = pd.read_sql(mysql_query, conn)
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4/m20202020/m20202020_q8_t0.py /platform/output/s01/v4/m20202020/m20202020_q8_t0.csv /platform/expected/s01/q8.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4/m20202020/m20202020_q8_t0.py", line 34, in <module>
    nation_df = get_redis_data(redis_instance, 'nation')
  File "/platform/source/s01/v4/m20202020/m20202020_q8_t0.py", line 27, in get_redis_data
    dataframe = pd.read_msgpack(redis_instance.get(table_name))
AttributeError: module 'pandas' has no attribute 'read_msgpack'
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4/m20202020/m20202020_q9_t0.py /platform/output/s01/v4/m20202020/m20202020_q9_t0.csv /platform/expected/s01/q9.csv
/platform/source/s01/v4/m20202020/m20202020_q9_t0.py:29: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql(query, connection)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/sql.py", line 2202, in execute
    cur.execute(sql, *args)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 822, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'tpch.nation' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/platform/source/s01/v4/m20202020/m20202020_q9_t0.py", line 63, in <module>
    mysql_df = get_mysql_data(mysql_query, mysql_connection_info)
  File "/platform/source/s01/v4/m20202020/m20202020_q9_t0.py", line 29, in get_mysql_data
    return pd.read_sql(query, connection)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/sql.py", line 635, in read_sql
    return pandas_sql.read_query(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/sql.py", line 2266, in read_query
    cursor = self.execute(sql, params)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/sql.py", line 2214, in execute
    raise ex from exc
pandas.errors.DatabaseError: Execution failed on sql '
SELECT 
    supplier.S_SUPPKEY,
    nation.N_NATIONKEY, 
    nation.N_NAME,
    lineitem.L_EXTENDEDPRICE,
    lineitem.L_DISCOUNT,
    lineitem.L_QUANTITY,
    lineitem.L_PARTKEY,
    lineitem.L_ORDERKEY
FROM 
    supplier, 
    lineitem, 
    nation
WHERE 
    supplier.S_SUPPKEY = lineitem.L_SUPPKEY
    AND supplier.S_NATIONKEY = nation.N_NATIONKEY;
': (1146, "Table 'tpch.nation' doesn't exist")
Score.fail_execute
