python /grader.py /platform/source/s01/v1_9/m00000000/m00000000_q10_t0.py /platform/output/m00000000/m00000000_q10_t0.csv /platform/expected/s01/q10.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m00000000/m00000000_q10_t0.py", line 2, in <module>
    import MySQLdb
ModuleNotFoundError: No module named 'MySQLdb'
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m00000000/m00000000_q10_t1.py /platform/output/m00000000/m00000000_q10_t1.csv /platform/expected/s01/q10.csv
>>> Expected
      C_CUSTKEY  ...                                          C_COMMENT
0         14441  ...  ts. quickly even instructions above the furiou...
1         14623  ...  cial deposits sleep bravely blithely even deco...
2          8333  ...  egular courts among the carefully final platel...
3           935  ...                 furiously pending ideas. daringly 
4          3925  ...  blithely regular, regular somas. blithely pend...
...         ...  ...                                                ...
3762      12106  ...  ly after the blithely regular foxes. accounts ...
3763       2455  ...  al asymptotes. finally ironic accounts cajole ...
3764      11032  ...       posits-- furiously ironic accounts are again
3765       7714  ...      arhorses according to the blithely express re
3766       8242  ...  slyly regular packages haggle carefully ironic...

[3767 rows x 8 columns]

>>> Actual
      C_CUSTKEY  ...                                          C_COMMENT
0         14441  ...  ts. quickly even instructions above the furiou...
1         14623  ...  cial deposits sleep bravely blithely even deco...
2          8333  ...  egular courts among the carefully final platel...
3           935  ...                 furiously pending ideas. daringly 
4          3925  ...  blithely regular, regular somas. blithely pend...
...         ...  ...                                                ...
3762      12106  ...  ly after the blithely regular foxes. accounts ...
3763       2455  ...  al asymptotes. finally ironic accounts cajole ...
3764      11032  ...       posits-- furiously ironic accounts are again
3765       7714  ...      arhorses according to the blithely express re
3766       8242  ...  slyly regular packages haggle carefully ironic...

[3767 rows x 8 columns]

Score.success
python /grader.py /platform/source/s01/v1_9/m00000000/m00000000_q10_t2.py /platform/output/m00000000/m00000000_q10_t2.csv /platform/expected/s01/q10.csv
Connected to Database
/platform/source/s01/v1_9/m00000000/m00000000_q10_t2.py:26: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)
Data has been written to query_output.csv
>>> Expected
      C_CUSTKEY  ...                                          C_COMMENT
0         14441  ...  ts. quickly even instructions above the furiou...
1         14623  ...  cial deposits sleep bravely blithely even deco...
2          8333  ...  egular courts among the carefully final platel...
3           935  ...                 furiously pending ideas. daringly 
4          3925  ...  blithely regular, regular somas. blithely pend...
...         ...  ...                                                ...
3762      12106  ...  ly after the blithely regular foxes. accounts ...
3763       2455  ...  al asymptotes. finally ironic accounts cajole ...
3764      11032  ...       posits-- furiously ironic accounts are again
3765       7714  ...      arhorses according to the blithely express re
3766       8242  ...  slyly regular packages haggle carefully ironic...

[3767 rows x 8 columns]

>>> Actual
      C_CUSTKEY  ...                                          C_COMMENT
0          8242  ...  slyly regular packages haggle carefully ironic...
1          7714  ...      arhorses according to the blithely express re
2         11032  ...       posits-- furiously ironic accounts are again
3          2455  ...  al asymptotes. finally ironic accounts cajole ...
4         12106  ...  ly after the blithely regular foxes. accounts ...
...         ...  ...                                                ...
3762       3925  ...  blithely regular, regular somas. blithely pend...
3763        935  ...                 furiously pending ideas. daringly 
3764       8333  ...  egular courts among the carefully final platel...
3765      14623  ...  cial deposits sleep bravely blithely even deco...
3766      14441  ...  ts. quickly even instructions above the furiou...

[3767 rows x 8 columns]

Score.fail_wrong_output
python /grader.py /platform/source/s01/v1_9/m00000000/m00000000_q11_t0.py /platform/output/m00000000/m00000000_q11_t0.csv /platform/expected/s01/q11.csv
>>> Expected
      PS_PARTKEY        VALUE
0          12098  16227681.21
1           5134  15709338.52
2          13334  15023662.41
3          17052  14351644.20
4           3452  14070870.14
...          ...          ...
2536       19870   1007919.36
2537       18564   1007416.20
2538       10179   1004920.00
2539         883   1004650.68
2540        3627   1004461.04

[2541 rows x 2 columns]

>>> Actual
      PS_PARTKEY        VALUE
0          12098  16227681.21
1           5134  15709338.52
2          13334  15023662.41
3          17052  14351644.20
4           3452  14070870.14
...          ...          ...
2536       19870   1007919.36
2537       18564   1007416.20
2538       10179   1004920.00
2539         883   1004650.68
2540        3627   1004461.04

[2541 rows x 2 columns]

Score.success
python /grader.py /platform/source/s01/v1_9/m00000000/m00000000_q11_t1.py /platform/output/m00000000/m00000000_q11_t1.csv /platform/expected/s01/q11.csv
>>> Expected
      PS_PARTKEY        VALUE
0          12098  16227681.21
1           5134  15709338.52
2          13334  15023662.41
3          17052  14351644.20
4           3452  14070870.14
...          ...          ...
2536       19870   1007919.36
2537       18564   1007416.20
2538       10179   1004920.00
2539         883   1004650.68
2540        3627   1004461.04

[2541 rows x 2 columns]

>>> Actual
      PS_PARTKEY        VALUE
0          12098  16227681.21
1           5134  15709338.52
2          13334  15023662.41
3          17052  14351644.20
4           3452  14070870.14
...          ...          ...
2536       19870   1007919.36
2537       18564   1007416.20
2538       10179   1004920.00
2539         883   1004650.68
2540        3627   1004461.04

[2541 rows x 2 columns]

Score.success
python /grader.py /platform/source/s01/v1_9/m00000000/m00000000_q11_t2.py /platform/output/m00000000/m00000000_q11_t2.csv /platform/expected/s01/q11.csv
>>> Expected
      PS_PARTKEY        VALUE
0          12098  16227681.21
1           5134  15709338.52
2          13334  15023662.41
3          17052  14351644.20
4           3452  14070870.14
...          ...          ...
2536       19870   1007919.36
2537       18564   1007416.20
2538       10179   1004920.00
2539         883   1004650.68
2540        3627   1004461.04

[2541 rows x 2 columns]

>>> Actual
      PS_PARTKEY        VALUE
0          12098  16227681.21
1           5134  15709338.52
2          13334  15023662.41
3          17052  14351644.20
4           3452  14070870.14
...          ...          ...
2536       19870   1007919.36
2537       18564   1007416.20
2538       10179   1004920.00
2539         883   1004650.68
2540        3627   1004461.04

[2541 rows x 2 columns]

Score.success
python /grader.py /platform/source/s01/v1_9/m00000000/m00000000_q12_t0.py /platform/output/m00000000/m00000000_q12_t0.csv /platform/expected/s01/q12.csv
>>> Expected
  L_SHIPMODE  ...  LOW_LINE_COUNT
0       MAIL  ...             945
1       SHIP  ...             943

[2 rows x 3 columns]

>>> Actual
   MAIL  ...  945
0  SHIP  ...  943

[1 rows x 3 columns]

Score.fail_wrong_output
python /grader.py /platform/source/s01/v1_9/m00000000/m00000000_q12_t1.py /platform/output/m00000000/m00000000_q12_t1.csv /platform/expected/s01/q12.csv
>>> Expected
  L_SHIPMODE  ...  LOW_LINE_COUNT
0       MAIL  ...             945
1       SHIP  ...             943

[2 rows x 3 columns]

>>> Actual
  L_SHIPMODE  ...  LOW_LINE_COUNT
0       MAIL  ...             945
1       SHIP  ...             943

[2 rows x 3 columns]

Score.success
python /grader.py /platform/source/s01/v1_9/m00000000/m00000000_q12_t2.py /platform/output/m00000000/m00000000_q12_t2.csv /platform/expected/s01/q12.csv
>>> Expected
  L_SHIPMODE  ...  LOW_LINE_COUNT
0       MAIL  ...             945
1       SHIP  ...             943

[2 rows x 3 columns]

>>> Actual
  L_SHIPMODE  ...  LOW_LINE_COUNT
0       MAIL  ...             945
1       SHIP  ...             943

[2 rows x 3 columns]

Score.success
python /grader.py /platform/source/s01/v1_9/m00000000/m00000000_q13_t0.py /platform/output/m00000000/m00000000_q13_t0.csv /platform/expected/s01/q13.csv
>>> Expected
    C_COUNT  CUSTDIST
0         0      5000
1        10       676
2         9       651
3        11       618
4        12       554
5         8       548
6        13       514
7         7       487
8        19       485
9        18       461
10       14       454
11       20       444
12       16       442
13       17       438
14       15       430
15       21       396
16       22       378
17        6       355
18       23       322
19       24       262
20       25       188
21        5       184
22       26       162
23       27       138
24       28       103
25        4        92
26       29        59
27        3        49
28       30        29
29       31        26
30       32        19
31        2        12
32       33         8
33       34         7
34       35         5
35        1         3
36       36         1

>>> Actual
    C_COUNT  CUSTDIST
0         0      5000
1        10       676
2         9       651
3        11       618
4        12       554
5         8       548
6        13       514
7         7       487
8        19       485
9        18       461
10       14       454
11       20       444
12       16       442
13       17       438
14       15       430
15       21       396
16       22       378
17        6       355
18       23       322
19       24       262
20       25       188
21        5       184
22       26       162
23       27       138
24       28       103
25        4        92
26       29        59
27        3        49
28       30        29
29       31        26
30       32        19
31        2        12
32       33         8
33       34         7
34       35         5
35        1         3
36       36         1

Score.success
python /grader.py /platform/source/s01/v1_9/m00000000/m00000000_q13_t1.py /platform/output/m00000000/m00000000_q13_t1.csv /platform/expected/s01/q13.csv
>>> Expected
    C_COUNT  CUSTDIST
0         0      5000
1        10       676
2         9       651
3        11       618
4        12       554
5         8       548
6        13       514
7         7       487
8        19       485
9        18       461
10       14       454
11       20       444
12       16       442
13       17       438
14       15       430
15       21       396
16       22       378
17        6       355
18       23       322
19       24       262
20       25       188
21        5       184
22       26       162
23       27       138
24       28       103
25        4        92
26       29        59
27        3        49
28       30        29
29       31        26
30       32        19
31        2        12
32       33         8
33       34         7
34       35         5
35        1         3
36       36         1

>>> Actual
     0  5000
0   10   676
1    9   651
2   11   618
3   12   554
4    8   548
5   13   514
6    7   487
7   19   485
8   18   461
9   14   454
10  20   444
11  16   442
12  17   438
13  15   430
14  21   396
15  22   378
16   6   355
17  23   322
18  24   262
19  25   188
20   5   184
21  26   162
22  27   138
23  28   103
24   4    92
25  29    59
26   3    49
27  30    29
28  31    26
29  32    19
30   2    12
31  33     8
32  34     7
33  35     5
34   1     3
35  36     1

Score.fail_wrong_output
python /grader.py /platform/source/s01/v1_9/m00000000/m00000000_q13_t2.py /platform/output/m00000000/m00000000_q13_t2.csv /platform/expected/s01/q13.csv
>>> Expected
    C_COUNT  CUSTDIST
0         0      5000
1        10       676
2         9       651
3        11       618
4        12       554
5         8       548
6        13       514
7         7       487
8        19       485
9        18       461
10       14       454
11       20       444
12       16       442
13       17       438
14       15       430
15       21       396
16       22       378
17        6       355
18       23       322
19       24       262
20       25       188
21        5       184
22       26       162
23       27       138
24       28       103
25        4        92
26       29        59
27        3        49
28       30        29
29       31        26
30       32        19
31        2        12
32       33         8
33       34         7
34       35         5
35        1         3
36       36         1

>>> Actual
    C_COUNT  CUSTDIST
0         0      5000
1        10       676
2         9       651
3        11       618
4        12       554
5         8       548
6        13       514
7         7       487
8        19       485
9        18       461
10       14       454
11       20       444
12       16       442
13       17       438
14       15       430
15       21       396
16       22       378
17        6       355
18       23       322
19       24       262
20       25       188
21        5       184
22       26       162
23       27       138
24       28       103
25        4        92
26       29        59
27        3        49
28       30        29
29       31        26
30       32        19
31        2        12
32       33         8
33       34         7
34       35         5
35        1         3
36       36         1

Score.success
python /grader.py /platform/source/s01/v1_9/m00000000/m00000000_q14_t0.py /platform/output/m00000000/m00000000_q14_t0.csv /platform/expected/s01/q14.csv
>>> Expected
   PROMO_REVENUE
0      16.283856

>>> Actual
   PROMO_REVENUE
0      16.283856

Score.fail_wrong_output
python /grader.py /platform/source/s01/v1_9/m00000000/m00000000_q14_t1.py /platform/output/m00000000/m00000000_q14_t1.csv /platform/expected/s01/q14.csv
>>> Expected
   PROMO_REVENUE
0      16.283856

>>> Actual
   PROMO_REVENUE
0      16.283856

Score.fail_wrong_output
python /grader.py /platform/source/s01/v1_9/m00000000/m00000000_q14_t2.py /platform/output/m00000000/m00000000_q14_t2.csv /platform/expected/s01/q14.csv
>>> Expected
   PROMO_REVENUE
0      16.283856

>>> Actual
   PROMO_REVENUE
0      16.283856

Score.fail_wrong_output
python /grader.py /platform/source/s01/v1_9/m00000000/m00000000_q15_t0.py /platform/output/m00000000/m00000000_q15_t0.csv /platform/expected/s01/q15.csv
>>> Expected
   S_SUPPKEY  ... TOTAL_REVENUE
0        677  ...  1.614410e+06

[1 rows x 5 columns]

>>> Actual
   S_SUPPKEY  ... TOTAL_REVENUE
0        677  ...  1.614410e+06

[1 rows x 5 columns]

Score.success
python /grader.py /platform/source/s01/v1_9/m00000000/m00000000_q15_t1.py /platform/output/m00000000/m00000000_q15_t1.csv /platform/expected/s01/q15.csv
/platform/source/s01/v1_9/m00000000/m00000000_q15_t1.py:42: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql_query(sql, con)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/sql.py", line 2202, in execute
    cur.execute(sql, *args)
  File "/usr/local/lib/python3.8/dist-packages/mysql/connector/cursor.py", line 617, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/usr/local/lib/python3.8/dist-packages/mysql/connector/opentelemetry/context_propagation.py", line 77, in wrapper
    return method(cnx, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/mysql/connector/connection.py", line 843, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "/usr/local/lib/python3.8/dist-packages/mysql/connector/connection.py", line 620, in _handle_result
    raise get_exception(packet)
mysql.connector.errors.ProgrammingError: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ', '+3 month')
  group by
  L_SUPPKEY)
select
S_SUPPKEY,
S_NAME,
S_ADDRESS,
S_PHO' at line 9

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m00000000/m00000000_q15_t1.py", line 42, in <module>
    result = pd.read_sql_query(sql, con)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/sql.py", line 469, in read_sql_query
    return pandas_sql.read_query(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/sql.py", line 2266, in read_query
    cursor = self.execute(sql, params)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/sql.py", line 2214, in execute
    raise ex from exc
pandas.errors.DatabaseError: Execution failed on sql '
with revenue0 as
(select
  L_SUPPKEY as SUPPLIER_NO,
  sum(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) as TOTAL_REVENUE
  from
  lineitem
  where
  L_SHIPDATE >= '1996-01-01'
  AND L_SHIPDATE < date('1996-01-01', '+3 month')
  group by
  L_SUPPKEY)
select
S_SUPPKEY,
S_NAME,
S_ADDRESS,
S_PHONE,
TOTAL_REVENUE
from
supplier,
revenue0
where
S_SUPPKEY = SUPPLIER_NO
and TOTAL_REVENUE = (
  select
  max(TOTAL_REVENUE)
  from
  revenue0
)
order by
S_SUPPKEY
': 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ', '+3 month')
  group by
  L_SUPPKEY)
select
S_SUPPKEY,
S_NAME,
S_ADDRESS,
S_PHO' at line 9
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m00000000/m00000000_q15_t2.py /platform/output/m00000000/m00000000_q15_t2.csv /platform/expected/s01/q15.csv
/platform/source/s01/v1_9/m00000000/m00000000_q15_t2.py:57: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(sqlQuery, connectionObject)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/sql.py", line 2202, in execute
    cur.execute(sql, *args)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 822, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'tpch.SUPPLIER' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m00000000/m00000000_q15_t2.py", line 57, in <module>
    df = pd.read_sql_query(sqlQuery, connectionObject)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/sql.py", line 469, in read_sql_query
    return pandas_sql.read_query(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/sql.py", line 2266, in read_query
    cursor = self.execute(sql, params)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/sql.py", line 2214, in execute
    raise ex from exc
pandas.errors.DatabaseError: Execution failed on sql '
with revenue0 as
(select
  L_SUPPKEY as SUPPLIER_NO,
  sum(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) as TOTAL_REVENUE
  from
  LINEITEM
  where
  L_SHIPDATE >= '1996-01-01'
  AND L_SHIPDATE < DATE_ADD('1996-01-01', INTERVAL 3 MONTH)
  group by
  L_SUPPKEY)
select
S_SUPPKEY,
S_NAME,
S_ADDRESS,
S_PHONE,
TOTAL_REVENUE
from
SUPPLIER, 
revenue0
where
S_SUPPKEY = SUPPLIER_NO
and TOTAL_REVENUE = (
  select
  max(TOTAL_REVENUE)
  from
  revenue0
)
order by
S_SUPPKEY
': (1146, "Table 'tpch.SUPPLIER' doesn't exist")
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m00000000/m00000000_q16_t0.py /platform/output/m00000000/m00000000_q16_t0.csv /platform/expected/s01/q16.csv
>>> Expected
       P_BRAND  ... SUPPLIER_CNT
0     Brand#14  ...           12
1     Brand#22  ...           12
2     Brand#25  ...           12
3     Brand#35  ...           12
4     Brand#35  ...           12
...        ...  ...          ...
2757  Brand#22  ...            3
2758  Brand#22  ...            3
2759  Brand#43  ...            3
2760  Brand#44  ...            3
2761  Brand#53  ...            3

[2762 rows x 4 columns]

>>> Actual
       P_BRAND  ... SUPPLIER_CNT
0     Brand#14  ...           12
1     Brand#22  ...           12
2     Brand#25  ...           12
3     Brand#35  ...           12
4     Brand#35  ...           12
...        ...  ...          ...
2757  Brand#22  ...            3
2758  Brand#22  ...            3
2759  Brand#43  ...            3
2760  Brand#44  ...            3
2761  Brand#53  ...            3

[2762 rows x 4 columns]

Score.success
python /grader.py /platform/source/s01/v1_9/m00000000/m00000000_q16_t1.py /platform/output/m00000000/m00000000_q16_t1.csv /platform/expected/s01/q16.csv
>>> Expected
       P_BRAND  ... SUPPLIER_CNT
0     Brand#14  ...           12
1     Brand#22  ...           12
2     Brand#25  ...           12
3     Brand#35  ...           12
4     Brand#35  ...           12
...        ...  ...          ...
2757  Brand#22  ...            3
2758  Brand#22  ...            3
2759  Brand#43  ...            3
2760  Brand#44  ...            3
2761  Brand#53  ...            3

[2762 rows x 4 columns]

>>> Actual
       P_BRAND  ... SUPPLIER_CNT
0     Brand#14  ...           12
1     Brand#22  ...           12
2     Brand#25  ...           12
3     Brand#35  ...           12
4     Brand#35  ...           12
...        ...  ...          ...
2757  Brand#22  ...            3
2758  Brand#22  ...            3
2759  Brand#43  ...            3
2760  Brand#44  ...            3
2761  Brand#53  ...            3

[2762 rows x 4 columns]

Score.success
python /grader.py /platform/source/s01/v1_9/m00000000/m00000000_q16_t2.py /platform/output/m00000000/m00000000_q16_t2.csv /platform/expected/s01/q16.csv
/platform/source/s01/v1_9/m00000000/m00000000_q16_t2.py:45: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(sql, con=db)
>>> Expected
       P_BRAND  ... SUPPLIER_CNT
0     Brand#14  ...           12
1     Brand#22  ...           12
2     Brand#25  ...           12
3     Brand#35  ...           12
4     Brand#35  ...           12
...        ...  ...          ...
2757  Brand#22  ...            3
2758  Brand#22  ...            3
2759  Brand#43  ...            3
2760  Brand#44  ...            3
2761  Brand#53  ...            3

[2762 rows x 4 columns]

>>> Actual
       P_BRAND  ... SUPPLIER_CNT
0     Brand#14  ...           12
1     Brand#22  ...           12
2     Brand#25  ...           12
3     Brand#35  ...           12
4     Brand#35  ...           12
...        ...  ...          ...
2757  Brand#22  ...            3
2758  Brand#22  ...            3
2759  Brand#43  ...            3
2760  Brand#44  ...            3
2761  Brand#53  ...            3

[2762 rows x 4 columns]

Score.success
python /grader.py /platform/source/s01/v1_9/m00000000/m00000000_q17_t0.py /platform/output/m00000000/m00000000_q17_t0.csv /platform/expected/s01/q17.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m00000000/m00000000_q17_t0.py", line 53, in <module>
    execute_query()
  File "/platform/source/s01/v1_9/m00000000/m00000000_q17_t0.py", line 39, in execute_query
    cursor.execute(query)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 822, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'tpch.LINEITEM' doesn't exist")
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m00000000/m00000000_q17_t1.py /platform/output/m00000000/m00000000_q17_t1.csv /platform/expected/s01/q17.csv
/platform/source/s01/v1_9/m00000000/m00000000_q17_t1.py:36: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, cnx)
>>> Expected
     AVG_YEARLY
0  31865.742857

>>> Actual
     AVG_YEARLY
0  31865.742857

Score.fail_wrong_output
python /grader.py /platform/source/s01/v1_9/m00000000/m00000000_q17_t2.py /platform/output/m00000000/m00000000_q17_t2.csv /platform/expected/s01/q17.csv
>>> Expected
     AVG_YEARLY
0  31865.742857

>>> Actual
     AVG_YEARLY
0  31865.742857

Score.fail_wrong_output
python /grader.py /platform/source/s01/v1_9/m00000000/m00000000_q18_t0.py /platform/output/m00000000/m00000000_q18_t0.csv /platform/expected/s01/q18.csv
MySQL Database connection successful
Query successful
>>> Expected
               C_NAME  ...  SUM(L_QUANTITY)
0  Customer#000001639  ...              312
1  Customer#000006655  ...              305
2  Customer#000014110  ...              301
3  Customer#000001775  ...              303
4  Customer#000011459  ...              308

[5 rows x 6 columns]

>>> Actual
               C_NAME  ...  SUM(L_QUANTITY)
0  Customer#000001639  ...            312.0
1  Customer#000006655  ...            305.0
2  Customer#000014110  ...            301.0
3  Customer#000001775  ...            303.0
4  Customer#000011459  ...            308.0

[5 rows x 6 columns]

Score.fail_wrong_output
python /grader.py /platform/source/s01/v1_9/m00000000/m00000000_q18_t1.py /platform/output/m00000000/m00000000_q18_t1.csv /platform/expected/s01/q18.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m00000000/m00000000_q18_t1.py", line 42, in <module>
    cursor.execute(query)
  File "/usr/local/lib/python3.8/dist-packages/mysql/connector/cursor.py", line 617, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/usr/local/lib/python3.8/dist-packages/mysql/connector/opentelemetry/context_propagation.py", line 77, in wrapper
    return method(cnx, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/mysql/connector/connection.py", line 843, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "/usr/local/lib/python3.8/dist-packages/mysql/connector/connection.py", line 620, in _handle_result
    raise get_exception(packet)
mysql.connector.errors.ProgrammingError: 1146 (42S02): Table 'tpch.CUSTOMER' doesn't exist
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m00000000/m00000000_q18_t2.py /platform/output/m00000000/m00000000_q18_t2.csv /platform/expected/s01/q18.csv
>>> Expected
               C_NAME  ...  SUM(L_QUANTITY)
0  Customer#000001639  ...              312
1  Customer#000006655  ...              305
2  Customer#000014110  ...              301
3  Customer#000001775  ...              303
4  Customer#000011459  ...              308

[5 rows x 6 columns]

>>> Actual
   Customer#000001639  ...  312.00
0  Customer#000006655  ...   305.0
1  Customer#000014110  ...   301.0
2  Customer#000001775  ...   303.0
3  Customer#000011459  ...   308.0

[4 rows x 6 columns]

Score.fail_wrong_output
python /grader.py /platform/source/s01/v1_9/m00000000/m00000000_q19_t0.py /platform/output/m00000000/m00000000_q19_t0.csv /platform/expected/s01/q19.csv
>>> Expected
      REVENUE
0  168597.286

>>> Actual
Empty DataFrame
Columns: [168597.2860]
Index: []

Score.fail_wrong_output
python /grader.py /platform/source/s01/v1_9/m00000000/m00000000_q19_t1.py /platform/output/m00000000/m00000000_q19_t1.csv /platform/expected/s01/q19.csv
/platform/source/s01/v1_9/m00000000/m00000000_q19_t1.py:48: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(sql, connection)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/sql.py", line 2202, in execute
    cur.execute(sql, *args)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 822, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'tpch.LINEITEM' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m00000000/m00000000_q19_t1.py", line 48, in <module>
    df = pd.read_sql(sql, connection)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/sql.py", line 635, in read_sql
    return pandas_sql.read_query(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/sql.py", line 2266, in read_query
    cursor = self.execute(sql, params)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/sql.py", line 2214, in execute
    raise ex from exc
pandas.errors.DatabaseError: Execution failed on sql '
SELECT SUM(L_EXTENDEDPRICE*(1 - L_DISCOUNT)) AS REVENUE
FROM LINEITEM, PART
WHERE (
P_PARTKEY = L_PARTKEY
AND P_BRAND = 'Brand#12'
AND P_CONTAINER IN ('SM CASE', 'SM BOX', 'SM PACK', 'SM PKG')
AND L_QUANTITY >= 1 AND L_QUANTITY <= 1 + 10
AND P_SIZE BETWEEN 1 AND 5
AND L_SHIPMODE IN ('AIR', 'AIR REG')
AND L_SHIPINSTRUCT = 'DELIVER IN PERSON'
)
OR
(
P_PARTKEY = L_PARTKEY
AND P_BRAND = 'Brand#23'
AND P_CONTAINER IN ('MED BAG', 'MED BOX', 'MED PKG', 'MED PACK')
AND L_QUANTITY >= 10 AND L_QUANTITY <= 10 + 10
AND P_SIZE BETWEEN 1 AND 10
AND L_SHIPMODE IN ('AIR', 'AIR REG')
AND L_SHIPINSTRUCT = 'DELIVER IN PERSON'
)
OR
(
P_PARTKEY = L_PARTKEY
AND P_BRAND = 'Brand#34'
AND P_CONTAINER IN ('LG CASE', 'LG BOX', 'LG PACK', 'LG PKG')
AND L_QUANTITY >= 20 AND L_QUANTITY <= 20 + 10
AND P_SIZE BETWEEN 1 AND 15
AND L_SHIPMODE IN ('AIR', 'AIR REG')
AND L_SHIPINSTRUCT = 'DELIVER IN PERSON'
)
': (1146, "Table 'tpch.LINEITEM' doesn't exist")
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m00000000/m00000000_q19_t2.py /platform/output/m00000000/m00000000_q19_t2.csv /platform/expected/s01/q19.csv
>>> Expected
      REVENUE
0  168597.286

>>> Actual
Empty DataFrame
Columns: [168597.2860]
Index: []

Score.fail_wrong_output
python /grader.py /platform/source/s01/v1_9/m00000000/m00000000_q1_t0.py /platform/output/m00000000/m00000000_q1_t0.csv /platform/expected/s01/q1.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m00000000/m00000000_q1_t0.py", line 4, in <module>
    db = pymysql.connect("mysql","root","my-secret-pw","tpch")
TypeError: __init__() takes 1 positional argument but 5 were given
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m00000000/m00000000_q1_t1.py /platform/output/m00000000/m00000000_q1_t1.csv /platform/expected/s01/q1.csv
>>> Expected
  L_RETURNFLAG  ... COUNT_ORDER
0            A  ...      147790
1            N  ...        3765
2            N  ...      292000
3            R  ...      148301

[4 rows x 10 columns]

>>> Actual
  L_RETURNFLAG  ... COUNT_ORDER
0            A  ...      147790
1            N  ...        3765
2            N  ...      292000
3            R  ...      148301

[4 rows x 10 columns]

Score.fail_wrong_output
python /grader.py /platform/source/s01/v1_9/m00000000/m00000000_q1_t2.py /platform/output/m00000000/m00000000_q1_t2.csv /platform/expected/s01/q1.csv
/platform/source/s01/v1_9/m00000000/m00000000_q1_t2.py:41: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, con=cnx)
>>> Expected
  L_RETURNFLAG  ... COUNT_ORDER
0            A  ...      147790
1            N  ...        3765
2            N  ...      292000
3            R  ...      148301

[4 rows x 10 columns]

>>> Actual
  L_RETURNFLAG  ... COUNT_ORDER
0            A  ...      147790
1            N  ...        3765
2            N  ...      292000
3            R  ...      148301

[4 rows x 10 columns]

Score.fail_wrong_output
python /grader.py /platform/source/s01/v1_9/m00000000/m00000000_q20_t0.py /platform/output/m00000000/m00000000_q20_t0.csv /platform/expected/s01/q20.csv
>>> Expected
               S_NAME                           S_ADDRESS
0  Supplier#000000157                         ,mEGorBfVIm
1  Supplier#000000197    YC2Acon6kjY3zj3Fbxs2k4Vdf7X0cd2F
2  Supplier#000000287                   7a9SP7qW5Yku5PvSg
3  Supplier#000000378                  FfbhyCxWvcPrO8ltp9
4  Supplier#000000530     0qwCMwobKY OcmLyfRXlagA8ukENJv,
5  Supplier#000000555       TfB,a5bfl3Ah 3Z 74GqnNs6zKVGM
6  Supplier#000000557            jj0wUYh9K3fG5Jhdhrkuy ,4
7  Supplier#000000729  pqck2ppy758TQpZCUAjPvlU55K3QjfL7Bi
8  Supplier#000000935     ij98czM 2KzWe7dDTOxB8sq0UfCdvrX

>>> Actual
               S_NAME                           S_ADDRESS
0  Supplier#000000157                         ,mEGorBfVIm
1  Supplier#000000197    YC2Acon6kjY3zj3Fbxs2k4Vdf7X0cd2F
2  Supplier#000000287                   7a9SP7qW5Yku5PvSg
3  Supplier#000000378                  FfbhyCxWvcPrO8ltp9
4  Supplier#000000530     0qwCMwobKY OcmLyfRXlagA8ukENJv,
5  Supplier#000000555       TfB,a5bfl3Ah 3Z 74GqnNs6zKVGM
6  Supplier#000000557            jj0wUYh9K3fG5Jhdhrkuy ,4
7  Supplier#000000729  pqck2ppy758TQpZCUAjPvlU55K3QjfL7Bi
8  Supplier#000000935     ij98czM 2KzWe7dDTOxB8sq0UfCdvrX

Score.success
python /grader.py /platform/source/s01/v1_9/m00000000/m00000000_q20_t1.py /platform/output/m00000000/m00000000_q20_t1.csv /platform/expected/s01/q20.csv
>>> Expected
               S_NAME                           S_ADDRESS
0  Supplier#000000157                         ,mEGorBfVIm
1  Supplier#000000197    YC2Acon6kjY3zj3Fbxs2k4Vdf7X0cd2F
2  Supplier#000000287                   7a9SP7qW5Yku5PvSg
3  Supplier#000000378                  FfbhyCxWvcPrO8ltp9
4  Supplier#000000530     0qwCMwobKY OcmLyfRXlagA8ukENJv,
5  Supplier#000000555       TfB,a5bfl3Ah 3Z 74GqnNs6zKVGM
6  Supplier#000000557            jj0wUYh9K3fG5Jhdhrkuy ,4
7  Supplier#000000729  pqck2ppy758TQpZCUAjPvlU55K3QjfL7Bi
8  Supplier#000000935     ij98czM 2KzWe7dDTOxB8sq0UfCdvrX

>>> Actual
               S_NAME                           S_ADDRESS
0  Supplier#000000157                         ,mEGorBfVIm
1  Supplier#000000197    YC2Acon6kjY3zj3Fbxs2k4Vdf7X0cd2F
2  Supplier#000000287                   7a9SP7qW5Yku5PvSg
3  Supplier#000000378                  FfbhyCxWvcPrO8ltp9
4  Supplier#000000530     0qwCMwobKY OcmLyfRXlagA8ukENJv,
5  Supplier#000000555       TfB,a5bfl3Ah 3Z 74GqnNs6zKVGM
6  Supplier#000000557            jj0wUYh9K3fG5Jhdhrkuy ,4
7  Supplier#000000729  pqck2ppy758TQpZCUAjPvlU55K3QjfL7Bi
8  Supplier#000000935     ij98czM 2KzWe7dDTOxB8sq0UfCdvrX

Score.success
python /grader.py /platform/source/s01/v1_9/m00000000/m00000000_q20_t2.py /platform/output/m00000000/m00000000_q20_t2.csv /platform/expected/s01/q20.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m00000000/m00000000_q20_t2.py", line 1, in <module>
    import MySQLdb
ModuleNotFoundError: No module named 'MySQLdb'
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m00000000/m00000000_q21_t0.py /platform/output/m00000000/m00000000_q21_t0.csv /platform/expected/s01/q21.csv
>>> Expected
                S_NAME  NUMWAIT
0   Supplier#000000445       16
1   Supplier#000000825       16
2   Supplier#000000709       15
3   Supplier#000000762       15
4   Supplier#000000357       14
5   Supplier#000000399       14
6   Supplier#000000496       14
7   Supplier#000000977       13
8   Supplier#000000144       12
9   Supplier#000000188       12
10  Supplier#000000415       12
11  Supplier#000000472       12
12  Supplier#000000633       12
13  Supplier#000000708       12
14  Supplier#000000889       12
15  Supplier#000000380       11
16  Supplier#000000602       11
17  Supplier#000000659       11
18  Supplier#000000821       11
19  Supplier#000000929       11
20  Supplier#000000262       10
21  Supplier#000000460       10
22  Supplier#000000486       10
23  Supplier#000000669       10
24  Supplier#000000718       10
25  Supplier#000000778       10
26  Supplier#000000167        9
27  Supplier#000000578        9
28  Supplier#000000673        9
29  Supplier#000000687        9
30  Supplier#000000074        8
31  Supplier#000000565        8
32  Supplier#000000648        8
33  Supplier#000000918        8
34  Supplier#000000427        7
35  Supplier#000000503        7
36  Supplier#000000610        7
37  Supplier#000000670        7
38  Supplier#000000811        7
39  Supplier#000000114        6
40  Supplier#000000379        6
41  Supplier#000000436        6
42  Supplier#000000500        6
43  Supplier#000000660        6
44  Supplier#000000788        6
45  Supplier#000000846        6
46  Supplier#000000920        4

>>> Actual
                S_NAME  NUMWAIT
0   Supplier#000000445       16
1   Supplier#000000825       16
2   Supplier#000000709       15
3   Supplier#000000762       15
4   Supplier#000000357       14
5   Supplier#000000399       14
6   Supplier#000000496       14
7   Supplier#000000977       13
8   Supplier#000000144       12
9   Supplier#000000188       12
10  Supplier#000000415       12
11  Supplier#000000472       12
12  Supplier#000000633       12
13  Supplier#000000708       12
14  Supplier#000000889       12
15  Supplier#000000380       11
16  Supplier#000000602       11
17  Supplier#000000659       11
18  Supplier#000000821       11
19  Supplier#000000929       11
20  Supplier#000000262       10
21  Supplier#000000460       10
22  Supplier#000000486       10
23  Supplier#000000669       10
24  Supplier#000000718       10
25  Supplier#000000778       10
26  Supplier#000000167        9
27  Supplier#000000578        9
28  Supplier#000000673        9
29  Supplier#000000687        9
30  Supplier#000000074        8
31  Supplier#000000565        8
32  Supplier#000000648        8
33  Supplier#000000918        8
34  Supplier#000000427        7
35  Supplier#000000503        7
36  Supplier#000000610        7
37  Supplier#000000670        7
38  Supplier#000000811        7
39  Supplier#000000114        6
40  Supplier#000000379        6
41  Supplier#000000436        6
42  Supplier#000000500        6
43  Supplier#000000660        6
44  Supplier#000000788        6
45  Supplier#000000846        6
46  Supplier#000000920        4

Score.success
python /grader.py /platform/source/s01/v1_9/m00000000/m00000000_q21_t1.py /platform/output/m00000000/m00000000_q21_t1.csv /platform/expected/s01/q21.csv
>>> Expected
                S_NAME  NUMWAIT
0   Supplier#000000445       16
1   Supplier#000000825       16
2   Supplier#000000709       15
3   Supplier#000000762       15
4   Supplier#000000357       14
5   Supplier#000000399       14
6   Supplier#000000496       14
7   Supplier#000000977       13
8   Supplier#000000144       12
9   Supplier#000000188       12
10  Supplier#000000415       12
11  Supplier#000000472       12
12  Supplier#000000633       12
13  Supplier#000000708       12
14  Supplier#000000889       12
15  Supplier#000000380       11
16  Supplier#000000602       11
17  Supplier#000000659       11
18  Supplier#000000821       11
19  Supplier#000000929       11
20  Supplier#000000262       10
21  Supplier#000000460       10
22  Supplier#000000486       10
23  Supplier#000000669       10
24  Supplier#000000718       10
25  Supplier#000000778       10
26  Supplier#000000167        9
27  Supplier#000000578        9
28  Supplier#000000673        9
29  Supplier#000000687        9
30  Supplier#000000074        8
31  Supplier#000000565        8
32  Supplier#000000648        8
33  Supplier#000000918        8
34  Supplier#000000427        7
35  Supplier#000000503        7
36  Supplier#000000610        7
37  Supplier#000000670        7
38  Supplier#000000811        7
39  Supplier#000000114        6
40  Supplier#000000379        6
41  Supplier#000000436        6
42  Supplier#000000500        6
43  Supplier#000000660        6
44  Supplier#000000788        6
45  Supplier#000000846        6
46  Supplier#000000920        4

>>> Actual
                S_NAME  NUMWAIT
0   Supplier#000000445       16
1   Supplier#000000825       16
2   Supplier#000000709       15
3   Supplier#000000762       15
4   Supplier#000000357       14
5   Supplier#000000399       14
6   Supplier#000000496       14
7   Supplier#000000977       13
8   Supplier#000000144       12
9   Supplier#000000188       12
10  Supplier#000000415       12
11  Supplier#000000472       12
12  Supplier#000000633       12
13  Supplier#000000708       12
14  Supplier#000000889       12
15  Supplier#000000380       11
16  Supplier#000000602       11
17  Supplier#000000659       11
18  Supplier#000000821       11
19  Supplier#000000929       11
20  Supplier#000000262       10
21  Supplier#000000460       10
22  Supplier#000000486       10
23  Supplier#000000669       10
24  Supplier#000000718       10
25  Supplier#000000778       10
26  Supplier#000000167        9
27  Supplier#000000578        9
28  Supplier#000000673        9
29  Supplier#000000687        9
30  Supplier#000000074        8
31  Supplier#000000565        8
32  Supplier#000000648        8
33  Supplier#000000918        8
34  Supplier#000000427        7
35  Supplier#000000503        7
36  Supplier#000000610        7
37  Supplier#000000670        7
38  Supplier#000000811        7
39  Supplier#000000114        6
40  Supplier#000000379        6
41  Supplier#000000436        6
42  Supplier#000000500        6
43  Supplier#000000660        6
44  Supplier#000000788        6
45  Supplier#000000846        6
46  Supplier#000000920        4

Score.success
python /grader.py /platform/source/s01/v1_9/m00000000/m00000000_q21_t2.py /platform/output/m00000000/m00000000_q21_t2.csv /platform/expected/s01/q21.csv
>>> Expected
                S_NAME  NUMWAIT
0   Supplier#000000445       16
1   Supplier#000000825       16
2   Supplier#000000709       15
3   Supplier#000000762       15
4   Supplier#000000357       14
5   Supplier#000000399       14
6   Supplier#000000496       14
7   Supplier#000000977       13
8   Supplier#000000144       12
9   Supplier#000000188       12
10  Supplier#000000415       12
11  Supplier#000000472       12
12  Supplier#000000633       12
13  Supplier#000000708       12
14  Supplier#000000889       12
15  Supplier#000000380       11
16  Supplier#000000602       11
17  Supplier#000000659       11
18  Supplier#000000821       11
19  Supplier#000000929       11
20  Supplier#000000262       10
21  Supplier#000000460       10
22  Supplier#000000486       10
23  Supplier#000000669       10
24  Supplier#000000718       10
25  Supplier#000000778       10
26  Supplier#000000167        9
27  Supplier#000000578        9
28  Supplier#000000673        9
29  Supplier#000000687        9
30  Supplier#000000074        8
31  Supplier#000000565        8
32  Supplier#000000648        8
33  Supplier#000000918        8
34  Supplier#000000427        7
35  Supplier#000000503        7
36  Supplier#000000610        7
37  Supplier#000000670        7
38  Supplier#000000811        7
39  Supplier#000000114        6
40  Supplier#000000379        6
41  Supplier#000000436        6
42  Supplier#000000500        6
43  Supplier#000000660        6
44  Supplier#000000788        6
45  Supplier#000000846        6
46  Supplier#000000920        4

>>> Actual
                S_NAME  NUMWAIT
0   Supplier#000000445       16
1   Supplier#000000825       16
2   Supplier#000000709       15
3   Supplier#000000762       15
4   Supplier#000000357       14
5   Supplier#000000399       14
6   Supplier#000000496       14
7   Supplier#000000977       13
8   Supplier#000000144       12
9   Supplier#000000188       12
10  Supplier#000000415       12
11  Supplier#000000472       12
12  Supplier#000000633       12
13  Supplier#000000708       12
14  Supplier#000000889       12
15  Supplier#000000380       11
16  Supplier#000000602       11
17  Supplier#000000659       11
18  Supplier#000000821       11
19  Supplier#000000929       11
20  Supplier#000000262       10
21  Supplier#000000460       10
22  Supplier#000000486       10
23  Supplier#000000669       10
24  Supplier#000000718       10
25  Supplier#000000778       10
26  Supplier#000000167        9
27  Supplier#000000578        9
28  Supplier#000000673        9
29  Supplier#000000687        9
30  Supplier#000000074        8
31  Supplier#000000565        8
32  Supplier#000000648        8
33  Supplier#000000918        8
34  Supplier#000000427        7
35  Supplier#000000503        7
36  Supplier#000000610        7
37  Supplier#000000670        7
38  Supplier#000000811        7
39  Supplier#000000114        6
40  Supplier#000000379        6
41  Supplier#000000436        6
42  Supplier#000000500        6
43  Supplier#000000660        6
44  Supplier#000000788        6
45  Supplier#000000846        6
46  Supplier#000000920        4

Score.success
python /grader.py /platform/source/s01/v1_9/m00000000/m00000000_q22_t0.py /platform/output/m00000000/m00000000_q22_t0.csv /platform/expected/s01/q22.csv
/platform/source/s01/v1_9/m00000000/m00000000_q22_t0.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(query, connection)
>>> Expected
   CNTRYCODE  ...  TOTACCTBAL
0         20  ...   666158.10
1         21  ...   760953.55
2         22  ...   759804.81
3         30  ...   646748.02

[4 rows x 3 columns]

>>> Actual
   CNTRYCODE  ...  TOTACCTBAL
0  CNTRYCODE  ...  TOTACCTBAL
1  CNTRYCODE  ...  TOTACCTBAL
2  CNTRYCODE  ...  TOTACCTBAL
3  CNTRYCODE  ...  TOTACCTBAL

[4 rows x 3 columns]

Score.fail_wrong_output
python /grader.py /platform/source/s01/v1_9/m00000000/m00000000_q22_t1.py /platform/output/m00000000/m00000000_q22_t1.csv /platform/expected/s01/q22.csv
/platform/source/s01/v1_9/m00000000/m00000000_q22_t1.py:54: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, con=mydb)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/sql.py", line 2202, in execute
    cur.execute(sql, *args)
  File "/usr/local/lib/python3.8/dist-packages/mysql/connector/cursor.py", line 617, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/usr/local/lib/python3.8/dist-packages/mysql/connector/opentelemetry/context_propagation.py", line 77, in wrapper
    return method(cnx, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/mysql/connector/connection.py", line 843, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "/usr/local/lib/python3.8/dist-packages/mysql/connector/connection.py", line 620, in _handle_result
    raise get_exception(packet)
mysql.connector.errors.ProgrammingError: 1146 (42S02): Table 'tpch.CUSTOMER' doesn't exist

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m00000000/m00000000_q22_t1.py", line 63, in <module>
    df = fetch_data(database, username, password, host)
  File "/platform/source/s01/v1_9/m00000000/m00000000_q22_t1.py", line 54, in fetch_data
    df = pd.read_sql(query, con=mydb)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/sql.py", line 635, in read_sql
    return pandas_sql.read_query(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/sql.py", line 2266, in read_query
    cursor = self.execute(sql, params)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/sql.py", line 2214, in execute
    raise ex from exc
pandas.errors.DatabaseError: Execution failed on sql '
    SELECT
        CNTRYCODE,
        COUNT(*) AS NUMCUST,
        SUM(C_ACCTBAL) AS TOTACCTBAL
    FROM
        (
        SELECT
            SUBSTR(C_PHONE, 1 , 2) AS CNTRYCODE,
            C_ACCTBAL
        FROM
            CUSTOMER
        WHERE
            SUBSTR(C_PHONE , 1 , 2) IN
            ('20', '40', '22', '30', '39', '42', '21')
        AND C_ACCTBAL > (
                SELECT
                    AVG(C_ACCTBAL)
                FROM
                    CUSTOMER
                WHERE
                    C_ACCTBAL > 0.00
                AND SUBSTR(C_PHONE , 1 , 2) IN
                ('20', '40', '22', '30', '39', '42', '21')
        )
        AND NOT EXISTS (
            SELECT
                *
            FROM
                ORDERS
            WHERE
                O_CUSTKEY = CUSTOMER.C_CUSTKEY
            )
        ) AS CUSTSALE
    GROUP BY
        CNTRYCODE
    ORDER BY
        CNTRYCODE
    ': 1146 (42S02): Table 'tpch.CUSTOMER' doesn't exist
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m00000000/m00000000_q22_t2.py /platform/output/m00000000/m00000000_q22_t2.csv /platform/expected/s01/q22.csv
>>> Expected
   CNTRYCODE  ...  TOTACCTBAL
0         20  ...   666158.10
1         21  ...   760953.55
2         22  ...   759804.81
3         30  ...   646748.02

[4 rows x 3 columns]

>>> Actual
   CNTRYCODE  ...  TOTACCTBAL
0         20  ...   666158.10
1         21  ...   760953.55
2         22  ...   759804.81
3         30  ...   646748.02

[4 rows x 3 columns]

Score.success
python /grader.py /platform/source/s01/v1_9/m00000000/m00000000_q2_t0.py /platform/output/m00000000/m00000000_q2_t0.csv /platform/expected/s01/q2.csv
>>> Expected
    S_ACCTBAL  ...                                          S_COMMENT
0     9828.21  ...             s the slyly even ideas poach fluffily 
1     9508.37  ...  ests sleep quickly express ideas. ironic ideas...
2     9508.37  ...  ests sleep quickly express ideas. ironic ideas...
3     9453.01  ...  gular frets. permanently special multipliers b...
4     9453.01  ...  gular frets. permanently special multipliers b...
5     9192.10  ...  es across the carefully express accounts boost...
6     9032.15  ...                      nding dependencies nag furiou
7     8702.02  ...  oss the deposits cajole carefully even pinto b...
8     8615.50  ...  y quickly regular deposits? quickly pending pa...
9     8615.50  ...  y quickly regular deposits? quickly pending pa...
10    8488.53  ...  ages. carefully final excuses nag finally. car...
11    8430.52  ...  ites among the always final ideas kindle accor...
12    8271.39  ...  s cajole quickly special requests. quickly ent...
13    8096.98  ...  ully after the regular requests. slyly final d...
14    7392.78  ...                   ake carefully across the quickly
15    7205.20  ...   excuses wake express deposits. furiously care...
16    6820.35  ...  s unwind silently furiously regular courts. fi...
17    6721.70  ...                   ect blithely blithely final acco
18    6329.90  ...                 ironic forges cajole blithely agai
19    6173.87  ...  blithely pending packages cajole furiously sly...
20    5364.99  ...      packages boost carefully. express ideas along
21    5069.27  ...           he unusual ideas. slyly final packages a
22    4941.88  ...                         y final requests impress s
23    4672.25  ...  arls wake furiously deposits. even, regular depen
24    4586.49  ...   the regularly regular dependencies. carefully...
25    4518.31  ...  ts detect along the foxes. final Tiresias are....
26    4315.15  ...  ronic orbits are furiously across the requests...
27    3526.53  ...                          lar dinos nag slyly brave
28    3526.53  ...                          lar dinos nag slyly brave
29    3294.68  ...  e slyly special foxes. furiously unusual depos...
30    2972.26  ...     ously express ideas haggle quickly dugouts? fu
31    2963.09  ...  eep blithely regular dependencies. blithely re...
32    2221.25  ...  nal foxes eat slyly about the fluffily permane...
33    1381.97  ...  gular ideas. bravely bold deposits haggle thro...
34     906.07  ...  ickly unusual requests cajole. accounts above ...
35     765.69  ...  nusual requests. furiously unusual epitaphs in...
36     727.89  ...  gular excuses. furiously regular excuses sleep...
37     683.07  ...                    ly regular requests cajole abou
38     167.56  ...    the theodolites. ironic, ironic deposits above 
39      91.39  ...       pinto beans. carefully express requests hagg
40    -314.06  ...                    bold deposits. carefully even d
41    -820.89  ...   y final, slow theodolites. furiously regular req
42    -845.44  ...                         ctions. carefully sly requ
43    -942.73  ...  slyly furiously final decoys; silent, special ...

[44 rows x 8 columns]

>>> Actual
    S_ACCTBAL  ...                                          S_COMMENT
0     9828.21  ...             s the slyly even ideas poach fluffily 
1     9508.37  ...  ests sleep quickly express ideas. ironic ideas...
2     9508.37  ...  ests sleep quickly express ideas. ironic ideas...
3     9453.01  ...  gular frets. permanently special multipliers b...
4     9453.01  ...  gular frets. permanently special multipliers b...
5     9192.10  ...  es across the carefully express accounts boost...
6     9032.15  ...                      nding dependencies nag furiou
7     8702.02  ...  oss the deposits cajole carefully even pinto b...
8     8615.50  ...  y quickly regular deposits? quickly pending pa...
9     8615.50  ...  y quickly regular deposits? quickly pending pa...
10    8488.53  ...  ages. carefully final excuses nag finally. car...
11    8430.52  ...  ites among the always final ideas kindle accor...
12    8271.39  ...  s cajole quickly special requests. quickly ent...
13    8096.98  ...  ully after the regular requests. slyly final d...
14    7392.78  ...                   ake carefully across the quickly
15    7205.20  ...   excuses wake express deposits. furiously care...
16    6820.35  ...  s unwind silently furiously regular courts. fi...
17    6721.70  ...                   ect blithely blithely final acco
18    6329.90  ...                 ironic forges cajole blithely agai
19    6173.87  ...  blithely pending packages cajole furiously sly...
20    5364.99  ...      packages boost carefully. express ideas along
21    5069.27  ...           he unusual ideas. slyly final packages a
22    4941.88  ...                         y final requests impress s
23    4672.25  ...  arls wake furiously deposits. even, regular depen
24    4586.49  ...   the regularly regular dependencies. carefully...
25    4518.31  ...  ts detect along the foxes. final Tiresias are....
26    4315.15  ...  ronic orbits are furiously across the requests...
27    3526.53  ...                          lar dinos nag slyly brave
28    3526.53  ...                          lar dinos nag slyly brave
29    3294.68  ...  e slyly special foxes. furiously unusual depos...
30    2972.26  ...     ously express ideas haggle quickly dugouts? fu
31    2963.09  ...  eep blithely regular dependencies. blithely re...
32    2221.25  ...  nal foxes eat slyly about the fluffily permane...
33    1381.97  ...  gular ideas. bravely bold deposits haggle thro...
34     906.07  ...  ickly unusual requests cajole. accounts above ...
35     765.69  ...  nusual requests. furiously unusual epitaphs in...
36     727.89  ...  gular excuses. furiously regular excuses sleep...
37     683.07  ...                    ly regular requests cajole abou
38     167.56  ...    the theodolites. ironic, ironic deposits above 
39      91.39  ...       pinto beans. carefully express requests hagg
40    -314.06  ...                    bold deposits. carefully even d
41    -820.89  ...   y final, slow theodolites. furiously regular req
42    -845.44  ...                         ctions. carefully sly requ
43    -942.73  ...  slyly furiously final decoys; silent, special ...

[44 rows x 8 columns]

Score.success
python /grader.py /platform/source/s01/v1_9/m00000000/m00000000_q2_t1.py /platform/output/m00000000/m00000000_q2_t1.csv /platform/expected/s01/q2.csv
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m00000000/m00000000_q2_t2.py /platform/output/m00000000/m00000000_q2_t2.csv /platform/expected/s01/q2.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m00000000/m00000000_q2_t2.py", line 55, in <module>
    cursor.execute(query)
  File "/usr/local/lib/python3.8/dist-packages/mysql/connector/cursor.py", line 617, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/usr/local/lib/python3.8/dist-packages/mysql/connector/opentelemetry/context_propagation.py", line 77, in wrapper
    return method(cnx, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/mysql/connector/connection.py", line 843, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "/usr/local/lib/python3.8/dist-packages/mysql/connector/connection.py", line 620, in _handle_result
    raise get_exception(packet)
mysql.connector.errors.ProgrammingError: 1146 (42S02): Table 'tpch.PART' doesn't exist
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m00000000/m00000000_q3_t0.py /platform/output/m00000000/m00000000_q3_t0.csv /platform/expected/s01/q3.csv
>>> Expected
      L_ORDERKEY  ...  O_SHIPPRIORITY
0         223140  ...               0
1         584291  ...               0
2         405063  ...               0
3         573861  ...               0
4         554757  ...               0
...          ...  ...             ...
1211      152096  ...               0
1212      521728  ...               0
1213      445159  ...               0
1214      598597  ...               0
1215      135490  ...               0

[1216 rows x 4 columns]

>>> Actual
      L_ORDERKEY  ...  O_SHIPPRIORITY
0         223140  ...               0
1         584291  ...               0
2         405063  ...               0
3         573861  ...               0
4         554757  ...               0
...          ...  ...             ...
1211      152096  ...               0
1212      521728  ...               0
1213      445159  ...               0
1214      598597  ...               0
1215      135490  ...               0

[1216 rows x 4 columns]

Score.success
python /grader.py /platform/source/s01/v1_9/m00000000/m00000000_q3_t1.py /platform/output/m00000000/m00000000_q3_t1.csv /platform/expected/s01/q3.csv
>>> Expected
      L_ORDERKEY  ...  O_SHIPPRIORITY
0         223140  ...               0
1         584291  ...               0
2         405063  ...               0
3         573861  ...               0
4         554757  ...               0
...          ...  ...             ...
1211      152096  ...               0
1212      521728  ...               0
1213      445159  ...               0
1214      598597  ...               0
1215      135490  ...               0

[1216 rows x 4 columns]

>>> Actual
      L_ORDERKEY  ...  O_SHIPPRIORITY
0         223140  ...               0
1         584291  ...               0
2         405063  ...               0
3         573861  ...               0
4         554757  ...               0
...          ...  ...             ...
1211      152096  ...               0
1212      521728  ...               0
1213      445159  ...               0
1214      598597  ...               0
1215      135490  ...               0

[1216 rows x 4 columns]

Score.success
python /grader.py /platform/source/s01/v1_9/m00000000/m00000000_q3_t2.py /platform/output/m00000000/m00000000_q3_t2.csv /platform/expected/s01/q3.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m00000000/m00000000_q3_t2.py", line 39, in <module>
    cursor.execute(sql)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 822, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'tpch.CUSTOMER' doesn't exist")
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m00000000/m00000000_q4_t0.py /platform/output/m00000000/m00000000_q4_t0.csv /platform/expected/s01/q4.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m00000000/m00000000_q4_t0.py", line 38, in <module>
    cursor.execute(sql)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 822, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'tpch.ORDERS' doesn't exist")
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m00000000/m00000000_q4_t1.py /platform/output/m00000000/m00000000_q4_t1.csv /platform/expected/s01/q4.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m00000000/m00000000_q4_t1.py", line 13, in <module>
    cursor.execute("""
  File "/usr/local/lib/python3.8/dist-packages/mysql/connector/cursor.py", line 617, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/usr/local/lib/python3.8/dist-packages/mysql/connector/opentelemetry/context_propagation.py", line 77, in wrapper
    return method(cnx, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/mysql/connector/connection.py", line 843, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "/usr/local/lib/python3.8/dist-packages/mysql/connector/connection.py", line 620, in _handle_result
    raise get_exception(packet)
mysql.connector.errors.ProgrammingError: 1146 (42S02): Table 'tpch.ORDERS' doesn't exist
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m00000000/m00000000_q4_t2.py /platform/output/m00000000/m00000000_q4_t2.csv /platform/expected/s01/q4.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m00000000/m00000000_q4_t2.py", line 44, in <module>
    rows = [list(item.values()) for item in rows]
  File "/platform/source/s01/v1_9/m00000000/m00000000_q4_t2.py", line 44, in <listcomp>
    rows = [list(item.values()) for item in rows]
AttributeError: 'tuple' object has no attribute 'values'
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m00000000/m00000000_q5_t0.py /platform/output/m00000000/m00000000_q5_t0.csv /platform/expected/s01/q5.csv
>>> Expected
      N_NAME       REVENUE
0      CHINA  2.094870e+07
1  INDONESIA  1.765375e+07
2      INDIA  1.758996e+07
3      JAPAN  1.634845e+07
4    VIETNAM  1.433735e+07

>>> Actual
       CHINA  20948697.3002
0  INDONESIA   1.765375e+07
1      INDIA   1.758996e+07
2      JAPAN   1.634845e+07
3    VIETNAM   1.433735e+07

Score.fail_wrong_output
python /grader.py /platform/source/s01/v1_9/m00000000/m00000000_q5_t1.py /platform/output/m00000000/m00000000_q5_t1.csv /platform/expected/s01/q5.csv
>>> Expected
      N_NAME       REVENUE
0      CHINA  2.094870e+07
1  INDONESIA  1.765375e+07
2      INDIA  1.758996e+07
3      JAPAN  1.634845e+07
4    VIETNAM  1.433735e+07

>>> Actual
      N_NAME       REVENUE
0      CHINA  2.094870e+07
1  INDONESIA  1.765375e+07
2      INDIA  1.758996e+07
3      JAPAN  1.634845e+07
4    VIETNAM  1.433735e+07

Score.success
python /grader.py /platform/source/s01/v1_9/m00000000/m00000000_q5_t2.py /platform/output/m00000000/m00000000_q5_t2.csv /platform/expected/s01/q5.csv
/platform/source/s01/v1_9/m00000000/m00000000_q5_t2.py:36: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, cnx)
>>> Expected
      N_NAME       REVENUE
0      CHINA  2.094870e+07
1  INDONESIA  1.765375e+07
2      INDIA  1.758996e+07
3      JAPAN  1.634845e+07
4    VIETNAM  1.433735e+07

>>> Actual
      N_NAME       REVENUE
0      CHINA  2.094870e+07
1  INDONESIA  1.765375e+07
2      INDIA  1.758996e+07
3      JAPAN  1.634845e+07
4    VIETNAM  1.433735e+07

Score.success
python /grader.py /platform/source/s01/v1_9/m00000000/m00000000_q6_t0.py /platform/output/m00000000/m00000000_q6_t0.csv /platform/expected/s01/q6.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m00000000/m00000000_q6_t0.py", line 27, in <module>
    cursor.execute(sql)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 822, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'tpch.LINEITEM' doesn't exist")
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m00000000/m00000000_q6_t1.py /platform/output/m00000000/m00000000_q6_t1.csv /platform/expected/s01/q6.csv
>>> Expected
        REVENUE
0  7.115407e+06

>>> Actual
        REVENUE
0  1.180342e+07

Score.fail_wrong_output
python /grader.py /platform/source/s01/v1_9/m00000000/m00000000_q6_t2.py /platform/output/m00000000/m00000000_q6_t2.csv /platform/expected/s01/q6.csv
/platform/source/s01/v1_9/m00000000/m00000000_q6_t2.py:22: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  dataframe = pd.read_sql(query, cnx)
>>> Expected
        REVENUE
0  7.115407e+06

>>> Actual
        REVENUE
0  1.180342e+07

Score.fail_wrong_output
python /grader.py /platform/source/s01/v1_9/m00000000/m00000000_q7_t0.py /platform/output/m00000000/m00000000_q7_t0.csv /platform/expected/s01/q7.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m00000000/m00000000_q7_t0.py", line 2, in <module>
    import MySQLdb
ModuleNotFoundError: No module named 'MySQLdb'
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m00000000/m00000000_q7_t1.py /platform/output/m00000000/m00000000_q7_t1.csv /platform/expected/s01/q7.csv
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1969, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 822, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'N1.N_NAME' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m00000000/m00000000_q7_t1.py", line 29, in <module>
    df = pd.read_sql_query(query, engine)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/sql.py", line 469, in read_sql_query
    return pandas_sql.read_query(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/sql.py", line 1738, in read_query
    result = self.execute(sql, params)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/sql.py", line 1562, in execute
    return self.con.exec_driver_sql(sql, *args)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1778, in exec_driver_sql
    ret = self._execute_context(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1848, in _execute_context
    return self._exec_single_context(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1988, in _exec_single_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 2343, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1969, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 822, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1054, "Unknown column 'N1.N_NAME' in 'field list'")
[SQL: 
    SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
    FROM (
        SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION,
        YEAR(L_SHIPDATE) AS L_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
        FROM supplier, lineitem, orders, customer, nation n1, nation n2
        WHERE S_SUPPKEY = L_SUPPKEY AND O_ORDERKEY = L_ORDERKEY AND C_CUSTKEY = O_CUSTKEY
        AND S_NATIONKEY = N1.N_NATIONKEY AND C_NATIONKEY = N2.N_NATIONKEY
        AND ((N1.N_NAME = 'JAPAN' AND N2.N_NAME = 'INDIA') 
        OR (N1.N_NAME = 'INDIA' AND N2.N_NAME = 'JAPAN')) 
        AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31'
    ) AS SHIPPING
    GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
    ORDER BY SUPP_NATION, CUST_NATION, L_YEAR
]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m00000000/m00000000_q7_t2.py /platform/output/m00000000/m00000000_q7_t2.csv /platform/expected/s01/q7.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m00000000/m00000000_q7_t2.py", line 56, in <module>
    cursor.execute(query)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 822, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'tpch.SUPPLIER' doesn't exist")
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m00000000/m00000000_q8_t0.py /platform/output/m00000000/m00000000_q8_t0.csv /platform/expected/s01/q8.csv
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1969, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.8/dist-packages/mysql/connector/cursor.py", line 617, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/usr/local/lib/python3.8/dist-packages/mysql/connector/opentelemetry/context_propagation.py", line 77, in wrapper
    return method(cnx, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/mysql/connector/connection.py", line 843, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "/usr/local/lib/python3.8/dist-packages/mysql/connector/connection.py", line 620, in _handle_result
    raise get_exception(packet)
mysql.connector.errors.ProgrammingError: 1146 (42S02): Table 'tpch.PART' doesn't exist

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m00000000/m00000000_q8_t0.py", line 46, in <module>
    data = pd.read_sql_query(query, engine)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/sql.py", line 469, in read_sql_query
    return pandas_sql.read_query(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/sql.py", line 1738, in read_query
    result = self.execute(sql, params)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/sql.py", line 1562, in execute
    return self.con.exec_driver_sql(sql, *args)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1778, in exec_driver_sql
    ret = self._execute_context(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1848, in _execute_context
    return self._exec_single_context(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1988, in _exec_single_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 2343, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1969, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.8/dist-packages/mysql/connector/cursor.py", line 617, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/usr/local/lib/python3.8/dist-packages/mysql/connector/opentelemetry/context_propagation.py", line 77, in wrapper
    return method(cnx, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/mysql/connector/connection.py", line 843, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "/usr/local/lib/python3.8/dist-packages/mysql/connector/connection.py", line 620, in _handle_result
    raise get_exception(packet)
sqlalchemy.exc.ProgrammingError: (mysql.connector.errors.ProgrammingError) 1146 (42S02): Table 'tpch.PART' doesn't exist
[SQL: 
SELECT
    O_YEAR,
    SUM(CASE WHEN NATION = 'INDIA' THEN VOLUME ELSE 0 END) / SUM(VOLUME) AS MKT_SHARE
FROM
    (
    SELECT
        YEAR(O_ORDERDATE) AS O_YEAR,
        L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME,
        N2.N_NAME AS NATION
    FROM
        PART,
        SUPPLIER,
        LINEITEM,
        ORDERS,
        CUSTOMER,
        NATION AS N1,
        NATION AS N2,
        REGION
    WHERE
        P_PARTKEY = L_PARTKEY
        AND S_SUPPKEY = L_SUPPKEY
        AND L_ORDERKEY = O_ORDERKEY
        AND O_CUSTKEY = C_CUSTKEY
        AND C_NATIONKEY = N1.N_NATIONKEY
        AND N1.N_REGIONKEY = R_REGIONKEY
        AND R_NAME = 'ASIA'
        AND S_NATIONKEY = N2.N_NATIONKEY
        AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
        AND P_TYPE = 'SMALL PLATED COPPER'
    ) AS ALL_NATIONS
GROUP BY
    O_YEAR
ORDER BY
    O_YEAR
]
(Background on this error at: https://sqlalche.me/e/20/f405)
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m00000000/m00000000_q8_t1.py /platform/output/m00000000/m00000000_q8_t1.csv /platform/expected/s01/q8.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m00000000/m00000000_q8_t1.py", line 14, in <module>
    cursor.execute("""
  File "/usr/local/lib/python3.8/dist-packages/mysql/connector/cursor.py", line 617, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/usr/local/lib/python3.8/dist-packages/mysql/connector/opentelemetry/context_propagation.py", line 77, in wrapper
    return method(cnx, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/mysql/connector/connection.py", line 843, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "/usr/local/lib/python3.8/dist-packages/mysql/connector/connection.py", line 620, in _handle_result
    raise get_exception(packet)
mysql.connector.errors.ProgrammingError: 1146 (42S02): Table 'tpch.PART' doesn't exist
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m00000000/m00000000_q8_t2.py /platform/output/m00000000/m00000000_q8_t2.csv /platform/expected/s01/q8.csv
/platform/source/s01/v1_9/m00000000/m00000000_q8_t2.py:36: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, connection)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/sql.py", line 2202, in execute
    cur.execute(sql, *args)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 822, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 1207, in read
    self._read_result_packet(first_packet)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 1284, in _read_result_packet
    self._read_rowdata_packet()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 1331, in _read_rowdata_packet
    packet = self.connection._read_packet()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (3, "Error writing file '/tmp/MYpYIPM7' (OS errno 28 - No space left on device)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m00000000/m00000000_q8_t2.py", line 36, in <module>
    df = pd.read_sql(query, connection)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/sql.py", line 635, in read_sql
    return pandas_sql.read_query(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/sql.py", line 2266, in read_query
    cursor = self.execute(sql, params)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/sql.py", line 2214, in execute
    raise ex from exc
pandas.errors.DatabaseError: Execution failed on sql '
SELECT O_YEAR, 
    SUM(CASE WHEN NATION = 'INDIA' THEN VOLUME ELSE 0 END) / SUM(VOLUME) AS MKT_SHARE 
FROM (
    SELECT 
        YEAR(O_ORDERDATE) AS O_YEAR, 
        L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, 
        N2.N_NAME AS NATION 
    FROM part, supplier, lineitem, orders, customer, nation N1, nation N2, region 
    WHERE P_PARTKEY = L_PARTKEY
        AND S_SUPPKEY = L_SUPPKEY 
        AND L_ORDERKEY = O_ORDERKEY 
        AND O_CUSTKEY = C_CUSTKEY 
        AND C_NATIONKEY = N1.N_NATIONKEY 
        AND N1.N_REGIONKEY = R_REGIONKEY 
        AND R_NAME = 'ASIA' 
        AND S_NATIONKEY = N2.N_NATIONKEY 
        AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31' 
        AND P_TYPE = 'SMALL PLATED COPPER'
) AS ALL_NATIONS 
GROUP BY O_YEAR 
ORDER BY O_YEAR;
': (3, "Error writing file '/tmp/MYpYIPM7' (OS errno 28 - No space left on device)")
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m00000000/m00000000_q9_t0.py /platform/output/m00000000/m00000000_q9_t0.csv /platform/expected/s01/q9.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m00000000/m00000000_q9_t0.py", line 12, in <module>
    cursor.execute("""
  File "/usr/local/lib/python3.8/dist-packages/mysql/connector/cursor.py", line 617, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/usr/local/lib/python3.8/dist-packages/mysql/connector/opentelemetry/context_propagation.py", line 77, in wrapper
    return method(cnx, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/mysql/connector/connection.py", line 843, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "/usr/local/lib/python3.8/dist-packages/mysql/connector/connection.py", line 620, in _handle_result
    raise get_exception(packet)
mysql.connector.errors.ProgrammingError: 1146 (42S02): Table 'tpch.PART' doesn't exist
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m00000000/m00000000_q9_t1.py /platform/output/m00000000/m00000000_q9_t1.csv /platform/expected/s01/q9.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m00000000/m00000000_q9_t1.py", line 46, in <module>
    cursor.execute(query)
  File "/usr/local/lib/python3.8/dist-packages/mysql/connector/cursor.py", line 617, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/usr/local/lib/python3.8/dist-packages/mysql/connector/opentelemetry/context_propagation.py", line 77, in wrapper
    return method(cnx, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/mysql/connector/connection.py", line 843, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "/usr/local/lib/python3.8/dist-packages/mysql/connector/connection.py", line 620, in _handle_result
    raise get_exception(packet)
mysql.connector.errors.ProgrammingError: 1146 (42S02): Table 'tpch.PART' doesn't exist
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m00000000/m00000000_q9_t2.py /platform/output/m00000000/m00000000_q9_t2.csv /platform/expected/s01/q9.csv
/platform/source/s01/v1_9/m00000000/m00000000_q9_t2.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(sql, con=mydb) # execute the query and take the data in pandas dataframe
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/sql.py", line 2202, in execute
    cur.execute(sql, *args)
  File "/usr/local/lib/python3.8/dist-packages/mysql/connector/cursor.py", line 617, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/usr/local/lib/python3.8/dist-packages/mysql/connector/opentelemetry/context_propagation.py", line 77, in wrapper
    return method(cnx, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/mysql/connector/connection.py", line 843, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "/usr/local/lib/python3.8/dist-packages/mysql/connector/connection.py", line 620, in _handle_result
    raise get_exception(packet)
mysql.connector.errors.ProgrammingError: 1146 (42S02): Table 'tpch.PART' doesn't exist

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m00000000/m00000000_q9_t2.py", line 51, in <module>
    df = pd.read_sql(sql, con=mydb) # execute the query and take the data in pandas dataframe
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/sql.py", line 635, in read_sql
    return pandas_sql.read_query(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/sql.py", line 2266, in read_query
    cursor = self.execute(sql, params)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/sql.py", line 2214, in execute
    raise ex from exc
pandas.errors.DatabaseError: Execution failed on sql '
SELECT
    NATION,
    YEAR(O_ORDERDATE) AS O_YEAR,
    SUM(AMOUNT) AS SUM_PROFIT
FROM
    (
    SELECT
        N_NAME AS NATION,
        O_ORDERDATE AS O_YEAR,
        L_EXTENDEDPRICE * (1 - L_DISCOUNT) - PS_SUPPLYCOST * L_QUANTITY AS AMOUNT
    FROM
        PART,
        SUPPLIER,
        LINEITEM,
        PARTSUPP,
        ORDERS,
        NATION
    WHERE
        S_SUPPKEY = L_SUPPKEY
        AND PS_SUPPKEY = L_SUPPKEY
        AND PS_PARTKEY = L_PARTKEY
        AND P_PARTKEY = L_PARTKEY
        AND O_ORDERKEY = L_ORDERKEY
        AND S_NATIONKEY = N_NATIONKEY
        AND P_NAME LIKE '%dim%'
    ) AS PROFIT
GROUP BY
    NATION,
    O_YEAR
ORDER BY
    NATION,
    O_YEAR DESC
': 1146 (42S02): Table 'tpch.PART' doesn't exist
Score.fail_missing_output
