Running /platform/source/s01/v1_9/m11111111/m11111111_q10_t0.sh
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.5.0)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v1_9/m11111111/m11111111_q10_t1.sh
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.5.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Collecting sklearn
  Downloading sklearn-0.0.post10.tar.gz (3.6 kB)
[31m    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-u2gji2x0/sklearn/setup.py'"'"'; __file__='"'"'/tmp/pip-install-u2gji2x0/sklearn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-u2gji2x0/sklearn/pip-egg-info
         cwd: /tmp/pip-install-u2gji2x0/sklearn/
    Complete output (18 lines):
    The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
    rather than 'sklearn' for pip commands.
    
    Here is how to fix this error in the main use cases:
    - use 'pip install scikit-learn' rather than 'pip install sklearn'
    - replace 'sklearn' by 'scikit-learn' in your pip requirements files
      (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
    - if the 'sklearn' package is used by one of your dependencies,
      it would be great if you take some time to track which package uses
      'sklearn' instead of 'scikit-learn' and report it to their issue tracker
    - as a last resort, set the environment variable
      SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error
    
    More information is available at
    https://github.com/scikit-learn/sklearn-pypi-package
    
    If the previous advice does not cover your use case, feel free to report it at
    https://github.com/scikit-learn/sklearn-pypi-package/issues/new
    ----------------------------------------[0m
[31mERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.[0m
Running /platform/source/s01/v1_9/m11111111/m11111111_q10_t2.sh
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.5.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v1_9/m11111111/m11111111_q11_t0.sh
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.5.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v1_9/m11111111/m11111111_q11_t1.sh
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.5.0)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v1_9/m11111111/m11111111_q11_t2.sh
/platform/source/s01/v1_9/m11111111/m11111111_q11_t2.sh: line 1: sudo: command not found
Running /platform/source/s01/v1_9/m11111111/m11111111_q12_t0.sh
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.5.0)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v1_9/m11111111/m11111111_q12_t1.sh
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.5.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v1_9/m11111111/m11111111_q12_t2.sh
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v1_9/m11111111/m11111111_q13_t0.sh
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.5.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v1_9/m11111111/m11111111_q13_t1.sh
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.5.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v1_9/m11111111/m11111111_q13_t2.sh
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.5.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: dnspython in /usr/local/lib/python3.8/dist-packages (2.4.2)
Collecting pandasql
  Downloading pandasql-0.7.3.tar.gz (26 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Collecting sqlalchemy
  Downloading SQLAlchemy-2.0.23-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (3.1 MB)
[?25l[K     |                                | 10 kB 5.7 MB/s eta 0:00:01[K     |▏                               | 20 kB 4.5 MB/s eta 0:00:01[K     |▎                               | 30 kB 6.6 MB/s eta 0:00:01[K     |▍                               | 40 kB 4.6 MB/s eta 0:00:01[K     |▌                               | 51 kB 4.6 MB/s eta 0:00:01[K     |▋                               | 61 kB 5.5 MB/s eta 0:00:01[K     |▊                               | 71 kB 5.0 MB/s eta 0:00:01[K     |▉                               | 81 kB 5.1 MB/s eta 0:00:01[K     |█                               | 92 kB 5.7 MB/s eta 0:00:01[K     |█                               | 102 kB 5.5 MB/s eta 0:00:01[K     |█▏                              | 112 kB 5.5 MB/s eta 0:00:01[K     |█▎                              | 122 kB 5.5 MB/s eta 0:00:01[K     |█▍                              | 133 kB 5.5 MB/s eta 0:00:01[K     |█▌                              | 143 kB 5.5 MB/s eta 0:00:01[K     |█▋                              | 153 kB 5.5 MB/s eta 0:00:01[K     |█▊                              | 163 kB 5.5 MB/s eta 0:00:01[K     |█▉                              | 174 kB 5.5 MB/s eta 0:00:01[K     |██                              | 184 kB 5.5 MB/s eta 0:00:01[K     |██                              | 194 kB 5.5 MB/s eta 0:00:01[K     |██▏                             | 204 kB 5.5 MB/s eta 0:00:01[K     |██▎                             | 215 kB 5.5 MB/s eta 0:00:01[K     |██▍                             | 225 kB 5.5 MB/s eta 0:00:01[K     |██▌                             | 235 kB 5.5 MB/s eta 0:00:01[K     |██▋                             | 245 kB 5.5 MB/s eta 0:00:01[K     |██▊                             | 256 kB 5.5 MB/s eta 0:00:01[K     |██▉                             | 266 kB 5.5 MB/s eta 0:00:01[K     |███                             | 276 kB 5.5 MB/s eta 0:00:01[K     |███                             | 286 kB 5.5 MB/s eta 0:00:01[K     |███                             | 296 kB 5.5 MB/s eta 0:00:01[K     |███▏                            | 307 kB 5.5 MB/s eta 0:00:01[K     |███▎                            | 317 kB 5.5 MB/s eta 0:00:01[K     |███▍                            | 327 kB 5.5 MB/s eta 0:00:01[K     |███▌                            | 337 kB 5.5 MB/s eta 0:00:01[K     |███▋                            | 348 kB 5.5 MB/s eta 0:00:01[K     |███▊                            | 358 kB 5.5 MB/s eta 0:00:01[K     |███▉                            | 368 kB 5.5 MB/s eta 0:00:01[K     |████                            | 378 kB 5.5 MB/s eta 0:00:01[K     |████                            | 389 kB 5.5 MB/s eta 0:00:01[K     |████▏                           | 399 kB 5.5 MB/s eta 0:00:01[K     |████▎                           | 409 kB 5.5 MB/s eta 0:00:01[K     |████▍                           | 419 kB 5.5 MB/s eta 0:00:01[K     |████▌                           | 430 kB 5.5 MB/s eta 0:00:01[K     |████▋                           | 440 kB 5.5 MB/s eta 0:00:01[K     |████▊                           | 450 kB 5.5 MB/s eta 0:00:01[K     |████▉                           | 460 kB 5.5 MB/s eta 0:00:01[K     |█████                           | 471 kB 5.5 MB/s eta 0:00:01[K     |█████                           | 481 kB 5.5 MB/s eta 0:00:01[K     |█████▏                          | 491 kB 5.5 MB/s eta 0:00:01[K     |█████▎                          | 501 kB 5.5 MB/s eta 0:00:01[K     |█████▍                          | 512 kB 5.5 MB/s eta 0:00:01[K     |█████▌                          | 522 kB 5.5 MB/s eta 0:00:01[K     |█████▋                          | 532 kB 5.5 MB/s eta 0:00:01[K     |█████▊                          | 542 kB 5.5 MB/s eta 0:00:01[K     |█████▉                          | 552 kB 5.5 MB/s eta 0:00:01[K     |█████▉                          | 563 kB 5.5 MB/s eta 0:00:01[K     |██████                          | 573 kB 5.5 MB/s eta 0:00:01[K     |██████                          | 583 kB 5.5 MB/s eta 0:00:01[K     |██████▏                         | 593 kB 5.5 MB/s eta 0:00:01[K     |██████▎                         | 604 kB 5.5 MB/s eta 0:00:01[K     |██████▍                         | 614 kB 5.5 MB/s eta 0:00:01[K     |██████▌                         | 624 kB 5.5 MB/s eta 0:00:01[K     |██████▋                         | 634 kB 5.5 MB/s eta 0:00:01[K     |██████▊                         | 645 kB 5.5 MB/s eta 0:00:01[K     |██████▉                         | 655 kB 5.5 MB/s eta 0:00:01[K     |███████                         | 665 kB 5.5 MB/s eta 0:00:01[K     |███████                         | 675 kB 5.5 MB/s eta 0:00:01[K     |███████▏                        | 686 kB 5.5 MB/s eta 0:00:01[K     |███████▎                        | 696 kB 5.5 MB/s eta 0:00:01[K     |███████▍                        | 706 kB 5.5 MB/s eta 0:00:01[K     |███████▌                        | 716 kB 5.5 MB/s eta 0:00:01[K     |███████▋                        | 727 kB 5.5 MB/s eta 0:00:01[K     |███████▊                        | 737 kB 5.5 MB/s eta 0:00:01[K     |███████▉                        | 747 kB 5.5 MB/s eta 0:00:01[K     |████████                        | 757 kB 5.5 MB/s eta 0:00:01[K     |████████                        | 768 kB 5.5 MB/s eta 0:00:01[K     |████████▏                       | 778 kB 5.5 MB/s eta 0:00:01[K     |████████▎                       | 788 kB 5.5 MB/s eta 0:00:01[K     |████████▍                       | 798 kB 5.5 MB/s eta 0:00:01[K     |████████▌                       | 808 kB 5.5 MB/s eta 0:00:01[K     |████████▋                       | 819 kB 5.5 MB/s eta 0:00:01[K     |████████▊                       | 829 kB 5.5 MB/s eta 0:00:01[K     |████████▉                       | 839 kB 5.5 MB/s eta 0:00:01[K     |████████▉                       | 849 kB 5.5 MB/s eta 0:00:01[K     |█████████                       | 860 kB 5.5 MB/s eta 0:00:01[K     |█████████                       | 870 kB 5.5 MB/s eta 0:00:01[K     |█████████▏                      | 880 kB 5.5 MB/s eta 0:00:01[K     |█████████▎                      | 890 kB 5.5 MB/s eta 0:00:01[K     |█████████▍                      | 901 kB 5.5 MB/s eta 0:00:01[K     |█████████▌                      | 911 kB 5.5 MB/s eta 0:00:01[K     |█████████▋                      | 921 kB 5.5 MB/s eta 0:00:01[K     |█████████▊                      | 931 kB 5.5 MB/s eta 0:00:01[K     |█████████▉                      | 942 kB 5.5 MB/s eta 0:00:01[K     |██████████                      | 952 kB 5.5 MB/s eta 0:00:01[K     |██████████                      | 962 kB 5.5 MB/s eta 0:00:01[K     |██████████▏                     | 972 kB 5.5 MB/s eta 0:00:01[K     |██████████▎                     | 983 kB 5.5 MB/s eta 0:00:01[K     |██████████▍                     | 993 kB 5.5 MB/s eta 0:00:01[K     |██████████▌                     | 1.0 MB 5.5 MB/s eta 0:00:01[K     |██████████▋                     | 1.0 MB 5.5 MB/s eta 0:00:01[K     |██████████▊                     | 1.0 MB 5.5 MB/s eta 0:00:01[K     |██████████▉                     | 1.0 MB 5.5 MB/s eta 0:00:01[K     |███████████                     | 1.0 MB 5.5 MB/s eta 0:00:01[K     |███████████                     | 1.1 MB 5.5 MB/s eta 0:00:01[K     |███████████▏                    | 1.1 MB 5.5 MB/s eta 0:00:01[K     |███████████▎                    | 1.1 MB 5.5 MB/s eta 0:00:01[K     |███████████▍                    | 1.1 MB 5.5 MB/s eta 0:00:01[K     |███████████▌                    | 1.1 MB 5.5 MB/s eta 0:00:01[K     |███████████▋                    | 1.1 MB 5.5 MB/s eta 0:00:01[K     |███████████▊                    | 1.1 MB 5.5 MB/s eta 0:00:01[K     |███████████▊                    | 1.1 MB 5.5 MB/s eta 0:00:01[K     |███████████▉                    | 1.1 MB 5.5 MB/s eta 0:00:01[K     |████████████                    | 1.1 MB 5.5 MB/s eta 0:00:01[K     |████████████                    | 1.2 MB 5.5 MB/s eta 0:00:01[K     |████████████▏                   | 1.2 MB 5.5 MB/s eta 0:00:01[K     |████████████▎                   | 1.2 MB 5.5 MB/s eta 0:00:01[K     |████████████▍                   | 1.2 MB 5.5 MB/s eta 0:00:01[K     |████████████▌                   | 1.2 MB 5.5 MB/s eta 0:00:01[K     |████████████▋                   | 1.2 MB 5.5 MB/s eta 0:00:01[K     |████████████▊                   | 1.2 MB 5.5 MB/s eta 0:00:01[K     |████████████▉                   | 1.2 MB 5.5 MB/s eta 0:00:01[K     |█████████████                   | 1.2 MB 5.5 MB/s eta 0:00:01[K     |█████████████                   | 1.2 MB 5.5 MB/s eta 0:00:01[K     |█████████████▏                  | 1.3 MB 5.5 MB/s eta 0:00:01[K     |█████████████▎                  | 1.3 MB 5.5 MB/s eta 0:00:01[K     |█████████████▍                  | 1.3 MB 5.5 MB/s eta 0:00:01[K     |█████████████▌                  | 1.3 MB 5.5 MB/s eta 0:00:01[K     |█████████████▋                  | 1.3 MB 5.5 MB/s eta 0:00:01[K     |█████████████▊                  | 1.3 MB 5.5 MB/s eta 0:00:01[K     |█████████████▉                  | 1.3 MB 5.5 MB/s eta 0:00:01[K     |██████████████                  | 1.3 MB 5.5 MB/s eta 0:00:01[K     |██████████████                  | 1.3 MB 5.5 MB/s eta 0:00:01[K     |██████████████▏                 | 1.4 MB 5.5 MB/s eta 0:00:01[K     |██████████████▎                 | 1.4 MB 5.5 MB/s eta 0:00:01[K     |██████████████▍                 | 1.4 MB 5.5 MB/s eta 0:00:01[K     |██████████████▌                 | 1.4 MB 5.5 MB/s eta 0:00:01[K     |██████████████▋                 | 1.4 MB 5.5 MB/s eta 0:00:01[K     |██████████████▋                 | 1.4 MB 5.5 MB/s eta 0:00:01[K     |██████████████▊                 | 1.4 MB 5.5 MB/s eta 0:00:01[K     |██████████████▉                 | 1.4 MB 5.5 MB/s eta 0:00:01[K     |███████████████                 | 1.4 MB 5.5 MB/s eta 0:00:01[K     |███████████████                 | 1.4 MB 5.5 MB/s eta 0:00:01[K     |███████████████▏                | 1.5 MB 5.5 MB/s eta 0:00:01[K     |███████████████▎                | 1.5 MB 5.5 MB/s eta 0:00:01[K     |███████████████▍                | 1.5 MB 5.5 MB/s eta 0:00:01[K     |███████████████▌                | 1.5 MB 5.5 MB/s eta 0:00:01[K     |███████████████▋                | 1.5 MB 5.5 MB/s eta 0:00:01[K     |███████████████▊                | 1.5 MB 5.5 MB/s eta 0:00:01[K     |███████████████▉                | 1.5 MB 5.5 MB/s eta 0:00:01[K     |████████████████                | 1.5 MB 5.5 MB/s eta 0:00:01[K     |████████████████                | 1.5 MB 5.5 MB/s eta 0:00:01[K     |████████████████▏               | 1.5 MB 5.5 MB/s eta 0:00:01[K     |████████████████▎               | 1.6 MB 5.5 MB/s eta 0:00:01[K     |████████████████▍               | 1.6 MB 5.5 MB/s eta 0:00:01[K     |████████████████▌               | 1.6 MB 5.5 MB/s eta 0:00:01[K     |████████████████▋               | 1.6 MB 5.5 MB/s eta 0:00:01[K     |████████████████▊               | 1.6 MB 5.5 MB/s eta 0:00:01[K     |████████████████▉               | 1.6 MB 5.5 MB/s eta 0:00:01[K     |█████████████████               | 1.6 MB 5.5 MB/s eta 0:00:01[K     |█████████████████               | 1.6 MB 5.5 MB/s eta 0:00:01[K     |█████████████████▏              | 1.6 MB 5.5 MB/s eta 0:00:01[K     |█████████████████▎              | 1.6 MB 5.5 MB/s eta 0:00:01[K     |█████████████████▍              | 1.7 MB 5.5 MB/s eta 0:00:01[K     |█████████████████▌              | 1.7 MB 5.5 MB/s eta 0:00:01[K     |█████████████████▋              | 1.7 MB 5.5 MB/s eta 0:00:01[K     |█████████████████▋              | 1.7 MB 5.5 MB/s eta 0:00:01[K     |█████████████████▊              | 1.7 MB 5.5 MB/s eta 0:00:01[K     |█████████████████▉              | 1.7 MB 5.5 MB/s eta 0:00:01[K     |██████████████████              | 1.7 MB 5.5 MB/s eta 0:00:01[K     |██████████████████              | 1.7 MB 5.5 MB/s eta 0:00:01[K     |██████████████████▏             | 1.7 MB 5.5 MB/s eta 0:00:01[K     |██████████████████▎             | 1.8 MB 5.5 MB/s eta 0:00:01[K     |██████████████████▍             | 1.8 MB 5.5 MB/s eta 0:00:01[K     |██████████████████▌             | 1.8 MB 5.5 MB/s eta 0:00:01[K     |██████████████████▋             | 1.8 MB 5.5 MB/s eta 0:00:01[K     |██████████████████▊             | 1.8 MB 5.5 MB/s eta 0:00:01[K     |██████████████████▉             | 1.8 MB 5.5 MB/s eta 0:00:01[K     |███████████████████             | 1.8 MB 5.5 MB/s eta 0:00:01[K     |███████████████████             | 1.8 MB 5.5 MB/s eta 0:00:01[K     |███████████████████▏            | 1.8 MB 5.5 MB/s eta 0:00:01[K     |███████████████████▎            | 1.8 MB 5.5 MB/s eta 0:00:01[K     |███████████████████▍            | 1.9 MB 5.5 MB/s eta 0:00:01[K     |███████████████████▌            | 1.9 MB 5.5 MB/s eta 0:00:01[K     |███████████████████▋            | 1.9 MB 5.5 MB/s eta 0:00:01[K     |███████████████████▊            | 1.9 MB 5.5 MB/s eta 0:00:01[K     |███████████████████▉            | 1.9 MB 5.5 MB/s eta 0:00:01[K     |████████████████████            | 1.9 MB 5.5 MB/s eta 0:00:01[K     |████████████████████            | 1.9 MB 5.5 MB/s eta 0:00:01[K     |████████████████████▏           | 1.9 MB 5.5 MB/s eta 0:00:01[K     |████████████████████▎           | 1.9 MB 5.5 MB/s eta 0:00:01[K     |████████████████████▍           | 1.9 MB 5.5 MB/s eta 0:00:01[K     |████████████████████▌           | 2.0 MB 5.5 MB/s eta 0:00:01[K     |████████████████████▌           | 2.0 MB 5.5 MB/s eta 0:00:01[K     |████████████████████▋           | 2.0 MB 5.5 MB/s eta 0:00:01[K     |████████████████████▊           | 2.0 MB 5.5 MB/s eta 0:00:01[K     |████████████████████▉           | 2.0 MB 5.5 MB/s eta 0:00:01[K     |█████████████████████           | 2.0 MB 5.5 MB/s eta 0:00:01[K     |█████████████████████           | 2.0 MB 5.5 MB/s eta 0:00:01[K     |█████████████████████▏          | 2.0 MB 5.5 MB/s eta 0:00:01[K     |█████████████████████▎          | 2.0 MB 5.5 MB/s eta 0:00:01[K     |█████████████████████▍          | 2.0 MB 5.5 MB/s eta 0:00:01[K     |█████████████████████▌          | 2.1 MB 5.5 MB/s eta 0:00:01[K     |█████████████████████▋          | 2.1 MB 5.5 MB/s eta 0:00:01[K     |█████████████████████▊          | 2.1 MB 5.5 MB/s eta 0:00:01[K     |█████████████████████▉          | 2.1 MB 5.5 MB/s eta 0:00:01[K     |██████████████████████          | 2.1 MB 5.5 MB/s eta 0:00:01[K     |██████████████████████          | 2.1 MB 5.5 MB/s eta 0:00:01[K     |██████████████████████▏         | 2.1 MB 5.5 MB/s eta 0:00:01[K     |██████████████████████▎         | 2.1 MB 5.5 MB/s eta 0:00:01[K     |██████████████████████▍         | 2.1 MB 5.5 MB/s eta 0:00:01[K     |██████████████████████▌         | 2.2 MB 5.5 MB/s eta 0:00:01[K     |██████████████████████▋         | 2.2 MB 5.5 MB/s eta 0:00:01[K     |██████████████████████▊         | 2.2 MB 5.5 MB/s eta 0:00:01[K     |██████████████████████▉         | 2.2 MB 5.5 MB/s eta 0:00:01[K     |███████████████████████         | 2.2 MB 5.5 MB/s eta 0:00:01[K     |███████████████████████         | 2.2 MB 5.5 MB/s eta 0:00:01[K     |███████████████████████▏        | 2.2 MB 5.5 MB/s eta 0:00:01[K     |███████████████████████▎        | 2.2 MB 5.5 MB/s eta 0:00:01[K     |███████████████████████▍        | 2.2 MB 5.5 MB/s eta 0:00:01[K     |███████████████████████▌        | 2.2 MB 5.5 MB/s eta 0:00:01[K     |███████████████████████▌        | 2.3 MB 5.5 MB/s eta 0:00:01[K     |███████████████████████▋        | 2.3 MB 5.5 MB/s eta 0:00:01[K     |███████████████████████▊        | 2.3 MB 5.5 MB/s eta 0:00:01[K     |███████████████████████▉        | 2.3 MB 5.5 MB/s eta 0:00:01[K     |████████████████████████        | 2.3 MB 5.5 MB/s eta 0:00:01[K     |████████████████████████        | 2.3 MB 5.5 MB/s eta 0:00:01[K     |████████████████████████▏       | 2.3 MB 5.5 MB/s eta 0:00:01[K     |████████████████████████▎       | 2.3 MB 5.5 MB/s eta 0:00:01[K     |████████████████████████▍       | 2.3 MB 5.5 MB/s eta 0:00:01[K     |████████████████████████▌       | 2.3 MB 5.5 MB/s eta 0:00:01[K     |████████████████████████▋       | 2.4 MB 5.5 MB/s eta 0:00:01[K     |████████████████████████▊       | 2.4 MB 5.5 MB/s eta 0:00:01[K     |████████████████████████▉       | 2.4 MB 5.5 MB/s eta 0:00:01[K     |█████████████████████████       | 2.4 MB 5.5 MB/s eta 0:00:01[K     |█████████████████████████       | 2.4 MB 5.5 MB/s eta 0:00:01[K     |█████████████████████████▏      | 2.4 MB 5.5 MB/s eta 0:00:01[K     |█████████████████████████▎      | 2.4 MB 5.5 MB/s eta 0:00:01[K     |█████████████████████████▍      | 2.4 MB 5.5 MB/s eta 0:00:01[K     |█████████████████████████▌      | 2.4 MB 5.5 MB/s eta 0:00:01[K     |█████████████████████████▋      | 2.4 MB 5.5 MB/s eta 0:00:01[K     |█████████████████████████▊      | 2.5 MB 5.5 MB/s eta 0:00:01[K     |█████████████████████████▉      | 2.5 MB 5.5 MB/s eta 0:00:01[K     |██████████████████████████      | 2.5 MB 5.5 MB/s eta 0:00:01[K     |██████████████████████████      | 2.5 MB 5.5 MB/s eta 0:00:01[K     |██████████████████████████▏     | 2.5 MB 5.5 MB/s eta 0:00:01[K     |██████████████████████████▎     | 2.5 MB 5.5 MB/s eta 0:00:01[K     |██████████████████████████▍     | 2.5 MB 5.5 MB/s eta 0:00:01[K     |██████████████████████████▍     | 2.5 MB 5.5 MB/s eta 0:00:01[K     |██████████████████████████▌     | 2.5 MB 5.5 MB/s eta 0:00:01[K     |██████████████████████████▋     | 2.5 MB 5.5 MB/s eta 0:00:01[K     |██████████████████████████▊     | 2.6 MB 5.5 MB/s eta 0:00:01[K     |██████████████████████████▉     | 2.6 MB 5.5 MB/s eta 0:00:01[K     |███████████████████████████     | 2.6 MB 5.5 MB/s eta 0:00:01[K     |███████████████████████████     | 2.6 MB 5.5 MB/s eta 0:00:01[K     |███████████████████████████▏    | 2.6 MB 5.5 MB/s eta 0:00:01[K     |███████████████████████████▎    | 2.6 MB 5.5 MB/s eta 0:00:01[K     |███████████████████████████▍    | 2.6 MB 5.5 MB/s eta 0:00:01[K     |███████████████████████████▌    | 2.6 MB 5.5 MB/s eta 0:00:01[K     |███████████████████████████▋    | 2.6 MB 5.5 MB/s eta 0:00:01[K     |███████████████████████████▊    | 2.7 MB 5.5 MB/s eta 0:00:01[K     |███████████████████████████▉    | 2.7 MB 5.5 MB/s eta 0:00:01[K     |████████████████████████████    | 2.7 MB 5.5 MB/s eta 0:00:01[K     |████████████████████████████    | 2.7 MB 5.5 MB/s eta 0:00:01[K     |████████████████████████████▏   | 2.7 MB 5.5 MB/s eta 0:00:01[K     |████████████████████████████▎   | 2.7 MB 5.5 MB/s eta 0:00:01[K     |████████████████████████████▍   | 2.7 MB 5.5 MB/s eta 0:00:01[K     |████████████████████████████▌   | 2.7 MB 5.5 MB/s eta 0:00:01[K     |████████████████████████████▋   | 2.7 MB 5.5 MB/s eta 0:00:01[K     |████████████████████████████▊   | 2.7 MB 5.5 MB/s eta 0:00:01[K     |████████████████████████████▉   | 2.8 MB 5.5 MB/s eta 0:00:01[K     |█████████████████████████████   | 2.8 MB 5.5 MB/s eta 0:00:01[K     |█████████████████████████████   | 2.8 MB 5.5 MB/s eta 0:00:01[K     |█████████████████████████████▏  | 2.8 MB 5.5 MB/s eta 0:00:01[K     |█████████████████████████████▎  | 2.8 MB 5.5 MB/s eta 0:00:01[K     |█████████████████████████████▎  | 2.8 MB 5.5 MB/s eta 0:00:01[K     |█████████████████████████████▍  | 2.8 MB 5.5 MB/s eta 0:00:01[K     |█████████████████████████████▌  | 2.8 MB 5.5 MB/s eta 0:00:01[K     |█████████████████████████████▋  | 2.8 MB 5.5 MB/s eta 0:00:01[K     |█████████████████████████████▊  | 2.8 MB 5.5 MB/s eta 0:00:01[K     |█████████████████████████████▉  | 2.9 MB 5.5 MB/s eta 0:00:01[K     |██████████████████████████████  | 2.9 MB 5.5 MB/s eta 0:00:01[K     |██████████████████████████████  | 2.9 MB 5.5 MB/s eta 0:00:01[K     |██████████████████████████████▏ | 2.9 MB 5.5 MB/s eta 0:00:01[K     |██████████████████████████████▎ | 2.9 MB 5.5 MB/s eta 0:00:01[K     |██████████████████████████████▍ | 2.9 MB 5.5 MB/s eta 0:00:01[K     |██████████████████████████████▌ | 2.9 MB 5.5 MB/s eta 0:00:01[K     |██████████████████████████████▋ | 2.9 MB 5.5 MB/s eta 0:00:01[K     |██████████████████████████████▊ | 2.9 MB 5.5 MB/s eta 0:00:01[K     |██████████████████████████████▉ | 2.9 MB 5.5 MB/s eta 0:00:01[K     |███████████████████████████████ | 3.0 MB 5.5 MB/s eta 0:00:01[K     |███████████████████████████████ | 3.0 MB 5.5 MB/s eta 0:00:01[K     |███████████████████████████████▏| 3.0 MB 5.5 MB/s eta 0:00:01[K     |███████████████████████████████▎| 3.0 MB 5.5 MB/s eta 0:00:01[K     |███████████████████████████████▍| 3.0 MB 5.5 MB/s eta 0:00:01[K     |███████████████████████████████▌| 3.0 MB 5.5 MB/s eta 0:00:01[K     |███████████████████████████████▋| 3.0 MB 5.5 MB/s eta 0:00:01[K     |███████████████████████████████▊| 3.0 MB 5.5 MB/s eta 0:00:01[K     |███████████████████████████████▉| 3.0 MB 5.5 MB/s eta 0:00:01[K     |████████████████████████████████| 3.1 MB 5.5 MB/s eta 0:00:01[K     |████████████████████████████████| 3.1 MB 5.5 MB/s 
[?25hRequirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Collecting typing-extensions>=4.2.0
  Downloading typing_extensions-4.8.0-py3-none-any.whl (31 kB)
Collecting greenlet!=0.4.17; platform_machine == "aarch64" or (platform_machine == "ppc64le" or (platform_machine == "x86_64" or (platform_machine == "amd64" or (platform_machine == "AMD64" or (platform_machine == "win32" or platform_machine == "WIN32")))))
  Downloading greenlet-3.0.1-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (654 kB)
[?25l[K     |▌                               | 10 kB 32.5 MB/s eta 0:00:01[K     |█                               | 20 kB 49.1 MB/s eta 0:00:01[K     |█▌                              | 30 kB 66.2 MB/s eta 0:00:01[K     |██                              | 40 kB 78.7 MB/s eta 0:00:01[K     |██▌                             | 51 kB 89.2 MB/s eta 0:00:01[K     |███                             | 61 kB 100.8 MB/s eta 0:00:01[K     |███▌                            | 71 kB 47.8 MB/s eta 0:00:01[K     |████                            | 81 kB 50.4 MB/s eta 0:00:01[K     |████▌                           | 92 kB 52.4 MB/s eta 0:00:01[K     |█████                           | 102 kB 55.6 MB/s eta 0:00:01[K     |█████▌                          | 112 kB 55.6 MB/s eta 0:00:01[K     |██████                          | 122 kB 55.6 MB/s eta 0:00:01[K     |██████▌                         | 133 kB 55.6 MB/s eta 0:00:01[K     |███████                         | 143 kB 55.6 MB/s eta 0:00:01[K     |███████▌                        | 153 kB 55.6 MB/s eta 0:00:01[K     |████████                        | 163 kB 55.6 MB/s eta 0:00:01[K     |████████▌                       | 174 kB 55.6 MB/s eta 0:00:01[K     |█████████                       | 184 kB 55.6 MB/s eta 0:00:01[K     |█████████▌                      | 194 kB 55.6 MB/s eta 0:00:01[K     |██████████                      | 204 kB 55.6 MB/s eta 0:00:01[K     |██████████▌                     | 215 kB 55.6 MB/s eta 0:00:01[K     |███████████                     | 225 kB 55.6 MB/s eta 0:00:01[K     |███████████▌                    | 235 kB 55.6 MB/s eta 0:00:01[K     |████████████                    | 245 kB 55.6 MB/s eta 0:00:01[K     |████████████▌                   | 256 kB 55.6 MB/s eta 0:00:01[K     |█████████████                   | 266 kB 55.6 MB/s eta 0:00:01[K     |█████████████▌                  | 276 kB 55.6 MB/s eta 0:00:01[K     |██████████████                  | 286 kB 55.6 MB/s eta 0:00:01[K     |██████████████▌                 | 296 kB 55.6 MB/s eta 0:00:01[K     |███████████████                 | 307 kB 55.6 MB/s eta 0:00:01[K     |███████████████▌                | 317 kB 55.6 MB/s eta 0:00:01[K     |████████████████                | 327 kB 55.6 MB/s eta 0:00:01[K     |████████████████▌               | 337 kB 55.6 MB/s eta 0:00:01[K     |█████████████████               | 348 kB 55.6 MB/s eta 0:00:01[K     |█████████████████▌              | 358 kB 55.6 MB/s eta 0:00:01[K     |██████████████████              | 368 kB 55.6 MB/s eta 0:00:01[K     |██████████████████▌             | 378 kB 55.6 MB/s eta 0:00:01[K     |███████████████████             | 389 kB 55.6 MB/s eta 0:00:01[K     |███████████████████▌            | 399 kB 55.6 MB/s eta 0:00:01[K     |████████████████████            | 409 kB 55.6 MB/s eta 0:00:01[K     |████████████████████▌           | 419 kB 55.6 MB/s eta 0:00:01[K     |█████████████████████           | 430 kB 55.6 MB/s eta 0:00:01[K     |█████████████████████▌          | 440 kB 55.6 MB/s eta 0:00:01[K     |██████████████████████          | 450 kB 55.6 MB/s eta 0:00:01[K     |██████████████████████▌         | 460 kB 55.6 MB/s eta 0:00:01[K     |███████████████████████         | 471 kB 55.6 MB/s eta 0:00:01[K     |███████████████████████▌        | 481 kB 55.6 MB/s eta 0:00:01[K     |████████████████████████        | 491 kB 55.6 MB/s eta 0:00:01[K     |████████████████████████▌       | 501 kB 55.6 MB/s eta 0:00:01[K     |█████████████████████████       | 512 kB 55.6 MB/s eta 0:00:01[K     |█████████████████████████▌      | 522 kB 55.6 MB/s eta 0:00:01[K     |██████████████████████████      | 532 kB 55.6 MB/s eta 0:00:01[K     |██████████████████████████▌     | 542 kB 55.6 MB/s eta 0:00:01[K     |███████████████████████████     | 552 kB 55.6 MB/s eta 0:00:01[K     |███████████████████████████▌    | 563 kB 55.6 MB/s eta 0:00:01[K     |████████████████████████████    | 573 kB 55.6 MB/s eta 0:00:01[K     |████████████████████████████▌   | 583 kB 55.6 MB/s eta 0:00:01[K     |█████████████████████████████   | 593 kB 55.6 MB/s eta 0:00:01[K     |█████████████████████████████▌  | 604 kB 55.6 MB/s eta 0:00:01[K     |██████████████████████████████  | 614 kB 55.6 MB/s eta 0:00:01[K     |██████████████████████████████▌ | 624 kB 55.6 MB/s eta 0:00:01[K     |███████████████████████████████ | 634 kB 55.6 MB/s eta 0:00:01[K     |███████████████████████████████▌| 645 kB 55.6 MB/s eta 0:00:01[K     |████████████████████████████████| 654 kB 55.6 MB/s 
[?25hBuilding wheels for collected packages: pandasql
  Building wheel for pandasql (setup.py) ... [?25l- done
[?25h  Created wheel for pandasql: filename=pandasql-0.7.3-py3-none-any.whl size=26817 sha256=8e28f37c0c71ff74f582879c98d8782019ef95e6dda278e662540dfae850a663
  Stored in directory: /root/.cache/pip/wheels/ed/8f/46/a383923333728744f01ba24adbd8e364f2cb9470a8b8e5b9ff
Successfully built pandasql
Installing collected packages: typing-extensions, greenlet, sqlalchemy, pandasql
Successfully installed greenlet-3.0.1 pandasql-0.7.3 sqlalchemy-2.0.23 typing-extensions-4.8.0
Running /platform/source/s01/v1_9/m11111111/m11111111_q14_t0.sh
Running /platform/source/s01/v1_9/m11111111/m11111111_q14_t1.sh
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.5.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: dnspython in /usr/local/lib/python3.8/dist-packages (2.4.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v1_9/m11111111/m11111111_q14_t2.sh
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.5.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v1_9/m11111111/m11111111_q15_t0.sh
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.5.0)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.8/dist-packages (2.8.2)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil) (1.16.0)
Running /platform/source/s01/v1_9/m11111111/m11111111_q15_t1.sh
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.5.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v1_9/m11111111/m11111111_q15_t2.sh
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.5.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.8/dist-packages (2.8.2)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil) (1.16.0)
Running /platform/source/s01/v1_9/m11111111/m11111111_q16_t0.sh
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.5.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v1_9/m11111111/m11111111_q16_t1.sh
/platform/source/s01/v1_9/m11111111/m11111111_q16_t1.sh: line 1: sudo: command not found
/platform/source/s01/v1_9/m11111111/m11111111_q16_t1.sh: line 2: sudo: command not found
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.5.0)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v1_9/m11111111/m11111111_q16_t2.sh
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.5.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v1_9/m11111111/m11111111_q17_t0.sh
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.5.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v1_9/m11111111/m11111111_q17_t1.sh
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.5.0)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v1_9/m11111111/m11111111_q17_t2.sh
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v1_9/m11111111/m11111111_q18_t0.sh
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.5.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v1_9/m11111111/m11111111_q18_t1.sh
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.5.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v1_9/m11111111/m11111111_q18_t2.sh
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.5.0)
[31mERROR: Could not find a version that satisfies the requirement csv (from versions: none)[0m
[31mERROR: No matching distribution found for csv[0m
Running /platform/source/s01/v1_9/m11111111/m11111111_q19_t0.sh
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.5.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v1_9/m11111111/m11111111_q19_t1.sh
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.5.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Running /platform/source/s01/v1_9/m11111111/m11111111_q19_t2.sh
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt install python3.8-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: ['/path/to/new/virtual/environment/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']

/platform/source/s01/v1_9/m11111111/m11111111_q19_t2.sh: line 2: /path/to/new/virtual/environment/bin/activate: No such file or directory
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.5.0)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v1_9/m11111111/m11111111_q1_t0.sh
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.5.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v1_9/m11111111/m11111111_q1_t1.sh
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.5.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v1_9/m11111111/m11111111_q1_t2.sh
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.5.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v1_9/m11111111/m11111111_q20_t0.sh
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.5.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v1_9/m11111111/m11111111_q20_t1.sh
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.5.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v1_9/m11111111/m11111111_q20_t2.sh
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.5.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v1_9/m11111111/m11111111_q21_t0.sh
Running /platform/source/s01/v1_9/m11111111/m11111111_q21_t1.sh
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.5.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v1_9/m11111111/m11111111_q21_t2.sh
Running /platform/source/s01/v1_9/m11111111/m11111111_q22_t0.sh
Running /platform/source/s01/v1_9/m11111111/m11111111_q22_t1.sh
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.5.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: dnspython in /usr/local/lib/python3.8/dist-packages (2.4.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v1_9/m11111111/m11111111_q22_t2.sh
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.5.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v1_9/m11111111/m11111111_q2_t0.sh
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.5.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v1_9/m11111111/m11111111_q2_t1.sh
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.5.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v1_9/m11111111/m11111111_q2_t2.sh
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.5.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v1_9/m11111111/m11111111_q3_t0.sh
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.5.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v1_9/m11111111/m11111111_q3_t1.sh
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.5.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Running /platform/source/s01/v1_9/m11111111/m11111111_q3_t2.sh
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.5.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v1_9/m11111111/m11111111_q4_t0.sh
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.5.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Running /platform/source/s01/v1_9/m11111111/m11111111_q4_t1.sh
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.5.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v1_9/m11111111/m11111111_q4_t2.sh
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.5.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: dnspython in /usr/local/lib/python3.8/dist-packages (2.4.2)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v1_9/m11111111/m11111111_q5_t0.sh
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.5.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Running /platform/source/s01/v1_9/m11111111/m11111111_q5_t1.sh
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.5.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v1_9/m11111111/m11111111_q5_t2.sh
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.5.0)
Collecting bson
  Downloading bson-0.5.10.tar.gz (10 kB)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.8/dist-packages (from bson) (1.16.0)
Building wheels for collected packages: bson
  Building wheel for bson (setup.py) ... [?25l- done
[?25h  Created wheel for bson: filename=bson-0.5.10-py3-none-any.whl size=11978 sha256=e7e2884562f937993cfe3111c0fa90f0d40773869f8ca63a475786cfa6165f64
  Stored in directory: /root/.cache/pip/wheels/92/1b/66/5a288fdf87a97b2f7e2cbdc387a431e60ed298b11003692055
Successfully built bson
Installing collected packages: bson
Successfully installed bson-0.5.10
Running /platform/source/s01/v1_9/m11111111/m11111111_q6_t0.sh
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.5.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v1_9/m11111111/m11111111_q6_t1.sh
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.5.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v1_9/m11111111/m11111111_q6_t2.sh
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.5.0)
[31mERROR: Could not find a version that satisfies the requirement csv (from versions: none)[0m
[31mERROR: No matching distribution found for csv[0m
Running /platform/source/s01/v1_9/m11111111/m11111111_q7_t0.sh
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.5.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v1_9/m11111111/m11111111_q7_t1.sh
Running /platform/source/s01/v1_9/m11111111/m11111111_q7_t2.sh
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.5.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Running /platform/source/s01/v1_9/m11111111/m11111111_q8_t0.sh
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.5.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v1_9/m11111111/m11111111_q8_t1.sh
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.5.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v1_9/m11111111/m11111111_q8_t2.sh
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.5.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v1_9/m11111111/m11111111_q9_t0.sh
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.5.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v1_9/m11111111/m11111111_q9_t1.sh
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.5.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v1_9/m11111111/m11111111_q9_t2.sh
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.5.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
python /grader.py /platform/source/s01/v1_9/m11111111/m11111111_q10_t0.py /platform/output/m11111111/m11111111_q10_t0.csv /platform/expected/s01/q10.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m11111111/m11111111_q10_t0.py", line 1, in <module>
    from pymongo import MongoClient
  File "/usr/local/lib/python3.8/dist-packages/pymongo/__init__.py", line 89, in <module>
    from pymongo.collection import ReturnDocument
  File "/usr/local/lib/python3.8/dist-packages/pymongo/collection.py", line 42, in <module>
    from bson.raw_bson import RawBSONDocument
  File "/usr/local/lib/python3.8/dist-packages/bson/raw_bson.py", line 56, in <module>
    from bson import _get_object_size, _raw_to_dict
ImportError: cannot import name '_get_object_size' from 'bson' (/usr/local/lib/python3.8/dist-packages/bson/__init__.py)
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m11111111/m11111111_q10_t1.py /platform/output/m11111111/m11111111_q10_t1.csv /platform/expected/s01/q10.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m11111111/m11111111_q10_t1.py", line 1, in <module>
    import pymongo
  File "/usr/local/lib/python3.8/dist-packages/pymongo/__init__.py", line 89, in <module>
    from pymongo.collection import ReturnDocument
  File "/usr/local/lib/python3.8/dist-packages/pymongo/collection.py", line 42, in <module>
    from bson.raw_bson import RawBSONDocument
  File "/usr/local/lib/python3.8/dist-packages/bson/raw_bson.py", line 56, in <module>
    from bson import _get_object_size, _raw_to_dict
ImportError: cannot import name '_get_object_size' from 'bson' (/usr/local/lib/python3.8/dist-packages/bson/__init__.py)
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m11111111/m11111111_q10_t2.py /platform/output/m11111111/m11111111_q10_t2.csv /platform/expected/s01/q10.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m11111111/m11111111_q10_t2.py", line 1, in <module>
    from pymongo import MongoClient
  File "/usr/local/lib/python3.8/dist-packages/pymongo/__init__.py", line 89, in <module>
    from pymongo.collection import ReturnDocument
  File "/usr/local/lib/python3.8/dist-packages/pymongo/collection.py", line 42, in <module>
    from bson.raw_bson import RawBSONDocument
  File "/usr/local/lib/python3.8/dist-packages/bson/raw_bson.py", line 56, in <module>
    from bson import _get_object_size, _raw_to_dict
ImportError: cannot import name '_get_object_size' from 'bson' (/usr/local/lib/python3.8/dist-packages/bson/__init__.py)
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m11111111/m11111111_q11_t0.py /platform/output/m11111111/m11111111_q11_t0.csv /platform/expected/s01/q11.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m11111111/m11111111_q11_t0.py", line 1, in <module>
    from pymongo import MongoClient
  File "/usr/local/lib/python3.8/dist-packages/pymongo/__init__.py", line 89, in <module>
    from pymongo.collection import ReturnDocument
  File "/usr/local/lib/python3.8/dist-packages/pymongo/collection.py", line 42, in <module>
    from bson.raw_bson import RawBSONDocument
  File "/usr/local/lib/python3.8/dist-packages/bson/raw_bson.py", line 56, in <module>
    from bson import _get_object_size, _raw_to_dict
ImportError: cannot import name '_get_object_size' from 'bson' (/usr/local/lib/python3.8/dist-packages/bson/__init__.py)
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m11111111/m11111111_q11_t1.py /platform/output/m11111111/m11111111_q11_t1.csv /platform/expected/s01/q11.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m11111111/m11111111_q11_t1.py", line 1, in <module>
    from pymongo import MongoClient
  File "/usr/local/lib/python3.8/dist-packages/pymongo/__init__.py", line 89, in <module>
    from pymongo.collection import ReturnDocument
  File "/usr/local/lib/python3.8/dist-packages/pymongo/collection.py", line 42, in <module>
    from bson.raw_bson import RawBSONDocument
  File "/usr/local/lib/python3.8/dist-packages/bson/raw_bson.py", line 56, in <module>
    from bson import _get_object_size, _raw_to_dict
ImportError: cannot import name '_get_object_size' from 'bson' (/usr/local/lib/python3.8/dist-packages/bson/__init__.py)
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m11111111/m11111111_q11_t2.py /platform/output/m11111111/m11111111_q11_t2.csv /platform/expected/s01/q11.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m11111111/m11111111_q11_t2.py", line 1, in <module>
    from pymongo import MongoClient
  File "/usr/local/lib/python3.8/dist-packages/pymongo/__init__.py", line 89, in <module>
    from pymongo.collection import ReturnDocument
  File "/usr/local/lib/python3.8/dist-packages/pymongo/collection.py", line 42, in <module>
    from bson.raw_bson import RawBSONDocument
  File "/usr/local/lib/python3.8/dist-packages/bson/raw_bson.py", line 56, in <module>
    from bson import _get_object_size, _raw_to_dict
ImportError: cannot import name '_get_object_size' from 'bson' (/usr/local/lib/python3.8/dist-packages/bson/__init__.py)
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m11111111/m11111111_q12_t0.py /platform/output/m11111111/m11111111_q12_t0.csv /platform/expected/s01/q12.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m11111111/m11111111_q12_t0.py", line 1, in <module>
    from pymongo import MongoClient
  File "/usr/local/lib/python3.8/dist-packages/pymongo/__init__.py", line 89, in <module>
    from pymongo.collection import ReturnDocument
  File "/usr/local/lib/python3.8/dist-packages/pymongo/collection.py", line 42, in <module>
    from bson.raw_bson import RawBSONDocument
  File "/usr/local/lib/python3.8/dist-packages/bson/raw_bson.py", line 56, in <module>
    from bson import _get_object_size, _raw_to_dict
ImportError: cannot import name '_get_object_size' from 'bson' (/usr/local/lib/python3.8/dist-packages/bson/__init__.py)
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m11111111/m11111111_q12_t1.py /platform/output/m11111111/m11111111_q12_t1.csv /platform/expected/s01/q12.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m11111111/m11111111_q12_t1.py", line 1, in <module>
    import pymongo
  File "/usr/local/lib/python3.8/dist-packages/pymongo/__init__.py", line 89, in <module>
    from pymongo.collection import ReturnDocument
  File "/usr/local/lib/python3.8/dist-packages/pymongo/collection.py", line 42, in <module>
    from bson.raw_bson import RawBSONDocument
  File "/usr/local/lib/python3.8/dist-packages/bson/raw_bson.py", line 56, in <module>
    from bson import _get_object_size, _raw_to_dict
ImportError: cannot import name '_get_object_size' from 'bson' (/usr/local/lib/python3.8/dist-packages/bson/__init__.py)
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m11111111/m11111111_q12_t2.py /platform/output/m11111111/m11111111_q12_t2.csv /platform/expected/s01/q12.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m11111111/m11111111_q12_t2.py", line 1, in <module>
    from pymongo import MongoClient
  File "/usr/local/lib/python3.8/dist-packages/pymongo/__init__.py", line 89, in <module>
    from pymongo.collection import ReturnDocument
  File "/usr/local/lib/python3.8/dist-packages/pymongo/collection.py", line 42, in <module>
    from bson.raw_bson import RawBSONDocument
  File "/usr/local/lib/python3.8/dist-packages/bson/raw_bson.py", line 56, in <module>
    from bson import _get_object_size, _raw_to_dict
ImportError: cannot import name '_get_object_size' from 'bson' (/usr/local/lib/python3.8/dist-packages/bson/__init__.py)
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m11111111/m11111111_q13_t0.py /platform/output/m11111111/m11111111_q13_t0.csv /platform/expected/s01/q13.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m11111111/m11111111_q13_t0.py", line 1, in <module>
    from pymongo import MongoClient
  File "/usr/local/lib/python3.8/dist-packages/pymongo/__init__.py", line 89, in <module>
    from pymongo.collection import ReturnDocument
  File "/usr/local/lib/python3.8/dist-packages/pymongo/collection.py", line 42, in <module>
    from bson.raw_bson import RawBSONDocument
  File "/usr/local/lib/python3.8/dist-packages/bson/raw_bson.py", line 56, in <module>
    from bson import _get_object_size, _raw_to_dict
ImportError: cannot import name '_get_object_size' from 'bson' (/usr/local/lib/python3.8/dist-packages/bson/__init__.py)
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m11111111/m11111111_q13_t1.py /platform/output/m11111111/m11111111_q13_t1.csv /platform/expected/s01/q13.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m11111111/m11111111_q13_t1.py", line 1, in <module>
    from pymongo import MongoClient
  File "/usr/local/lib/python3.8/dist-packages/pymongo/__init__.py", line 89, in <module>
    from pymongo.collection import ReturnDocument
  File "/usr/local/lib/python3.8/dist-packages/pymongo/collection.py", line 42, in <module>
    from bson.raw_bson import RawBSONDocument
  File "/usr/local/lib/python3.8/dist-packages/bson/raw_bson.py", line 56, in <module>
    from bson import _get_object_size, _raw_to_dict
ImportError: cannot import name '_get_object_size' from 'bson' (/usr/local/lib/python3.8/dist-packages/bson/__init__.py)
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m11111111/m11111111_q13_t2.py /platform/output/m11111111/m11111111_q13_t2.csv /platform/expected/s01/q13.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m11111111/m11111111_q13_t2.py", line 1, in <module>
    from pymongo import MongoClient
  File "/usr/local/lib/python3.8/dist-packages/pymongo/__init__.py", line 89, in <module>
    from pymongo.collection import ReturnDocument
  File "/usr/local/lib/python3.8/dist-packages/pymongo/collection.py", line 42, in <module>
    from bson.raw_bson import RawBSONDocument
  File "/usr/local/lib/python3.8/dist-packages/bson/raw_bson.py", line 56, in <module>
    from bson import _get_object_size, _raw_to_dict
ImportError: cannot import name '_get_object_size' from 'bson' (/usr/local/lib/python3.8/dist-packages/bson/__init__.py)
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m11111111/m11111111_q14_t0.py /platform/output/m11111111/m11111111_q14_t0.csv /platform/expected/s01/q14.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m11111111/m11111111_q14_t0.py", line 1, in <module>
    from pymongo import MongoClient
  File "/usr/local/lib/python3.8/dist-packages/pymongo/__init__.py", line 89, in <module>
    from pymongo.collection import ReturnDocument
  File "/usr/local/lib/python3.8/dist-packages/pymongo/collection.py", line 42, in <module>
    from bson.raw_bson import RawBSONDocument
  File "/usr/local/lib/python3.8/dist-packages/bson/raw_bson.py", line 56, in <module>
    from bson import _get_object_size, _raw_to_dict
ImportError: cannot import name '_get_object_size' from 'bson' (/usr/local/lib/python3.8/dist-packages/bson/__init__.py)
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m11111111/m11111111_q14_t1.py /platform/output/m11111111/m11111111_q14_t1.csv /platform/expected/s01/q14.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m11111111/m11111111_q14_t1.py", line 1, in <module>
    from pymongo import MongoClient
  File "/usr/local/lib/python3.8/dist-packages/pymongo/__init__.py", line 89, in <module>
    from pymongo.collection import ReturnDocument
  File "/usr/local/lib/python3.8/dist-packages/pymongo/collection.py", line 42, in <module>
    from bson.raw_bson import RawBSONDocument
  File "/usr/local/lib/python3.8/dist-packages/bson/raw_bson.py", line 56, in <module>
    from bson import _get_object_size, _raw_to_dict
ImportError: cannot import name '_get_object_size' from 'bson' (/usr/local/lib/python3.8/dist-packages/bson/__init__.py)
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m11111111/m11111111_q14_t2.py /platform/output/m11111111/m11111111_q14_t2.csv /platform/expected/s01/q14.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m11111111/m11111111_q14_t2.py", line 1, in <module>
    from pymongo import MongoClient
  File "/usr/local/lib/python3.8/dist-packages/pymongo/__init__.py", line 89, in <module>
    from pymongo.collection import ReturnDocument
  File "/usr/local/lib/python3.8/dist-packages/pymongo/collection.py", line 42, in <module>
    from bson.raw_bson import RawBSONDocument
  File "/usr/local/lib/python3.8/dist-packages/bson/raw_bson.py", line 56, in <module>
    from bson import _get_object_size, _raw_to_dict
ImportError: cannot import name '_get_object_size' from 'bson' (/usr/local/lib/python3.8/dist-packages/bson/__init__.py)
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m11111111/m11111111_q15_t0.py /platform/output/m11111111/m11111111_q15_t0.csv /platform/expected/s01/q15.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m11111111/m11111111_q15_t0.py", line 1, in <module>
    from pymongo import MongoClient
  File "/usr/local/lib/python3.8/dist-packages/pymongo/__init__.py", line 89, in <module>
    from pymongo.collection import ReturnDocument
  File "/usr/local/lib/python3.8/dist-packages/pymongo/collection.py", line 42, in <module>
    from bson.raw_bson import RawBSONDocument
  File "/usr/local/lib/python3.8/dist-packages/bson/raw_bson.py", line 56, in <module>
    from bson import _get_object_size, _raw_to_dict
ImportError: cannot import name '_get_object_size' from 'bson' (/usr/local/lib/python3.8/dist-packages/bson/__init__.py)
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m11111111/m11111111_q15_t1.py /platform/output/m11111111/m11111111_q15_t1.csv /platform/expected/s01/q15.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m11111111/m11111111_q15_t1.py", line 1, in <module>
    from pymongo import MongoClient
  File "/usr/local/lib/python3.8/dist-packages/pymongo/__init__.py", line 89, in <module>
    from pymongo.collection import ReturnDocument
  File "/usr/local/lib/python3.8/dist-packages/pymongo/collection.py", line 42, in <module>
    from bson.raw_bson import RawBSONDocument
  File "/usr/local/lib/python3.8/dist-packages/bson/raw_bson.py", line 56, in <module>
    from bson import _get_object_size, _raw_to_dict
ImportError: cannot import name '_get_object_size' from 'bson' (/usr/local/lib/python3.8/dist-packages/bson/__init__.py)
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m11111111/m11111111_q15_t2.py /platform/output/m11111111/m11111111_q15_t2.csv /platform/expected/s01/q15.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m11111111/m11111111_q15_t2.py", line 1, in <module>
    from pymongo import MongoClient
  File "/usr/local/lib/python3.8/dist-packages/pymongo/__init__.py", line 89, in <module>
    from pymongo.collection import ReturnDocument
  File "/usr/local/lib/python3.8/dist-packages/pymongo/collection.py", line 42, in <module>
    from bson.raw_bson import RawBSONDocument
  File "/usr/local/lib/python3.8/dist-packages/bson/raw_bson.py", line 56, in <module>
    from bson import _get_object_size, _raw_to_dict
ImportError: cannot import name '_get_object_size' from 'bson' (/usr/local/lib/python3.8/dist-packages/bson/__init__.py)
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m11111111/m11111111_q16_t0.py /platform/output/m11111111/m11111111_q16_t0.csv /platform/expected/s01/q16.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m11111111/m11111111_q16_t0.py", line 1, in <module>
    from pymongo import MongoClient
  File "/usr/local/lib/python3.8/dist-packages/pymongo/__init__.py", line 89, in <module>
    from pymongo.collection import ReturnDocument
  File "/usr/local/lib/python3.8/dist-packages/pymongo/collection.py", line 42, in <module>
    from bson.raw_bson import RawBSONDocument
  File "/usr/local/lib/python3.8/dist-packages/bson/raw_bson.py", line 56, in <module>
    from bson import _get_object_size, _raw_to_dict
ImportError: cannot import name '_get_object_size' from 'bson' (/usr/local/lib/python3.8/dist-packages/bson/__init__.py)
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m11111111/m11111111_q16_t1.py /platform/output/m11111111/m11111111_q16_t1.csv /platform/expected/s01/q16.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m11111111/m11111111_q16_t1.py", line 1, in <module>
    from pymongo import MongoClient
  File "/usr/local/lib/python3.8/dist-packages/pymongo/__init__.py", line 89, in <module>
    from pymongo.collection import ReturnDocument
  File "/usr/local/lib/python3.8/dist-packages/pymongo/collection.py", line 42, in <module>
    from bson.raw_bson import RawBSONDocument
  File "/usr/local/lib/python3.8/dist-packages/bson/raw_bson.py", line 56, in <module>
    from bson import _get_object_size, _raw_to_dict
ImportError: cannot import name '_get_object_size' from 'bson' (/usr/local/lib/python3.8/dist-packages/bson/__init__.py)
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m11111111/m11111111_q16_t2.py /platform/output/m11111111/m11111111_q16_t2.csv /platform/expected/s01/q16.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m11111111/m11111111_q16_t2.py", line 1, in <module>
    from pymongo import MongoClient
  File "/usr/local/lib/python3.8/dist-packages/pymongo/__init__.py", line 89, in <module>
    from pymongo.collection import ReturnDocument
  File "/usr/local/lib/python3.8/dist-packages/pymongo/collection.py", line 42, in <module>
    from bson.raw_bson import RawBSONDocument
  File "/usr/local/lib/python3.8/dist-packages/bson/raw_bson.py", line 56, in <module>
    from bson import _get_object_size, _raw_to_dict
ImportError: cannot import name '_get_object_size' from 'bson' (/usr/local/lib/python3.8/dist-packages/bson/__init__.py)
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m11111111/m11111111_q17_t0.py /platform/output/m11111111/m11111111_q17_t0.csv /platform/expected/s01/q17.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m11111111/m11111111_q17_t0.py", line 1, in <module>
    from pymongo import MongoClient
  File "/usr/local/lib/python3.8/dist-packages/pymongo/__init__.py", line 89, in <module>
    from pymongo.collection import ReturnDocument
  File "/usr/local/lib/python3.8/dist-packages/pymongo/collection.py", line 42, in <module>
    from bson.raw_bson import RawBSONDocument
  File "/usr/local/lib/python3.8/dist-packages/bson/raw_bson.py", line 56, in <module>
    from bson import _get_object_size, _raw_to_dict
ImportError: cannot import name '_get_object_size' from 'bson' (/usr/local/lib/python3.8/dist-packages/bson/__init__.py)
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m11111111/m11111111_q17_t1.py /platform/output/m11111111/m11111111_q17_t1.csv /platform/expected/s01/q17.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m11111111/m11111111_q17_t1.py", line 1, in <module>
    from pymongo import MongoClient
  File "/usr/local/lib/python3.8/dist-packages/pymongo/__init__.py", line 89, in <module>
    from pymongo.collection import ReturnDocument
  File "/usr/local/lib/python3.8/dist-packages/pymongo/collection.py", line 42, in <module>
    from bson.raw_bson import RawBSONDocument
  File "/usr/local/lib/python3.8/dist-packages/bson/raw_bson.py", line 56, in <module>
    from bson import _get_object_size, _raw_to_dict
ImportError: cannot import name '_get_object_size' from 'bson' (/usr/local/lib/python3.8/dist-packages/bson/__init__.py)
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m11111111/m11111111_q17_t2.py /platform/output/m11111111/m11111111_q17_t2.csv /platform/expected/s01/q17.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m11111111/m11111111_q17_t2.py", line 1, in <module>
    from pymongo import MongoClient
  File "/usr/local/lib/python3.8/dist-packages/pymongo/__init__.py", line 89, in <module>
    from pymongo.collection import ReturnDocument
  File "/usr/local/lib/python3.8/dist-packages/pymongo/collection.py", line 42, in <module>
    from bson.raw_bson import RawBSONDocument
  File "/usr/local/lib/python3.8/dist-packages/bson/raw_bson.py", line 56, in <module>
    from bson import _get_object_size, _raw_to_dict
ImportError: cannot import name '_get_object_size' from 'bson' (/usr/local/lib/python3.8/dist-packages/bson/__init__.py)
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m11111111/m11111111_q18_t0.py /platform/output/m11111111/m11111111_q18_t0.csv /platform/expected/s01/q18.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m11111111/m11111111_q18_t0.py", line 1, in <module>
    from pymongo import MongoClient
  File "/usr/local/lib/python3.8/dist-packages/pymongo/__init__.py", line 89, in <module>
    from pymongo.collection import ReturnDocument
  File "/usr/local/lib/python3.8/dist-packages/pymongo/collection.py", line 42, in <module>
    from bson.raw_bson import RawBSONDocument
  File "/usr/local/lib/python3.8/dist-packages/bson/raw_bson.py", line 56, in <module>
    from bson import _get_object_size, _raw_to_dict
ImportError: cannot import name '_get_object_size' from 'bson' (/usr/local/lib/python3.8/dist-packages/bson/__init__.py)
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m11111111/m11111111_q18_t1.py /platform/output/m11111111/m11111111_q18_t1.csv /platform/expected/s01/q18.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m11111111/m11111111_q18_t1.py", line 2, in <module>
    from pymongo import MongoClient
  File "/usr/local/lib/python3.8/dist-packages/pymongo/__init__.py", line 89, in <module>
    from pymongo.collection import ReturnDocument
  File "/usr/local/lib/python3.8/dist-packages/pymongo/collection.py", line 42, in <module>
    from bson.raw_bson import RawBSONDocument
  File "/usr/local/lib/python3.8/dist-packages/bson/raw_bson.py", line 56, in <module>
    from bson import _get_object_size, _raw_to_dict
ImportError: cannot import name '_get_object_size' from 'bson' (/usr/local/lib/python3.8/dist-packages/bson/__init__.py)
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m11111111/m11111111_q18_t2.py /platform/output/m11111111/m11111111_q18_t2.csv /platform/expected/s01/q18.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m11111111/m11111111_q18_t2.py", line 1, in <module>
    from pymongo import MongoClient
  File "/usr/local/lib/python3.8/dist-packages/pymongo/__init__.py", line 89, in <module>
    from pymongo.collection import ReturnDocument
  File "/usr/local/lib/python3.8/dist-packages/pymongo/collection.py", line 42, in <module>
    from bson.raw_bson import RawBSONDocument
  File "/usr/local/lib/python3.8/dist-packages/bson/raw_bson.py", line 56, in <module>
    from bson import _get_object_size, _raw_to_dict
ImportError: cannot import name '_get_object_size' from 'bson' (/usr/local/lib/python3.8/dist-packages/bson/__init__.py)
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m11111111/m11111111_q19_t0.py /platform/output/m11111111/m11111111_q19_t0.csv /platform/expected/s01/q19.csv
  File "/platform/source/s01/v1_9/m11111111/m11111111_q19_t0.py", line 18
    and p['P_SIZE'] between 1 and 5
                    ^
SyntaxError: invalid syntax
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m11111111/m11111111_q19_t1.py /platform/output/m11111111/m11111111_q19_t1.csv /platform/expected/s01/q19.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m11111111/m11111111_q19_t1.py", line 1, in <module>
    from pymongo import MongoClient
  File "/usr/local/lib/python3.8/dist-packages/pymongo/__init__.py", line 89, in <module>
    from pymongo.collection import ReturnDocument
  File "/usr/local/lib/python3.8/dist-packages/pymongo/collection.py", line 42, in <module>
    from bson.raw_bson import RawBSONDocument
  File "/usr/local/lib/python3.8/dist-packages/bson/raw_bson.py", line 56, in <module>
    from bson import _get_object_size, _raw_to_dict
ImportError: cannot import name '_get_object_size' from 'bson' (/usr/local/lib/python3.8/dist-packages/bson/__init__.py)
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m11111111/m11111111_q19_t2.py /platform/output/m11111111/m11111111_q19_t2.csv /platform/expected/s01/q19.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m11111111/m11111111_q19_t2.py", line 1, in <module>
    from pymongo import MongoClient
  File "/usr/local/lib/python3.8/dist-packages/pymongo/__init__.py", line 89, in <module>
    from pymongo.collection import ReturnDocument
  File "/usr/local/lib/python3.8/dist-packages/pymongo/collection.py", line 42, in <module>
    from bson.raw_bson import RawBSONDocument
  File "/usr/local/lib/python3.8/dist-packages/bson/raw_bson.py", line 56, in <module>
    from bson import _get_object_size, _raw_to_dict
ImportError: cannot import name '_get_object_size' from 'bson' (/usr/local/lib/python3.8/dist-packages/bson/__init__.py)
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m11111111/m11111111_q1_t0.py /platform/output/m11111111/m11111111_q1_t0.csv /platform/expected/s01/q1.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m11111111/m11111111_q1_t0.py", line 1, in <module>
    from pymongo import MongoClient
  File "/usr/local/lib/python3.8/dist-packages/pymongo/__init__.py", line 89, in <module>
    from pymongo.collection import ReturnDocument
  File "/usr/local/lib/python3.8/dist-packages/pymongo/collection.py", line 42, in <module>
    from bson.raw_bson import RawBSONDocument
  File "/usr/local/lib/python3.8/dist-packages/bson/raw_bson.py", line 56, in <module>
    from bson import _get_object_size, _raw_to_dict
ImportError: cannot import name '_get_object_size' from 'bson' (/usr/local/lib/python3.8/dist-packages/bson/__init__.py)
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m11111111/m11111111_q1_t1.py /platform/output/m11111111/m11111111_q1_t1.csv /platform/expected/s01/q1.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m11111111/m11111111_q1_t1.py", line 1, in <module>
    from pymongo import MongoClient
  File "/usr/local/lib/python3.8/dist-packages/pymongo/__init__.py", line 89, in <module>
    from pymongo.collection import ReturnDocument
  File "/usr/local/lib/python3.8/dist-packages/pymongo/collection.py", line 42, in <module>
    from bson.raw_bson import RawBSONDocument
  File "/usr/local/lib/python3.8/dist-packages/bson/raw_bson.py", line 56, in <module>
    from bson import _get_object_size, _raw_to_dict
ImportError: cannot import name '_get_object_size' from 'bson' (/usr/local/lib/python3.8/dist-packages/bson/__init__.py)
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m11111111/m11111111_q1_t2.py /platform/output/m11111111/m11111111_q1_t2.csv /platform/expected/s01/q1.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m11111111/m11111111_q1_t2.py", line 1, in <module>
    from pymongo import MongoClient
  File "/usr/local/lib/python3.8/dist-packages/pymongo/__init__.py", line 89, in <module>
    from pymongo.collection import ReturnDocument
  File "/usr/local/lib/python3.8/dist-packages/pymongo/collection.py", line 42, in <module>
    from bson.raw_bson import RawBSONDocument
  File "/usr/local/lib/python3.8/dist-packages/bson/raw_bson.py", line 56, in <module>
    from bson import _get_object_size, _raw_to_dict
ImportError: cannot import name '_get_object_size' from 'bson' (/usr/local/lib/python3.8/dist-packages/bson/__init__.py)
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m11111111/m11111111_q20_t0.py /platform/output/m11111111/m11111111_q20_t0.csv /platform/expected/s01/q20.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m11111111/m11111111_q20_t0.py", line 1, in <module>
    from pymongo import MongoClient
  File "/usr/local/lib/python3.8/dist-packages/pymongo/__init__.py", line 89, in <module>
    from pymongo.collection import ReturnDocument
  File "/usr/local/lib/python3.8/dist-packages/pymongo/collection.py", line 42, in <module>
    from bson.raw_bson import RawBSONDocument
  File "/usr/local/lib/python3.8/dist-packages/bson/raw_bson.py", line 56, in <module>
    from bson import _get_object_size, _raw_to_dict
ImportError: cannot import name '_get_object_size' from 'bson' (/usr/local/lib/python3.8/dist-packages/bson/__init__.py)
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m11111111/m11111111_q20_t1.py /platform/output/m11111111/m11111111_q20_t1.csv /platform/expected/s01/q20.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m11111111/m11111111_q20_t1.py", line 2, in <module>
    from pymongo import MongoClient
  File "/usr/local/lib/python3.8/dist-packages/pymongo/__init__.py", line 89, in <module>
    from pymongo.collection import ReturnDocument
  File "/usr/local/lib/python3.8/dist-packages/pymongo/collection.py", line 42, in <module>
    from bson.raw_bson import RawBSONDocument
  File "/usr/local/lib/python3.8/dist-packages/bson/raw_bson.py", line 56, in <module>
    from bson import _get_object_size, _raw_to_dict
ImportError: cannot import name '_get_object_size' from 'bson' (/usr/local/lib/python3.8/dist-packages/bson/__init__.py)
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m11111111/m11111111_q20_t2.py /platform/output/m11111111/m11111111_q20_t2.csv /platform/expected/s01/q20.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m11111111/m11111111_q20_t2.py", line 1, in <module>
    import pymongo
  File "/usr/local/lib/python3.8/dist-packages/pymongo/__init__.py", line 89, in <module>
    from pymongo.collection import ReturnDocument
  File "/usr/local/lib/python3.8/dist-packages/pymongo/collection.py", line 42, in <module>
    from bson.raw_bson import RawBSONDocument
  File "/usr/local/lib/python3.8/dist-packages/bson/raw_bson.py", line 56, in <module>
    from bson import _get_object_size, _raw_to_dict
ImportError: cannot import name '_get_object_size' from 'bson' (/usr/local/lib/python3.8/dist-packages/bson/__init__.py)
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m11111111/m11111111_q21_t0.py /platform/output/m11111111/m11111111_q21_t0.csv /platform/expected/s01/q21.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m11111111/m11111111_q21_t0.py", line 1, in <module>
    from pymongo import MongoClient
  File "/usr/local/lib/python3.8/dist-packages/pymongo/__init__.py", line 89, in <module>
    from pymongo.collection import ReturnDocument
  File "/usr/local/lib/python3.8/dist-packages/pymongo/collection.py", line 42, in <module>
    from bson.raw_bson import RawBSONDocument
  File "/usr/local/lib/python3.8/dist-packages/bson/raw_bson.py", line 56, in <module>
    from bson import _get_object_size, _raw_to_dict
ImportError: cannot import name '_get_object_size' from 'bson' (/usr/local/lib/python3.8/dist-packages/bson/__init__.py)
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m11111111/m11111111_q21_t1.py /platform/output/m11111111/m11111111_q21_t1.csv /platform/expected/s01/q21.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m11111111/m11111111_q21_t1.py", line 1, in <module>
    from pymongo import MongoClient
  File "/usr/local/lib/python3.8/dist-packages/pymongo/__init__.py", line 89, in <module>
    from pymongo.collection import ReturnDocument
  File "/usr/local/lib/python3.8/dist-packages/pymongo/collection.py", line 42, in <module>
    from bson.raw_bson import RawBSONDocument
  File "/usr/local/lib/python3.8/dist-packages/bson/raw_bson.py", line 56, in <module>
    from bson import _get_object_size, _raw_to_dict
ImportError: cannot import name '_get_object_size' from 'bson' (/usr/local/lib/python3.8/dist-packages/bson/__init__.py)
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m11111111/m11111111_q21_t2.py /platform/output/m11111111/m11111111_q21_t2.csv /platform/expected/s01/q21.csv
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m11111111/m11111111_q22_t0.py /platform/output/m11111111/m11111111_q22_t0.csv /platform/expected/s01/q22.csv
  File "/platform/source/s01/v1_9/m11111111/m11111111_q22_t0.py", line 24
    ]
    ^
SyntaxError: closing parenthesis ']' does not match opening parenthesis '{' on line 20
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m11111111/m11111111_q22_t1.py /platform/output/m11111111/m11111111_q22_t1.csv /platform/expected/s01/q22.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m11111111/m11111111_q22_t1.py", line 1, in <module>
    import pymongo
  File "/usr/local/lib/python3.8/dist-packages/pymongo/__init__.py", line 89, in <module>
    from pymongo.collection import ReturnDocument
  File "/usr/local/lib/python3.8/dist-packages/pymongo/collection.py", line 42, in <module>
    from bson.raw_bson import RawBSONDocument
  File "/usr/local/lib/python3.8/dist-packages/bson/raw_bson.py", line 56, in <module>
    from bson import _get_object_size, _raw_to_dict
ImportError: cannot import name '_get_object_size' from 'bson' (/usr/local/lib/python3.8/dist-packages/bson/__init__.py)
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m11111111/m11111111_q22_t2.py /platform/output/m11111111/m11111111_q22_t2.csv /platform/expected/s01/q22.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m11111111/m11111111_q22_t2.py", line 1, in <module>
    import pymongo
  File "/usr/local/lib/python3.8/dist-packages/pymongo/__init__.py", line 89, in <module>
    from pymongo.collection import ReturnDocument
  File "/usr/local/lib/python3.8/dist-packages/pymongo/collection.py", line 42, in <module>
    from bson.raw_bson import RawBSONDocument
  File "/usr/local/lib/python3.8/dist-packages/bson/raw_bson.py", line 56, in <module>
    from bson import _get_object_size, _raw_to_dict
ImportError: cannot import name '_get_object_size' from 'bson' (/usr/local/lib/python3.8/dist-packages/bson/__init__.py)
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m11111111/m11111111_q2_t0.py /platform/output/m11111111/m11111111_q2_t0.csv /platform/expected/s01/q2.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m11111111/m11111111_q2_t0.py", line 1, in <module>
    from pymongo import MongoClient
  File "/usr/local/lib/python3.8/dist-packages/pymongo/__init__.py", line 89, in <module>
    from pymongo.collection import ReturnDocument
  File "/usr/local/lib/python3.8/dist-packages/pymongo/collection.py", line 42, in <module>
    from bson.raw_bson import RawBSONDocument
  File "/usr/local/lib/python3.8/dist-packages/bson/raw_bson.py", line 56, in <module>
    from bson import _get_object_size, _raw_to_dict
ImportError: cannot import name '_get_object_size' from 'bson' (/usr/local/lib/python3.8/dist-packages/bson/__init__.py)
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m11111111/m11111111_q2_t1.py /platform/output/m11111111/m11111111_q2_t1.csv /platform/expected/s01/q2.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m11111111/m11111111_q2_t1.py", line 1, in <module>
    from pymongo import MongoClient
  File "/usr/local/lib/python3.8/dist-packages/pymongo/__init__.py", line 89, in <module>
    from pymongo.collection import ReturnDocument
  File "/usr/local/lib/python3.8/dist-packages/pymongo/collection.py", line 42, in <module>
    from bson.raw_bson import RawBSONDocument
  File "/usr/local/lib/python3.8/dist-packages/bson/raw_bson.py", line 56, in <module>
    from bson import _get_object_size, _raw_to_dict
ImportError: cannot import name '_get_object_size' from 'bson' (/usr/local/lib/python3.8/dist-packages/bson/__init__.py)
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m11111111/m11111111_q2_t2.py /platform/output/m11111111/m11111111_q2_t2.csv /platform/expected/s01/q2.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m11111111/m11111111_q2_t2.py", line 1, in <module>
    from pymongo import MongoClient
  File "/usr/local/lib/python3.8/dist-packages/pymongo/__init__.py", line 89, in <module>
    from pymongo.collection import ReturnDocument
  File "/usr/local/lib/python3.8/dist-packages/pymongo/collection.py", line 42, in <module>
    from bson.raw_bson import RawBSONDocument
  File "/usr/local/lib/python3.8/dist-packages/bson/raw_bson.py", line 56, in <module>
    from bson import _get_object_size, _raw_to_dict
ImportError: cannot import name '_get_object_size' from 'bson' (/usr/local/lib/python3.8/dist-packages/bson/__init__.py)
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m11111111/m11111111_q3_t0.py /platform/output/m11111111/m11111111_q3_t0.csv /platform/expected/s01/q3.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m11111111/m11111111_q3_t0.py", line 1, in <module>
    from pymongo import MongoClient
  File "/usr/local/lib/python3.8/dist-packages/pymongo/__init__.py", line 89, in <module>
    from pymongo.collection import ReturnDocument
  File "/usr/local/lib/python3.8/dist-packages/pymongo/collection.py", line 42, in <module>
    from bson.raw_bson import RawBSONDocument
  File "/usr/local/lib/python3.8/dist-packages/bson/raw_bson.py", line 56, in <module>
    from bson import _get_object_size, _raw_to_dict
ImportError: cannot import name '_get_object_size' from 'bson' (/usr/local/lib/python3.8/dist-packages/bson/__init__.py)
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m11111111/m11111111_q3_t1.py /platform/output/m11111111/m11111111_q3_t1.csv /platform/expected/s01/q3.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m11111111/m11111111_q3_t1.py", line 1, in <module>
    from pymongo import MongoClient
  File "/usr/local/lib/python3.8/dist-packages/pymongo/__init__.py", line 89, in <module>
    from pymongo.collection import ReturnDocument
  File "/usr/local/lib/python3.8/dist-packages/pymongo/collection.py", line 42, in <module>
    from bson.raw_bson import RawBSONDocument
  File "/usr/local/lib/python3.8/dist-packages/bson/raw_bson.py", line 56, in <module>
    from bson import _get_object_size, _raw_to_dict
ImportError: cannot import name '_get_object_size' from 'bson' (/usr/local/lib/python3.8/dist-packages/bson/__init__.py)
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m11111111/m11111111_q3_t2.py /platform/output/m11111111/m11111111_q3_t2.csv /platform/expected/s01/q3.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m11111111/m11111111_q3_t2.py", line 1, in <module>
    from pymongo import MongoClient
  File "/usr/local/lib/python3.8/dist-packages/pymongo/__init__.py", line 89, in <module>
    from pymongo.collection import ReturnDocument
  File "/usr/local/lib/python3.8/dist-packages/pymongo/collection.py", line 42, in <module>
    from bson.raw_bson import RawBSONDocument
  File "/usr/local/lib/python3.8/dist-packages/bson/raw_bson.py", line 56, in <module>
    from bson import _get_object_size, _raw_to_dict
ImportError: cannot import name '_get_object_size' from 'bson' (/usr/local/lib/python3.8/dist-packages/bson/__init__.py)
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m11111111/m11111111_q4_t0.py /platform/output/m11111111/m11111111_q4_t0.csv /platform/expected/s01/q4.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m11111111/m11111111_q4_t0.py", line 1, in <module>
    from pymongo import MongoClient
  File "/usr/local/lib/python3.8/dist-packages/pymongo/__init__.py", line 89, in <module>
    from pymongo.collection import ReturnDocument
  File "/usr/local/lib/python3.8/dist-packages/pymongo/collection.py", line 42, in <module>
    from bson.raw_bson import RawBSONDocument
  File "/usr/local/lib/python3.8/dist-packages/bson/raw_bson.py", line 56, in <module>
    from bson import _get_object_size, _raw_to_dict
ImportError: cannot import name '_get_object_size' from 'bson' (/usr/local/lib/python3.8/dist-packages/bson/__init__.py)
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m11111111/m11111111_q4_t1.py /platform/output/m11111111/m11111111_q4_t1.csv /platform/expected/s01/q4.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m11111111/m11111111_q4_t1.py", line 1, in <module>
    from pymongo import MongoClient
  File "/usr/local/lib/python3.8/dist-packages/pymongo/__init__.py", line 89, in <module>
    from pymongo.collection import ReturnDocument
  File "/usr/local/lib/python3.8/dist-packages/pymongo/collection.py", line 42, in <module>
    from bson.raw_bson import RawBSONDocument
  File "/usr/local/lib/python3.8/dist-packages/bson/raw_bson.py", line 56, in <module>
    from bson import _get_object_size, _raw_to_dict
ImportError: cannot import name '_get_object_size' from 'bson' (/usr/local/lib/python3.8/dist-packages/bson/__init__.py)
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m11111111/m11111111_q4_t2.py /platform/output/m11111111/m11111111_q4_t2.csv /platform/expected/s01/q4.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m11111111/m11111111_q4_t2.py", line 1, in <module>
    from pymongo import MongoClient
  File "/usr/local/lib/python3.8/dist-packages/pymongo/__init__.py", line 89, in <module>
    from pymongo.collection import ReturnDocument
  File "/usr/local/lib/python3.8/dist-packages/pymongo/collection.py", line 42, in <module>
    from bson.raw_bson import RawBSONDocument
  File "/usr/local/lib/python3.8/dist-packages/bson/raw_bson.py", line 56, in <module>
    from bson import _get_object_size, _raw_to_dict
ImportError: cannot import name '_get_object_size' from 'bson' (/usr/local/lib/python3.8/dist-packages/bson/__init__.py)
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m11111111/m11111111_q5_t0.py /platform/output/m11111111/m11111111_q5_t0.csv /platform/expected/s01/q5.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m11111111/m11111111_q5_t0.py", line 1, in <module>
    from pymongo import MongoClient
  File "/usr/local/lib/python3.8/dist-packages/pymongo/__init__.py", line 89, in <module>
    from pymongo.collection import ReturnDocument
  File "/usr/local/lib/python3.8/dist-packages/pymongo/collection.py", line 42, in <module>
    from bson.raw_bson import RawBSONDocument
  File "/usr/local/lib/python3.8/dist-packages/bson/raw_bson.py", line 56, in <module>
    from bson import _get_object_size, _raw_to_dict
ImportError: cannot import name '_get_object_size' from 'bson' (/usr/local/lib/python3.8/dist-packages/bson/__init__.py)
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m11111111/m11111111_q5_t1.py /platform/output/m11111111/m11111111_q5_t1.csv /platform/expected/s01/q5.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m11111111/m11111111_q5_t1.py", line 1, in <module>
    from pymongo import MongoClient
  File "/usr/local/lib/python3.8/dist-packages/pymongo/__init__.py", line 89, in <module>
    from pymongo.collection import ReturnDocument
  File "/usr/local/lib/python3.8/dist-packages/pymongo/collection.py", line 42, in <module>
    from bson.raw_bson import RawBSONDocument
  File "/usr/local/lib/python3.8/dist-packages/bson/raw_bson.py", line 56, in <module>
    from bson import _get_object_size, _raw_to_dict
ImportError: cannot import name '_get_object_size' from 'bson' (/usr/local/lib/python3.8/dist-packages/bson/__init__.py)
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m11111111/m11111111_q5_t2.py /platform/output/m11111111/m11111111_q5_t2.csv /platform/expected/s01/q5.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m11111111/m11111111_q5_t2.py", line 1, in <module>
    from pymongo import MongoClient
  File "/usr/local/lib/python3.8/dist-packages/pymongo/__init__.py", line 89, in <module>
    from pymongo.collection import ReturnDocument
  File "/usr/local/lib/python3.8/dist-packages/pymongo/collection.py", line 42, in <module>
    from bson.raw_bson import RawBSONDocument
  File "/usr/local/lib/python3.8/dist-packages/bson/raw_bson.py", line 56, in <module>
    from bson import _get_object_size, _raw_to_dict
ImportError: cannot import name '_get_object_size' from 'bson' (/usr/local/lib/python3.8/dist-packages/bson/__init__.py)
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m11111111/m11111111_q6_t0.py /platform/output/m11111111/m11111111_q6_t0.csv /platform/expected/s01/q6.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m11111111/m11111111_q6_t0.py", line 2, in <module>
    from pymongo import MongoClient
  File "/usr/local/lib/python3.8/dist-packages/pymongo/__init__.py", line 89, in <module>
    from pymongo.collection import ReturnDocument
  File "/usr/local/lib/python3.8/dist-packages/pymongo/collection.py", line 42, in <module>
    from bson.raw_bson import RawBSONDocument
  File "/usr/local/lib/python3.8/dist-packages/bson/raw_bson.py", line 56, in <module>
    from bson import _get_object_size, _raw_to_dict
ImportError: cannot import name '_get_object_size' from 'bson' (/usr/local/lib/python3.8/dist-packages/bson/__init__.py)
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m11111111/m11111111_q6_t1.py /platform/output/m11111111/m11111111_q6_t1.csv /platform/expected/s01/q6.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m11111111/m11111111_q6_t1.py", line 1, in <module>
    from pymongo import MongoClient
  File "/usr/local/lib/python3.8/dist-packages/pymongo/__init__.py", line 89, in <module>
    from pymongo.collection import ReturnDocument
  File "/usr/local/lib/python3.8/dist-packages/pymongo/collection.py", line 42, in <module>
    from bson.raw_bson import RawBSONDocument
  File "/usr/local/lib/python3.8/dist-packages/bson/raw_bson.py", line 56, in <module>
    from bson import _get_object_size, _raw_to_dict
ImportError: cannot import name '_get_object_size' from 'bson' (/usr/local/lib/python3.8/dist-packages/bson/__init__.py)
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m11111111/m11111111_q6_t2.py /platform/output/m11111111/m11111111_q6_t2.csv /platform/expected/s01/q6.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m11111111/m11111111_q6_t2.py", line 1, in <module>
    from pymongo import MongoClient
  File "/usr/local/lib/python3.8/dist-packages/pymongo/__init__.py", line 89, in <module>
    from pymongo.collection import ReturnDocument
  File "/usr/local/lib/python3.8/dist-packages/pymongo/collection.py", line 42, in <module>
    from bson.raw_bson import RawBSONDocument
  File "/usr/local/lib/python3.8/dist-packages/bson/raw_bson.py", line 56, in <module>
    from bson import _get_object_size, _raw_to_dict
ImportError: cannot import name '_get_object_size' from 'bson' (/usr/local/lib/python3.8/dist-packages/bson/__init__.py)
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m11111111/m11111111_q7_t0.py /platform/output/m11111111/m11111111_q7_t0.csv /platform/expected/s01/q7.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m11111111/m11111111_q7_t0.py", line 1, in <module>
    from pymongo import MongoClient
  File "/usr/local/lib/python3.8/dist-packages/pymongo/__init__.py", line 89, in <module>
    from pymongo.collection import ReturnDocument
  File "/usr/local/lib/python3.8/dist-packages/pymongo/collection.py", line 42, in <module>
    from bson.raw_bson import RawBSONDocument
  File "/usr/local/lib/python3.8/dist-packages/bson/raw_bson.py", line 56, in <module>
    from bson import _get_object_size, _raw_to_dict
ImportError: cannot import name '_get_object_size' from 'bson' (/usr/local/lib/python3.8/dist-packages/bson/__init__.py)
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m11111111/m11111111_q7_t1.py /platform/output/m11111111/m11111111_q7_t1.csv /platform/expected/s01/q7.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m11111111/m11111111_q7_t1.py", line 1, in <module>
    from pymongo import MongoClient
  File "/usr/local/lib/python3.8/dist-packages/pymongo/__init__.py", line 89, in <module>
    from pymongo.collection import ReturnDocument
  File "/usr/local/lib/python3.8/dist-packages/pymongo/collection.py", line 42, in <module>
    from bson.raw_bson import RawBSONDocument
  File "/usr/local/lib/python3.8/dist-packages/bson/raw_bson.py", line 56, in <module>
    from bson import _get_object_size, _raw_to_dict
ImportError: cannot import name '_get_object_size' from 'bson' (/usr/local/lib/python3.8/dist-packages/bson/__init__.py)
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m11111111/m11111111_q7_t2.py /platform/output/m11111111/m11111111_q7_t2.csv /platform/expected/s01/q7.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m11111111/m11111111_q7_t2.py", line 1, in <module>
    from pymongo import MongoClient
  File "/usr/local/lib/python3.8/dist-packages/pymongo/__init__.py", line 89, in <module>
    from pymongo.collection import ReturnDocument
  File "/usr/local/lib/python3.8/dist-packages/pymongo/collection.py", line 42, in <module>
    from bson.raw_bson import RawBSONDocument
  File "/usr/local/lib/python3.8/dist-packages/bson/raw_bson.py", line 56, in <module>
    from bson import _get_object_size, _raw_to_dict
ImportError: cannot import name '_get_object_size' from 'bson' (/usr/local/lib/python3.8/dist-packages/bson/__init__.py)
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m11111111/m11111111_q8_t0.py /platform/output/m11111111/m11111111_q8_t0.csv /platform/expected/s01/q8.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m11111111/m11111111_q8_t0.py", line 1, in <module>
    from pymongo import MongoClient
  File "/usr/local/lib/python3.8/dist-packages/pymongo/__init__.py", line 89, in <module>
    from pymongo.collection import ReturnDocument
  File "/usr/local/lib/python3.8/dist-packages/pymongo/collection.py", line 42, in <module>
    from bson.raw_bson import RawBSONDocument
  File "/usr/local/lib/python3.8/dist-packages/bson/raw_bson.py", line 56, in <module>
    from bson import _get_object_size, _raw_to_dict
ImportError: cannot import name '_get_object_size' from 'bson' (/usr/local/lib/python3.8/dist-packages/bson/__init__.py)
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m11111111/m11111111_q8_t1.py /platform/output/m11111111/m11111111_q8_t1.csv /platform/expected/s01/q8.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m11111111/m11111111_q8_t1.py", line 1, in <module>
    from pymongo import MongoClient
  File "/usr/local/lib/python3.8/dist-packages/pymongo/__init__.py", line 89, in <module>
    from pymongo.collection import ReturnDocument
  File "/usr/local/lib/python3.8/dist-packages/pymongo/collection.py", line 42, in <module>
    from bson.raw_bson import RawBSONDocument
  File "/usr/local/lib/python3.8/dist-packages/bson/raw_bson.py", line 56, in <module>
    from bson import _get_object_size, _raw_to_dict
ImportError: cannot import name '_get_object_size' from 'bson' (/usr/local/lib/python3.8/dist-packages/bson/__init__.py)
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m11111111/m11111111_q8_t2.py /platform/output/m11111111/m11111111_q8_t2.csv /platform/expected/s01/q8.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m11111111/m11111111_q8_t2.py", line 1, in <module>
    from pymongo import MongoClient
  File "/usr/local/lib/python3.8/dist-packages/pymongo/__init__.py", line 89, in <module>
    from pymongo.collection import ReturnDocument
  File "/usr/local/lib/python3.8/dist-packages/pymongo/collection.py", line 42, in <module>
    from bson.raw_bson import RawBSONDocument
  File "/usr/local/lib/python3.8/dist-packages/bson/raw_bson.py", line 56, in <module>
    from bson import _get_object_size, _raw_to_dict
ImportError: cannot import name '_get_object_size' from 'bson' (/usr/local/lib/python3.8/dist-packages/bson/__init__.py)
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m11111111/m11111111_q9_t0.py /platform/output/m11111111/m11111111_q9_t0.csv /platform/expected/s01/q9.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m11111111/m11111111_q9_t0.py", line 1, in <module>
    from pymongo import MongoClient
  File "/usr/local/lib/python3.8/dist-packages/pymongo/__init__.py", line 89, in <module>
    from pymongo.collection import ReturnDocument
  File "/usr/local/lib/python3.8/dist-packages/pymongo/collection.py", line 42, in <module>
    from bson.raw_bson import RawBSONDocument
  File "/usr/local/lib/python3.8/dist-packages/bson/raw_bson.py", line 56, in <module>
    from bson import _get_object_size, _raw_to_dict
ImportError: cannot import name '_get_object_size' from 'bson' (/usr/local/lib/python3.8/dist-packages/bson/__init__.py)
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m11111111/m11111111_q9_t1.py /platform/output/m11111111/m11111111_q9_t1.csv /platform/expected/s01/q9.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m11111111/m11111111_q9_t1.py", line 1, in <module>
    from pymongo import MongoClient
  File "/usr/local/lib/python3.8/dist-packages/pymongo/__init__.py", line 89, in <module>
    from pymongo.collection import ReturnDocument
  File "/usr/local/lib/python3.8/dist-packages/pymongo/collection.py", line 42, in <module>
    from bson.raw_bson import RawBSONDocument
  File "/usr/local/lib/python3.8/dist-packages/bson/raw_bson.py", line 56, in <module>
    from bson import _get_object_size, _raw_to_dict
ImportError: cannot import name '_get_object_size' from 'bson' (/usr/local/lib/python3.8/dist-packages/bson/__init__.py)
Score.fail_missing_output
python /grader.py /platform/source/s01/v1_9/m11111111/m11111111_q9_t2.py /platform/output/m11111111/m11111111_q9_t2.csv /platform/expected/s01/q9.csv
Traceback (most recent call last):
  File "/platform/source/s01/v1_9/m11111111/m11111111_q9_t2.py", line 1, in <module>
    import pymongo
  File "/usr/local/lib/python3.8/dist-packages/pymongo/__init__.py", line 89, in <module>
    from pymongo.collection import ReturnDocument
  File "/usr/local/lib/python3.8/dist-packages/pymongo/collection.py", line 42, in <module>
    from bson.raw_bson import RawBSONDocument
  File "/usr/local/lib/python3.8/dist-packages/bson/raw_bson.py", line 56, in <module>
    from bson import _get_object_size, _raw_to_dict
ImportError: cannot import name '_get_object_size' from 'bson' (/usr/local/lib/python3.8/dist-packages/bson/__init__.py)
Score.fail_missing_output
