Using MAPPING_STR=21212121, VERSION_DIR=v4_engman
Running /platform/source/s01/v4_engman/m21212121/m21212121_q10_t0.sh
/platform/source/s01/v4_engman/m21212121/m21212121_q10_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4_engman/m21212121/m21212121_q10_t0.sh: line 5: sudo: command not found
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: redis in /usr/local/lib/python3.8/dist-packages (3.4.1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4_engman/m21212121/m21212121_q11_t0.sh
/platform/source/s01/v4_engman/m21212121/m21212121_q11_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4_engman/m21212121/m21212121_q11_t0.sh: line 5: sudo: command not found
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4_engman/m21212121/m21212121_q12_t0.sh
/platform/source/s01/v4_engman/m21212121/m21212121_q12_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4_engman/m21212121/m21212121_q12_t0.sh: line 7: sudo: command not found
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: redis in /usr/local/lib/python3.8/dist-packages (3.4.1)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4_engman/m21212121/m21212121_q13_t0.sh
/platform/source/s01/v4_engman/m21212121/m21212121_q13_t0.sh: line 5: sudo: command not found
/platform/source/s01/v4_engman/m21212121/m21212121_q13_t0.sh: line 6: sudo: command not found
/platform/source/s01/v4_engman/m21212121/m21212121_q13_t0.sh: line 9: sudo: command not found
/platform/source/s01/v4_engman/m21212121/m21212121_q13_t0.sh: line 10: sudo: command not found
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: direct-redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct-redis) (3.4.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4_engman/m21212121/m21212121_q14_t0.sh
0% [Working]            Hit:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease
0% [Working]            Get:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease [114 kB]
0% [2 InRelease 4135 B/114 kB 4%]0% [2 InRelease 15.7 kB/114 kB 14%]                                   0% [Waiting for headers]0% [Waiting for headers]                        Hit:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease
                        0% [Working]0% [Waiting for headers]                        Hit:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease
                        0% [Working]100% [Working]              Fetched 114 kB in 1s (119 kB/s)
Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Building dependency tree... 0%Building dependency tree... 0%Building dependency tree... 50%Building dependency tree... 50%Building dependency tree       
Reading state information... 0%Reading state information... 0%Reading state information... Done
python3 is already the newest version (3.8.2-0ubuntu2).
python3 set to manually installed.
python3-pip is already the newest version (20.0.2-5ubuntu1.10).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4_engman/m21212121/m21212121_q15_t0.sh
/platform/source/s01/v4_engman/m21212121/m21212121_q15_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4_engman/m21212121/m21212121_q15_t0.sh: line 7: sudo: command not found
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Running /platform/source/s01/v4_engman/m21212121/m21212121_q16_t0.sh
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Collecting git+https://github.com/Unturned3/direct_redis.git
  Cloning https://github.com/Unturned3/direct_redis.git to /tmp/pip-req-build-7u7ng6cb
  Running command git clone -q https://github.com/Unturned3/direct_redis.git /tmp/pip-req-build-7u7ng6cb
[31m  ERROR: Error [Errno 2] No such file or directory: 'git' while executing command git clone -q https://github.com/Unturned3/direct_redis.git /tmp/pip-req-build-7u7ng6cb[0m
[31mERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?[0m
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4_engman/m21212121/m21212121_q17_t0.sh
/platform/source/s01/v4_engman/m21212121/m21212121_q17_t0.sh: line 5: sudo: command not found
/platform/source/s01/v4_engman/m21212121/m21212121_q17_t0.sh: line 11: sudo: command not found
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4_engman/m21212121/m21212121_q18_t0.sh
/platform/source/s01/v4_engman/m21212121/m21212121_q18_t0.sh: line 6: sudo: command not found
/platform/source/s01/v4_engman/m21212121/m21212121_q18_t0.sh: line 9: sudo: command not found
/platform/source/s01/v4_engman/m21212121/m21212121_q18_t0.sh: line 12: sudo: command not found
/platform/source/s01/v4_engman/m21212121/m21212121_q18_t0.sh: line 15: sudo: command not found
/platform/source/s01/v4_engman/m21212121/m21212121_q18_t0.sh: line 18: sudo: command not found
/platform/source/s01/v4_engman/m21212121/m21212121_q18_t0.sh: line 21: sudo: command not found
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4_engman/m21212121/m21212121_q19_t0.sh
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: redis in /usr/local/lib/python3.8/dist-packages (3.4.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4_engman/m21212121/m21212121_q1_t0.sh
/platform/source/s01/v4_engman/m21212121/m21212121_q1_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4_engman/m21212121/m21212121_q1_t0.sh: line 7: sudo: command not found
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Running /platform/source/s01/v4_engman/m21212121/m21212121_q20_t0.sh
/platform/source/s01/v4_engman/m21212121/m21212121_q20_t0.sh: line 6: sudo: command not found
/platform/source/s01/v4_engman/m21212121/m21212121_q20_t0.sh: line 9: sudo: command not found
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4_engman/m21212121/m21212121_q21_t0.sh
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4_engman/m21212121/m21212121_q22_t0.sh
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4_engman/m21212121/m21212121_q2_t0.sh
/platform/source/s01/v4_engman/m21212121/m21212121_q2_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4_engman/m21212121/m21212121_q2_t0.sh: line 5: sudo: command not found
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: redis in /usr/local/lib/python3.8/dist-packages (3.4.1)
Requirement already satisfied: direct-redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4_engman/m21212121/m21212121_q3_t0.sh
Running /platform/source/s01/v4_engman/m21212121/m21212121_q4_t0.sh
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4_engman/m21212121/m21212121_q5_t0.sh
/platform/source/s01/v4_engman/m21212121/m21212121_q5_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4_engman/m21212121/m21212121_q5_t0.sh: line 7: sudo: command not found
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: redis in /usr/local/lib/python3.8/dist-packages (3.4.1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Collecting git+https://github.com/yourrepo/direct_redis.git
  Cloning https://github.com/yourrepo/direct_redis.git to /tmp/pip-req-build-260tji2v
  Running command git clone -q https://github.com/yourrepo/direct_redis.git /tmp/pip-req-build-260tji2v
[31m  ERROR: Error [Errno 2] No such file or directory: 'git' while executing command git clone -q https://github.com/yourrepo/direct_redis.git /tmp/pip-req-build-260tji2v[0m
[31mERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?[0m
Running /platform/source/s01/v4_engman/m21212121/m21212121_q6_t0.sh
0% [Working]0% [Connecting to ports.ubuntu.com (185.125.190.39)]0% [Connecting to ports.ubuntu.com (185.125.190.39)]0% [Connecting to ports.ubuntu.com (185.125.190.39)]0% [Connecting to ports.ubuntu.com (185.125.190.39)]0% [Connecting to ports.ubuntu.com (185.125.190.39)]0% [Connecting to ports.ubuntu.com (185.125.190.39)]0% [Connecting to ports.ubuntu.com (185.125.190.39)]0% [Connecting to ports.ubuntu.com (185.125.190.39)]0% [Connecting to ports.ubuntu.com (185.125.190.39)]0% [Connecting to ports.ubuntu.com (185.125.190.39)]0% [Connecting to ports.ubuntu.com (185.125.190.39)]0% [Connecting to ports.ubuntu.com (185.125.190.39)]0% [Connecting to ports.ubuntu.com (185.125.190.39)]0% [Connecting to ports.ubuntu.com (185.125.190.39)]0% [Connecting to ports.ubuntu.com (185.125.190.39)]0% [Connecting to ports.ubuntu.com (185.125.190.39)]0% [Connecting to ports.ubuntu.com (185.125.190.39)]0% [Connecting to ports.ubuntu.com (185.125.190.39)]0% [Connecting to ports.ubuntu.com (185.125.190.39)]0% [Connecting to ports.ubuntu.com (185.125.190.39)]0% [Connecting to ports.ubuntu.com (185.125.190.39)]0% [Connecting to ports.ubuntu.com (185.125.190.39)]0% [Connecting to ports.ubuntu.com (185.125.190.39)]0% [Connecting to ports.ubuntu.com (185.125.190.39)]0% [Connecting to ports.ubuntu.com (185.125.190.39)]0% [Connecting to ports.ubuntu.com (185.125.190.39)]0% [Connecting to ports.ubuntu.com (185.125.190.39)]0% [Connecting to ports.ubuntu.com (185.125.190.39)]0% [Connecting to ports.ubuntu.com (185.125.190.39)]0% [Connecting to ports.ubuntu.com (185.125.190.39)]0% [Connecting to ports.ubuntu.com (185.125.190.39)]0% [Connecting to ports.ubuntu.com (185.125.190.39)]0% [Connecting to ports.ubuntu.com (185.125.190.39)]0% [Connecting to ports.ubuntu.com (185.125.190.39)]0% [Connecting to ports.ubuntu.com (185.125.190.39)]0% [Connecting to ports.ubuntu.com (185.125.190.39)]0% [Connecting to ports.ubuntu.com (185.125.190.39)]0% [Connecting to ports.ubuntu.com (185.125.190.39)]0% [Connecting to ports.ubuntu.com (185.125.190.39)]0% [Connecting to ports.ubuntu.com (185.125.190.39)]0% [Connecting to ports.ubuntu.com (185.125.190.39)]0% [Connecting to ports.ubuntu.com (185.125.190.39)]0% [Connecting to ports.ubuntu.com (185.125.190.39)]0% [Connecting to ports.ubuntu.com (185.125.190.39)]0% [Connecting to ports.ubuntu.com (185.125.190.39)]0% [Connecting to ports.ubuntu.com (185.125.190.39)]0% [Connecting to ports.ubuntu.com (185.125.190.39)]0% [Connecting to ports.ubuntu.com (185.125.190.39)]0% [Connecting to ports.ubuntu.com (185.125.190.39)]0% [Connecting to ports.ubuntu.com (185.125.190.39)]0% [Connecting to ports.ubuntu.com (185.125.190.39)]0% [Connecting to ports.ubuntu.com (185.125.190.39)]0% [Connecting to ports.ubuntu.com (185.125.190.39)]0% [Connecting to ports.ubuntu.com (185.125.190.39)]0% [Connecting to ports.ubuntu.com (185.125.190.39)]0% [Connecting to ports.ubuntu.com (185.125.190.39)]0% [Connecting to ports.ubuntu.com (185.125.190.39)]0% [Connecting to ports.ubuntu.com (185.125.190.39)]0% [Connecting to ports.ubuntu.com (185.125.190.39)]0% [Connecting to ports.ubuntu.com (185.125.190.39)]                                                    Err:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease
  Could not connect to ports.ubuntu.com:80 (185.125.190.36), connection timed out Could not connect to ports.ubuntu.com:80 (185.125.190.39), connection timed out
                                                    Err:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease
  Unable to connect to ports.ubuntu.com:http:
                                                    0% [Working]            Err:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease
  Unable to connect to ports.ubuntu.com:http:
            Err:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease
  Unable to connect to ports.ubuntu.com:http:
0% [Working]            Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/focal/InRelease  Could not connect to ports.ubuntu.com:80 (185.125.190.36), connection timed out Could not connect to ports.ubuntu.com:80 (185.125.190.39), connection timed out
W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/focal-updates/InRelease  Unable to connect to ports.ubuntu.com:http:
W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/focal-backports/InRelease  Unable to connect to ports.ubuntu.com:http:
W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/focal-security/InRelease  Unable to connect to ports.ubuntu.com:http:
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Building dependency tree... 0%Building dependency tree... 0%Building dependency tree... 50%Building dependency tree... 50%Building dependency tree       
Reading state information... 0%Reading state information... 0%Reading state information... Done
python3 is already the newest version (3.8.2-0ubuntu2).
python3-pip is already the newest version (20.0.2-5ubuntu1.10).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Running /platform/source/s01/v4_engman/m21212121/m21212121_q7_t0.sh
/platform/source/s01/v4_engman/m21212121/m21212121_q7_t0.sh: line 6: sudo: command not found
/platform/source/s01/v4_engman/m21212121/m21212121_q7_t0.sh: line 9: sudo: command not found
/platform/source/s01/v4_engman/m21212121/m21212121_q7_t0.sh: line 10: sudo: command not found
[33mWARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0xffffb2d81dc0>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/pip/[0m
[33mWARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0xffffb2d816d0>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/pip/[0m
[33mWARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0xffffb2d817c0>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/pip/[0m
[33mWARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0xffffb2d81550>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/pip/[0m
[33mWARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0xffffb2d813a0>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/pip/[0m
Collecting pip
  Downloading pip-23.3.1-py3-none-any.whl (2.1 MB)
[?25l[K     |▏                               | 10 kB 23.0 MB/s eta 0:00:01[K     |▎                               | 20 kB 6.0 MB/s eta 0:00:01[K     |▌                               | 30 kB 8.8 MB/s eta 0:00:01[K     |▋                               | 40 kB 3.9 MB/s eta 0:00:01[K     |▊                               | 51 kB 3.8 MB/s eta 0:00:01[K     |█                               | 61 kB 4.5 MB/s eta 0:00:01[K     |█                               | 71 kB 5.2 MB/s eta 0:00:01[K     |█▎                              | 81 kB 5.7 MB/s eta 0:00:01[K     |█▍                              | 92 kB 6.3 MB/s eta 0:00:01[K     |█▌                              | 102 kB 6.1 MB/s eta 0:00:01[K     |█▊                              | 112 kB 6.1 MB/s eta 0:00:01[K     |█▉                              | 122 kB 6.1 MB/s eta 0:00:01[K     |██                              | 133 kB 6.1 MB/s eta 0:00:01[K     |██▏                             | 143 kB 6.1 MB/s eta 0:00:01[K     |██▎                             | 153 kB 6.1 MB/s eta 0:00:01[K     |██▌                             | 163 kB 6.1 MB/s eta 0:00:01[K     |██▋                             | 174 kB 6.1 MB/s eta 0:00:01[K     |██▉                             | 184 kB 6.1 MB/s eta 0:00:01[K     |███                             | 194 kB 6.1 MB/s eta 0:00:01[K     |███                             | 204 kB 6.1 MB/s eta 0:00:01[K     |███▎                            | 215 kB 6.1 MB/s eta 0:00:01[K     |███▍                            | 225 kB 6.1 MB/s eta 0:00:01[K     |███▋                            | 235 kB 6.1 MB/s eta 0:00:01[K     |███▊                            | 245 kB 6.1 MB/s eta 0:00:01[K     |███▉                            | 256 kB 6.1 MB/s eta 0:00:01[K     |████                            | 266 kB 6.1 MB/s eta 0:00:01[K     |████▏                           | 276 kB 6.1 MB/s eta 0:00:01[K     |████▍                           | 286 kB 6.1 MB/s eta 0:00:01[K     |████▌                           | 296 kB 6.1 MB/s eta 0:00:01[K     |████▋                           | 307 kB 6.1 MB/s eta 0:00:01[K     |████▉                           | 317 kB 6.1 MB/s eta 0:00:01[K     |█████                           | 327 kB 6.1 MB/s eta 0:00:01[K     |█████▏                          | 337 kB 6.1 MB/s eta 0:00:01[K     |█████▎                          | 348 kB 6.1 MB/s eta 0:00:01[K     |█████▍                          | 358 kB 6.1 MB/s eta 0:00:01[K     |█████▋                          | 368 kB 6.1 MB/s eta 0:00:01[K     |█████▊                          | 378 kB 6.1 MB/s eta 0:00:01[K     |██████                          | 389 kB 6.1 MB/s eta 0:00:01[K     |██████                          | 399 kB 6.1 MB/s eta 0:00:01[K     |██████▏                         | 409 kB 6.1 MB/s eta 0:00:01[K     |██████▍                         | 419 kB 6.1 MB/s eta 0:00:01[K     |██████▌                         | 430 kB 6.1 MB/s eta 0:00:01[K     |██████▊                         | 440 kB 6.1 MB/s eta 0:00:01[K     |██████▉                         | 450 kB 6.1 MB/s eta 0:00:01[K     |███████                         | 460 kB 6.1 MB/s eta 0:00:01[K     |███████▏                        | 471 kB 6.1 MB/s eta 0:00:01[K     |███████▎                        | 481 kB 6.1 MB/s eta 0:00:01[K     |███████▌                        | 491 kB 6.1 MB/s eta 0:00:01[K     |███████▋                        | 501 kB 6.1 MB/s eta 0:00:01[K     |███████▊                        | 512 kB 6.1 MB/s eta 0:00:01[K     |████████                        | 522 kB 6.1 MB/s eta 0:00:01[K     |████████                        | 532 kB 6.1 MB/s eta 0:00:01[K     |████████▎                       | 542 kB 6.1 MB/s eta 0:00:01[K     |████████▍                       | 552 kB 6.1 MB/s eta 0:00:01[K     |████████▌                       | 563 kB 6.1 MB/s eta 0:00:01[K     |████████▊                       | 573 kB 6.1 MB/s eta 0:00:01[K     |████████▉                       | 583 kB 6.1 MB/s eta 0:00:01[K     |█████████                       | 593 kB 6.1 MB/s eta 0:00:01[K     |█████████▏                      | 604 kB 6.1 MB/s eta 0:00:01[K     |█████████▎                      | 614 kB 6.1 MB/s eta 0:00:01[K     |█████████▌                      | 624 kB 6.1 MB/s eta 0:00:01[K     |█████████▋                      | 634 kB 6.1 MB/s eta 0:00:01[K     |█████████▉                      | 645 kB 6.1 MB/s eta 0:00:01[K     |██████████                      | 655 kB 6.1 MB/s eta 0:00:01[K     |██████████                      | 665 kB 6.1 MB/s eta 0:00:01[K     |██████████▎                     | 675 kB 6.1 MB/s eta 0:00:01[K     |██████████▍                     | 686 kB 6.1 MB/s eta 0:00:01[K     |██████████▋                     | 696 kB 6.1 MB/s eta 0:00:01[K     |██████████▊                     | 706 kB 6.1 MB/s eta 0:00:01[K     |██████████▉                     | 716 kB 6.1 MB/s eta 0:00:01[K     |███████████                     | 727 kB 6.1 MB/s eta 0:00:01[K     |███████████▏                    | 737 kB 6.1 MB/s eta 0:00:01[K     |███████████▍                    | 747 kB 6.1 MB/s eta 0:00:01[K     |███████████▌                    | 757 kB 6.1 MB/s eta 0:00:01[K     |███████████▋                    | 768 kB 6.1 MB/s eta 0:00:01[K     |███████████▉                    | 778 kB 6.1 MB/s eta 0:00:01[K     |████████████                    | 788 kB 6.1 MB/s eta 0:00:01[K     |████████████▏                   | 798 kB 6.1 MB/s eta 0:00:01[K     |████████████▎                   | 808 kB 6.1 MB/s eta 0:00:01[K     |████████████▍                   | 819 kB 6.1 MB/s eta 0:00:01[K     |████████████▋                   | 829 kB 6.1 MB/s eta 0:00:01[K     |████████████▊                   | 839 kB 6.1 MB/s eta 0:00:01[K     |█████████████                   | 849 kB 6.1 MB/s eta 0:00:01[K     |█████████████                   | 860 kB 6.1 MB/s eta 0:00:01[K     |█████████████▏                  | 870 kB 6.1 MB/s eta 0:00:01[K     |█████████████▍                  | 880 kB 6.1 MB/s eta 0:00:01[K     |█████████████▌                  | 890 kB 6.1 MB/s eta 0:00:01[K     |█████████████▊                  | 901 kB 6.1 MB/s eta 0:00:01[K     |█████████████▉                  | 911 kB 6.1 MB/s eta 0:00:01[K     |██████████████                  | 921 kB 6.1 MB/s eta 0:00:01[K     |██████████████▏                 | 931 kB 6.1 MB/s eta 0:00:01[K     |██████████████▎                 | 942 kB 6.1 MB/s eta 0:00:01[K     |██████████████▌                 | 952 kB 6.1 MB/s eta 0:00:01[K     |██████████████▋                 | 962 kB 6.1 MB/s eta 0:00:01[K     |██████████████▊                 | 972 kB 6.1 MB/s eta 0:00:01[K     |███████████████                 | 983 kB 6.1 MB/s eta 0:00:01[K     |███████████████                 | 993 kB 6.1 MB/s eta 0:00:01[K     |███████████████▎                | 1.0 MB 6.1 MB/s eta 0:00:01[K     |███████████████▍                | 1.0 MB 6.1 MB/s eta 0:00:01[K     |███████████████▌                | 1.0 MB 6.1 MB/s eta 0:00:01[K     |███████████████▊                | 1.0 MB 6.1 MB/s eta 0:00:01[K     |███████████████▉                | 1.0 MB 6.1 MB/s eta 0:00:01[K     |████████████████                | 1.1 MB 6.1 MB/s eta 0:00:01[K     |████████████████▏               | 1.1 MB 6.1 MB/s eta 0:00:01[K     |████████████████▎               | 1.1 MB 6.1 MB/s eta 0:00:01[K     |████████████████▌               | 1.1 MB 6.1 MB/s eta 0:00:01[K     |████████████████▋               | 1.1 MB 6.1 MB/s eta 0:00:01[K     |████████████████▉               | 1.1 MB 6.1 MB/s eta 0:00:01[K     |█████████████████               | 1.1 MB 6.1 MB/s eta 0:00:01[K     |█████████████████               | 1.1 MB 6.1 MB/s eta 0:00:01[K     |█████████████████▎              | 1.1 MB 6.1 MB/s eta 0:00:01[K     |█████████████████▍              | 1.1 MB 6.1 MB/s eta 0:00:01[K     |█████████████████▋              | 1.2 MB 6.1 MB/s eta 0:00:01[K     |█████████████████▊              | 1.2 MB 6.1 MB/s eta 0:00:01[K     |█████████████████▉              | 1.2 MB 6.1 MB/s eta 0:00:01[K     |██████████████████              | 1.2 MB 6.1 MB/s eta 0:00:01[K     |██████████████████▏             | 1.2 MB 6.1 MB/s eta 0:00:01[K     |██████████████████▍             | 1.2 MB 6.1 MB/s eta 0:00:01[K     |██████████████████▌             | 1.2 MB 6.1 MB/s eta 0:00:01[K     |██████████████████▋             | 1.2 MB 6.1 MB/s eta 0:00:01[K     |██████████████████▉             | 1.2 MB 6.1 MB/s eta 0:00:01[K     |███████████████████             | 1.2 MB 6.1 MB/s eta 0:00:01[K     |███████████████████▏            | 1.3 MB 6.1 MB/s eta 0:00:01[K     |███████████████████▎            | 1.3 MB 6.1 MB/s eta 0:00:01[K     |███████████████████▍            | 1.3 MB 6.1 MB/s eta 0:00:01[K     |███████████████████▋            | 1.3 MB 6.1 MB/s eta 0:00:01[K     |███████████████████▊            | 1.3 MB 6.1 MB/s eta 0:00:01[K     |████████████████████            | 1.3 MB 6.1 MB/s eta 0:00:01[K     |████████████████████            | 1.3 MB 6.1 MB/s eta 0:00:01[K     |████████████████████▏           | 1.3 MB 6.1 MB/s eta 0:00:01[K     |████████████████████▍           | 1.3 MB 6.1 MB/s eta 0:00:01[K     |████████████████████▌           | 1.4 MB 6.1 MB/s eta 0:00:01[K     |████████████████████▊           | 1.4 MB 6.1 MB/s eta 0:00:01[K     |████████████████████▉           | 1.4 MB 6.1 MB/s eta 0:00:01[K     |█████████████████████           | 1.4 MB 6.1 MB/s eta 0:00:01[K     |█████████████████████▏          | 1.4 MB 6.1 MB/s eta 0:00:01[K     |█████████████████████▎          | 1.4 MB 6.1 MB/s eta 0:00:01[K     |█████████████████████▌          | 1.4 MB 6.1 MB/s eta 0:00:01[K     |█████████████████████▋          | 1.4 MB 6.1 MB/s eta 0:00:01[K     |█████████████████████▊          | 1.4 MB 6.1 MB/s eta 0:00:01[K     |██████████████████████          | 1.4 MB 6.1 MB/s eta 0:00:01[K     |██████████████████████          | 1.5 MB 6.1 MB/s eta 0:00:01[K     |██████████████████████▎         | 1.5 MB 6.1 MB/s eta 0:00:01[K     |██████████████████████▍         | 1.5 MB 6.1 MB/s eta 0:00:01[K     |██████████████████████▌         | 1.5 MB 6.1 MB/s eta 0:00:01[K     |██████████████████████▊         | 1.5 MB 6.1 MB/s eta 0:00:01[K     |██████████████████████▉         | 1.5 MB 6.1 MB/s eta 0:00:01[K     |███████████████████████         | 1.5 MB 6.1 MB/s eta 0:00:01[K     |███████████████████████▏        | 1.5 MB 6.1 MB/s eta 0:00:01[K     |███████████████████████▎        | 1.5 MB 6.1 MB/s eta 0:00:01[K     |███████████████████████▌        | 1.5 MB 6.1 MB/s eta 0:00:01[K     |███████████████████████▋        | 1.6 MB 6.1 MB/s eta 0:00:01[K     |███████████████████████▉        | 1.6 MB 6.1 MB/s eta 0:00:01[K     |████████████████████████        | 1.6 MB 6.1 MB/s eta 0:00:01[K     |████████████████████████        | 1.6 MB 6.1 MB/s eta 0:00:01[K     |████████████████████████▎       | 1.6 MB 6.1 MB/s eta 0:00:01[K     |████████████████████████▍       | 1.6 MB 6.1 MB/s eta 0:00:01[K     |████████████████████████▋       | 1.6 MB 6.1 MB/s eta 0:00:01[K     |████████████████████████▊       | 1.6 MB 6.1 MB/s eta 0:00:01[K     |████████████████████████▉       | 1.6 MB 6.1 MB/s eta 0:00:01[K     |█████████████████████████       | 1.6 MB 6.1 MB/s eta 0:00:01[K     |█████████████████████████▏      | 1.7 MB 6.1 MB/s eta 0:00:01[K     |█████████████████████████▍      | 1.7 MB 6.1 MB/s eta 0:00:01[K     |█████████████████████████▌      | 1.7 MB 6.1 MB/s eta 0:00:01[K     |█████████████████████████▋      | 1.7 MB 6.1 MB/s eta 0:00:01[K     |█████████████████████████▉      | 1.7 MB 6.1 MB/s eta 0:00:01[K     |██████████████████████████      | 1.7 MB 6.1 MB/s eta 0:00:01[K     |██████████████████████████▏     | 1.7 MB 6.1 MB/s eta 0:00:01[K     |██████████████████████████▎     | 1.7 MB 6.1 MB/s eta 0:00:01[K     |██████████████████████████▍     | 1.7 MB 6.1 MB/s eta 0:00:01[K     |██████████████████████████▋     | 1.8 MB 6.1 MB/s eta 0:00:01[K     |██████████████████████████▊     | 1.8 MB 6.1 MB/s eta 0:00:01[K     |███████████████████████████     | 1.8 MB 6.1 MB/s eta 0:00:01[K     |███████████████████████████     | 1.8 MB 6.1 MB/s eta 0:00:01[K     |███████████████████████████▏    | 1.8 MB 6.1 MB/s eta 0:00:01[K     |███████████████████████████▍    | 1.8 MB 6.1 MB/s eta 0:00:01[K     |███████████████████████████▌    | 1.8 MB 6.1 MB/s eta 0:00:01[K     |███████████████████████████▊    | 1.8 MB 6.1 MB/s eta 0:00:01[K     |███████████████████████████▉    | 1.8 MB 6.1 MB/s eta 0:00:01[K     |████████████████████████████    | 1.8 MB 6.1 MB/s eta 0:00:01[K     |████████████████████████████▏   | 1.9 MB 6.1 MB/s eta 0:00:01[K     |████████████████████████████▎   | 1.9 MB 6.1 MB/s eta 0:00:01[K     |████████████████████████████▌   | 1.9 MB 6.1 MB/s eta 0:00:01[K     |████████████████████████████▋   | 1.9 MB 6.1 MB/s eta 0:00:01[K     |████████████████████████████▊   | 1.9 MB 6.1 MB/s eta 0:00:01[K     |█████████████████████████████   | 1.9 MB 6.1 MB/s eta 0:00:01[K     |█████████████████████████████   | 1.9 MB 6.1 MB/s eta 0:00:01[K     |█████████████████████████████▎  | 1.9 MB 6.1 MB/s eta 0:00:01[K     |█████████████████████████████▍  | 1.9 MB 6.1 MB/s eta 0:00:01[K     |█████████████████████████████▌  | 1.9 MB 6.1 MB/s eta 0:00:01[K     |█████████████████████████████▊  | 2.0 MB 6.1 MB/s eta 0:00:01[K     |█████████████████████████████▉  | 2.0 MB 6.1 MB/s eta 0:00:01[K     |██████████████████████████████  | 2.0 MB 6.1 MB/s eta 0:00:01[K     |██████████████████████████████▏ | 2.0 MB 6.1 MB/s eta 0:00:01[K     |██████████████████████████████▎ | 2.0 MB 6.1 MB/s eta 0:00:01[K     |██████████████████████████████▌ | 2.0 MB 6.1 MB/s eta 0:00:01[K     |██████████████████████████████▋ | 2.0 MB 6.1 MB/s eta 0:00:01[K     |██████████████████████████████▉ | 2.0 MB 6.1 MB/s eta 0:00:01[K     |███████████████████████████████ | 2.0 MB 6.1 MB/s eta 0:00:01[K     |███████████████████████████████ | 2.0 MB 6.1 MB/s eta 0:00:01[K     |███████████████████████████████▎| 2.1 MB 6.1 MB/s eta 0:00:01[K     |███████████████████████████████▍| 2.1 MB 6.1 MB/s eta 0:00:01[K     |███████████████████████████████▋| 2.1 MB 6.1 MB/s eta 0:00:01[K     |███████████████████████████████▊| 2.1 MB 6.1 MB/s eta 0:00:01[K     |███████████████████████████████▉| 2.1 MB 6.1 MB/s eta 0:00:01[K     |████████████████████████████████| 2.1 MB 6.1 MB/s 
[?25hInstalling collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.0.2
    Not uninstalling pip at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'pip'. No files were found to uninstall.
Successfully installed pip-23.3.1
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: direct-redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct-redis) (3.4.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4_engman/m21212121/m21212121_q8_t0.sh
/platform/source/s01/v4_engman/m21212121/m21212121_q8_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4_engman/m21212121/m21212121_q8_t0.sh: line 7: sudo: command not found
/platform/source/s01/v4_engman/m21212121/m21212121_q8_t0.sh: line 10: sudo: command not found
/platform/source/s01/v4_engman/m21212121/m21212121_q8_t0.sh: line 13: sudo: command not found
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: redis in /usr/local/lib/python3.8/dist-packages (3.4.1)
Requirement already satisfied: direct-redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRunning /platform/source/s01/v4_engman/m21212121/m21212121_q9_t0.sh
/platform/source/s01/v4_engman/m21212121/m21212121_q9_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4_engman/m21212121/m21212121_q9_t0.sh: line 7: sudo: command not found
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRequirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRequirement already satisfied: direct-redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct-redis) (3.4.1)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mpython /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engman/m21212121/m21212121_q10_t0.py /platform/output/s01/v4_engman/m21212121/m21212121_q10_t0.csv /platform/expected/s01/q10.csv
^[[A    Score.fail_timeout
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engman/m21212121/m21212121_q11_t0.py /platform/output/s01/v4_engman/m21212121/m21212121_q11_t0.csv /platform/expected/s01/q11.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engman/m21212121/m21212121_q11_t0.py", line 26, in <module>
    nation = pd.read_json(redis_client.get('nation'))
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engman/m21212121/m21212121_q12_t0.py /platform/output/s01/v4_engman/m21212121/m21212121_q12_t0.csv /platform/expected/s01/q12.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engman/m21212121/m21212121_q12_t0.py", line 25, in <module>
    orders_df = pd.read_json(redis_client.get('orders'))
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engman/m21212121/m21212121_q13_t0.py /platform/output/s01/v4_engman/m21212121/m21212121_q13_t0.csv /platform/expected/s01/q13.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engman/m21212121/m21212121_q13_t0.py", line 48, in <module>
    main()
  File "/platform/source/s01/v4_engman/m21212121/m21212121_q13_t0.py", line 34, in main
    redis_orders = get_orders_from_redis(redis_conn)
  File "/platform/source/s01/v4_engman/m21212121/m21212121_q13_t0.py", line 23, in get_orders_from_redis
    orders_df = pd.read_json(orders_df, orient='records')
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engman/m21212121/m21212121_q14_t0.py /platform/output/s01/v4_engman/m21212121/m21212121_q14_t0.csv /platform/expected/s01/q14.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engman/m21212121/m21212121_q14_t0.py", line 25, in <module>
    part_df = pd.read_json(part_raw)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engman/m21212121/m21212121_q15_t0.py /platform/output/s01/v4_engman/m21212121/m21212121_q15_t0.csv /platform/expected/s01/q15.csv
>>> Expected ((1, 5))
               S_ADDRESS              S_NAME          S_PHONE  S_SUPPKEY  TOTAL_REVENUE
0  8mhrffG7D2WJBSQbOGstQ  Supplier#000000677  23-290-639-3315        677   1.614410e+06

>>> Actual ((0, 5))
Empty DataFrame
Columns: [S_ADDRESS, S_NAME, S_PHONE, S_SUPPKEY, TOTAL_REVENUE]
Index: []

Score.fail_wrong_output
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engman/m21212121/m21212121_q16_t0.py /platform/output/s01/v4_engman/m21212121/m21212121_q16_t0.csv /platform/expected/s01/q16.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engman/m21212121/m21212121_q16_t0.py", line 15, in <module>
    part_df = pd.read_json(r.get('part'), orient='records')
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engman/m21212121/m21212121_q17_t0.py /platform/output/s01/v4_engman/m21212121/m21212121_q17_t0.csv /platform/expected/s01/q17.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engman/m21212121/m21212121_q17_t0.py", line 31, in <module>
    part_df = pd.read_json(part_records)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engman/m21212121/m21212121_q18_t0.py /platform/output/s01/v4_engman/m21212121/m21212121_q18_t0.csv /platform/expected/s01/q18.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engman/m21212121/m21212121_q18_t0.py", line 19, in <module>
    orders_df = pd.read_json(r.get('orders'), orient='records')
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engman/m21212121/m21212121_q19_t0.py /platform/output/s01/v4_engman/m21212121/m21212121_q19_t0.csv /platform/expected/s01/q19.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engman/m21212121/m21212121_q19_t0.py", line 51, in <module>
    redis_data = redis_client.get('part')
  File "/platform/source/s01/v4_engman/m21212121/m21212121_q19_t0.py", line 44, in get
    return pd.read_json(record, orient='records')
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 903, in get_handle
    raise TypeError(
TypeError: Expected file path name or file-like object, got <class 'bytes'> type
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engman/m21212121/m21212121_q1_t0.py /platform/output/s01/v4_engman/m21212121/m21212121_q1_t0.csv /platform/expected/s01/q1.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engman/m21212121/m21212121_q1_t0.py", line 57, in <module>
    os.makedirs(os.path.dirname(output_file), exist_ok=True)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: ''
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engman/m21212121/m21212121_q20_t0.py /platform/output/s01/v4_engman/m21212121/m21212121_q20_t0.csv /platform/expected/s01/q20.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engman/m21212121/m21212121_q20_t0.py", line 21, in <module>
    nation = pd.read_json(redis_client.get('nation'), orient='records')
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engman/m21212121/m21212121_q21_t0.py /platform/output/s01/v4_engman/m21212121/m21212121_q21_t0.csv /platform/expected/s01/q21.csv
>>> Expected ((47, 2))
    NUMWAIT              S_NAME
0        16  Supplier#000000445
1        16  Supplier#000000825
2        15  Supplier#000000709
3        15  Supplier#000000762
4        14  Supplier#000000357
5        14  Supplier#000000399
6        14  Supplier#000000496
7        13  Supplier#000000977
8        12  Supplier#000000144
9        12  Supplier#000000188
10       12  Supplier#000000415
11       12  Supplier#000000472
12       12  Supplier#000000633
13       12  Supplier#000000708
14       12  Supplier#000000889
15       11  Supplier#000000380
16       11  Supplier#000000602
17       11  Supplier#000000659
18       11  Supplier#000000821
19       11  Supplier#000000929
20       10  Supplier#000000262
21       10  Supplier#000000460
22       10  Supplier#000000486
23       10  Supplier#000000669
24       10  Supplier#000000718
25       10  Supplier#000000778
26        9  Supplier#000000167
27        9  Supplier#000000578
28        9  Supplier#000000673
29        9  Supplier#000000687
30        8  Supplier#000000074
31        8  Supplier#000000565
32        8  Supplier#000000648
33        8  Supplier#000000918
34        7  Supplier#000000427
35        7  Supplier#000000503
36        7  Supplier#000000610
37        7  Supplier#000000670
38        7  Supplier#000000811
39        6  Supplier#000000114
40        6  Supplier#000000379
41        6  Supplier#000000436
42        6  Supplier#000000500
43        6  Supplier#000000660
44        6  Supplier#000000788
45        6  Supplier#000000846
46        4  Supplier#000000920

>>> Actual ((1000, 2))
     NUMWAIT              S_NAME
0        227  Supplier#000000074
1        217  Supplier#000000876
2        216  Supplier#000000418
3        216  Supplier#000000496
4        216  Supplier#000000692
..       ...                 ...
995      143  Supplier#000000930
996      142  Supplier#000000487
997      142  Supplier#000000995
998      139  Supplier#000000226
999      138  Supplier#000000189

[1000 rows x 2 columns]

Score.fail_wrong_output
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engman/m21212121/m21212121_q22_t0.py /platform/output/s01/v4_engman/m21212121/m21212121_q22_t0.csv /platform/expected/s01/q22.csv
>>> Expected ((4, 3))
   CNTRYCODE  NUMCUST  TOTACCTBAL
0         20       91   666158.10
1         21      101   760953.55
2         22      106   759804.81
3         30       87   646748.02

>>> Actual ((4, 3))
   CNTRYCODE  Number_of_Customers  Total_Account_Balance
0         20                  292             2148310.48
1         21                  271             2069045.28
2         22                  283             2124577.79
3         30                  250             1884286.16

Head row similarity: 0.543046357615894
Score.fail_wrong_output
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engman/m21212121/m21212121_q2_t0.py /platform/output/s01/v4_engman/m21212121/m21212121_q2_t0.csv /platform/expected/s01/q2.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engman/m21212121/m21212121_q2_t0.py", line 17, in <module>
    nation_df = pd.read_json(redis_client.get('nation'))
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engman/m21212121/m21212121_q3_t0.py /platform/output/s01/v4_engman/m21212121/m21212121_q3_t0.csv /platform/expected/s01/q3.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engman/m21212121/m21212121_q3_t0.py", line 22, in <module>
    orders_data = json.loads(orders_str)
  File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not DataFrame
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engman/m21212121/m21212121_q4_t0.py /platform/output/s01/v4_engman/m21212121/m21212121_q4_t0.csv /platform/expected/s01/q4.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engman/m21212121/m21212121_q4_t0.py", line 19, in <module>
    orders_df = pd.DataFrame(eval(r.get('orders')))
TypeError: eval() arg 1 must be a string, bytes or code object
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engman/m21212121/m21212121_q5_t0.py /platform/output/s01/v4_engman/m21212121/m21212121_q5_t0.csv /platform/expected/s01/q5.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engman/m21212121/m21212121_q5_t0.py", line 22, in <module>
    nation_redis = pd.read_json(redis_client.get('nation'))
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engman/m21212121/m21212121_q6_t0.py /platform/output/s01/v4_engman/m21212121/m21212121_q6_t0.csv /platform/expected/s01/q6.csv
Query results written to query_output.csv
>>> Expected ((1, 1))
        REVENUE
0  7.115407e+06

>>> Actual ((0, 1))
Empty DataFrame
Columns: [REVENUE]
Index: []

Score.fail_wrong_output
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engman/m21212121/m21212121_q7_t0.py /platform/output/s01/v4_engman/m21212121/m21212121_q7_t0.csv /platform/expected/s01/q7.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engman/m21212121/m21212121_q7_t0.py", line 22, in <module>
    nation_df = pd.read_json(redis.get('nation'), orient='records')
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engman/m21212121/m21212121_q8_t0.py /platform/output/s01/v4_engman/m21212121/m21212121_q8_t0.csv /platform/expected/s01/q8.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engman/m21212121/m21212121_q8_t0.py", line 17, in <module>
    nation = pd.read_json(redis_client.get('nation'))
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engman/m21212121/m21212121_q9_t0.py /platform/output/s01/v4_engman/m21212121/m21212121_q9_t0.csv /platform/expected/s01/q9.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engman/m21212121/m21212121_q9_t0.py", line 23, in <module>
    nation_df = pd.read_json(nation_str)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
