Using MAPPING_STR=11112222, VERSION_DIR=v4_engoff
Running /platform/source/s01/v4_engoff/m11112222/m11112222_q10_t0.sh
Running /platform/source/s01/v4_engoff/m11112222/m11112222_q11_t0.sh
/platform/source/s01/v4_engoff/m11112222/m11112222_q11_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4_engoff/m11112222/m11112222_q11_t0.sh: line 5: sudo: command not found
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: redis in /usr/local/lib/python3.8/dist-packages (3.4.1)
Requirement already satisfied: direct-redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4_engoff/m11112222/m11112222_q12_t0.sh
/platform/source/s01/v4_engoff/m11112222/m11112222_q12_t0.sh: line 5: sudo: command not found
/platform/source/s01/v4_engoff/m11112222/m11112222_q12_t0.sh: line 6: sudo: command not found
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt install python3.8-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: ['/query_env/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']

/platform/source/s01/v4_engoff/m11112222/m11112222_q12_t0.sh: line 10: query_env/bin/activate: No such file or directory
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
Running /platform/source/s01/v4_engoff/m11112222/m11112222_q13_t0.sh
/platform/source/s01/v4_engoff/m11112222/m11112222_q13_t0.sh: line 3: sudo: command not found
/platform/source/s01/v4_engoff/m11112222/m11112222_q13_t0.sh: line 4: sudo: command not found
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4_engoff/m11112222/m11112222_q14_t0.sh
/platform/source/s01/v4_engoff/m11112222/m11112222_q14_t0.sh: line 5: sudo: command not found
/platform/source/s01/v4_engoff/m11112222/m11112222_q14_t0.sh: line 8: sudo: command not found
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Running /platform/source/s01/v4_engoff/m11112222/m11112222_q15_t0.sh
Running /platform/source/s01/v4_engoff/m11112222/m11112222_q16_t0.sh

0% [Working]
            
Hit:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease

0% [Working]
0% [Waiting for headers]
                        
Get:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease [114 kB]

0% [2 InRelease 4135 B/114 kB 4%]
                                 
0% [Working]
0% [Waiting for headers]
                        
Hit:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease

0% [Waiting for headers]
0% [Waiting for headers]
                        
Get:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease [114 kB]

0% [4 InRelease 2687 B/114 kB 2%]
                                 
0% [Working]
24% [Working]
             
Get:5 http://ports.ubuntu.com/ubuntu-ports focal-security/universe arm64 Packages [1023 kB]

24% [5 Packages 2686 B/1023 kB 0%]
                                  
46% [Working]
46% [5 Packages store 0 B] [Waiting for headers]
                                                
47% [Waiting for headers]
                         
Get:6 http://ports.ubuntu.com/ubuntu-ports focal-security/main arm64 Packages [2408 kB]

48% [6 Packages 49.0 kB/2408 kB 2%]
                                   
99% [Working]
99% [6 Packages store 0 B]
                          
100% [Working]
              
Fetched 3659 kB in 2s (2137 kB/s)

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 60%

Reading package lists... 60%

Reading package lists... 61%

Reading package lists... 61%

Reading package lists... 74%

Reading package lists... 74%

Reading package lists... 75%

Reading package lists... 75%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... Done


Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 60%

Reading package lists... 60%

Reading package lists... 61%

Reading package lists... 61%

Reading package lists... 74%

Reading package lists... 74%

Reading package lists... 75%

Reading package lists... 75%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... Done


Building dependency tree... 0%

Building dependency tree... 0%

Building dependency tree... 50%

Building dependency tree... 50%

Building dependency tree       


Reading state information... 0%

Reading state information... 0%

Reading state information... Done

python3 is already the newest version (3.8.2-0ubuntu2).
python3 set to manually installed.
python3-pip is already the newest version (20.0.2-5ubuntu1.10).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Collecting git+https://github.com/redis/direct_redis.git
  Cloning https://github.com/redis/direct_redis.git to /tmp/pip-req-build-ioyy0ehc
  Running command git clone -q https://github.com/redis/direct_redis.git /tmp/pip-req-build-ioyy0ehc
[31m  ERROR: Error [Errno 2] No such file or directory: 'git' while executing command git clone -q https://github.com/redis/direct_redis.git /tmp/pip-req-build-ioyy0ehc[0m
[31mERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?[0m
Collecting msgpack-python
  Downloading msgpack-python-0.5.6.tar.gz (138 kB)
[?25l
[K     |██▍                             | 10 kB 13.5 MB/s eta 0:00:01
[K     |████▊                           | 20 kB 3.8 MB/s eta 0:00:01
[K     |███████                         | 30 kB 5.5 MB/s eta 0:00:01
[K     |█████████▍                      | 40 kB 5.3 MB/s eta 0:00:01
[K     |███████████▉                    | 51 kB 5.4 MB/s eta 0:00:01
[K     |██████████████▏                 | 61 kB 6.4 MB/s eta 0:00:01
[K     |████████████████▌               | 71 kB 6.1 MB/s eta 0:00:01
[K     |██████████████████▉             | 81 kB 6.1 MB/s eta 0:00:01
[K     |█████████████████████▏          | 92 kB 6.8 MB/s eta 0:00:01
[K     |███████████████████████▋        | 102 kB 6.9 MB/s eta 0:00:01
[K     |██████████████████████████      | 112 kB 6.9 MB/s eta 0:00:01
[K     |████████████████████████████▎   | 122 kB 6.9 MB/s eta 0:00:01
[K     |██████████████████████████████▋ | 133 kB 6.9 MB/s eta 0:00:01
[K     |████████████████████████████████| 138 kB 6.9 MB/s 
[?25hBuilding wheels for collected packages: msgpack-python
  Building wheel for msgpack-python (setup.py) ... [?25l- \ | / - done
[?25h  Created wheel for msgpack-python: filename=msgpack_python-0.5.6-cp38-cp38-linux_aarch64.whl size=446720 sha256=89f23eed464bc34e2e8b30d458792e1d3435dc56de44841f3e6a49736a3c1865
  Stored in directory: /root/.cache/pip/wheels/03/7f/e7/8ec405fe5220fe1401be3dfa943f6e1f10b525f54f68d75e0a
Successfully built msgpack-python
Installing collected packages: msgpack-python
Successfully installed msgpack-python-0.5.6
Running /platform/source/s01/v4_engoff/m11112222/m11112222_q17_t0.sh
/platform/source/s01/v4_engoff/m11112222/m11112222_q17_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4_engoff/m11112222/m11112222_q17_t0.sh: line 7: sudo: command not found
/platform/source/s01/v4_engoff/m11112222/m11112222_q17_t0.sh: line 10: sudo: command not found
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4_engoff/m11112222/m11112222_q18_t0.sh
/platform/source/s01/v4_engoff/m11112222/m11112222_q18_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4_engoff/m11112222/m11112222_q18_t0.sh: line 5: sudo: command not found
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: direct-redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct-redis) (3.4.1)
python3: can't open file 'query_data.py': [Errno 2] No such file or directory
Running /platform/source/s01/v4_engoff/m11112222/m11112222_q19_t0.sh
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt install python3.8-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: ['/venv/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']

/platform/source/s01/v4_engoff/m11112222/m11112222_q19_t0.sh: line 5: venv/bin/activate: No such file or directory
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Collecting redis>=4.0.0
  Using cached redis-5.0.1-py3-none-any.whl (250 kB)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: async-timeout>=4.0.2; python_full_version <= "3.11.2" in /usr/local/lib/python3.8/dist-packages (from redis>=4.0.0) (4.0.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
[31mERROR: direct-redis 0.3.1 has requirement redis==3.4.1, but you'll have redis 5.0.1 which is incompatible.[0m
Installing collected packages: redis
  Attempting uninstall: redis
    Found existing installation: redis 3.4.1
    Uninstalling redis-3.4.1:
      Successfully uninstalled redis-3.4.1
Successfully installed redis-5.0.1
Running /platform/source/s01/v4_engoff/m11112222/m11112222_q1_t0.sh
/platform/source/s01/v4_engoff/m11112222/m11112222_q1_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4_engoff/m11112222/m11112222_q1_t0.sh: line 7: sudo: command not found
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Collecting redis==3.4.1
  Using cached redis-3.4.1-py2.py3-none-any.whl (71 kB)
Installing collected packages: redis
  Attempting uninstall: redis
    Found existing installation: redis 5.0.1
    Uninstalling redis-5.0.1:
      Successfully uninstalled redis-5.0.1
Successfully installed redis-3.4.1
Running /platform/source/s01/v4_engoff/m11112222/m11112222_q20_t0.sh

0% [Working]
            
Hit:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease

0% [Working]
            
Hit:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease

0% [Working]
0% [Waiting for headers]
0% [Waiting for headers]
                        
Hit:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease

                        
0% [Working]
0% [Waiting for headers]
                        
Hit:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease

                        
0% [Working]
20% [Working]
             

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 60%

Reading package lists... 60%

Reading package lists... 61%

Reading package lists... 61%

Reading package lists... 74%

Reading package lists... 74%

Reading package lists... 75%

Reading package lists... 75%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... Done


Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 60%

Reading package lists... 60%

Reading package lists... 61%

Reading package lists... 61%

Reading package lists... 74%

Reading package lists... 74%

Reading package lists... 75%

Reading package lists... 75%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... Done


Building dependency tree... 0%

Building dependency tree... 0%

Building dependency tree... 50%

Building dependency tree... 50%

Building dependency tree       


Reading state information... 0%

Reading state information... 0%

Reading state information... Done

python3 is already the newest version (3.8.2-0ubuntu2).
python3-pip is already the newest version (20.0.2-5ubuntu1.10).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4_engoff/m11112222/m11112222_q21_t0.sh
/platform/source/s01/v4_engoff/m11112222/m11112222_q21_t0.sh: line 5: sudo: command not found
/platform/source/s01/v4_engoff/m11112222/m11112222_q21_t0.sh: line 8: sudo: command not found
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: redis in /usr/local/lib/python3.8/dist-packages (3.4.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4_engoff/m11112222/m11112222_q22_t0.sh
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.8/dist-packages (1.24.4)
Collecting redis-py-cluster
  Downloading redis_py_cluster-2.1.3-py2.py3-none-any.whl (42 kB)
[?25l
[K     |███████▊                        | 10 kB 10.6 MB/s eta 0:00:01
[K     |███████████████▍                | 20 kB 587 kB/s eta 0:00:01
[K     |███████████████████████         | 30 kB 827 kB/s eta 0:00:01
[K     |██████████████████████████████▉ | 40 kB 1.1 MB/s eta 0:00:01
[K     |████████████████████████████████| 42 kB 845 kB/s 
[?25hRequirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: redis<4.0.0,>=3.0.0 in /usr/local/lib/python3.8/dist-packages (from redis-py-cluster) (3.4.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Installing collected packages: redis-py-cluster
Successfully installed redis-py-cluster-2.1.3
Running /platform/source/s01/v4_engoff/m11112222/m11112222_q2_t0.sh
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt install python3.8-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: ['/venv/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']

/platform/source/s01/v4_engoff/m11112222/m11112222_q2_t0.sh: line 6: venv/bin/activate: No such file or directory
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: redis in /usr/local/lib/python3.8/dist-packages (3.4.1)
Requirement already satisfied: direct-redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Running /platform/source/s01/v4_engoff/m11112222/m11112222_q3_t0.sh
/platform/source/s01/v4_engoff/m11112222/m11112222_q3_t0.sh: line 6: sudo: command not found
/platform/source/s01/v4_engoff/m11112222/m11112222_q3_t0.sh: line 7: sudo: command not found
/platform/source/s01/v4_engoff/m11112222/m11112222_q3_t0.sh: line 10: sudo: command not found
Requirement already satisfied: direct-redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct-redis) (3.4.1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4_engoff/m11112222/m11112222_q4_t0.sh
Running /platform/source/s01/v4_engoff/m11112222/m11112222_q5_t0.sh
/platform/source/s01/v4_engoff/m11112222/m11112222_q5_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4_engoff/m11112222/m11112222_q5_t0.sh: line 7: sudo: command not found
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: direct-redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct-redis) (3.4.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4_engoff/m11112222/m11112222_q6_t0.sh
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: redis in /usr/local/lib/python3.8/dist-packages (3.4.1)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4_engoff/m11112222/m11112222_q7_t0.sh
/platform/source/s01/v4_engoff/m11112222/m11112222_q7_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4_engoff/m11112222/m11112222_q7_t0.sh: line 5: sudo: command not found
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4_engoff/m11112222/m11112222_q8_t0.sh
/platform/source/s01/v4_engoff/m11112222/m11112222_q8_t0.sh: line 6: sudo: command not found
/platform/source/s01/v4_engoff/m11112222/m11112222_q8_t0.sh: line 7: sudo: command not found
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: redis in /usr/local/lib/python3.8/dist-packages (3.4.1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4_engoff/m11112222/m11112222_q9_t0.sh
/platform/source/s01/v4_engoff/m11112222/m11112222_q9_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4_engoff/m11112222/m11112222_q9_t0.sh: line 5: sudo: command not found
Collecting pip
  Downloading pip-23.3.1-py3-none-any.whl (2.1 MB)
[?25l
[K     |▏                               | 10 kB 10.6 MB/s eta 0:00:01
[K     |▎                               | 20 kB 3.4 MB/s eta 0:00:01
[K     |▌                               | 30 kB 5.0 MB/s eta 0:00:01
[K     |▋                               | 40 kB 3.8 MB/s eta 0:00:01
[K     |▊                               | 51 kB 4.3 MB/s eta 0:00:01
[K     |█                               | 61 kB 5.2 MB/s eta 0:00:01
[K     |█                               | 71 kB 5.4 MB/s eta 0:00:01
[K     |█▎                              | 81 kB 4.1 MB/s eta 0:00:01
[K     |█▍                              | 92 kB 4.6 MB/s eta 0:00:01
[K     |█▌                              | 102 kB 5.1 MB/s eta 0:00:01
[K     |█▊                              | 112 kB 5.1 MB/s eta 0:00:01
[K     |█▉                              | 122 kB 5.1 MB/s eta 0:00:01
[K     |██                              | 133 kB 5.1 MB/s eta 0:00:01
[K     |██▏                             | 143 kB 5.1 MB/s eta 0:00:01
[K     |██▎                             | 153 kB 5.1 MB/s eta 0:00:01
[K     |██▌                             | 163 kB 5.1 MB/s eta 0:00:01
[K     |██▋                             | 174 kB 5.1 MB/s eta 0:00:01
[K     |██▉                             | 184 kB 5.1 MB/s eta 0:00:01
[K     |███                             | 194 kB 5.1 MB/s eta 0:00:01
[K     |███                             | 204 kB 5.1 MB/s eta 0:00:01
[K     |███▎                            | 215 kB 5.1 MB/s eta 0:00:01
[K     |███▍                            | 225 kB 5.1 MB/s eta 0:00:01
[K     |███▋                            | 235 kB 5.1 MB/s eta 0:00:01
[K     |███▊                            | 245 kB 5.1 MB/s eta 0:00:01
[K     |███▉                            | 256 kB 5.1 MB/s eta 0:00:01
[K     |████                            | 266 kB 5.1 MB/s eta 0:00:01
[K     |████▏                           | 276 kB 5.1 MB/s eta 0:00:01
[K     |████▍                           | 286 kB 5.1 MB/s eta 0:00:01
[K     |████▌                           | 296 kB 5.1 MB/s eta 0:00:01
[K     |████▋                           | 307 kB 5.1 MB/s eta 0:00:01
[K     |████▉                           | 317 kB 5.1 MB/s eta 0:00:01
[K     |█████                           | 327 kB 5.1 MB/s eta 0:00:01
[K     |█████▏                          | 337 kB 5.1 MB/s eta 0:00:01
[K     |█████▎                          | 348 kB 5.1 MB/s eta 0:00:01
[K     |█████▍                          | 358 kB 5.1 MB/s eta 0:00:01
[K     |█████▋                          | 368 kB 5.1 MB/s eta 0:00:01
[K     |█████▊                          | 378 kB 5.1 MB/s eta 0:00:01
[K     |██████                          | 389 kB 5.1 MB/s eta 0:00:01
[K     |██████                          | 399 kB 5.1 MB/s eta 0:00:01
[K     |██████▏                         | 409 kB 5.1 MB/s eta 0:00:01
[K     |██████▍                         | 419 kB 5.1 MB/s eta 0:00:01
[K     |██████▌                         | 430 kB 5.1 MB/s eta 0:00:01
[K     |██████▊                         | 440 kB 5.1 MB/s eta 0:00:01
[K     |██████▉                         | 450 kB 5.1 MB/s eta 0:00:01
[K     |███████                         | 460 kB 5.1 MB/s eta 0:00:01
[K     |███████▏                        | 471 kB 5.1 MB/s eta 0:00:01
[K     |███████▎                        | 481 kB 5.1 MB/s eta 0:00:01
[K     |███████▌                        | 491 kB 5.1 MB/s eta 0:00:01
[K     |███████▋                        | 501 kB 5.1 MB/s eta 0:00:01
[K     |███████▊                        | 512 kB 5.1 MB/s eta 0:00:01
[K     |████████                        | 522 kB 5.1 MB/s eta 0:00:01
[K     |████████                        | 532 kB 5.1 MB/s eta 0:00:01
[K     |████████▎                       | 542 kB 5.1 MB/s eta 0:00:01
[K     |████████▍                       | 552 kB 5.1 MB/s eta 0:00:01
[K     |████████▌                       | 563 kB 5.1 MB/s eta 0:00:01
[K     |████████▊                       | 573 kB 5.1 MB/s eta 0:00:01
[K     |████████▉                       | 583 kB 5.1 MB/s eta 0:00:01
[K     |█████████                       | 593 kB 5.1 MB/s eta 0:00:01
[K     |█████████▏                      | 604 kB 5.1 MB/s eta 0:00:01
[K     |█████████▎                      | 614 kB 5.1 MB/s eta 0:00:01
[K     |█████████▌                      | 624 kB 5.1 MB/s eta 0:00:01
[K     |█████████▋                      | 634 kB 5.1 MB/s eta 0:00:01
[K     |█████████▉                      | 645 kB 5.1 MB/s eta 0:00:01
[K     |██████████                      | 655 kB 5.1 MB/s eta 0:00:01
[K     |██████████                      | 665 kB 5.1 MB/s eta 0:00:01
[K     |██████████▎                     | 675 kB 5.1 MB/s eta 0:00:01
[K     |██████████▍                     | 686 kB 5.1 MB/s eta 0:00:01
[K     |██████████▋                     | 696 kB 5.1 MB/s eta 0:00:01
[K     |██████████▊                     | 706 kB 5.1 MB/s eta 0:00:01
[K     |██████████▉                     | 716 kB 5.1 MB/s eta 0:00:01
[K     |███████████                     | 727 kB 5.1 MB/s eta 0:00:01
[K     |███████████▏                    | 737 kB 5.1 MB/s eta 0:00:01
[K     |███████████▍                    | 747 kB 5.1 MB/s eta 0:00:01
[K     |███████████▌                    | 757 kB 5.1 MB/s eta 0:00:01
[K     |███████████▋                    | 768 kB 5.1 MB/s eta 0:00:01
[K     |███████████▉                    | 778 kB 5.1 MB/s eta 0:00:01
[K     |████████████                    | 788 kB 5.1 MB/s eta 0:00:01
[K     |████████████▏                   | 798 kB 5.1 MB/s eta 0:00:01
[K     |████████████▎                   | 808 kB 5.1 MB/s eta 0:00:01
[K     |████████████▍                   | 819 kB 5.1 MB/s eta 0:00:01
[K     |████████████▋                   | 829 kB 5.1 MB/s eta 0:00:01
[K     |████████████▊                   | 839 kB 5.1 MB/s eta 0:00:01
[K     |█████████████                   | 849 kB 5.1 MB/s eta 0:00:01
[K     |█████████████                   | 860 kB 5.1 MB/s eta 0:00:01
[K     |█████████████▏                  | 870 kB 5.1 MB/s eta 0:00:01
[K     |█████████████▍                  | 880 kB 5.1 MB/s eta 0:00:01
[K     |█████████████▌                  | 890 kB 5.1 MB/s eta 0:00:01
[K     |█████████████▊                  | 901 kB 5.1 MB/s eta 0:00:01
[K     |█████████████▉                  | 911 kB 5.1 MB/s eta 0:00:01
[K     |██████████████                  | 921 kB 5.1 MB/s eta 0:00:01
[K     |██████████████▏                 | 931 kB 5.1 MB/s eta 0:00:01
[K     |██████████████▎                 | 942 kB 5.1 MB/s eta 0:00:01
[K     |██████████████▌                 | 952 kB 5.1 MB/s eta 0:00:01
[K     |██████████████▋                 | 962 kB 5.1 MB/s eta 0:00:01
[K     |██████████████▊                 | 972 kB 5.1 MB/s eta 0:00:01
[K     |███████████████                 | 983 kB 5.1 MB/s eta 0:00:01
[K     |███████████████                 | 993 kB 5.1 MB/s eta 0:00:01
[K     |███████████████▎                | 1.0 MB 5.1 MB/s eta 0:00:01
[K     |███████████████▍                | 1.0 MB 5.1 MB/s eta 0:00:01
[K     |███████████████▌                | 1.0 MB 5.1 MB/s eta 0:00:01
[K     |███████████████▊                | 1.0 MB 5.1 MB/s eta 0:00:01
[K     |███████████████▉                | 1.0 MB 5.1 MB/s eta 0:00:01
[K     |████████████████                | 1.1 MB 5.1 MB/s eta 0:00:01
[K     |████████████████▏               | 1.1 MB 5.1 MB/s eta 0:00:01
[K     |████████████████▎               | 1.1 MB 5.1 MB/s eta 0:00:01
[K     |████████████████▌               | 1.1 MB 5.1 MB/s eta 0:00:01
[K     |████████████████▋               | 1.1 MB 5.1 MB/s eta 0:00:01
[K     |████████████████▉               | 1.1 MB 5.1 MB/s eta 0:00:01
[K     |█████████████████               | 1.1 MB 5.1 MB/s eta 0:00:01
[K     |█████████████████               | 1.1 MB 5.1 MB/s eta 0:00:01
[K     |█████████████████▎              | 1.1 MB 5.1 MB/s eta 0:00:01
[K     |█████████████████▍              | 1.1 MB 5.1 MB/s eta 0:00:01
[K     |█████████████████▋              | 1.2 MB 5.1 MB/s eta 0:00:01
[K     |█████████████████▊              | 1.2 MB 5.1 MB/s eta 0:00:01
[K     |█████████████████▉              | 1.2 MB 5.1 MB/s eta 0:00:01
[K     |██████████████████              | 1.2 MB 5.1 MB/s eta 0:00:01
[K     |██████████████████▏             | 1.2 MB 5.1 MB/s eta 0:00:01
[K     |██████████████████▍             | 1.2 MB 5.1 MB/s eta 0:00:01
[K     |██████████████████▌             | 1.2 MB 5.1 MB/s eta 0:00:01
[K     |██████████████████▋             | 1.2 MB 5.1 MB/s eta 0:00:01
[K     |██████████████████▉             | 1.2 MB 5.1 MB/s eta 0:00:01
[K     |███████████████████             | 1.2 MB 5.1 MB/s eta 0:00:01
[K     |███████████████████▏            | 1.3 MB 5.1 MB/s eta 0:00:01
[K     |███████████████████▎            | 1.3 MB 5.1 MB/s eta 0:00:01
[K     |███████████████████▍            | 1.3 MB 5.1 MB/s eta 0:00:01
[K     |███████████████████▋            | 1.3 MB 5.1 MB/s eta 0:00:01
[K     |███████████████████▊            | 1.3 MB 5.1 MB/s eta 0:00:01
[K     |████████████████████            | 1.3 MB 5.1 MB/s eta 0:00:01
[K     |████████████████████            | 1.3 MB 5.1 MB/s eta 0:00:01
[K     |████████████████████▏           | 1.3 MB 5.1 MB/s eta 0:00:01
[K     |████████████████████▍           | 1.3 MB 5.1 MB/s eta 0:00:01
[K     |████████████████████▌           | 1.4 MB 5.1 MB/s eta 0:00:01
[K     |████████████████████▊           | 1.4 MB 5.1 MB/s eta 0:00:01
[K     |████████████████████▉           | 1.4 MB 5.1 MB/s eta 0:00:01
[K     |█████████████████████           | 1.4 MB 5.1 MB/s eta 0:00:01
[K     |█████████████████████▏          | 1.4 MB 5.1 MB/s eta 0:00:01
[K     |█████████████████████▎          | 1.4 MB 5.1 MB/s eta 0:00:01
[K     |█████████████████████▌          | 1.4 MB 5.1 MB/s eta 0:00:01
[K     |█████████████████████▋          | 1.4 MB 5.1 MB/s eta 0:00:01
[K     |█████████████████████▊          | 1.4 MB 5.1 MB/s eta 0:00:01
[K     |██████████████████████          | 1.4 MB 5.1 MB/s eta 0:00:01
[K     |██████████████████████          | 1.5 MB 5.1 MB/s eta 0:00:01
[K     |██████████████████████▎         | 1.5 MB 5.1 MB/s eta 0:00:01
[K     |██████████████████████▍         | 1.5 MB 5.1 MB/s eta 0:00:01
[K     |██████████████████████▌         | 1.5 MB 5.1 MB/s eta 0:00:01
[K     |██████████████████████▊         | 1.5 MB 5.1 MB/s eta 0:00:01
[K     |██████████████████████▉         | 1.5 MB 5.1 MB/s eta 0:00:01
[K     |███████████████████████         | 1.5 MB 5.1 MB/s eta 0:00:01
[K     |███████████████████████▏        | 1.5 MB 5.1 MB/s eta 0:00:01
[K     |███████████████████████▎        | 1.5 MB 5.1 MB/s eta 0:00:01
[K     |███████████████████████▌        | 1.5 MB 5.1 MB/s eta 0:00:01
[K     |███████████████████████▋        | 1.6 MB 5.1 MB/s eta 0:00:01
[K     |███████████████████████▉        | 1.6 MB 5.1 MB/s eta 0:00:01
[K     |████████████████████████        | 1.6 MB 5.1 MB/s eta 0:00:01
[K     |████████████████████████        | 1.6 MB 5.1 MB/s eta 0:00:01
[K     |████████████████████████▎       | 1.6 MB 5.1 MB/s eta 0:00:01
[K     |████████████████████████▍       | 1.6 MB 5.1 MB/s eta 0:00:01
[K     |████████████████████████▋       | 1.6 MB 5.1 MB/s eta 0:00:01
[K     |████████████████████████▊       | 1.6 MB 5.1 MB/s eta 0:00:01
[K     |████████████████████████▉       | 1.6 MB 5.1 MB/s eta 0:00:01
[K     |█████████████████████████       | 1.6 MB 5.1 MB/s eta 0:00:01
[K     |█████████████████████████▏      | 1.7 MB 5.1 MB/s eta 0:00:01
[K     |█████████████████████████▍      | 1.7 MB 5.1 MB/s eta 0:00:01
[K     |█████████████████████████▌      | 1.7 MB 5.1 MB/s eta 0:00:01
[K     |█████████████████████████▋      | 1.7 MB 5.1 MB/s eta 0:00:01
[K     |█████████████████████████▉      | 1.7 MB 5.1 MB/s eta 0:00:01
[K     |██████████████████████████      | 1.7 MB 5.1 MB/s eta 0:00:01
[K     |██████████████████████████▏     | 1.7 MB 5.1 MB/s eta 0:00:01
[K     |██████████████████████████▎     | 1.7 MB 5.1 MB/s eta 0:00:01
[K     |██████████████████████████▍     | 1.7 MB 5.1 MB/s eta 0:00:01
[K     |██████████████████████████▋     | 1.8 MB 5.1 MB/s eta 0:00:01
[K     |██████████████████████████▊     | 1.8 MB 5.1 MB/s eta 0:00:01
[K     |███████████████████████████     | 1.8 MB 5.1 MB/s eta 0:00:01
[K     |███████████████████████████     | 1.8 MB 5.1 MB/s eta 0:00:01
[K     |███████████████████████████▏    | 1.8 MB 5.1 MB/s eta 0:00:01
[K     |███████████████████████████▍    | 1.8 MB 5.1 MB/s eta 0:00:01
[K     |███████████████████████████▌    | 1.8 MB 5.1 MB/s eta 0:00:01
[K     |███████████████████████████▊    | 1.8 MB 5.1 MB/s eta 0:00:01
[K     |███████████████████████████▉    | 1.8 MB 5.1 MB/s eta 0:00:01
[K     |████████████████████████████    | 1.8 MB 5.1 MB/s eta 0:00:01
[K     |████████████████████████████▏   | 1.9 MB 5.1 MB/s eta 0:00:01
[K     |████████████████████████████▎   | 1.9 MB 5.1 MB/s eta 0:00:01
[K     |████████████████████████████▌   | 1.9 MB 5.1 MB/s eta 0:00:01
[K     |████████████████████████████▋   | 1.9 MB 5.1 MB/s eta 0:00:01
[K     |████████████████████████████▊   | 1.9 MB 5.1 MB/s eta 0:00:01
[K     |█████████████████████████████   | 1.9 MB 5.1 MB/s eta 0:00:01
[K     |█████████████████████████████   | 1.9 MB 5.1 MB/s eta 0:00:01
[K     |█████████████████████████████▎  | 1.9 MB 5.1 MB/s eta 0:00:01
[K     |█████████████████████████████▍  | 1.9 MB 5.1 MB/s eta 0:00:01
[K     |█████████████████████████████▌  | 1.9 MB 5.1 MB/s eta 0:00:01
[K     |█████████████████████████████▊  | 2.0 MB 5.1 MB/s eta 0:00:01
[K     |█████████████████████████████▉  | 2.0 MB 5.1 MB/s eta 0:00:01
[K     |██████████████████████████████  | 2.0 MB 5.1 MB/s eta 0:00:01
[K     |██████████████████████████████▏ | 2.0 MB 5.1 MB/s eta 0:00:01
[K     |██████████████████████████████▎ | 2.0 MB 5.1 MB/s eta 0:00:01
[K     |██████████████████████████████▌ | 2.0 MB 5.1 MB/s eta 0:00:01
[K     |██████████████████████████████▋ | 2.0 MB 5.1 MB/s eta 0:00:01
[K     |██████████████████████████████▉ | 2.0 MB 5.1 MB/s eta 0:00:01
[K     |███████████████████████████████ | 2.0 MB 5.1 MB/s eta 0:00:01
[K     |███████████████████████████████ | 2.0 MB 5.1 MB/s eta 0:00:01
[K     |███████████████████████████████▎| 2.1 MB 5.1 MB/s eta 0:00:01
[K     |███████████████████████████████▍| 2.1 MB 5.1 MB/s eta 0:00:01
[K     |███████████████████████████████▋| 2.1 MB 5.1 MB/s eta 0:00:01
[K     |███████████████████████████████▊| 2.1 MB 5.1 MB/s eta 0:00:01
[K     |███████████████████████████████▉| 2.1 MB 5.1 MB/s eta 0:00:01
[K     |████████████████████████████████| 2.1 MB 5.1 MB/s 
[?25hCollecting setuptools
  Using cached setuptools-69.0.2-py3-none-any.whl (819 kB)
Collecting wheel
  Using cached wheel-0.42.0-py3-none-any.whl (65 kB)
Installing collected packages: pip, setuptools, wheel
  Attempting uninstall: pip
    Found existing installation: pip 20.0.2
    Not uninstalling pip at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'pip'. No files were found to uninstall.
  Attempting uninstall: setuptools
    Found existing installation: setuptools 45.2.0
    Not uninstalling setuptools at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'setuptools'. No files were found to uninstall.
  Attempting uninstall: wheel
    Found existing installation: wheel 0.34.2
    Not uninstalling wheel at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'wheel'. No files were found to uninstall.
Successfully installed pip-23.3.1 setuptools-69.0.2 wheel-0.42.0
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: redis in /usr/local/lib/python3.8/dist-packages (3.4.1)
Requirement already satisfied: direct-redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mpython /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m11112222/m11112222_q10_t0.py /platform/output/s01/v4_engoff/m11112222/m11112222_q10_t0.csv /platform/expected/s01/q10.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engoff/m11112222/m11112222_q10_t0.py", line 25, in <module>
    customer_df = get_df_from_redis('customer')
  File "/platform/source/s01/v4_engoff/m11112222/m11112222_q10_t0.py", line 20, in get_df_from_redis
    if data:
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/generic.py", line 1466, in __nonzero__
    raise ValueError(
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m11112222/m11112222_q11_t0.py /platform/output/s01/v4_engoff/m11112222/m11112222_q11_t0.csv /platform/expected/s01/q11.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engoff/m11112222/m11112222_q11_t0.py", line 4, in <module>
    import redis.clients.jedis.exceptions
ModuleNotFoundError: No module named 'redis.clients'
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m11112222/m11112222_q12_t0.py /platform/output/s01/v4_engoff/m11112222/m11112222_q12_t0.csv /platform/expected/s01/q12.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engoff/m11112222/m11112222_q12_t0.py", line 8, in <module>
    orders_df = pd.read_json(redis_client.get('orders'))
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m11112222/m11112222_q13_t0.py /platform/output/s01/v4_engoff/m11112222/m11112222_q13_t0.csv /platform/expected/s01/q13.csv
Error loading data from Redis: argument of type 'method' is not iterable
Score.fail_missing_output
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m11112222/m11112222_q14_t0.py /platform/output/s01/v4_engoff/m11112222/m11112222_q14_t0.csv /platform/expected/s01/q14.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engoff/m11112222/m11112222_q14_t0.py", line 21, in <module>
    if lineitem_df:
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/generic.py", line 1466, in __nonzero__
    raise ValueError(
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m11112222/m11112222_q15_t0.py /platform/output/s01/v4_engoff/m11112222/m11112222_q15_t0.csv /platform/expected/s01/q15.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engoff/m11112222/m11112222_q15_t0.py", line 26, in <module>
    lineitem_df = read_from_redis(host='redis', port=6379, db_name=0, table_name='lineitem')
  File "/platform/source/s01/v4_engoff/m11112222/m11112222_q15_t0.py", line 17, in read_from_redis
    df = pd.read_json(data)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m11112222/m11112222_q16_t0.py /platform/output/s01/v4_engoff/m11112222/m11112222_q16_t0.csv /platform/expected/s01/q16.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engoff/m11112222/m11112222_q16_t0.py", line 30, in <module>
    partsupp = pd.read_msgpack(partsupp_data)
AttributeError: module 'pandas' has no attribute 'read_msgpack'
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m11112222/m11112222_q17_t0.py /platform/output/s01/v4_engoff/m11112222/m11112222_q17_t0.csv /platform/expected/s01/q17.csv
/platform/source/s01/v4_engoff/m11112222/m11112222_q17_t0.py:31: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  small_quantity_df['L_LOST_REVENUE'] = small_quantity_df['L_EXTENDEDPRICE']
>>> Expected ((1, 1))
     AVG_YEARLY
0  31865.742857

>>> Actual ((1, 1))
   AverageYearlyLostRevenue
0                  36006.55

Head row similarity: 0.2558139534883721
Score.fail_wrong_output
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m11112222/m11112222_q18_t0.py /platform/output/s01/v4_engoff/m11112222/m11112222_q18_t0.csv /platform/expected/s01/q18.csv
>>> Expected ((5, 6))
   C_CUSTKEY              C_NAME O_ORDERDATE  O_ORDERKEY  O_TOTALPRICE  SUM(L_QUANTITY)
0       1639  Customer#000001639  1994-04-12      502886     456423.88              312
1       6655  Customer#000006655  1995-10-21       29158     452805.02              305
2      14110  Customer#000014110  1995-09-24      565574     425099.85              301
3       1775  Customer#000001775  1997-04-09        6882     408368.10              303
4      11459  Customer#000011459  1993-05-19      551136     386812.74              308

>>> Actual ((5, 6))
   C_CUSTKEY              C_NAME  L_QUANTITY O_ORDERDATE  O_ORDERKEY  O_TOTALPRICE
0       1639  Customer#000001639         312  1994-04-12      502886     456423.88
1       1775  Customer#000001775         303  1997-04-09        6882     408368.10
2       6655  Customer#000006655         305  1995-10-21       29158     452805.02
3      11459  Customer#000011459         308  1993-05-19      551136     386812.74
4      14110  Customer#000014110         301  1995-09-24      565574     425099.85

Head row similarity: 0.419921875
Score.success_approx_manual
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m11112222/m11112222_q19_t0.py /platform/output/s01/v4_engoff/m11112222/m11112222_q19_t0.csv /platform/expected/s01/q19.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engoff/m11112222/m11112222_q19_t0.py", line 34, in <module>
    lineitem_df = pd.DataFrame(eval(redis_client.get('lineitem')))
TypeError: eval() arg 1 must be a string, bytes or code object
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m11112222/m11112222_q1_t0.py /platform/output/s01/v4_engoff/m11112222/m11112222_q1_t0.csv /platform/expected/s01/q1.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engoff/m11112222/m11112222_q1_t0.py", line 13, in <module>
    df_lineitem = pd.read_json(lineitem_data)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m11112222/m11112222_q20_t0.py /platform/output/s01/v4_engoff/m11112222/m11112222_q20_t0.csv /platform/expected/s01/q20.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engoff/m11112222/m11112222_q20_t0.py", line 25, in <module>
    partsupp_df = pd.read_json(redis_client.get('partsupp'), orient='records')
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m11112222/m11112222_q21_t0.py /platform/output/s01/v4_engoff/m11112222/m11112222_q21_t0.csv /platform/expected/s01/q21.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engoff/m11112222/m11112222_q21_t0.py", line 28, in <module>
    orders_json = r.get('orders')
  File "/usr/local/lib/python3.8/dist-packages/redis/client.py", line 1579, in get
    return self.execute_command('GET', name)
  File "/usr/local/lib/python3.8/dist-packages/redis/client.py", line 878, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/usr/local/lib/python3.8/dist-packages/redis/client.py", line 892, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python3.8/dist-packages/redis/connection.py", line 734, in read_response
    response = self._parser.read_response()
  File "/usr/local/lib/python3.8/dist-packages/redis/connection.py", line 358, in read_response
    response = self.encoder.decode(response)
  File "/usr/local/lib/python3.8/dist-packages/redis/connection.py", line 129, in decode
    value = value.decode(self.encoding, self.encoding_errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m11112222/m11112222_q22_t0.py /platform/output/s01/v4_engoff/m11112222/m11112222_q22_t0.csv /platform/expected/s01/q22.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engoff/m11112222/m11112222_q22_t0.py", line 50, in <module>
    main()
  File "/platform/source/s01/v4_engoff/m11112222/m11112222_q22_t0.py", line 40, in main
    customers = get_data_from_redis('customer')
  File "/platform/source/s01/v4_engoff/m11112222/m11112222_q22_t0.py", line 9, in get_data_from_redis
    df = pd.read_json(table_data)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m11112222/m11112222_q2_t0.py /platform/output/s01/v4_engoff/m11112222/m11112222_q2_t0.csv /platform/expected/s01/q2.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engoff/m11112222/m11112222_q2_t0.py", line 32, in <module>
    partsupp_df = pd.read_json(partsupp_df_raw)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m11112222/m11112222_q3_t0.py /platform/output/s01/v4_engoff/m11112222/m11112222_q3_t0.csv /platform/expected/s01/q3.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engoff/m11112222/m11112222_q3_t0.py", line 44, in <module>
    main()
  File "/platform/source/s01/v4_engoff/m11112222/m11112222_q3_t0.py", line 11, in main
    customer_df = pd.read_json(redis_conn.get('customer'))
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m11112222/m11112222_q4_t0.py /platform/output/s01/v4_engoff/m11112222/m11112222_q4_t0.csv /platform/expected/s01/q4.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engoff/m11112222/m11112222_q4_t0.py", line 9, in <module>
    orders_df = pd.read_json(connection.get('orders'))
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m11112222/m11112222_q5_t0.py /platform/output/s01/v4_engoff/m11112222/m11112222_q5_t0.csv /platform/expected/s01/q5.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engoff/m11112222/m11112222_q5_t0.py", line 32, in <module>
    customer_df = pd.read_msgpack(redis_client.get('customer'))
AttributeError: module 'pandas' has no attribute 'read_msgpack'
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m11112222/m11112222_q6_t0.py /platform/output/s01/v4_engoff/m11112222/m11112222_q6_t0.csv /platform/expected/s01/q6.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engoff/m11112222/m11112222_q6_t0.py", line 13, in <module>
    lineitem_df = pd.read_json(lineitem_data)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m11112222/m11112222_q7_t0.py /platform/output/s01/v4_engoff/m11112222/m11112222_q7_t0.csv /platform/expected/s01/q7.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engoff/m11112222/m11112222_q7_t0.py", line 16, in <module>
    customer_df = pd.read_json(redis_client.get('customer'))
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m11112222/m11112222_q8_t0.py /platform/output/s01/v4_engoff/m11112222/m11112222_q8_t0.csv /platform/expected/s01/q8.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engoff/m11112222/m11112222_q8_t0.py", line 20, in <module>
    customer_df = pd.read_json(r.get('customer'))
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m11112222/m11112222_q9_t0.py /platform/output/s01/v4_engoff/m11112222/m11112222_q9_t0.csv /platform/expected/s01/q9.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engoff/m11112222/m11112222_q9_t0.py", line 17, in <module>
    partsupp_df = pd.read_json(redis_client.get('partsupp'), orient='records')
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
