Using MAPPING_STR=10210210, VERSION_DIR=v4_engoff
Running /platform/source/s01/v4_engoff/m10210210/m10210210_q10_t0.sh
/platform/source/s01/v4_engoff/m10210210/m10210210_q10_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4_engoff/m10210210/m10210210_q10_t0.sh: line 7: sudo: command not found
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: redis in /usr/local/lib/python3.8/dist-packages (3.4.1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
Running /platform/source/s01/v4_engoff/m10210210/m10210210_q11_t0.sh
/platform/source/s01/v4_engoff/m10210210/m10210210_q11_t0.sh: line 5: sudo: command not found
Running /platform/source/s01/v4_engoff/m10210210/m10210210_q12_t0.sh
Running /platform/source/s01/v4_engoff/m10210210/m10210210_q13_t0.sh
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Collecting git+https://github.com/storyscript/direct_redis.git
  Cloning https://github.com/storyscript/direct_redis.git to /tmp/pip-req-build-ham8tj97
  Running command git clone -q https://github.com/storyscript/direct_redis.git /tmp/pip-req-build-ham8tj97
[31m  ERROR: Error [Errno 2] No such file or directory: 'git' while executing command git clone -q https://github.com/storyscript/direct_redis.git /tmp/pip-req-build-ham8tj97[0m
[31mERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?[0m
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4_engoff/m10210210/m10210210_q14_t0.sh

0% [Working]
            
Hit:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease

0% [Working]
0% [Waiting for headers]
                        
Get:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease [114 kB]

0% [2 InRelease 8479 B/114 kB 7%]
                                 
0% [Working]
0% [Waiting for headers]
                        
Hit:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease

                        
0% [Working]
0% [Waiting for headers]
                        
Hit:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease

                        
0% [Working]
100% [Working]
              
Fetched 114 kB in 1s (137 kB/s)

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 60%

Reading package lists... 60%

Reading package lists... 61%

Reading package lists... 61%

Reading package lists... 74%

Reading package lists... 74%

Reading package lists... 75%

Reading package lists... 75%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... Done


Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 60%

Reading package lists... 60%

Reading package lists... 61%

Reading package lists... 61%

Reading package lists... 74%

Reading package lists... 74%

Reading package lists... 75%

Reading package lists... 75%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... Done


Building dependency tree... 0%

Building dependency tree... 0%

Building dependency tree... 50%

Building dependency tree... 50%

Building dependency tree       


Reading state information... 0%

Reading state information... 0%

Reading state information... Done

python3-pip is already the newest version (20.0.2-5ubuntu1.10).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: redis in /usr/local/lib/python3.8/dist-packages (3.4.1)
Requirement already satisfied: direct-redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4_engoff/m10210210/m10210210_q15_t0.sh
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Running /platform/source/s01/v4_engoff/m10210210/m10210210_q16_t0.sh

0% [Working]
            
Hit:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease

0% [Working]
0% [Waiting for headers]
                        
Hit:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease

                        
0% [Working]
0% [Waiting for headers]
                        
Hit:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease

                        
0% [Working]
0% [Waiting for headers]
                        
Hit:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease

                        
0% [Working]
20% [Working]
             

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 60%

Reading package lists... 60%

Reading package lists... 61%

Reading package lists... 61%

Reading package lists... 74%

Reading package lists... 74%

Reading package lists... 75%

Reading package lists... 75%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... Done


Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 60%

Reading package lists... 60%

Reading package lists... 61%

Reading package lists... 61%

Reading package lists... 74%

Reading package lists... 74%

Reading package lists... 75%

Reading package lists... 75%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... Done


Building dependency tree... 0%

Building dependency tree... 0%

Building dependency tree... 50%

Building dependency tree... 50%

Building dependency tree       


Reading state information... 0%

Reading state information... 0%

Reading state information... Done

python3 is already the newest version (3.8.2-0ubuntu2).
python3 set to manually installed.
python3-pip is already the newest version (20.0.2-5ubuntu1.10).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: direct-redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct-redis) (3.4.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4_engoff/m10210210/m10210210_q17_t0.sh
/platform/source/s01/v4_engoff/m10210210/m10210210_q17_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4_engoff/m10210210/m10210210_q17_t0.sh: line 7: sudo: command not found
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4_engoff/m10210210/m10210210_q18_t0.sh
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4_engoff/m10210210/m10210210_q19_t0.sh
/platform/source/s01/v4_engoff/m10210210/m10210210_q19_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4_engoff/m10210210/m10210210_q19_t0.sh: line 7: sudo: command not found
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Collecting git+https://github.com/danmcinerney/direct-redis.git
  Cloning https://github.com/danmcinerney/direct-redis.git to /tmp/pip-req-build-72rkgii1
  Running command git clone -q https://github.com/danmcinerney/direct-redis.git /tmp/pip-req-build-72rkgii1
[31m  ERROR: Error [Errno 2] No such file or directory: 'git' while executing command git clone -q https://github.com/danmcinerney/direct-redis.git /tmp/pip-req-build-72rkgii1[0m
[31mERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?[0m
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4_engoff/m10210210/m10210210_q1_t0.sh
/platform/source/s01/v4_engoff/m10210210/m10210210_q1_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4_engoff/m10210210/m10210210_q1_t0.sh: line 7: sudo: command not found
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Running /platform/source/s01/v4_engoff/m10210210/m10210210_q20_t0.sh
/platform/source/s01/v4_engoff/m10210210/m10210210_q20_t0.sh: line 5: sudo: command not found
/platform/source/s01/v4_engoff/m10210210/m10210210_q20_t0.sh: line 8: sudo: command not found
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: direct-redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct-redis) (3.4.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4_engoff/m10210210/m10210210_q21_t0.sh
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Running /platform/source/s01/v4_engoff/m10210210/m10210210_q22_t0.sh
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Collecting jsonpickle
  Downloading jsonpickle-3.0.2-py3-none-any.whl (40 kB)
[?25l
[K     |████████                        | 10 kB 41.4 MB/s eta 0:00:01
[K     |████████████████                | 20 kB 17.4 MB/s eta 0:00:01
[K     |████████████████████████▏       | 30 kB 8.5 MB/s eta 0:00:01
[K     |████████████████████████████████| 40 kB 5.6 MB/s 
[?25hInstalling collected packages: jsonpickle
Successfully installed jsonpickle-3.0.2
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
Running /platform/source/s01/v4_engoff/m10210210/m10210210_q2_t0.sh
Running /platform/source/s01/v4_engoff/m10210210/m10210210_q3_t0.sh

0% [Working]
            
Hit:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease

0% [Working]
0% [Waiting for headers]
                        
Hit:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease

0% [Waiting for headers]
0% [Waiting for headers]
                        
Hit:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease

                        
0% [Working]
0% [Waiting for headers]
                        
Hit:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease

                        
0% [Working]
20% [Working]
             

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 60%

Reading package lists... 60%

Reading package lists... 61%

Reading package lists... 61%

Reading package lists... 74%

Reading package lists... 74%

Reading package lists... 75%

Reading package lists... 75%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... Done


Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 60%

Reading package lists... 60%

Reading package lists... 61%

Reading package lists... 61%

Reading package lists... 74%

Reading package lists... 74%

Reading package lists... 75%

Reading package lists... 75%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... Done


Building dependency tree... 0%

Building dependency tree... 0%

Building dependency tree... 50%

Building dependency tree... 50%

Building dependency tree       


Reading state information... 0%

Reading state information... 0%

Reading state information... Done

python3-pip is already the newest version (20.0.2-5ubuntu1.10).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: direct-redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct-redis) (3.4.1)
Running /platform/source/s01/v4_engoff/m10210210/m10210210_q4_t0.sh

0% [Working]
            
Hit:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease

0% [Working]
0% [Waiting for headers]
                        
Hit:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease

                        
0% [Working]
0% [Waiting for headers]
                        
Hit:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease

                        
0% [Working]
0% [Waiting for headers]
                        
Hit:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease

                        
0% [Working]
20% [Working]
             

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 60%

Reading package lists... 60%

Reading package lists... 61%

Reading package lists... 61%

Reading package lists... 74%

Reading package lists... 74%

Reading package lists... 75%

Reading package lists... 75%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... Done


Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 60%

Reading package lists... 60%

Reading package lists... 61%

Reading package lists... 61%

Reading package lists... 74%

Reading package lists... 74%

Reading package lists... 75%

Reading package lists... 75%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... Done


Building dependency tree... 0%

Building dependency tree... 0%

Building dependency tree... 50%

Building dependency tree... 50%

Building dependency tree       


Reading state information... 0%

Reading state information... 0%

Reading state information... Done

python3-pip is already the newest version (20.0.2-5ubuntu1.10).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Running /platform/source/s01/v4_engoff/m10210210/m10210210_q5_t0.sh
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4_engoff/m10210210/m10210210_q6_t0.sh
/platform/source/s01/v4_engoff/m10210210/m10210210_q6_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4_engoff/m10210210/m10210210_q6_t0.sh: line 5: sudo: command not found
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Running /platform/source/s01/v4_engoff/m10210210/m10210210_q7_t0.sh
Running /platform/source/s01/v4_engoff/m10210210/m10210210_q8_t0.sh
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt install python3.8-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: ['/venv/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']

/platform/source/s01/v4_engoff/m10210210/m10210210_q8_t0.sh: line 5: venv/bin/activate: No such file or directory
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
python: can't open file 'query.py': [Errno 2] No such file or directory
Running /platform/source/s01/v4_engoff/m10210210/m10210210_q9_t0.sh

0% [Working]
            
Hit:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease

0% [Working]
0% [Waiting for headers]
                        
Hit:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease

0% [Waiting for headers]
0% [Waiting for headers]
                        
Hit:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease

                        
0% [Working]
0% [Waiting for headers]
                        
Hit:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease

                        
0% [Working]
20% [Working]
             

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 60%

Reading package lists... 60%

Reading package lists... 61%

Reading package lists... 61%

Reading package lists... 74%

Reading package lists... 74%

Reading package lists... 75%

Reading package lists... 75%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... Done


Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 60%

Reading package lists... 60%

Reading package lists... 61%

Reading package lists... 61%

Reading package lists... 74%

Reading package lists... 74%

Reading package lists... 75%

Reading package lists... 75%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... Done


Building dependency tree... 0%

Building dependency tree... 0%

Building dependency tree... 50%

Building dependency tree... 50%

Building dependency tree       


Reading state information... 0%

Reading state information... 0%

Reading state information... Done

python3-pip is already the newest version (20.0.2-5ubuntu1.10).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: direct-redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct-redis) (3.4.1)
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m10210210/m10210210_q10_t0.py /platform/output/s01/v4_engoff/m10210210/m10210210_q10_t0.csv /platform/expected/s01/q10.csv
/platform/source/s01/v4_engoff/m10210210/m10210210_q10_t0.py:25: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  lineitem_df = pd.read_sql_query(query_mysql, mysql_conn)
Traceback (most recent call last):
  File "/platform/source/s01/v4_engoff/m10210210/m10210210_q10_t0.py", line 52, in <module>
    customer_df = pd.read_json(customer_json_str)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m10210210/m10210210_q11_t0.py /platform/output/s01/v4_engoff/m10210210/m10210210_q11_t0.csv /platform/expected/s01/q11.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engoff/m10210210/m10210210_q11_t0.py", line 20, in <module>
    mysql_cur.execute("""
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 822, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'tpch.supplier' doesn't exist")
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m10210210/m10210210_q12_t0.py /platform/output/s01/v4_engoff/m10210210/m10210210_q12_t0.csv /platform/expected/s01/q12.csv
>>> Expected ((2, 3))
   HIGH_LINE_COUNT  LOW_LINE_COUNT L_SHIPMODE
0              647             945       MAIL
1              620             943       SHIP

>>> Actual ((3057, 3))
      1  MAIL  OTHER
0     1  MAIL  OTHER
1     1  MAIL  OTHER
2     1  MAIL  OTHER
3     1  MAIL  OTHER
4     1  MAIL  OTHER
...  ..   ...    ...
3052  2  SHIP  OTHER
3053  2  SHIP  OTHER
3054  2  SHIP  OTHER
3055  2  SHIP  OTHER
3056  2  SHIP  OTHER

[3057 rows x 3 columns]

Score.fail_wrong_output
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m10210210/m10210210_q13_t0.py /platform/output/s01/v4_engoff/m10210210/m10210210_q13_t0.csv /platform/expected/s01/q13.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engoff/m10210210/m10210210_q13_t0.py", line 44, in <module>
    customer_orders = pd.merge(customer_df, orders_count_by_customer, on='O_CUSTKEY', how='left')
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/reshape/merge.py", line 148, in merge
    op = _MergeOperation(
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/reshape/merge.py", line 737, in __init__
    ) = self._get_merge_keys()
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/reshape/merge.py", line 1221, in _get_merge_keys
    left_keys.append(left._get_label_or_level_values(lk))
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/generic.py", line 1778, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'O_CUSTKEY'
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m10210210/m10210210_q14_t0.py /platform/output/s01/v4_engoff/m10210210/m10210210_q14_t0.csv /platform/expected/s01/q14.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engoff/m10210210/m10210210_q14_t0.py", line 31, in <module>
    part_data = eval(redis_client.get('part'))
TypeError: eval() arg 1 must be a string, bytes or code object
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m10210210/m10210210_q15_t0.py /platform/output/s01/v4_engoff/m10210210/m10210210_q15_t0.csv /platform/expected/s01/q15.csv
>>> Expected ((1, 5))
               S_ADDRESS              S_NAME          S_PHONE  S_SUPPKEY  TOTAL_REVENUE
0  8mhrffG7D2WJBSQbOGstQ  Supplier#000000677  23-290-639-3315        677   1.614410e+06

>>> Actual ((1, 8))
   S_ACCTBAL              S_ADDRESS                           S_COMMENT              S_NAME  S_NATIONKEY          S_PHONE  S_SUPPKEY  TOTAL_REVENUE
0    7128.81  8mhrffG7D2WJBSQbOGstQ  nder blithely. slyly unusual theod  Supplier#000000677           13  23-290-639-3315        677   1.614410e+06

Score.success_approx_manual
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m10210210/m10210210_q16_t0.py /platform/output/s01/v4_engoff/m10210210/m10210210_q16_t0.csv /platform/expected/s01/q16.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engoff/m10210210/m10210210_q16_t0.py", line 41, in <module>
    part_df = pd.read_json(parts_data)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m10210210/m10210210_q17_t0.py /platform/output/s01/v4_engoff/m10210210/m10210210_q17_t0.csv /platform/expected/s01/q17.csv
/platform/source/s01/v4_engoff/m10210210/m10210210_q17_t0.py:20: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  lineitem_df = pd.read_sql(query_lineitem, mysql_connection)
Traceback (most recent call last):
  File "/platform/source/s01/v4_engoff/m10210210/m10210210_q17_t0.py", line 29, in <module>
    part_df = pd.read_json(redis_connection.get('part'))
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m10210210/m10210210_q18_t0.py /platform/output/s01/v4_engoff/m10210210/m10210210_q18_t0.csv /platform/expected/s01/q18.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engoff/m10210210/m10210210_q18_t0.py", line 42, in <module>
    customers_df = pd.read_json(customer_data)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m10210210/m10210210_q19_t0.py /platform/output/s01/v4_engoff/m10210210/m10210210_q19_t0.csv /platform/expected/s01/q19.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engoff/m10210210/m10210210_q19_t0.py", line 27, in <module>
    part_df = pd.read_json(redis_conn.get('part'), orient='index')
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m10210210/m10210210_q1_t0.py /platform/output/s01/v4_engoff/m10210210/m10210210_q1_t0.csv /platform/expected/s01/q1.csv
>>> Expected ((4, 10))
   AVG_DISC     AVG_PRICE    AVG_QTY  COUNT_ORDER L_LINESTATUS L_RETURNFLAG  SUM_BASE_PRICE    SUM_CHARGE  SUM_DISC_PRICE  SUM_QTY
0  0.050145  36002.123829  25.537587       147790            F            A    5.320754e+09  5.256751e+09    5.054096e+09  3774200
1  0.049394  35521.326916  25.300664         3765            F            N    1.337378e+08  1.322863e+08    1.271324e+08    95257
2  0.050096  36000.924688  25.545538       292000            O            N    1.051227e+10  1.038558e+10    9.986238e+09  7459297
3  0.049989  35994.029214  25.525944       148301            F            R    5.337951e+09  5.274406e+09    5.071819e+09  3785523

>>> Actual ((4, 10))
   AVG_DISC     AVG_PRICE    AVG_QTY  COUNT_ORDER LINESTATUS RETURNFLAG  SUM_BASE_PRICE    SUM_CHARGE  SUM_DISC_PRICE    SUM_QTY
0  0.050145  36002.123829  25.537587       147790          F          A    5.320754e+09  5.256751e+09    5.054096e+09  3774200.0
1  0.049394  35521.326916  25.300664         3765          F          N    1.337378e+08  1.322863e+08    1.271324e+08    95257.0
2  0.050097  36000.382356  25.545184       291817          O          N    1.050552e+10  1.037890e+10    9.979831e+09  7454519.0
3  0.049989  35994.029214  25.525944       148301          F          R    5.337951e+09  5.274406e+09    5.071819e+09  3785523.0

Head row similarity: 0.6733436055469953
Score.fail_wrong_output
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m10210210/m10210210_q20_t0.py /platform/output/s01/v4_engoff/m10210210/m10210210_q20_t0.csv /platform/expected/s01/q20.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engoff/m10210210/m10210210_q20_t0.py", line 25, in <module>
    cursor.execute("""
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 822, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (3593, "You cannot use the window function 'sum' in this context.'")
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m10210210/m10210210_q21_t0.py /platform/output/s01/v4_engoff/m10210210/m10210210_q21_t0.csv /platform/expected/s01/q21.csv
>>> Expected ((47, 2))
    NUMWAIT              S_NAME
0        16  Supplier#000000445
1        16  Supplier#000000825
2        15  Supplier#000000709
3        15  Supplier#000000762
4        14  Supplier#000000357
5        14  Supplier#000000399
6        14  Supplier#000000496
7        13  Supplier#000000977
8        12  Supplier#000000144
9        12  Supplier#000000188
10       12  Supplier#000000415
11       12  Supplier#000000472
12       12  Supplier#000000633
13       12  Supplier#000000708
14       12  Supplier#000000889
15       11  Supplier#000000380
16       11  Supplier#000000602
17       11  Supplier#000000659
18       11  Supplier#000000821
19       11  Supplier#000000929
20       10  Supplier#000000262
21       10  Supplier#000000460
22       10  Supplier#000000486
23       10  Supplier#000000669
24       10  Supplier#000000718
25       10  Supplier#000000778
26        9  Supplier#000000167
27        9  Supplier#000000578
28        9  Supplier#000000673
29        9  Supplier#000000687
30        8  Supplier#000000074
31        8  Supplier#000000565
32        8  Supplier#000000648
33        8  Supplier#000000918
34        7  Supplier#000000427
35        7  Supplier#000000503
36        7  Supplier#000000610
37        7  Supplier#000000670
38        7  Supplier#000000811
39        6  Supplier#000000114
40        6  Supplier#000000379
41        6  Supplier#000000436
42        6  Supplier#000000500
43        6  Supplier#000000660
44        6  Supplier#000000788
45        6  Supplier#000000846
46        4  Supplier#000000920

>>> Actual ((0, 6))
Empty DataFrame
Columns: [S_ACCTBAL, S_ADDRESS, S_COMMENT, S_NAME, S_PHONE, S_SUPPKEY]
Index: []

Score.fail_wrong_output
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m10210210/m10210210_q22_t0.py /platform/output/s01/v4_engoff/m10210210/m10210210_q22_t0.csv /platform/expected/s01/q22.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engoff/m10210210/m10210210_q22_t0.py", line 26, in <module>
    customer_df = pd.read_json(customer_data)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m10210210/m10210210_q2_t0.py /platform/output/s01/v4_engoff/m10210210/m10210210_q2_t0.csv /platform/expected/s01/q2.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engoff/m10210210/m10210210_q2_t0.py", line 33, in <module>
    cursor.execute(partsupp_query)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 148, in execute
    while self.nextset():
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 98, in nextset
    return self._nextset(False)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 85, in _nextset
    conn = self._get_db()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 67, in _get_db
    raise err.ProgrammingError("Cursor closed")
pymysql.err.ProgrammingError: Cursor closed
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m10210210/m10210210_q3_t0.py /platform/output/s01/v4_engoff/m10210210/m10210210_q3_t0.csv /platform/expected/s01/q3.csv
/platform/source/s01/v4_engoff/m10210210/m10210210_q3_t0.py:30: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  lineitem_df = pd.read_sql(mysql_query, mysql_conn)
>>> Expected ((1216, 4))
      L_ORDERKEY O_ORDERDATE  O_SHIPPRIORITY      REVENUE
0         223140  1995-03-14               0  355369.0698
1         584291  1995-02-21               0  354494.7318
2         405063  1995-03-03               0  353125.4577
3         573861  1995-03-09               0  351238.2770
4         554757  1995-03-14               0  349181.7426
...          ...         ...             ...          ...
1211      152096  1995-01-25               0    1113.2000
1212      521728  1994-12-14               0    1013.7761
1213      445159  1994-12-06               0     949.6260
1214      598597  1994-12-03               0     939.0182
1215      135490  1994-12-20               0     934.9592

[1216 rows x 4 columns]

>>> Actual ((0, 3))
Empty DataFrame
Columns: [O_ORDERKEY, O_SHIPPRIORITY, REVENUE]
Index: []

Score.fail_wrong_output
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m10210210/m10210210_q4_t0.py /platform/output/s01/v4_engoff/m10210210/m10210210_q4_t0.csv /platform/expected/s01/q4.csv
>>> Expected ((5, 2))
   ORDER_COUNT  O_ORDERPRIORITY
0          999         1-URGENT
1          997           2-HIGH
2         1031         3-MEDIUM
3          989  4-NOT SPECIFIED
4         1077            5-LOW

>>> Actual ((5, 2))
   O_ORDERPRIORITY  order_count
0         1-URGENT          999
1           2-HIGH          997
2         3-MEDIUM         1031
3  4-NOT SPECIFIED          989
4            5-LOW         1077

Head row similarity: 0.7539267015706806
Score.success_approx
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m10210210/m10210210_q5_t0.py /platform/output/s01/v4_engoff/m10210210/m10210210_q5_t0.csv /platform/expected/s01/q5.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engoff/m10210210/m10210210_q5_t0.py", line 39, in <module>
    customers_df = pd.read_json(customer_data_json, orient='records')
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m10210210/m10210210_q6_t0.py /platform/output/s01/v4_engoff/m10210210/m10210210_q6_t0.csv /platform/expected/s01/q6.csv
>>> Expected ((1, 1))
        REVENUE
0  7.115407e+06

>>> Actual ((1, 1))
   potential_revenue_increase
0                1.180342e+07

Head row similarity: 0.35555555555555557
Score.fail_wrong_output
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m10210210/m10210210_q7_t0.py /platform/output/s01/v4_engoff/m10210210/m10210210_q7_t0.csv /platform/expected/s01/q7.csv
/platform/source/s01/v4_engoff/m10210210/m10210210_q7_t0.py:17: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  lineitem_data = pd.read_sql(query_mysql, conn_mysql)
Traceback (most recent call last):
  File "/platform/source/s01/v4_engoff/m10210210/m10210210_q7_t0.py", line 29, in <module>
    customer_data = pd.read_json(redis_conn.get('customer'))
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m10210210/m10210210_q8_t0.py /platform/output/s01/v4_engoff/m10210210/m10210210_q8_t0.csv /platform/expected/s01/q8.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engoff/m10210210/m10210210_q8_t0.py", line 36, in <module>
    asian_nations = execute_mysql_query(mysql_query_asia)
  File "/platform/source/s01/v4_engoff/m10210210/m10210210_q8_t0.py", line 27, in execute_mysql_query
    cursor.execute(query)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 822, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'tpch.nation' doesn't exist")
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m10210210/m10210210_q9_t0.py /platform/output/s01/v4_engoff/m10210210/m10210210_q9_t0.csv /platform/expected/s01/q9.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engoff/m10210210/m10210210_q9_t0.py", line 10, in <module>
    cursor.execute("""
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 822, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'tpch.supplier' doesn't exist")
Score.fail_execute
