Using MAPPING_STR=11100022, VERSION_DIR=v4
Running /platform/source/s01/v4/m11100022/m11100022_q10_t0.sh
/platform/source/s01/v4/m11100022/m11100022_q10_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4/m11100022/m11100022_q10_t0.sh: line 7: sudo: command not found
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: direct-redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct-redis) (3.4.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4/m11100022/m11100022_q11_t0.sh
0% [Working]            Hit:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease
0% [Working]0% [Waiting for headers]                        Get:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease [114 kB]
0% [2 InRelease 7031 B/114 kB 6%]                                 0% [Working]0% [Waiting for headers]                        Hit:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease
                        0% [Working]0% [Waiting for headers]                        Hit:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease
                        0% [Working]100% [Working]              Fetched 114 kB in 1s (115 kB/s)
Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Building dependency tree... 0%Building dependency tree... 0%Building dependency tree... 50%Building dependency tree... 50%Building dependency tree       
Reading state information... 0%Reading state information... 0%Reading state information... Done
python3 is already the newest version (3.8.2-0ubuntu2).
python3 set to manually installed.
python3-pip is already the newest version (20.0.2-5ubuntu1.10).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Running /platform/source/s01/v4/m11100022/m11100022_q12_t0.sh
Running /platform/source/s01/v4/m11100022/m11100022_q13_t0.sh
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4/m11100022/m11100022_q14_t0.sh
/platform/source/s01/v4/m11100022/m11100022_q14_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4/m11100022/m11100022_q14_t0.sh: line 5: sudo: command not found
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: direct-redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct-redis) (3.4.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4/m11100022/m11100022_q15_t0.sh
0% [Working]            Hit:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease
0% [Working]0% [Waiting for headers]                        Hit:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease
                        0% [Working]0% [Waiting for headers]                        Hit:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease
                        0% [Working]0% [Waiting for headers]                        Hit:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease
                        0% [Working]20% [Working]             Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Building dependency tree... 0%Building dependency tree... 0%Building dependency tree... 50%Building dependency tree... 50%Building dependency tree       
Reading state information... 0%Reading state information... 0%Reading state information... Done
python3-pip is already the newest version (20.0.2-5ubuntu1.10).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: redis in /usr/local/lib/python3.8/dist-packages (3.4.1)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4/m11100022/m11100022_q16_t0.sh
Running /platform/source/s01/v4/m11100022/m11100022_q17_t0.sh
0% [Working]            Hit:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease
0% [Working]0% [Waiting for headers]                        Hit:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease
                        0% [Working]0% [Waiting for headers]                        Hit:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease
                        0% [Working]0% [Waiting for headers]                        Hit:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease
                        0% [Working]20% [Working]             Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Building dependency tree... 0%Building dependency tree... 0%Building dependency tree... 50%Building dependency tree... 50%Building dependency tree       
Reading state information... 0%Reading state information... 0%Reading state information... Done
python3-pip is already the newest version (20.0.2-5ubuntu1.10).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Collecting pip
  Downloading pip-23.3.1-py3-none-any.whl (2.1 MB)
[?25l[K     |▏                               | 10 kB 4.9 MB/s eta 0:00:01[K     |▎                               | 20 kB 5.5 MB/s eta 0:00:01[K     |▌                               | 30 kB 7.8 MB/s eta 0:00:01[K     |▋                               | 40 kB 4.4 MB/s eta 0:00:01[K     |▊                               | 51 kB 4.7 MB/s eta 0:00:01[K     |█                               | 61 kB 5.6 MB/s eta 0:00:01[K     |█                               | 71 kB 6.4 MB/s eta 0:00:01[K     |█▎                              | 81 kB 7.2 MB/s eta 0:00:01[K     |█▍                              | 92 kB 7.2 MB/s eta 0:00:01[K     |█▌                              | 102 kB 7.2 MB/s eta 0:00:01[K     |█▊                              | 112 kB 7.2 MB/s eta 0:00:01[K     |█▉                              | 122 kB 7.2 MB/s eta 0:00:01[K     |██                              | 133 kB 7.2 MB/s eta 0:00:01[K     |██▏                             | 143 kB 7.2 MB/s eta 0:00:01[K     |██▎                             | 153 kB 7.2 MB/s eta 0:00:01[K     |██▌                             | 163 kB 7.2 MB/s eta 0:00:01[K     |██▋                             | 174 kB 7.2 MB/s eta 0:00:01[K     |██▉                             | 184 kB 7.2 MB/s eta 0:00:01[K     |███                             | 194 kB 7.2 MB/s eta 0:00:01[K     |███                             | 204 kB 7.2 MB/s eta 0:00:01[K     |███▎                            | 215 kB 7.2 MB/s eta 0:00:01[K     |███▍                            | 225 kB 7.2 MB/s eta 0:00:01[K     |███▋                            | 235 kB 7.2 MB/s eta 0:00:01[K     |███▊                            | 245 kB 7.2 MB/s eta 0:00:01[K     |███▉                            | 256 kB 7.2 MB/s eta 0:00:01[K     |████                            | 266 kB 7.2 MB/s eta 0:00:01[K     |████▏                           | 276 kB 7.2 MB/s eta 0:00:01[K     |████▍                           | 286 kB 7.2 MB/s eta 0:00:01[K     |████▌                           | 296 kB 7.2 MB/s eta 0:00:01[K     |████▋                           | 307 kB 7.2 MB/s eta 0:00:01[K     |████▉                           | 317 kB 7.2 MB/s eta 0:00:01[K     |█████                           | 327 kB 7.2 MB/s eta 0:00:01[K     |█████▏                          | 337 kB 7.2 MB/s eta 0:00:01[K     |█████▎                          | 348 kB 7.2 MB/s eta 0:00:01[K     |█████▍                          | 358 kB 7.2 MB/s eta 0:00:01[K     |█████▋                          | 368 kB 7.2 MB/s eta 0:00:01[K     |█████▊                          | 378 kB 7.2 MB/s eta 0:00:01[K     |██████                          | 389 kB 7.2 MB/s eta 0:00:01[K     |██████                          | 399 kB 7.2 MB/s eta 0:00:01[K     |██████▏                         | 409 kB 7.2 MB/s eta 0:00:01[K     |██████▍                         | 419 kB 7.2 MB/s eta 0:00:01[K     |██████▌                         | 430 kB 7.2 MB/s eta 0:00:01[K     |██████▊                         | 440 kB 7.2 MB/s eta 0:00:01[K     |██████▉                         | 450 kB 7.2 MB/s eta 0:00:01[K     |███████                         | 460 kB 7.2 MB/s eta 0:00:01[K     |███████▏                        | 471 kB 7.2 MB/s eta 0:00:01[K     |███████▎                        | 481 kB 7.2 MB/s eta 0:00:01[K     |███████▌                        | 491 kB 7.2 MB/s eta 0:00:01[K     |███████▋                        | 501 kB 7.2 MB/s eta 0:00:01[K     |███████▊                        | 512 kB 7.2 MB/s eta 0:00:01[K     |████████                        | 522 kB 7.2 MB/s eta 0:00:01[K     |████████                        | 532 kB 7.2 MB/s eta 0:00:01[K     |████████▎                       | 542 kB 7.2 MB/s eta 0:00:01[K     |████████▍                       | 552 kB 7.2 MB/s eta 0:00:01[K     |████████▌                       | 563 kB 7.2 MB/s eta 0:00:01[K     |████████▊                       | 573 kB 7.2 MB/s eta 0:00:01[K     |████████▉                       | 583 kB 7.2 MB/s eta 0:00:01[K     |█████████                       | 593 kB 7.2 MB/s eta 0:00:01[K     |█████████▏                      | 604 kB 7.2 MB/s eta 0:00:01[K     |█████████▎                      | 614 kB 7.2 MB/s eta 0:00:01[K     |█████████▌                      | 624 kB 7.2 MB/s eta 0:00:01[K     |█████████▋                      | 634 kB 7.2 MB/s eta 0:00:01[K     |█████████▉                      | 645 kB 7.2 MB/s eta 0:00:01[K     |██████████                      | 655 kB 7.2 MB/s eta 0:00:01[K     |██████████                      | 665 kB 7.2 MB/s eta 0:00:01[K     |██████████▎                     | 675 kB 7.2 MB/s eta 0:00:01[K     |██████████▍                     | 686 kB 7.2 MB/s eta 0:00:01[K     |██████████▋                     | 696 kB 7.2 MB/s eta 0:00:01[K     |██████████▊                     | 706 kB 7.2 MB/s eta 0:00:01[K     |██████████▉                     | 716 kB 7.2 MB/s eta 0:00:01[K     |███████████                     | 727 kB 7.2 MB/s eta 0:00:01[K     |███████████▏                    | 737 kB 7.2 MB/s eta 0:00:01[K     |███████████▍                    | 747 kB 7.2 MB/s eta 0:00:01[K     |███████████▌                    | 757 kB 7.2 MB/s eta 0:00:01[K     |███████████▋                    | 768 kB 7.2 MB/s eta 0:00:01[K     |███████████▉                    | 778 kB 7.2 MB/s eta 0:00:01[K     |████████████                    | 788 kB 7.2 MB/s eta 0:00:01[K     |████████████▏                   | 798 kB 7.2 MB/s eta 0:00:01[K     |████████████▎                   | 808 kB 7.2 MB/s eta 0:00:01[K     |████████████▍                   | 819 kB 7.2 MB/s eta 0:00:01[K     |████████████▋                   | 829 kB 7.2 MB/s eta 0:00:01[K     |████████████▊                   | 839 kB 7.2 MB/s eta 0:00:01[K     |█████████████                   | 849 kB 7.2 MB/s eta 0:00:01[K     |█████████████                   | 860 kB 7.2 MB/s eta 0:00:01[K     |█████████████▏                  | 870 kB 7.2 MB/s eta 0:00:01[K     |█████████████▍                  | 880 kB 7.2 MB/s eta 0:00:01[K     |█████████████▌                  | 890 kB 7.2 MB/s eta 0:00:01[K     |█████████████▊                  | 901 kB 7.2 MB/s eta 0:00:01[K     |█████████████▉                  | 911 kB 7.2 MB/s eta 0:00:01[K     |██████████████                  | 921 kB 7.2 MB/s eta 0:00:01[K     |██████████████▏                 | 931 kB 7.2 MB/s eta 0:00:01[K     |██████████████▎                 | 942 kB 7.2 MB/s eta 0:00:01[K     |██████████████▌                 | 952 kB 7.2 MB/s eta 0:00:01[K     |██████████████▋                 | 962 kB 7.2 MB/s eta 0:00:01[K     |██████████████▊                 | 972 kB 7.2 MB/s eta 0:00:01[K     |███████████████                 | 983 kB 7.2 MB/s eta 0:00:01[K     |███████████████                 | 993 kB 7.2 MB/s eta 0:00:01[K     |███████████████▎                | 1.0 MB 7.2 MB/s eta 0:00:01[K     |███████████████▍                | 1.0 MB 7.2 MB/s eta 0:00:01[K     |███████████████▌                | 1.0 MB 7.2 MB/s eta 0:00:01[K     |███████████████▊                | 1.0 MB 7.2 MB/s eta 0:00:01[K     |███████████████▉                | 1.0 MB 7.2 MB/s eta 0:00:01[K     |████████████████                | 1.1 MB 7.2 MB/s eta 0:00:01[K     |████████████████▏               | 1.1 MB 7.2 MB/s eta 0:00:01[K     |████████████████▎               | 1.1 MB 7.2 MB/s eta 0:00:01[K     |████████████████▌               | 1.1 MB 7.2 MB/s eta 0:00:01[K     |████████████████▋               | 1.1 MB 7.2 MB/s eta 0:00:01[K     |████████████████▉               | 1.1 MB 7.2 MB/s eta 0:00:01[K     |█████████████████               | 1.1 MB 7.2 MB/s eta 0:00:01[K     |█████████████████               | 1.1 MB 7.2 MB/s eta 0:00:01[K     |█████████████████▎              | 1.1 MB 7.2 MB/s eta 0:00:01[K     |█████████████████▍              | 1.1 MB 7.2 MB/s eta 0:00:01[K     |█████████████████▋              | 1.2 MB 7.2 MB/s eta 0:00:01[K     |█████████████████▊              | 1.2 MB 7.2 MB/s eta 0:00:01[K     |█████████████████▉              | 1.2 MB 7.2 MB/s eta 0:00:01[K     |██████████████████              | 1.2 MB 7.2 MB/s eta 0:00:01[K     |██████████████████▏             | 1.2 MB 7.2 MB/s eta 0:00:01[K     |██████████████████▍             | 1.2 MB 7.2 MB/s eta 0:00:01[K     |██████████████████▌             | 1.2 MB 7.2 MB/s eta 0:00:01[K     |██████████████████▋             | 1.2 MB 7.2 MB/s eta 0:00:01[K     |██████████████████▉             | 1.2 MB 7.2 MB/s eta 0:00:01[K     |███████████████████             | 1.2 MB 7.2 MB/s eta 0:00:01[K     |███████████████████▏            | 1.3 MB 7.2 MB/s eta 0:00:01[K     |███████████████████▎            | 1.3 MB 7.2 MB/s eta 0:00:01[K     |███████████████████▍            | 1.3 MB 7.2 MB/s eta 0:00:01[K     |███████████████████▋            | 1.3 MB 7.2 MB/s eta 0:00:01[K     |███████████████████▊            | 1.3 MB 7.2 MB/s eta 0:00:01[K     |████████████████████            | 1.3 MB 7.2 MB/s eta 0:00:01[K     |████████████████████            | 1.3 MB 7.2 MB/s eta 0:00:01[K     |████████████████████▏           | 1.3 MB 7.2 MB/s eta 0:00:01[K     |████████████████████▍           | 1.3 MB 7.2 MB/s eta 0:00:01[K     |████████████████████▌           | 1.4 MB 7.2 MB/s eta 0:00:01[K     |████████████████████▊           | 1.4 MB 7.2 MB/s eta 0:00:01[K     |████████████████████▉           | 1.4 MB 7.2 MB/s eta 0:00:01[K     |█████████████████████           | 1.4 MB 7.2 MB/s eta 0:00:01[K     |█████████████████████▏          | 1.4 MB 7.2 MB/s eta 0:00:01[K     |█████████████████████▎          | 1.4 MB 7.2 MB/s eta 0:00:01[K     |█████████████████████▌          | 1.4 MB 7.2 MB/s eta 0:00:01[K     |█████████████████████▋          | 1.4 MB 7.2 MB/s eta 0:00:01[K     |█████████████████████▊          | 1.4 MB 7.2 MB/s eta 0:00:01[K     |██████████████████████          | 1.4 MB 7.2 MB/s eta 0:00:01[K     |██████████████████████          | 1.5 MB 7.2 MB/s eta 0:00:01[K     |██████████████████████▎         | 1.5 MB 7.2 MB/s eta 0:00:01[K     |██████████████████████▍         | 1.5 MB 7.2 MB/s eta 0:00:01[K     |██████████████████████▌         | 1.5 MB 7.2 MB/s eta 0:00:01[K     |██████████████████████▊         | 1.5 MB 7.2 MB/s eta 0:00:01[K     |██████████████████████▉         | 1.5 MB 7.2 MB/s eta 0:00:01[K     |███████████████████████         | 1.5 MB 7.2 MB/s eta 0:00:01[K     |███████████████████████▏        | 1.5 MB 7.2 MB/s eta 0:00:01[K     |███████████████████████▎        | 1.5 MB 7.2 MB/s eta 0:00:01[K     |███████████████████████▌        | 1.5 MB 7.2 MB/s eta 0:00:01[K     |███████████████████████▋        | 1.6 MB 7.2 MB/s eta 0:00:01[K     |███████████████████████▉        | 1.6 MB 7.2 MB/s eta 0:00:01[K     |████████████████████████        | 1.6 MB 7.2 MB/s eta 0:00:01[K     |████████████████████████        | 1.6 MB 7.2 MB/s eta 0:00:01[K     |████████████████████████▎       | 1.6 MB 7.2 MB/s eta 0:00:01[K     |████████████████████████▍       | 1.6 MB 7.2 MB/s eta 0:00:01[K     |████████████████████████▋       | 1.6 MB 7.2 MB/s eta 0:00:01[K     |████████████████████████▊       | 1.6 MB 7.2 MB/s eta 0:00:01[K     |████████████████████████▉       | 1.6 MB 7.2 MB/s eta 0:00:01[K     |█████████████████████████       | 1.6 MB 7.2 MB/s eta 0:00:01[K     |█████████████████████████▏      | 1.7 MB 7.2 MB/s eta 0:00:01[K     |█████████████████████████▍      | 1.7 MB 7.2 MB/s eta 0:00:01[K     |█████████████████████████▌      | 1.7 MB 7.2 MB/s eta 0:00:01[K     |█████████████████████████▋      | 1.7 MB 7.2 MB/s eta 0:00:01[K     |█████████████████████████▉      | 1.7 MB 7.2 MB/s eta 0:00:01[K     |██████████████████████████      | 1.7 MB 7.2 MB/s eta 0:00:01[K     |██████████████████████████▏     | 1.7 MB 7.2 MB/s eta 0:00:01[K     |██████████████████████████▎     | 1.7 MB 7.2 MB/s eta 0:00:01[K     |██████████████████████████▍     | 1.7 MB 7.2 MB/s eta 0:00:01[K     |██████████████████████████▋     | 1.8 MB 7.2 MB/s eta 0:00:01[K     |██████████████████████████▊     | 1.8 MB 7.2 MB/s eta 0:00:01[K     |███████████████████████████     | 1.8 MB 7.2 MB/s eta 0:00:01[K     |███████████████████████████     | 1.8 MB 7.2 MB/s eta 0:00:01[K     |███████████████████████████▏    | 1.8 MB 7.2 MB/s eta 0:00:01[K     |███████████████████████████▍    | 1.8 MB 7.2 MB/s eta 0:00:01[K     |███████████████████████████▌    | 1.8 MB 7.2 MB/s eta 0:00:01[K     |███████████████████████████▊    | 1.8 MB 7.2 MB/s eta 0:00:01[K     |███████████████████████████▉    | 1.8 MB 7.2 MB/s eta 0:00:01[K     |████████████████████████████    | 1.8 MB 7.2 MB/s eta 0:00:01[K     |████████████████████████████▏   | 1.9 MB 7.2 MB/s eta 0:00:01[K     |████████████████████████████▎   | 1.9 MB 7.2 MB/s eta 0:00:01[K     |████████████████████████████▌   | 1.9 MB 7.2 MB/s eta 0:00:01[K     |████████████████████████████▋   | 1.9 MB 7.2 MB/s eta 0:00:01[K     |████████████████████████████▊   | 1.9 MB 7.2 MB/s eta 0:00:01[K     |█████████████████████████████   | 1.9 MB 7.2 MB/s eta 0:00:01[K     |█████████████████████████████   | 1.9 MB 7.2 MB/s eta 0:00:01[K     |█████████████████████████████▎  | 1.9 MB 7.2 MB/s eta 0:00:01[K     |█████████████████████████████▍  | 1.9 MB 7.2 MB/s eta 0:00:01[K     |█████████████████████████████▌  | 1.9 MB 7.2 MB/s eta 0:00:01[K     |█████████████████████████████▊  | 2.0 MB 7.2 MB/s eta 0:00:01[K     |█████████████████████████████▉  | 2.0 MB 7.2 MB/s eta 0:00:01[K     |██████████████████████████████  | 2.0 MB 7.2 MB/s eta 0:00:01[K     |██████████████████████████████▏ | 2.0 MB 7.2 MB/s eta 0:00:01[K     |██████████████████████████████▎ | 2.0 MB 7.2 MB/s eta 0:00:01[K     |██████████████████████████████▌ | 2.0 MB 7.2 MB/s eta 0:00:01[K     |██████████████████████████████▋ | 2.0 MB 7.2 MB/s eta 0:00:01[K     |██████████████████████████████▉ | 2.0 MB 7.2 MB/s eta 0:00:01[K     |███████████████████████████████ | 2.0 MB 7.2 MB/s eta 0:00:01[K     |███████████████████████████████ | 2.0 MB 7.2 MB/s eta 0:00:01[K     |███████████████████████████████▎| 2.1 MB 7.2 MB/s eta 0:00:01[K     |███████████████████████████████▍| 2.1 MB 7.2 MB/s eta 0:00:01[K     |███████████████████████████████▋| 2.1 MB 7.2 MB/s eta 0:00:01[K     |███████████████████████████████▊| 2.1 MB 7.2 MB/s eta 0:00:01[K     |███████████████████████████████▉| 2.1 MB 7.2 MB/s eta 0:00:01[K     |████████████████████████████████| 2.1 MB 7.2 MB/s 
[?25hInstalling collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.0.2
    Not uninstalling pip at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'pip'. No files were found to uninstall.
Successfully installed pip-23.3.1
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: direct-redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct-redis) (3.4.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4/m11100022/m11100022_q18_t0.sh
0% [Working]            Hit:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease
0% [Working]0% [Waiting for headers]                        Hit:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease
0% [Waiting for headers]0% [Waiting for headers]                        Hit:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease
                        0% [Working]0% [Waiting for headers]                        Hit:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease
                        0% [Working]20% [Working]             Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Building dependency tree... 0%Building dependency tree... 0%Building dependency tree... 50%Building dependency tree... 50%Building dependency tree       
Reading state information... 0%Reading state information... 0%Reading state information... Done
python3 is already the newest version (3.8.2-0ubuntu2).
python3-pip is already the newest version (20.0.2-5ubuntu1.10).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mCollecting git+https://github.com/paksu/py-direct-redis
  Cloning https://github.com/paksu/py-direct-redis to /tmp/pip-req-build-gqnm81lm
[31m  ERROR: Error [Errno 2] No such file or directory: 'git' while executing command git version[0m[31m
[0m[31mERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?[0m[31m
[0mRunning /platform/source/s01/v4/m11100022/m11100022_q19_t0.sh
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: direct-redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct-redis) (3.4.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRunning /platform/source/s01/v4/m11100022/m11100022_q1_t0.sh
Running /platform/source/s01/v4/m11100022/m11100022_q20_t0.sh
/platform/source/s01/v4/m11100022/m11100022_q20_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4/m11100022/m11100022_q20_t0.sh: line 5: sudo: command not found
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Collecting pickle5
  Downloading pickle5-0.0.11.tar.gz (132 kB)
[?25l     [90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━[0m [32m0.0/132.1 kB[0m [31m?[0m eta [36m-:--:--[0m[2K     [90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━[0m [32m132.1/132.1 kB[0m [31m5.2 MB/s[0m eta [36m0:00:00[0m
[?25h  Preparing metadata (setup.py) ... [?25l- done
[?25hRequirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Building wheels for collected packages: pickle5
  Building wheel for pickle5 (setup.py) ... [?25l- \ | done
[?25h  Created wheel for pickle5: filename=pickle5-0.0.11-cp38-cp38-linux_aarch64.whl size=264933 sha256=69befbb955d05acb5d630539350bfc51b57d469a8559ef57690444f64533f18b
  Stored in directory: /root/.cache/pip/wheels/25/d4/61/dbd8edd1a0d656be7b4267c85db3b61951eb60016a0154a122
Successfully built pickle5
Installing collected packages: pickle5
Successfully installed pickle5-0.0.11
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRunning /platform/source/s01/v4/m11100022/m11100022_q21_t0.sh
/platform/source/s01/v4/m11100022/m11100022_q21_t0.sh: line 5: sudo: command not found
/platform/source/s01/v4/m11100022/m11100022_q21_t0.sh: line 8: sudo: command not found
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: redis in /usr/local/lib/python3.8/dist-packages (3.4.1)
Requirement already satisfied: direct-redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRunning /platform/source/s01/v4/m11100022/m11100022_q22_t0.sh
0% [Working]            Hit:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease
0% [Working]0% [Waiting for headers]                        Hit:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease
                        0% [Working]0% [Waiting for headers]                        Hit:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease
                        0% [Working]0% [Waiting for headers]                        Hit:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease
                        0% [Working]20% [Working]             Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Building dependency tree... 0%Building dependency tree... 0%Building dependency tree... 50%Building dependency tree... 50%Building dependency tree... 75%Building dependency tree       
Reading state information... 0%Reading state information... 0%Reading state information... Done
python3-pip is already the newest version (20.0.2-5ubuntu1.10).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: redis in /usr/local/lib/python3.8/dist-packages (3.4.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0m/platform/source/s01/v4/m11100022/m11100022_q22_t0.sh: line 13: username: No such file or directory
Running /platform/source/s01/v4/m11100022/m11100022_q2_t0.sh
/platform/source/s01/v4/m11100022/m11100022_q2_t0.sh: line 7: sudo: command not found
/platform/source/s01/v4/m11100022/m11100022_q2_t0.sh: line 8: sudo: command not found
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRunning /platform/source/s01/v4/m11100022/m11100022_q3_t0.sh
Running /platform/source/s01/v4/m11100022/m11100022_q4_t0.sh
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt install python3.8-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: ['/env/bin/python', '-Im', 'ensurepip', '--upgrade', '--default-pip']

/platform/source/s01/v4/m11100022/m11100022_q4_t0.sh: line 7: env/bin/activate: No such file or directory
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRequirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0m/platform/source/s01/v4/m11100022/m11100022_q4_t0.sh: line 19: deactivate: command not found
Running /platform/source/s01/v4/m11100022/m11100022_q5_t0.sh
Running /platform/source/s01/v4/m11100022/m11100022_q6_t0.sh
Running /platform/source/s01/v4/m11100022/m11100022_q7_t0.sh
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRequirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRequirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRequirement already satisfied: direct-redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct-redis) (3.4.1)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRunning /platform/source/s01/v4/m11100022/m11100022_q8_t0.sh
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRequirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRequirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRequirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRunning /platform/source/s01/v4/m11100022/m11100022_q9_t0.sh
/platform/source/s01/v4/m11100022/m11100022_q9_t0.sh: line 5: sudo: command not found
/platform/source/s01/v4/m11100022/m11100022_q9_t0.sh: line 6: sudo: command not found
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: direct-redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct-redis) (3.4.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mpython /dbknitter/dbknitter/grader.py /platform/source/s01/v4/m11100022/m11100022_q10_t0.py /platform/output/s01/v4/m11100022/m11100022_q10_t0.csv /platform/expected/s01/q10.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4/m11100022/m11100022_q10_t0.py", line 9, in <module>
    mysql_conn = pymysql.connect(
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 358, in __init__
    self.connect()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 664, in connect
    self._request_authentication()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 976, in _request_authentication
    auth_packet = _auth.caching_sha2_password_auth(self, auth_packet)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/_auth.py", line 267, in caching_sha2_password_auth
    pkt = _roundtrip(conn, data)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/_auth.py", line 120, in _roundtrip
    pkt = conn._read_packet()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database 'tpch'")
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4/m11100022/m11100022_q11_t0.py /platform/output/s01/v4/m11100022/m11100022_q11_t0.csv /platform/expected/s01/q11.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4/m11100022/m11100022_q11_t0.py", line 13, in <module>
    mysql_conn = pymysql.connect(**mysql_conn_info)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 358, in __init__
    self.connect()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 664, in connect
    self._request_authentication()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 976, in _request_authentication
    auth_packet = _auth.caching_sha2_password_auth(self, auth_packet)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/_auth.py", line 240, in caching_sha2_password_auth
    pkt = conn._read_packet()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database 'tpch'")
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4/m11100022/m11100022_q12_t0.py /platform/output/s01/v4/m11100022/m11100022_q12_t0.csv /platform/expected/s01/q12.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4/m11100022/m11100022_q12_t0.py", line 13, in <module>
    orders_df = pd.read_json(orders_data)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4/m11100022/m11100022_q13_t0.py /platform/output/s01/v4/m11100022/m11100022_q13_t0.csv /platform/expected/s01/q13.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4/m11100022/m11100022_q13_t0.py", line 6, in <module>
    mysql_conn = pymysql.connect(
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 358, in __init__
    self.connect()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 664, in connect
    self._request_authentication()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 976, in _request_authentication
    auth_packet = _auth.caching_sha2_password_auth(self, auth_packet)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/_auth.py", line 240, in caching_sha2_password_auth
    pkt = conn._read_packet()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database 'tpch'")
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4/m11100022/m11100022_q14_t0.py /platform/output/s01/v4/m11100022/m11100022_q14_t0.csv /platform/expected/s01/q14.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4/m11100022/m11100022_q14_t0.py", line 21, in <module>
    lineitem_df = pd.read_json(lineitem_df_str)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4/m11100022/m11100022_q15_t0.py /platform/output/s01/v4/m11100022/m11100022_q15_t0.csv /platform/expected/s01/q15.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4/m11100022/m11100022_q15_t0.py", line 23, in <module>
    mysql_connection = pymysql.connect(**mysql_conn_info)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 358, in __init__
    self.connect()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 664, in connect
    self._request_authentication()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 976, in _request_authentication
    auth_packet = _auth.caching_sha2_password_auth(self, auth_packet)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/_auth.py", line 240, in caching_sha2_password_auth
    pkt = conn._read_packet()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database 'tpch'")
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4/m11100022/m11100022_q16_t0.py /platform/output/s01/v4/m11100022/m11100022_q16_t0.csv /platform/expected/s01/q16.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4/m11100022/m11100022_q16_t0.py", line 6, in <module>
    mysql_conn = pymysql.connect(
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 358, in __init__
    self.connect()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 664, in connect
    self._request_authentication()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 976, in _request_authentication
    auth_packet = _auth.caching_sha2_password_auth(self, auth_packet)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/_auth.py", line 240, in caching_sha2_password_auth
    pkt = conn._read_packet()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database 'tpch'")
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4/m11100022/m11100022_q17_t0.py /platform/output/s01/v4/m11100022/m11100022_q17_t0.csv /platform/expected/s01/q17.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4/m11100022/m11100022_q17_t0.py", line 45, in <module>
    main()
  File "/platform/source/s01/v4/m11100022/m11100022_q17_t0.py", line 25, in main
    lineitem_df = get_redis_data()
  File "/platform/source/s01/v4/m11100022/m11100022_q17_t0.py", line 20, in get_redis_data
    return pd.read_csv(lineitem_df.decode('utf-8'))
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'decode'
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4/m11100022/m11100022_q18_t0.py /platform/output/s01/v4/m11100022/m11100022_q18_t0.csv /platform/expected/s01/q18.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4/m11100022/m11100022_q18_t0.py", line 7, in <module>
    mysql_conn = pymysql.connect(host='mysql', user='root', passwd='my-secret-pw', db='tpch')
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 358, in __init__
    self.connect()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 664, in connect
    self._request_authentication()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 976, in _request_authentication
    auth_packet = _auth.caching_sha2_password_auth(self, auth_packet)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/_auth.py", line 240, in caching_sha2_password_auth
    pkt = conn._read_packet()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database 'tpch'")
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4/m11100022/m11100022_q19_t0.py /platform/output/s01/v4/m11100022/m11100022_q19_t0.csv /platform/expected/s01/q19.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4/m11100022/m11100022_q19_t0.py", line 38, in <module>
    lineitem_df = pd.read_msgpack(redis.get('lineitem'))
AttributeError: module 'pandas' has no attribute 'read_msgpack'
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4/m11100022/m11100022_q1_t0.py /platform/output/s01/v4/m11100022/m11100022_q1_t0.csv /platform/expected/s01/q1.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4/m11100022/m11100022_q1_t0.py", line 30, in <module>
    lineitem_df = pd.read_json(lineitem_str)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4/m11100022/m11100022_q20_t0.py /platform/output/s01/v4/m11100022/m11100022_q20_t0.csv /platform/expected/s01/q20.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4/m11100022/m11100022_q20_t0.py", line 8, in <module>
    mysql_conn = pymysql.connect(
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 358, in __init__
    self.connect()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 664, in connect
    self._request_authentication()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 976, in _request_authentication
    auth_packet = _auth.caching_sha2_password_auth(self, auth_packet)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/_auth.py", line 240, in caching_sha2_password_auth
    pkt = conn._read_packet()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database 'tpch'")
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4/m11100022/m11100022_q21_t0.py /platform/output/s01/v4/m11100022/m11100022_q21_t0.csv /platform/expected/s01/q21.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4/m11100022/m11100022_q21_t0.py", line 83, in <module>
    main()
  File "/platform/source/s01/v4/m11100022/m11100022_q21_t0.py", line 46, in main
    supplier_df = fetch_supplier_data()
  File "/platform/source/s01/v4/m11100022/m11100022_q21_t0.py", line 10, in fetch_supplier_data
    mysql_connection = pymysql.connect(host='mysql',
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 358, in __init__
    self.connect()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 664, in connect
    self._request_authentication()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 976, in _request_authentication
    auth_packet = _auth.caching_sha2_password_auth(self, auth_packet)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/_auth.py", line 240, in caching_sha2_password_auth
    pkt = conn._read_packet()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database 'tpch'")
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4/m11100022/m11100022_q22_t0.py /platform/output/s01/v4/m11100022/m11100022_q22_t0.csv /platform/expected/s01/q22.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4/m11100022/m11100022_q22_t0.py", line 6, in <module>
    mysql_connection = pymysql.connect(
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 358, in __init__
    self.connect()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 664, in connect
    self._request_authentication()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 976, in _request_authentication
    auth_packet = _auth.caching_sha2_password_auth(self, auth_packet)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/_auth.py", line 240, in caching_sha2_password_auth
    pkt = conn._read_packet()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database 'tpch'")
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4/m11100022/m11100022_q2_t0.py /platform/output/s01/v4/m11100022/m11100022_q2_t0.csv /platform/expected/s01/q2.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4/m11100022/m11100022_q2_t0.py", line 21, in <module>
    conn = pymysql.connect(**mysql_params)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 358, in __init__
    self.connect()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 664, in connect
    self._request_authentication()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 976, in _request_authentication
    auth_packet = _auth.caching_sha2_password_auth(self, auth_packet)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/_auth.py", line 240, in caching_sha2_password_auth
    pkt = conn._read_packet()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database 'tpch'")
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4/m11100022/m11100022_q3_t0.py /platform/output/s01/v4/m11100022/m11100022_q3_t0.csv /platform/expected/s01/q3.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4/m11100022/m11100022_q3_t0.py", line 7, in <module>
    mysql_conn = pymysql.connect(
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 358, in __init__
    self.connect()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 664, in connect
    self._request_authentication()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 976, in _request_authentication
    auth_packet = _auth.caching_sha2_password_auth(self, auth_packet)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/_auth.py", line 240, in caching_sha2_password_auth
    pkt = conn._read_packet()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database 'tpch'")
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4/m11100022/m11100022_q4_t0.py /platform/output/s01/v4/m11100022/m11100022_q4_t0.csv /platform/expected/s01/q4.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4/m11100022/m11100022_q4_t0.py", line 45, in <module>
    main()
  File "/platform/source/s01/v4/m11100022/m11100022_q4_t0.py", line 8, in main
    orders_df = pd.read_json(redis.get('orders'), orient='records')
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4/m11100022/m11100022_q5_t0.py /platform/output/s01/v4/m11100022/m11100022_q5_t0.csv /platform/expected/s01/q5.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4/m11100022/m11100022_q5_t0.py", line 7, in <module>
    mysql_conn = pymysql.connect(host='mysql', user='root', password='my-secret-pw', database='tpch')
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 358, in __init__
    self.connect()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 664, in connect
    self._request_authentication()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 976, in _request_authentication
    auth_packet = _auth.caching_sha2_password_auth(self, auth_packet)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/_auth.py", line 240, in caching_sha2_password_auth
    pkt = conn._read_packet()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database 'tpch'")
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4/m11100022/m11100022_q6_t0.py /platform/output/s01/v4/m11100022/m11100022_q6_t0.csv /platform/expected/s01/q6.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4/m11100022/m11100022_q6_t0.py", line 36, in <module>
    query_redis_data()
  File "/platform/source/s01/v4/m11100022/m11100022_q6_t0.py", line 13, in query_redis_data
    lineitem_df = pd.read_msgpack(redis_client.get(lineitem_key))
AttributeError: module 'pandas' has no attribute 'read_msgpack'
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4/m11100022/m11100022_q7_t0.py /platform/output/s01/v4/m11100022/m11100022_q7_t0.csv /platform/expected/s01/q7.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4/m11100022/m11100022_q7_t0.py", line 72, in <module>
    main()
  File "/platform/source/s01/v4/m11100022/m11100022_q7_t0.py", line 38, in main
    df_supplier, df_customer = get_mysql_data()
  File "/platform/source/s01/v4/m11100022/m11100022_q7_t0.py", line 10, in get_mysql_data
    conn = pymysql.connect(host='mysql', user='root', passwd='my-secret-pw', db='tpch')
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 358, in __init__
    self.connect()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 664, in connect
    self._request_authentication()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 976, in _request_authentication
    auth_packet = _auth.caching_sha2_password_auth(self, auth_packet)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/_auth.py", line 240, in caching_sha2_password_auth
    pkt = conn._read_packet()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database 'tpch'")
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4/m11100022/m11100022_q8_t0.py /platform/output/s01/v4/m11100022/m11100022_q8_t0.csv /platform/expected/s01/q8.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4/m11100022/m11100022_q8_t0.py", line 21, in <module>
    conn = pymysql.connect(
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 358, in __init__
    self.connect()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 664, in connect
    self._request_authentication()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 976, in _request_authentication
    auth_packet = _auth.caching_sha2_password_auth(self, auth_packet)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/_auth.py", line 240, in caching_sha2_password_auth
    pkt = conn._read_packet()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database 'tpch'")
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4/m11100022/m11100022_q9_t0.py /platform/output/s01/v4/m11100022/m11100022_q9_t0.csv /platform/expected/s01/q9.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4/m11100022/m11100022_q9_t0.py", line 9, in <module>
    mysql_conn = pymysql.connect(
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 358, in __init__
    self.connect()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 664, in connect
    self._request_authentication()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 976, in _request_authentication
    auth_packet = _auth.caching_sha2_password_auth(self, auth_packet)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/_auth.py", line 240, in caching_sha2_password_auth
    pkt = conn._read_packet()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database 'tpch'")
Score.fail_execute
