Using MAPPING_STR=00022211, VERSION_DIR=v4_engman
Running /platform/source/s01/v4_engman/m00022211/m00022211_q10_t0.sh
Running /platform/source/s01/v4_engman/m00022211/m00022211_q11_t0.sh
/platform/source/s01/v4_engman/m00022211/m00022211_q11_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4_engman/m00022211/m00022211_q11_t0.sh: line 5: sudo: command not found
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Collecting git+https://github.com/Avature/direct-redis.git
  Cloning https://github.com/Avature/direct-redis.git to /tmp/pip-req-build-clf4f7rb
  Running command git clone -q https://github.com/Avature/direct-redis.git /tmp/pip-req-build-clf4f7rb
[31m  ERROR: Error [Errno 2] No such file or directory: 'git' while executing command git clone -q https://github.com/Avature/direct-redis.git /tmp/pip-req-build-clf4f7rb[0m
[31mERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?[0m
Running /platform/source/s01/v4_engman/m00022211/m00022211_q12_t0.sh
/platform/source/s01/v4_engman/m00022211/m00022211_q12_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4_engman/m00022211/m00022211_q12_t0.sh: line 5: sudo: command not found
/platform/source/s01/v4_engman/m00022211/m00022211_q12_t0.sh: line 6: sudo: command not found
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Running /platform/source/s01/v4_engman/m00022211/m00022211_q13_t0.sh
/platform/source/s01/v4_engman/m00022211/m00022211_q13_t0.sh: line 7: sudo: command not found
/platform/source/s01/v4_engman/m00022211/m00022211_q13_t0.sh: line 8: sudo: command not found
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4_engman/m00022211/m00022211_q14_t0.sh
0% [Working]            Hit:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease
0% [Working]0% [Waiting for headers]                        Get:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease [114 kB]
0% [2 InRelease 1239 B/114 kB 1%]                                 0% [Working]0% [Waiting for headers]                        Hit:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease
                        0% [Working]0% [Waiting for headers]                        Hit:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease
                        0% [Working]100% [Working]              Fetched 114 kB in 1s (137 kB/s)
Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Building dependency tree... 0%Building dependency tree... 0%Building dependency tree... 50%Building dependency tree... 50%Building dependency tree       
Reading state information... 0%Reading state information... 0%Reading state information... Done
python3 is already the newest version (3.8.2-0ubuntu2).
python3 set to manually installed.
python3-pip is already the newest version (20.0.2-5ubuntu1.10).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Running /platform/source/s01/v4_engman/m00022211/m00022211_q15_t0.sh
/platform/source/s01/v4_engman/m00022211/m00022211_q15_t0.sh: line 5: sudo: command not found
/platform/source/s01/v4_engman/m00022211/m00022211_q15_t0.sh: line 8: sudo: command not found
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4_engman/m00022211/m00022211_q16_t0.sh
0% [Working]            Hit:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease
0% [Working]0% [Waiting for headers]                        Hit:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease
                        0% [Working]0% [Waiting for headers]                        Hit:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease
                        0% [Working]0% [Waiting for headers]                        Hit:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease
                        0% [Working]20% [Working]             Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Building dependency tree... 0%Building dependency tree... 0%Building dependency tree... 50%Building dependency tree... 50%Building dependency tree       
Reading state information... 0%Reading state information... 0%Reading state information... Done
python3-dev is already the newest version (3.8.2-0ubuntu2).
python3-dev set to manually installed.
python3-pip is already the newest version (20.0.2-5ubuntu1.10).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: redis in /usr/local/lib/python3.8/dist-packages (3.4.1)
Collecting git+https://github.com/patrys/direct_redis.git
  Cloning https://github.com/patrys/direct_redis.git to /tmp/pip-req-build-w3zvaxa1
  Running command git clone -q https://github.com/patrys/direct_redis.git /tmp/pip-req-build-w3zvaxa1
[31m  ERROR: Error [Errno 2] No such file or directory: 'git' while executing command git clone -q https://github.com/patrys/direct_redis.git /tmp/pip-req-build-w3zvaxa1[0m
[31mERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?[0m
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4_engman/m00022211/m00022211_q17_t0.sh
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4_engman/m00022211/m00022211_q18_t0.sh
/platform/source/s01/v4_engman/m00022211/m00022211_q18_t0.sh: line 6: sudo: command not found
/platform/source/s01/v4_engman/m00022211/m00022211_q18_t0.sh: line 9: sudo: command not found
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: direct-redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct-redis) (3.4.1)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4_engman/m00022211/m00022211_q19_t0.sh
0% [Working]            Hit:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease
0% [Working]0% [Waiting for headers]                        Hit:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease
                        0% [Working]0% [Waiting for headers]                        Hit:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease
                        0% [Working]0% [Waiting for headers]                        Hit:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease
                        0% [Working]20% [Working]             Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Building dependency tree... 0%Building dependency tree... 0%Building dependency tree... 50%Building dependency tree... 50%Building dependency tree       
Reading state information... 0%Reading state information... 0%Reading state information... Done
python3 is already the newest version (3.8.2-0ubuntu2).
python3-pip is already the newest version (20.0.2-5ubuntu1.10).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4_engman/m00022211/m00022211_q1_t0.sh
0% [Working]            Hit:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease
0% [Working]0% [Waiting for headers]                        Hit:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease
0% [Waiting for headers]0% [Waiting for headers]                        Hit:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease
                        0% [Working]0% [Waiting for headers]                        Hit:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease
                        0% [Working]20% [Working]             Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Building dependency tree... 0%Building dependency tree... 0%Building dependency tree... 50%Building dependency tree... 50%Building dependency tree       
Reading state information... 0%Reading state information... 0%Reading state information... Done
python3 is already the newest version (3.8.2-0ubuntu2).
python3-pip is already the newest version (20.0.2-5ubuntu1.10).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Running /platform/source/s01/v4_engman/m00022211/m00022211_q20_t0.sh
/platform/source/s01/v4_engman/m00022211/m00022211_q20_t0.sh: line 5: sudo: command not found
/platform/source/s01/v4_engman/m00022211/m00022211_q20_t0.sh: line 6: sudo: command not found
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Collecting git+https://github.com/username/direct_redis.git
  Cloning https://github.com/username/direct_redis.git to /tmp/pip-req-build-e7qqtjmv
  Running command git clone -q https://github.com/username/direct_redis.git /tmp/pip-req-build-e7qqtjmv
[31m  ERROR: Error [Errno 2] No such file or directory: 'git' while executing command git clone -q https://github.com/username/direct_redis.git /tmp/pip-req-build-e7qqtjmv[0m
[31mERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?[0m
Running /platform/source/s01/v4_engman/m00022211/m00022211_q21_t0.sh
/platform/source/s01/v4_engman/m00022211/m00022211_q21_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4_engman/m00022211/m00022211_q21_t0.sh: line 7: sudo: command not found
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: direct-redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct-redis) (3.4.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
python3: can't open file '/path/to/query_code.py': [Errno 2] No such file or directory
Running /platform/source/s01/v4_engman/m00022211/m00022211_q22_t0.sh
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Collecting git+https://github.com/RedisJSON/direct_redis.git
  Cloning https://github.com/RedisJSON/direct_redis.git to /tmp/pip-req-build-hgkdqp_h
  Running command git clone -q https://github.com/RedisJSON/direct_redis.git /tmp/pip-req-build-hgkdqp_h
[31m  ERROR: Error [Errno 2] No such file or directory: 'git' while executing command git clone -q https://github.com/RedisJSON/direct_redis.git /tmp/pip-req-build-hgkdqp_h[0m
[31mERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?[0m
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4_engman/m00022211/m00022211_q2_t0.sh
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4_engman/m00022211/m00022211_q3_t0.sh
Collecting pip
  Downloading pip-23.3.1-py3-none-any.whl (2.1 MB)
[?25l[K     |▏                               | 10 kB 5.6 MB/s eta 0:00:01[K     |▎                               | 20 kB 5.6 MB/s eta 0:00:01[K     |▌                               | 30 kB 8.2 MB/s eta 0:00:01[K     |▋                               | 40 kB 2.8 MB/s eta 0:00:01[K     |▊                               | 51 kB 3.1 MB/s eta 0:00:01[K     |█                               | 61 kB 3.8 MB/s eta 0:00:01[K     |█                               | 71 kB 4.4 MB/s eta 0:00:01[K     |█▎                              | 81 kB 4.6 MB/s eta 0:00:01[K     |█▍                              | 92 kB 5.2 MB/s eta 0:00:01[K     |█▌                              | 102 kB 5.7 MB/s eta 0:00:01[K     |█▊                              | 112 kB 5.7 MB/s eta 0:00:01[K     |█▉                              | 122 kB 5.7 MB/s eta 0:00:01[K     |██                              | 133 kB 5.7 MB/s eta 0:00:01[K     |██▏                             | 143 kB 5.7 MB/s eta 0:00:01[K     |██▎                             | 153 kB 5.7 MB/s eta 0:00:01[K     |██▌                             | 163 kB 5.7 MB/s eta 0:00:01[K     |██▋                             | 174 kB 5.7 MB/s eta 0:00:01[K     |██▉                             | 184 kB 5.7 MB/s eta 0:00:01[K     |███                             | 194 kB 5.7 MB/s eta 0:00:01[K     |███                             | 204 kB 5.7 MB/s eta 0:00:01[K     |███▎                            | 215 kB 5.7 MB/s eta 0:00:01[K     |███▍                            | 225 kB 5.7 MB/s eta 0:00:01[K     |███▋                            | 235 kB 5.7 MB/s eta 0:00:01[K     |███▊                            | 245 kB 5.7 MB/s eta 0:00:01[K     |███▉                            | 256 kB 5.7 MB/s eta 0:00:01[K     |████                            | 266 kB 5.7 MB/s eta 0:00:01[K     |████▏                           | 276 kB 5.7 MB/s eta 0:00:01[K     |████▍                           | 286 kB 5.7 MB/s eta 0:00:01[K     |████▌                           | 296 kB 5.7 MB/s eta 0:00:01[K     |████▋                           | 307 kB 5.7 MB/s eta 0:00:01[K     |████▉                           | 317 kB 5.7 MB/s eta 0:00:01[K     |█████                           | 327 kB 5.7 MB/s eta 0:00:01[K     |█████▏                          | 337 kB 5.7 MB/s eta 0:00:01[K     |█████▎                          | 348 kB 5.7 MB/s eta 0:00:01[K     |█████▍                          | 358 kB 5.7 MB/s eta 0:00:01[K     |█████▋                          | 368 kB 5.7 MB/s eta 0:00:01[K     |█████▊                          | 378 kB 5.7 MB/s eta 0:00:01[K     |██████                          | 389 kB 5.7 MB/s eta 0:00:01[K     |██████                          | 399 kB 5.7 MB/s eta 0:00:01[K     |██████▏                         | 409 kB 5.7 MB/s eta 0:00:01[K     |██████▍                         | 419 kB 5.7 MB/s eta 0:00:01[K     |██████▌                         | 430 kB 5.7 MB/s eta 0:00:01[K     |██████▊                         | 440 kB 5.7 MB/s eta 0:00:01[K     |██████▉                         | 450 kB 5.7 MB/s eta 0:00:01[K     |███████                         | 460 kB 5.7 MB/s eta 0:00:01[K     |███████▏                        | 471 kB 5.7 MB/s eta 0:00:01[K     |███████▎                        | 481 kB 5.7 MB/s eta 0:00:01[K     |███████▌                        | 491 kB 5.7 MB/s eta 0:00:01[K     |███████▋                        | 501 kB 5.7 MB/s eta 0:00:01[K     |███████▊                        | 512 kB 5.7 MB/s eta 0:00:01[K     |████████                        | 522 kB 5.7 MB/s eta 0:00:01[K     |████████                        | 532 kB 5.7 MB/s eta 0:00:01[K     |████████▎                       | 542 kB 5.7 MB/s eta 0:00:01[K     |████████▍                       | 552 kB 5.7 MB/s eta 0:00:01[K     |████████▌                       | 563 kB 5.7 MB/s eta 0:00:01[K     |████████▊                       | 573 kB 5.7 MB/s eta 0:00:01[K     |████████▉                       | 583 kB 5.7 MB/s eta 0:00:01[K     |█████████                       | 593 kB 5.7 MB/s eta 0:00:01[K     |█████████▏                      | 604 kB 5.7 MB/s eta 0:00:01[K     |█████████▎                      | 614 kB 5.7 MB/s eta 0:00:01[K     |█████████▌                      | 624 kB 5.7 MB/s eta 0:00:01[K     |█████████▋                      | 634 kB 5.7 MB/s eta 0:00:01[K     |█████████▉                      | 645 kB 5.7 MB/s eta 0:00:01[K     |██████████                      | 655 kB 5.7 MB/s eta 0:00:01[K     |██████████                      | 665 kB 5.7 MB/s eta 0:00:01[K     |██████████▎                     | 675 kB 5.7 MB/s eta 0:00:01[K     |██████████▍                     | 686 kB 5.7 MB/s eta 0:00:01[K     |██████████▋                     | 696 kB 5.7 MB/s eta 0:00:01[K     |██████████▊                     | 706 kB 5.7 MB/s eta 0:00:01[K     |██████████▉                     | 716 kB 5.7 MB/s eta 0:00:01[K     |███████████                     | 727 kB 5.7 MB/s eta 0:00:01[K     |███████████▏                    | 737 kB 5.7 MB/s eta 0:00:01[K     |███████████▍                    | 747 kB 5.7 MB/s eta 0:00:01[K     |███████████▌                    | 757 kB 5.7 MB/s eta 0:00:01[K     |███████████▋                    | 768 kB 5.7 MB/s eta 0:00:01[K     |███████████▉                    | 778 kB 5.7 MB/s eta 0:00:01[K     |████████████                    | 788 kB 5.7 MB/s eta 0:00:01[K     |████████████▏                   | 798 kB 5.7 MB/s eta 0:00:01[K     |████████████▎                   | 808 kB 5.7 MB/s eta 0:00:01[K     |████████████▍                   | 819 kB 5.7 MB/s eta 0:00:01[K     |████████████▋                   | 829 kB 5.7 MB/s eta 0:00:01[K     |████████████▊                   | 839 kB 5.7 MB/s eta 0:00:01[K     |█████████████                   | 849 kB 5.7 MB/s eta 0:00:01[K     |█████████████                   | 860 kB 5.7 MB/s eta 0:00:01[K     |█████████████▏                  | 870 kB 5.7 MB/s eta 0:00:01[K     |█████████████▍                  | 880 kB 5.7 MB/s eta 0:00:01[K     |█████████████▌                  | 890 kB 5.7 MB/s eta 0:00:01[K     |█████████████▊                  | 901 kB 5.7 MB/s eta 0:00:01[K     |█████████████▉                  | 911 kB 5.7 MB/s eta 0:00:01[K     |██████████████                  | 921 kB 5.7 MB/s eta 0:00:01[K     |██████████████▏                 | 931 kB 5.7 MB/s eta 0:00:01[K     |██████████████▎                 | 942 kB 5.7 MB/s eta 0:00:01[K     |██████████████▌                 | 952 kB 5.7 MB/s eta 0:00:01[K     |██████████████▋                 | 962 kB 5.7 MB/s eta 0:00:01[K     |██████████████▊                 | 972 kB 5.7 MB/s eta 0:00:01[K     |███████████████                 | 983 kB 5.7 MB/s eta 0:00:01[K     |███████████████                 | 993 kB 5.7 MB/s eta 0:00:01[K     |███████████████▎                | 1.0 MB 5.7 MB/s eta 0:00:01[K     |███████████████▍                | 1.0 MB 5.7 MB/s eta 0:00:01[K     |███████████████▌                | 1.0 MB 5.7 MB/s eta 0:00:01[K     |███████████████▊                | 1.0 MB 5.7 MB/s eta 0:00:01[K     |███████████████▉                | 1.0 MB 5.7 MB/s eta 0:00:01[K     |████████████████                | 1.1 MB 5.7 MB/s eta 0:00:01[K     |████████████████▏               | 1.1 MB 5.7 MB/s eta 0:00:01[K     |████████████████▎               | 1.1 MB 5.7 MB/s eta 0:00:01[K     |████████████████▌               | 1.1 MB 5.7 MB/s eta 0:00:01[K     |████████████████▋               | 1.1 MB 5.7 MB/s eta 0:00:01[K     |████████████████▉               | 1.1 MB 5.7 MB/s eta 0:00:01[K     |█████████████████               | 1.1 MB 5.7 MB/s eta 0:00:01[K     |█████████████████               | 1.1 MB 5.7 MB/s eta 0:00:01[K     |█████████████████▎              | 1.1 MB 5.7 MB/s eta 0:00:01[K     |█████████████████▍              | 1.1 MB 5.7 MB/s eta 0:00:01[K     |█████████████████▋              | 1.2 MB 5.7 MB/s eta 0:00:01[K     |█████████████████▊              | 1.2 MB 5.7 MB/s eta 0:00:01[K     |█████████████████▉              | 1.2 MB 5.7 MB/s eta 0:00:01[K     |██████████████████              | 1.2 MB 5.7 MB/s eta 0:00:01[K     |██████████████████▏             | 1.2 MB 5.7 MB/s eta 0:00:01[K     |██████████████████▍             | 1.2 MB 5.7 MB/s eta 0:00:01[K     |██████████████████▌             | 1.2 MB 5.7 MB/s eta 0:00:01[K     |██████████████████▋             | 1.2 MB 5.7 MB/s eta 0:00:01[K     |██████████████████▉             | 1.2 MB 5.7 MB/s eta 0:00:01[K     |███████████████████             | 1.2 MB 5.7 MB/s eta 0:00:01[K     |███████████████████▏            | 1.3 MB 5.7 MB/s eta 0:00:01[K     |███████████████████▎            | 1.3 MB 5.7 MB/s eta 0:00:01[K     |███████████████████▍            | 1.3 MB 5.7 MB/s eta 0:00:01[K     |███████████████████▋            | 1.3 MB 5.7 MB/s eta 0:00:01[K     |███████████████████▊            | 1.3 MB 5.7 MB/s eta 0:00:01[K     |████████████████████            | 1.3 MB 5.7 MB/s eta 0:00:01[K     |████████████████████            | 1.3 MB 5.7 MB/s eta 0:00:01[K     |████████████████████▏           | 1.3 MB 5.7 MB/s eta 0:00:01[K     |████████████████████▍           | 1.3 MB 5.7 MB/s eta 0:00:01[K     |████████████████████▌           | 1.4 MB 5.7 MB/s eta 0:00:01[K     |████████████████████▊           | 1.4 MB 5.7 MB/s eta 0:00:01[K     |████████████████████▉           | 1.4 MB 5.7 MB/s eta 0:00:01[K     |█████████████████████           | 1.4 MB 5.7 MB/s eta 0:00:01[K     |█████████████████████▏          | 1.4 MB 5.7 MB/s eta 0:00:01[K     |█████████████████████▎          | 1.4 MB 5.7 MB/s eta 0:00:01[K     |█████████████████████▌          | 1.4 MB 5.7 MB/s eta 0:00:01[K     |█████████████████████▋          | 1.4 MB 5.7 MB/s eta 0:00:01[K     |█████████████████████▊          | 1.4 MB 5.7 MB/s eta 0:00:01[K     |██████████████████████          | 1.4 MB 5.7 MB/s eta 0:00:01[K     |██████████████████████          | 1.5 MB 5.7 MB/s eta 0:00:01[K     |██████████████████████▎         | 1.5 MB 5.7 MB/s eta 0:00:01[K     |██████████████████████▍         | 1.5 MB 5.7 MB/s eta 0:00:01[K     |██████████████████████▌         | 1.5 MB 5.7 MB/s eta 0:00:01[K     |██████████████████████▊         | 1.5 MB 5.7 MB/s eta 0:00:01[K     |██████████████████████▉         | 1.5 MB 5.7 MB/s eta 0:00:01[K     |███████████████████████         | 1.5 MB 5.7 MB/s eta 0:00:01[K     |███████████████████████▏        | 1.5 MB 5.7 MB/s eta 0:00:01[K     |███████████████████████▎        | 1.5 MB 5.7 MB/s eta 0:00:01[K     |███████████████████████▌        | 1.5 MB 5.7 MB/s eta 0:00:01[K     |███████████████████████▋        | 1.6 MB 5.7 MB/s eta 0:00:01[K     |███████████████████████▉        | 1.6 MB 5.7 MB/s eta 0:00:01[K     |████████████████████████        | 1.6 MB 5.7 MB/s eta 0:00:01[K     |████████████████████████        | 1.6 MB 5.7 MB/s eta 0:00:01[K     |████████████████████████▎       | 1.6 MB 5.7 MB/s eta 0:00:01[K     |████████████████████████▍       | 1.6 MB 5.7 MB/s eta 0:00:01[K     |████████████████████████▋       | 1.6 MB 5.7 MB/s eta 0:00:01[K     |████████████████████████▊       | 1.6 MB 5.7 MB/s eta 0:00:01[K     |████████████████████████▉       | 1.6 MB 5.7 MB/s eta 0:00:01[K     |█████████████████████████       | 1.6 MB 5.7 MB/s eta 0:00:01[K     |█████████████████████████▏      | 1.7 MB 5.7 MB/s eta 0:00:01[K     |█████████████████████████▍      | 1.7 MB 5.7 MB/s eta 0:00:01[K     |█████████████████████████▌      | 1.7 MB 5.7 MB/s eta 0:00:01[K     |█████████████████████████▋      | 1.7 MB 5.7 MB/s eta 0:00:01[K     |█████████████████████████▉      | 1.7 MB 5.7 MB/s eta 0:00:01[K     |██████████████████████████      | 1.7 MB 5.7 MB/s eta 0:00:01[K     |██████████████████████████▏     | 1.7 MB 5.7 MB/s eta 0:00:01[K     |██████████████████████████▎     | 1.7 MB 5.7 MB/s eta 0:00:01[K     |██████████████████████████▍     | 1.7 MB 5.7 MB/s eta 0:00:01[K     |██████████████████████████▋     | 1.8 MB 5.7 MB/s eta 0:00:01[K     |██████████████████████████▊     | 1.8 MB 5.7 MB/s eta 0:00:01[K     |███████████████████████████     | 1.8 MB 5.7 MB/s eta 0:00:01[K     |███████████████████████████     | 1.8 MB 5.7 MB/s eta 0:00:01[K     |███████████████████████████▏    | 1.8 MB 5.7 MB/s eta 0:00:01[K     |███████████████████████████▍    | 1.8 MB 5.7 MB/s eta 0:00:01[K     |███████████████████████████▌    | 1.8 MB 5.7 MB/s eta 0:00:01[K     |███████████████████████████▊    | 1.8 MB 5.7 MB/s eta 0:00:01[K     |███████████████████████████▉    | 1.8 MB 5.7 MB/s eta 0:00:01[K     |████████████████████████████    | 1.8 MB 5.7 MB/s eta 0:00:01[K     |████████████████████████████▏   | 1.9 MB 5.7 MB/s eta 0:00:01[K     |████████████████████████████▎   | 1.9 MB 5.7 MB/s eta 0:00:01[K     |████████████████████████████▌   | 1.9 MB 5.7 MB/s eta 0:00:01[K     |████████████████████████████▋   | 1.9 MB 5.7 MB/s eta 0:00:01[K     |████████████████████████████▊   | 1.9 MB 5.7 MB/s eta 0:00:01[K     |█████████████████████████████   | 1.9 MB 5.7 MB/s eta 0:00:01[K     |█████████████████████████████   | 1.9 MB 5.7 MB/s eta 0:00:01[K     |█████████████████████████████▎  | 1.9 MB 5.7 MB/s eta 0:00:01[K     |█████████████████████████████▍  | 1.9 MB 5.7 MB/s eta 0:00:01[K     |█████████████████████████████▌  | 1.9 MB 5.7 MB/s eta 0:00:01[K     |█████████████████████████████▊  | 2.0 MB 5.7 MB/s eta 0:00:01[K     |█████████████████████████████▉  | 2.0 MB 5.7 MB/s eta 0:00:01[K     |██████████████████████████████  | 2.0 MB 5.7 MB/s eta 0:00:01[K     |██████████████████████████████▏ | 2.0 MB 5.7 MB/s eta 0:00:01[K     |██████████████████████████████▎ | 2.0 MB 5.7 MB/s eta 0:00:01[K     |██████████████████████████████▌ | 2.0 MB 5.7 MB/s eta 0:00:01[K     |██████████████████████████████▋ | 2.0 MB 5.7 MB/s eta 0:00:01[K     |██████████████████████████████▉ | 2.0 MB 5.7 MB/s eta 0:00:01[K     |███████████████████████████████ | 2.0 MB 5.7 MB/s eta 0:00:01[K     |███████████████████████████████ | 2.0 MB 5.7 MB/s eta 0:00:01[K     |███████████████████████████████▎| 2.1 MB 5.7 MB/s eta 0:00:01[K     |███████████████████████████████▍| 2.1 MB 5.7 MB/s eta 0:00:01[K     |███████████████████████████████▋| 2.1 MB 5.7 MB/s eta 0:00:01[K     |███████████████████████████████▊| 2.1 MB 5.7 MB/s eta 0:00:01[K     |███████████████████████████████▉| 2.1 MB 5.7 MB/s eta 0:00:01[K     |████████████████████████████████| 2.1 MB 5.7 MB/s 
[?25hInstalling collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.0.2
    Not uninstalling pip at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'pip'. No files were found to uninstall.
Successfully installed pip-23.3.1
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: direct-redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct-redis) (3.4.1)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4_engman/m00022211/m00022211_q4_t0.sh
/platform/source/s01/v4_engman/m00022211/m00022211_q4_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4_engman/m00022211/m00022211_q4_t0.sh: line 7: sudo: command not found
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRunning /platform/source/s01/v4_engman/m00022211/m00022211_q5_t0.sh
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRequirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRequirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRequirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRunning /platform/source/s01/v4_engman/m00022211/m00022211_q6_t0.sh
/platform/source/s01/v4_engman/m00022211/m00022211_q6_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4_engman/m00022211/m00022211_q6_t0.sh: line 7: sudo: command not found
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRunning /platform/source/s01/v4_engman/m00022211/m00022211_q7_t0.sh
0% [Working]            Hit:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease
0% [Working]0% [Waiting for headers]                        Hit:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease
                        0% [Working]0% [Waiting for headers]                        Hit:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease
                        0% [Working]0% [Waiting for headers]                        Hit:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease
                        0% [Working]20% [Working]             Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Building dependency tree... 0%Building dependency tree... 0%Building dependency tree... 50%Building dependency tree... 50%Building dependency tree       
Reading state information... 0%Reading state information... 0%Reading state information... Done
python3 is already the newest version (3.8.2-0ubuntu2).
python3-pip is already the newest version (20.0.2-5ubuntu1.10).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
[31mERROR: Could not find a version that satisfies the requirement direct_redis>=1.0 (from versions: 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.1.7, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.2.5, 0.2.6, 0.2.7, 0.2.8, 0.2.9, 0.3.0, 0.3.1)[0m[31m
[0m[31mERROR: No matching distribution found for direct_redis>=1.0[0m[31m
[0mRunning /platform/source/s01/v4_engman/m00022211/m00022211_q8_t0.sh
0% [Working]            Hit:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease
0% [Working]0% [Waiting for headers]                        Hit:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease
0% [Waiting for headers]0% [Waiting for headers]                        Hit:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease
                        0% [Working]0% [Waiting for headers]                        Hit:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease
                        0% [Working]20% [Working]             Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Building dependency tree... 0%Building dependency tree... 0%Building dependency tree... 50%Building dependency tree... 50%Building dependency tree       
Reading state information... 0%Reading state information... 0%Reading state information... Done
python3-pip is already the newest version (20.0.2-5ubuntu1.10).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRequirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRequirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRequirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRunning /platform/source/s01/v4_engman/m00022211/m00022211_q9_t0.sh
/platform/source/s01/v4_engman/m00022211/m00022211_q9_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4_engman/m00022211/m00022211_q9_t0.sh: line 7: sudo: command not found
/platform/source/s01/v4_engman/m00022211/m00022211_q9_t0.sh: line 10: sudo: command not found
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: redis in /usr/local/lib/python3.8/dist-packages (3.4.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: direct-redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mpython /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engman/m00022211/m00022211_q10_t0.py /platform/output/s01/v4_engman/m00022211/m00022211_q10_t0.csv /platform/expected/s01/q10.csv
/platform/source/s01/v4_engman/m00022211/m00022211_q10_t0.py:19: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  customer_data = pd.read_sql(mysql_query, mysql_conn)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/sql.py", line 2202, in execute
    cur.execute(sql, *args)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 822, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'tpch.customer' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/platform/source/s01/v4_engman/m00022211/m00022211_q10_t0.py", line 19, in <module>
    customer_data = pd.read_sql(mysql_query, mysql_conn)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/sql.py", line 635, in read_sql
    return pandas_sql.read_query(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/sql.py", line 2266, in read_query
    cursor = self.execute(sql, params)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/sql.py", line 2214, in execute
    raise ex from exc
pandas.errors.DatabaseError: Execution failed on sql '
SELECT n.N_NATIONKEY, n.N_NAME, c.C_CUSTKEY, c.C_NAME, c.C_ACCTBAL,
c.C_ADDRESS, c.C_PHONE, c.C_COMMENT
FROM nation n
JOIN customer c ON n.N_NATIONKEY = c.C_NATIONKEY;
': (1146, "Table 'tpch.customer' doesn't exist")
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engman/m00022211/m00022211_q11_t0.py /platform/output/s01/v4_engman/m00022211/m00022211_q11_t0.csv /platform/expected/s01/q11.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engman/m00022211/m00022211_q11_t0.py", line 28, in <module>
    supplier_df = pd.read_json(redis_conn.get('supplier'))
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engman/m00022211/m00022211_q12_t0.py /platform/output/s01/v4_engman/m00022211/m00022211_q12_t0.csv /platform/expected/s01/q12.csv
>>> Expected ((2, 3))
   HIGH_LINE_COUNT  LOW_LINE_COUNT L_SHIPMODE
0              647             945       MAIL
1              620             943       SHIP

>>> Actual ((0, 3))
Empty DataFrame
Columns: [L_SHIPMODE, high_order_priority_count, low_order_priority_count]
Index: []

Score.fail_wrong_output
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engman/m00022211/m00022211_q13_t0.py /platform/output/s01/v4_engman/m00022211/m00022211_q13_t0.csv /platform/expected/s01/q13.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engman/m00022211/m00022211_q13_t0.py", line 30, in <module>
    customer_df = pd.read_json(redis_connection.get('customer'), orient='records')
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engman/m00022211/m00022211_q14_t0.py /platform/output/s01/v4_engman/m00022211/m00022211_q14_t0.csv /platform/expected/s01/q14.csv
>>> Expected ((1, 1))
   PROMO_REVENUE
0      16.283856

>>> Actual ((1, 1))
   REVENUE
0        0

Head row similarity: 0.6666666666666666
Score.fail_wrong_output
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engman/m00022211/m00022211_q15_t0.py /platform/output/s01/v4_engman/m00022211/m00022211_q15_t0.csv /platform/expected/s01/q15.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engman/m00022211/m00022211_q15_t0.py", line 46, in <module>
    merged_df = pd.merge(supplier_df, lineitem_df, left_on='S_SUPPKEY', right_on='_id')
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/reshape/merge.py", line 148, in merge
    op = _MergeOperation(
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/reshape/merge.py", line 737, in __init__
    ) = self._get_merge_keys()
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/reshape/merge.py", line 1203, in _get_merge_keys
    right_keys.append(right._get_label_or_level_values(rk))
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/generic.py", line 1778, in _get_label_or_level_values
    raise KeyError(key)
KeyError: '_id'
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engman/m00022211/m00022211_q16_t0.py /platform/output/s01/v4_engman/m00022211/m00022211_q16_t0.csv /platform/expected/s01/q16.csv
/platform/source/s01/v4_engman/m00022211/m00022211_q16_t0.py:20: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  parts_df = pd.read_sql(part_query, mysql_connection)
>>> Expected ((2762, 4))
       P_BRAND  P_SIZE                  P_TYPE  SUPPLIER_CNT
0     Brand#14      45   SMALL ANODIZED NICKEL            12
1     Brand#22      19   SMALL BURNISHED BRASS            12
2     Brand#25      14   PROMO POLISHED COPPER            12
3     Brand#35      45    LARGE ANODIZED STEEL            12
4     Brand#35       9    PROMO BRUSHED COPPER            12
...        ...     ...                     ...           ...
2757  Brand#22      19     PROMO BRUSHED BRASS             3
2758  Brand#22      14  PROMO BURNISHED COPPER             3
2759  Brand#43      23  STANDARD BRUSHED BRASS             3
2760  Brand#44       9  MEDIUM ANODIZED NICKEL             3
2761  Brand#53      49  MEDIUM BURNISHED BRASS             3

[2762 rows x 4 columns]

>>> Actual ((2762, 4))
       P_BRAND  P_SIZE                    P_TYPE  SUPPLIER_COUNT
0     Brand#14      45     SMALL ANODIZED NICKEL              12
1     Brand#22      19     SMALL BURNISHED BRASS              12
2     Brand#25      14     PROMO POLISHED COPPER              12
3     Brand#35      45      LARGE ANODIZED STEEL              12
4     Brand#35       9      PROMO BRUSHED COPPER              12
...        ...     ...                       ...             ...
2757  Brand#55      19  STANDARD POLISHED COPPER               4
2758  Brand#55      36  STANDARD POLISHED COPPER               4
2759  Brand#55      14  STANDARD POLISHED NICKEL               4
2760  Brand#55       9   STANDARD POLISHED STEEL               4
2761  Brand#55      36   STANDARD POLISHED STEEL               4

[2762 rows x 4 columns]

Head row similarity: 0.5051870480980823
Score.fail_wrong_output
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engman/m00022211/m00022211_q17_t0.py /platform/output/s01/v4_engman/m00022211/m00022211_q17_t0.csv /platform/expected/s01/q17.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engman/m00022211/m00022211_q17_t0.py", line 37, in <module>
    mysql_conn.close()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 409, in close
    raise err.Error("Already closed")
pymysql.err.Error: Already closed
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engman/m00022211/m00022211_q18_t0.py /platform/output/s01/v4_engman/m00022211/m00022211_q18_t0.csv /platform/expected/s01/q18.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engman/m00022211/m00022211_q18_t0.py", line 55, in <module>
    customers_df = pd.read_json(customer_data)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engman/m00022211/m00022211_q19_t0.py /platform/output/s01/v4_engman/m00022211/m00022211_q19_t0.csv /platform/expected/s01/q19.csv
>>> Expected ((1, 1))
      REVENUE
0  168597.286

>>> Actual ((1, 1))
       REVENUE
0  468171.7745

Head row similarity: 0.75
Score.success_approx
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engman/m00022211/m00022211_q1_t0.py /platform/output/s01/v4_engman/m00022211/m00022211_q1_t0.csv /platform/expected/s01/q1.csv
>>> Expected ((4, 10))
   AVG_DISC     AVG_PRICE    AVG_QTY  COUNT_ORDER L_LINESTATUS L_RETURNFLAG  SUM_BASE_PRICE    SUM_CHARGE  SUM_DISC_PRICE  SUM_QTY
0  0.050145  36002.123829  25.537587       147790            F            A    5.320754e+09  5.256751e+09    5.054096e+09  3774200
1  0.049394  35521.326916  25.300664         3765            F            N    1.337378e+08  1.322863e+08    1.271324e+08    95257
2  0.050096  36000.924688  25.545538       292000            O            N    1.051227e+10  1.038558e+10    9.986238e+09  7459297
3  0.049989  35994.029214  25.525944       148301            F            R    5.337951e+09  5.274406e+09    5.071819e+09  3785523

>>> Actual ((0, 10))
Empty DataFrame
Columns: [AVG_DISC, AVG_PRICE, AVG_QTY, COUNT_ORDER, LINESTATUS, RETURNFLAG, SUM_BASE_PRICE, SUM_CHARGE, SUM_DISC_PRICE, SUM_QTY]
Index: []

Score.fail_wrong_output
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engman/m00022211/m00022211_q20_t0.py /platform/output/s01/v4_engman/m00022211/m00022211_q20_t0.csv /platform/expected/s01/q20.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engman/m00022211/m00022211_q20_t0.py", line 30, in <module>
    cursor.execute(mysql_query)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 822, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'tpch.lineitem' doesn't exist")
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engman/m00022211/m00022211_q21_t0.py /platform/output/s01/v4_engman/m00022211/m00022211_q21_t0.csv /platform/expected/s01/q21.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engman/m00022211/m00022211_q21_t0.py", line 39, in <module>
    supplier_df = pd.DataFrame(eval(redis_db.get("supplier")))
TypeError: eval() arg 1 must be a string, bytes or code object
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engman/m00022211/m00022211_q22_t0.py /platform/output/s01/v4_engman/m00022211/m00022211_q22_t0.csv /platform/expected/s01/q22.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engman/m00022211/m00022211_q22_t0.py", line 18, in <module>
    customers_df = pd.read_json(customers_data)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engman/m00022211/m00022211_q2_t0.py /platform/output/s01/v4_engman/m00022211/m00022211_q2_t0.csv /platform/expected/s01/q2.csv
/platform/source/s01/v4_engman/m00022211/m00022211_q2_t0.py:10: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql(query, connection)
Traceback (most recent call last):
  File "/platform/source/s01/v4_engman/m00022211/m00022211_q2_t0.py", line 57, in <module>
    main()
  File "/platform/source/s01/v4_engman/m00022211/m00022211_q2_t0.py", line 43, in main
    suppliers_parts_europe = pd.merge(partsupp_df, suppliers_in_europe, on='S_SUPPKEY', how='inner')
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/reshape/merge.py", line 148, in merge
    op = _MergeOperation(
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/reshape/merge.py", line 737, in __init__
    ) = self._get_merge_keys()
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/reshape/merge.py", line 1221, in _get_merge_keys
    left_keys.append(left._get_label_or_level_values(lk))
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/generic.py", line 1778, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'S_SUPPKEY'
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engman/m00022211/m00022211_q3_t0.py /platform/output/s01/v4_engman/m00022211/m00022211_q3_t0.csv /platform/expected/s01/q3.csv
Score.fail_timeout
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engman/m00022211/m00022211_q4_t0.py /platform/output/s01/v4_engman/m00022211/m00022211_q4_t0.csv /platform/expected/s01/q4.csv
Score.fail_timeout
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engman/m00022211/m00022211_q5_t0.py /platform/output/s01/v4_engman/m00022211/m00022211_q5_t0.csv /platform/expected/s01/q5.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engman/m00022211/m00022211_q5_t0.py", line 49, in <module>
    suppliers_df = pd.read_json(redis_conn.get('supplier').decode('utf-8'))
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'decode'
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engman/m00022211/m00022211_q6_t0.py /platform/output/s01/v4_engman/m00022211/m00022211_q6_t0.csv /platform/expected/s01/q6.csv
>>> Expected ((1, 1))
        REVENUE
0  7.115407e+06

>>> Actual ((0, 1))
Empty DataFrame
Columns: [REVENUE]
Index: []

Score.fail_wrong_output
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engman/m00022211/m00022211_q7_t0.py /platform/output/s01/v4_engman/m00022211/m00022211_q7_t0.csv /platform/expected/s01/q7.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engman/m00022211/m00022211_q7_t0.py", line 48, in <module>
    supplier_df = pd.read_json(redis_conn.get('supplier'))
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engman/m00022211/m00022211_q8_t0.py /platform/output/s01/v4_engman/m00022211/m00022211_q8_t0.csv /platform/expected/s01/q8.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engman/m00022211/m00022211_q8_t0.py", line 76, in <module>
    orders_df['Revenue'] = orders_df['L_EXTENDEDPRICE'] * (1 - orders_df['L_DISCOUNT'])
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/frame.py", line 3761, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/indexes/range.py", line 349, in get_loc
    raise KeyError(key)
KeyError: 'L_EXTENDEDPRICE'
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engman/m00022211/m00022211_q9_t0.py /platform/output/s01/v4_engman/m00022211/m00022211_q9_t0.csv /platform/expected/s01/q9.csv
/platform/source/s01/v4_engman/m00022211/m00022211_q9_t0.py:22: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  mysql_df = pd.read_sql(mysql_query, con=mysql_conn)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/sql.py", line 2202, in execute
    cur.execute(sql, *args)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 822, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'tpch.lineitem' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/platform/source/s01/v4_engman/m00022211/m00022211_q9_t0.py", line 22, in <module>
    mysql_df = pd.read_sql(mysql_query, con=mysql_conn)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/sql.py", line 635, in read_sql
    return pandas_sql.read_query(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/sql.py", line 2266, in read_query
    cursor = self.execute(sql, params)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/sql.py", line 2214, in execute
    raise ex from exc
pandas.errors.DatabaseError: Execution failed on sql '
SELECT p.P_TYPE, n.N_NAME, n.N_NATIONKEY,
    YEAR(o.O_ORDERDATE) AS o_year, 
    SUM(l.L_EXTENDEDPRICE * (1 - l.L_DISCOUNT) - ps.PS_SUPPLYCOST * l.L_QUANTITY) AS profit
FROM part p
JOIN lineitem l ON p.P_PARTKEY = l.L_PARTKEY
JOIN orders o ON l.L_ORDERKEY = o.O_ORDERKEY
JOIN supplier s ON l.L_SUPPKEY = s.S_SUPPKEY
JOIN nation n ON s.S_NATIONKEY = n.N_NATIONKEY
JOIN partsupp ps ON l.L_PARTKEY = ps.PS_PARTKEY AND l.L_SUPPKEY = ps.PS_SUPPKEY
WHERE p.P_NAME LIKE '%dim%'
GROUP BY p.P_TYPE, n.N_NAME, n.N_NATIONKEY, o_year
ORDER BY n.N_NAME ASC, o_year DESC;
': (1146, "Table 'tpch.lineitem' doesn't exist")
Score.fail_execute
