Using MAPPING_STR=11100022, VERSION_DIR=v4_enggpt
Running /platform/source/s01/v4_enggpt/m11100022/m11100022_q10_t0.sh
/platform/source/s01/v4_enggpt/m11100022/m11100022_q10_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4_enggpt/m11100022/m11100022_q10_t0.sh: line 5: sudo: command not found
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4_enggpt/m11100022/m11100022_q11_t0.sh
/platform/source/s01/v4_enggpt/m11100022/m11100022_q11_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4_enggpt/m11100022/m11100022_q11_t0.sh: line 5: sudo: command not found
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Running /platform/source/s01/v4_enggpt/m11100022/m11100022_q12_t0.sh
/platform/source/s01/v4_enggpt/m11100022/m11100022_q12_t0.sh: line 6: sudo: command not found
/platform/source/s01/v4_enggpt/m11100022/m11100022_q12_t0.sh: line 9: sudo: command not found
/platform/source/s01/v4_enggpt/m11100022/m11100022_q12_t0.sh: line 12: sudo: command not found
/platform/source/s01/v4_enggpt/m11100022/m11100022_q12_t0.sh: line 15: sudo: command not found
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: redis in /usr/local/lib/python3.8/dist-packages (3.4.1)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4_enggpt/m11100022/m11100022_q13_t0.sh

0% [Working]
            
Err:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease
  Could not resolve 'ports.ubuntu.com'

0% [Working]
            
Err:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease
  Could not resolve 'ports.ubuntu.com'

0% [Working]
            
Err:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease
  Could not resolve 'ports.ubuntu.com'

0% [Working]
            
Err:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease
  Could not resolve 'ports.ubuntu.com'

0% [Working]
            

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 31%

Reading package lists... 60%

Reading package lists... 60%

Reading package lists... 61%

Reading package lists... 61%

Reading package lists... 74%

Reading package lists... 74%

Reading package lists... 75%

Reading package lists... 75%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... Done

W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/focal/InRelease  Could not resolve 'ports.ubuntu.com'
W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/focal-updates/InRelease  Could not resolve 'ports.ubuntu.com'
W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/focal-backports/InRelease  Could not resolve 'ports.ubuntu.com'
W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/focal-security/InRelease  Could not resolve 'ports.ubuntu.com'
W: Some index files failed to download. They have been ignored, or old ones used instead.

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 60%

Reading package lists... 60%

Reading package lists... 61%

Reading package lists... 61%

Reading package lists... 74%

Reading package lists... 74%

Reading package lists... 75%

Reading package lists... 75%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... Done


Building dependency tree... 0%

Building dependency tree... 0%

Building dependency tree... 50%

Building dependency tree... 50%

Building dependency tree       


Reading state information... 0%

Reading state information... 0%

Reading state information... Done

python3-pip is already the newest version (20.0.2-5ubuntu1.10).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4_enggpt/m11100022/m11100022_q14_t0.sh
/platform/source/s01/v4_enggpt/m11100022/m11100022_q14_t0.sh: line 5: sudo: command not found
/platform/source/s01/v4_enggpt/m11100022/m11100022_q14_t0.sh: line 6: sudo: command not found
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Collecting git+https://github.com/RedisLabsModules/direct_redis.git
  Cloning https://github.com/RedisLabsModules/direct_redis.git to /tmp/pip-req-build-3czvtwhm
  Running command git clone -q https://github.com/RedisLabsModules/direct_redis.git /tmp/pip-req-build-3czvtwhm
[31m  ERROR: Error [Errno 2] No such file or directory: 'git' while executing command git clone -q https://github.com/RedisLabsModules/direct_redis.git /tmp/pip-req-build-3czvtwhm[0m
[31mERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?[0m
Running /platform/source/s01/v4_enggpt/m11100022/m11100022_q15_t0.sh
Running /platform/source/s01/v4_enggpt/m11100022/m11100022_q16_t0.sh

0% [Working]
            
Err:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease
  Could not resolve 'ports.ubuntu.com'

0% [Working]
            
Err:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease
  Could not resolve 'ports.ubuntu.com'

0% [Working]
            
Err:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease
  Could not resolve 'ports.ubuntu.com'

0% [Working]
            
Err:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease
  Could not resolve 'ports.ubuntu.com'

0% [Working]
            

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 60%

Reading package lists... 60%

Reading package lists... 61%

Reading package lists... 61%

Reading package lists... 74%

Reading package lists... 74%

Reading package lists... 75%

Reading package lists... 75%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... Done

W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/focal/InRelease  Could not resolve 'ports.ubuntu.com'
W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/focal-updates/InRelease  Could not resolve 'ports.ubuntu.com'
W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/focal-backports/InRelease  Could not resolve 'ports.ubuntu.com'
W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/focal-security/InRelease  Could not resolve 'ports.ubuntu.com'
W: Some index files failed to download. They have been ignored, or old ones used instead.

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 31%

Reading package lists... 60%

Reading package lists... 60%

Reading package lists... 61%

Reading package lists... 61%

Reading package lists... 66%

Reading package lists... 74%

Reading package lists... 74%

Reading package lists... 75%

Reading package lists... 75%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... Done


Building dependency tree... 0%

Building dependency tree... 0%

Building dependency tree... 50%

Building dependency tree... 50%

Building dependency tree... 56%

Building dependency tree       


Reading state information... 0%

Reading state information... 0%

Reading state information... Done

The following additional packages will be installed:
  libmysqlclient-dev libmysqlclient21 libssl-dev
Suggested packages:
  libssl-doc
The following NEW packages will be installed:
  default-libmysqlclient-dev default-mysql-client libmysqlclient-dev
  libmysqlclient21 libssl-dev
0 upgraded, 5 newly installed, 0 to remove and 0 not upgraded.
Need to get 4325 kB of archives.
After this operation, 25.1 MB of additional disk space will be used.

0% [Working]
            
Ign:1 http://ports.ubuntu.com/ubuntu-ports focal-updates/main arm64 libmysqlclient21 arm64 8.0.35-0ubuntu0.20.04.1

0% [Working]
            
Ign:2 http://ports.ubuntu.com/ubuntu-ports focal-updates/main arm64 libssl-dev arm64 1.1.1f-1ubuntu2.20

0% [Working]
            
Ign:3 http://ports.ubuntu.com/ubuntu-ports focal-updates/main arm64 libmysqlclient-dev arm64 8.0.35-0ubuntu0.20.04.1

0% [Working]
            
Err:4 http://ports.ubuntu.com/ubuntu-ports focal/main arm64 default-libmysqlclient-dev arm64 1.0.5ubuntu2
  Could not resolve 'ports.ubuntu.com'

0% [Working]
            
Err:5 http://ports.ubuntu.com/ubuntu-ports focal/universe arm64 default-mysql-client all 1.0.5ubuntu2
  Could not resolve 'ports.ubuntu.com'

0% [Working]
            
Err:1 http://ports.ubuntu.com/ubuntu-ports focal-updates/main arm64 libmysqlclient21 arm64 8.0.35-0ubuntu0.20.04.1
  Could not resolve 'ports.ubuntu.com'

0% [Working]
            
Err:2 http://ports.ubuntu.com/ubuntu-ports focal-updates/main arm64 libssl-dev arm64 1.1.1f-1ubuntu2.20
  Could not resolve 'ports.ubuntu.com'

0% [Working]
            
Err:3 http://ports.ubuntu.com/ubuntu-ports focal-updates/main arm64 libmysqlclient-dev arm64 8.0.35-0ubuntu0.20.04.1
  Could not resolve 'ports.ubuntu.com'

0% [Working]
            
E: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/pool/main/m/mysql-8.0/libmysqlclient21_8.0.35-0ubuntu0.20.04.1_arm64.deb  Could not resolve 'ports.ubuntu.com'
E: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/pool/main/o/openssl/libssl-dev_1.1.1f-1ubuntu2.20_arm64.deb  Could not resolve 'ports.ubuntu.com'
E: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/pool/main/m/mysql-8.0/libmysqlclient-dev_8.0.35-0ubuntu0.20.04.1_arm64.deb  Could not resolve 'ports.ubuntu.com'
E: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/pool/main/m/mysql-defaults/default-libmysqlclient-dev_1.0.5ubuntu2_arm64.deb  Could not resolve 'ports.ubuntu.com'
E: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/pool/universe/m/mysql-defaults/default-mysql-client_1.0.5ubuntu2_all.deb  Could not resolve 'ports.ubuntu.com'
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 32%

Reading package lists... 60%

Reading package lists... 60%

Reading package lists... 61%

Reading package lists... 61%

Reading package lists... 67%

Reading package lists... 74%

Reading package lists... 74%

Reading package lists... 75%

Reading package lists... 75%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... Done


Building dependency tree... 0%

Building dependency tree... 0%

Building dependency tree... 50%

Building dependency tree... 50%

Building dependency tree... 57%

Building dependency tree       


Reading state information... 0%

Reading state information... 0%

Reading state information... Done

The following additional packages will be installed:
  libboost-filesystem1.71.0 libboost-iostreams1.71.0
  libboost-program-options1.71.0 libgoogle-perftools4 libpcap0.8 libpcrecpp0v5
  libsnappy1v5 libstemmer0d libtcmalloc-minimal4 libyaml-cpp0.6 mongo-tools
The following NEW packages will be installed:
  libboost-filesystem1.71.0 libboost-iostreams1.71.0
  libboost-program-options1.71.0 libgoogle-perftools4 libpcap0.8 libpcrecpp0v5
  libsnappy1v5 libstemmer0d libtcmalloc-minimal4 libyaml-cpp0.6 mongo-tools
  mongodb-clients
0 upgraded, 12 newly installed, 0 to remove and 0 not upgraded.
Need to get 30.3 MB of archives.
After this operation, 144 MB of additional disk space will be used.

0% [Working]
            
Err:1 http://ports.ubuntu.com/ubuntu-ports focal/main arm64 libpcap0.8 arm64 1.9.1-3
  Could not resolve 'ports.ubuntu.com'

0% [Working]
            
Err:2 http://ports.ubuntu.com/ubuntu-ports focal/main arm64 libboost-filesystem1.71.0 arm64 1.71.0-6ubuntu6
  Could not resolve 'ports.ubuntu.com'

0% [Working]
            
Err:3 http://ports.ubuntu.com/ubuntu-ports focal/main arm64 libboost-iostreams1.71.0 arm64 1.71.0-6ubuntu6
  Could not resolve 'ports.ubuntu.com'

0% [Working]
            
Err:4 http://ports.ubuntu.com/ubuntu-ports focal/main arm64 libboost-program-options1.71.0 arm64 1.71.0-6ubuntu6
  Could not resolve 'ports.ubuntu.com'

0% [Working]
            
Err:5 http://ports.ubuntu.com/ubuntu-ports focal/main arm64 libtcmalloc-minimal4 arm64 2.7-1ubuntu2
  Could not resolve 'ports.ubuntu.com'

0% [Working]
            
Err:6 http://ports.ubuntu.com/ubuntu-ports focal/main arm64 libgoogle-perftools4 arm64 2.7-1ubuntu2
  Could not resolve 'ports.ubuntu.com'

0% [Working]
            
Ign:7 http://ports.ubuntu.com/ubuntu-ports focal-updates/main arm64 libpcrecpp0v5 arm64 2:8.39-12ubuntu0.1

0% [Working]
            
Err:8 http://ports.ubuntu.com/ubuntu-ports focal/main arm64 libstemmer0d arm64 0+svn585-2
  Could not resolve 'ports.ubuntu.com'

0% [Working]
            
Err:9 http://ports.ubuntu.com/ubuntu-ports focal/main arm64 libyaml-cpp0.6 arm64 0.6.2-4ubuntu1
  Could not resolve 'ports.ubuntu.com'

0% [Working]
            
Err:10 http://ports.ubuntu.com/ubuntu-ports focal/universe arm64 mongo-tools arm64 3.6.3-0ubuntu1
  Could not resolve 'ports.ubuntu.com'

0% [Working]
            
Err:11 http://ports.ubuntu.com/ubuntu-ports focal/main arm64 libsnappy1v5 arm64 1.1.8-1build1
  Could not resolve 'ports.ubuntu.com'

0% [Working]
            
Ign:12 http://ports.ubuntu.com/ubuntu-ports focal-updates/universe arm64 mongodb-clients arm64 1:3.6.9+really3.6.8+90~g8e540c0b6d-0ubuntu5.3

0% [Working]
            
Err:7 http://ports.ubuntu.com/ubuntu-ports focal-updates/main arm64 libpcrecpp0v5 arm64 2:8.39-12ubuntu0.1
  Could not resolve 'ports.ubuntu.com'

0% [Working]
            
Err:12 http://ports.ubuntu.com/ubuntu-ports focal-updates/universe arm64 mongodb-clients arm64 1:3.6.9+really3.6.8+90~g8e540c0b6d-0ubuntu5.3
  Could not resolve 'ports.ubuntu.com'

0% [Working]
            
E: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/pool/main/libp/libpcap/libpcap0.8_1.9.1-3_arm64.deb  Could not resolve 'ports.ubuntu.com'
E: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/pool/main/b/boost1.71/libboost-filesystem1.71.0_1.71.0-6ubuntu6_arm64.deb  Could not resolve 'ports.ubuntu.com'
E: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/pool/main/b/boost1.71/libboost-iostreams1.71.0_1.71.0-6ubuntu6_arm64.deb  Could not resolve 'ports.ubuntu.com'
E: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/pool/main/b/boost1.71/libboost-program-options1.71.0_1.71.0-6ubuntu6_arm64.deb  Could not resolve 'ports.ubuntu.com'
E: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/pool/main/g/google-perftools/libtcmalloc-minimal4_2.7-1ubuntu2_arm64.deb  Could not resolve 'ports.ubuntu.com'
E: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/pool/main/g/google-perftools/libgoogle-perftools4_2.7-1ubuntu2_arm64.deb  Could not resolve 'ports.ubuntu.com'
E: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/pool/main/p/pcre3/libpcrecpp0v5_8.39-12ubuntu0.1_arm64.deb  Could not resolve 'ports.ubuntu.com'
E: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/pool/main/s/snowball/libstemmer0d_0+svn585-2_arm64.deb  Could not resolve 'ports.ubuntu.com'
E: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/pool/main/y/yaml-cpp/libyaml-cpp0.6_0.6.2-4ubuntu1_arm64.deb  Could not resolve 'ports.ubuntu.com'
E: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/pool/universe/m/mongo-tools/mongo-tools_3.6.3-0ubuntu1_arm64.deb  Could not resolve 'ports.ubuntu.com'
E: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/pool/main/s/snappy/libsnappy1v5_1.1.8-1build1_arm64.deb  Could not resolve 'ports.ubuntu.com'
E: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/pool/universe/m/mongodb/mongodb-clients_3.6.9+really3.6.8+90~g8e540c0b6d-0ubuntu5.3_arm64.deb  Could not resolve 'ports.ubuntu.com'
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 31%

Reading package lists... 60%

Reading package lists... 60%

Reading package lists... 61%

Reading package lists... 61%

Reading package lists... 64%

Reading package lists... 74%

Reading package lists... 74%

Reading package lists... 75%

Reading package lists... 75%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... Done


Building dependency tree... 0%

Building dependency tree... 0%

Building dependency tree... 50%

Building dependency tree... 50%

Building dependency tree... 53%

Building dependency tree       


Reading state information... 0%

Reading state information... 0%

Reading state information... Done

python3-pip is already the newest version (20.0.2-5ubuntu1.10).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
[33mWARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xffffb0461d90>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/pip/[0m
[33mWARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xffffb0461700>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/pip/[0m
[33mWARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xffffb0461730>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/pip/[0m
[33mWARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xffffb0461430>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/pip/[0m
[33mWARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xffffb04613a0>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/pip/[0m
Collecting pip
  Downloading pip-23.3.1-py3-none-any.whl (2.1 MB)
[?25l
[K     |▏                               | 10 kB 9.1 MB/s eta 0:00:01
[K     |▎                               | 20 kB 7.8 MB/s eta 0:00:01
[K     |▌                               | 30 kB 11.3 MB/s eta 0:00:01
[K     |▋                               | 40 kB 5.2 MB/s eta 0:00:01
[K     |▊                               | 51 kB 4.4 MB/s eta 0:00:01
[K     |█                               | 61 kB 5.2 MB/s eta 0:00:01
[K     |█                               | 71 kB 5.9 MB/s eta 0:00:01
[K     |█▎                              | 81 kB 5.7 MB/s eta 0:00:01
[K     |█▍                              | 92 kB 6.4 MB/s eta 0:00:01
[K     |█▌                              | 102 kB 7.0 MB/s eta 0:00:01
[K     |█▊                              | 112 kB 7.0 MB/s eta 0:00:01
[K     |█▉                              | 122 kB 7.0 MB/s eta 0:00:01
[K     |██                              | 133 kB 7.0 MB/s eta 0:00:01
[K     |██▏                             | 143 kB 7.0 MB/s eta 0:00:01
[K     |██▎                             | 153 kB 7.0 MB/s eta 0:00:01
[K     |██▌                             | 163 kB 7.0 MB/s eta 0:00:01
[K     |██▋                             | 174 kB 7.0 MB/s eta 0:00:01
[K     |██▉                             | 184 kB 7.0 MB/s eta 0:00:01
[K     |███                             | 194 kB 7.0 MB/s eta 0:00:01
[K     |███                             | 204 kB 7.0 MB/s eta 0:00:01
[K     |███▎                            | 215 kB 7.0 MB/s eta 0:00:01
[K     |███▍                            | 225 kB 7.0 MB/s eta 0:00:01
[K     |███▋                            | 235 kB 7.0 MB/s eta 0:00:01
[K     |███▊                            | 245 kB 7.0 MB/s eta 0:00:01
[K     |███▉                            | 256 kB 7.0 MB/s eta 0:00:01
[K     |████                            | 266 kB 7.0 MB/s eta 0:00:01
[K     |████▏                           | 276 kB 7.0 MB/s eta 0:00:01
[K     |████▍                           | 286 kB 7.0 MB/s eta 0:00:01
[K     |████▌                           | 296 kB 7.0 MB/s eta 0:00:01
[K     |████▋                           | 307 kB 7.0 MB/s eta 0:00:01
[K     |████▉                           | 317 kB 7.0 MB/s eta 0:00:01
[K     |█████                           | 327 kB 7.0 MB/s eta 0:00:01
[K     |█████▏                          | 337 kB 7.0 MB/s eta 0:00:01
[K     |█████▎                          | 348 kB 7.0 MB/s eta 0:00:01
[K     |█████▍                          | 358 kB 7.0 MB/s eta 0:00:01
[K     |█████▋                          | 368 kB 7.0 MB/s eta 0:00:01
[K     |█████▊                          | 378 kB 7.0 MB/s eta 0:00:01
[K     |██████                          | 389 kB 7.0 MB/s eta 0:00:01
[K     |██████                          | 399 kB 7.0 MB/s eta 0:00:01
[K     |██████▏                         | 409 kB 7.0 MB/s eta 0:00:01
[K     |██████▍                         | 419 kB 7.0 MB/s eta 0:00:01
[K     |██████▌                         | 430 kB 7.0 MB/s eta 0:00:01
[K     |██████▊                         | 440 kB 7.0 MB/s eta 0:00:01
[K     |██████▉                         | 450 kB 7.0 MB/s eta 0:00:01
[K     |███████                         | 460 kB 7.0 MB/s eta 0:00:01
[K     |███████▏                        | 471 kB 7.0 MB/s eta 0:00:01
[K     |███████▎                        | 481 kB 7.0 MB/s eta 0:00:01
[K     |███████▌                        | 491 kB 7.0 MB/s eta 0:00:01
[K     |███████▋                        | 501 kB 7.0 MB/s eta 0:00:01
[K     |███████▊                        | 512 kB 7.0 MB/s eta 0:00:01
[K     |████████                        | 522 kB 7.0 MB/s eta 0:00:01
[K     |████████                        | 532 kB 7.0 MB/s eta 0:00:01
[K     |████████▎                       | 542 kB 7.0 MB/s eta 0:00:01
[K     |████████▍                       | 552 kB 7.0 MB/s eta 0:00:01
[K     |████████▌                       | 563 kB 7.0 MB/s eta 0:00:01
[K     |████████▊                       | 573 kB 7.0 MB/s eta 0:00:01
[K     |████████▉                       | 583 kB 7.0 MB/s eta 0:00:01
[K     |█████████                       | 593 kB 7.0 MB/s eta 0:00:01
[K     |█████████▏                      | 604 kB 7.0 MB/s eta 0:00:01
[K     |█████████▎                      | 614 kB 7.0 MB/s eta 0:00:01
[K     |█████████▌                      | 624 kB 7.0 MB/s eta 0:00:01
[K     |█████████▋                      | 634 kB 7.0 MB/s eta 0:00:01
[K     |█████████▉                      | 645 kB 7.0 MB/s eta 0:00:01
[K     |██████████                      | 655 kB 7.0 MB/s eta 0:00:01
[K     |██████████                      | 665 kB 7.0 MB/s eta 0:00:01
[K     |██████████▎                     | 675 kB 7.0 MB/s eta 0:00:01
[K     |██████████▍                     | 686 kB 7.0 MB/s eta 0:00:01
[K     |██████████▋                     | 696 kB 7.0 MB/s eta 0:00:01
[K     |██████████▊                     | 706 kB 7.0 MB/s eta 0:00:01
[K     |██████████▉                     | 716 kB 7.0 MB/s eta 0:00:01
[K     |███████████                     | 727 kB 7.0 MB/s eta 0:00:01
[K     |███████████▏                    | 737 kB 7.0 MB/s eta 0:00:01
[K     |███████████▍                    | 747 kB 7.0 MB/s eta 0:00:01
[K     |███████████▌                    | 757 kB 7.0 MB/s eta 0:00:01
[K     |███████████▋                    | 768 kB 7.0 MB/s eta 0:00:01
[K     |███████████▉                    | 778 kB 7.0 MB/s eta 0:00:01
[K     |████████████                    | 788 kB 7.0 MB/s eta 0:00:01
[K     |████████████▏                   | 798 kB 7.0 MB/s eta 0:00:01
[K     |████████████▎                   | 808 kB 7.0 MB/s eta 0:00:01
[K     |████████████▍                   | 819 kB 7.0 MB/s eta 0:00:01
[K     |████████████▋                   | 829 kB 7.0 MB/s eta 0:00:01
[K     |████████████▊                   | 839 kB 7.0 MB/s eta 0:00:01
[K     |█████████████                   | 849 kB 7.0 MB/s eta 0:00:01
[K     |█████████████                   | 860 kB 7.0 MB/s eta 0:00:01
[K     |█████████████▏                  | 870 kB 7.0 MB/s eta 0:00:01
[K     |█████████████▍                  | 880 kB 7.0 MB/s eta 0:00:01
[K     |█████████████▌                  | 890 kB 7.0 MB/s eta 0:00:01
[K     |█████████████▊                  | 901 kB 7.0 MB/s eta 0:00:01
[K     |█████████████▉                  | 911 kB 7.0 MB/s eta 0:00:01
[K     |██████████████                  | 921 kB 7.0 MB/s eta 0:00:01
[K     |██████████████▏                 | 931 kB 7.0 MB/s eta 0:00:01
[K     |██████████████▎                 | 942 kB 7.0 MB/s eta 0:00:01
[K     |██████████████▌                 | 952 kB 7.0 MB/s eta 0:00:01
[K     |██████████████▋                 | 962 kB 7.0 MB/s eta 0:00:01
[K     |██████████████▊                 | 972 kB 7.0 MB/s eta 0:00:01
[K     |███████████████                 | 983 kB 7.0 MB/s eta 0:00:01
[K     |███████████████                 | 993 kB 7.0 MB/s eta 0:00:01
[K     |███████████████▎                | 1.0 MB 7.0 MB/s eta 0:00:01
[K     |███████████████▍                | 1.0 MB 7.0 MB/s eta 0:00:01
[K     |███████████████▌                | 1.0 MB 7.0 MB/s eta 0:00:01
[K     |███████████████▊                | 1.0 MB 7.0 MB/s eta 0:00:01
[K     |███████████████▉                | 1.0 MB 7.0 MB/s eta 0:00:01
[K     |████████████████                | 1.1 MB 7.0 MB/s eta 0:00:01
[K     |████████████████▏               | 1.1 MB 7.0 MB/s eta 0:00:01
[K     |████████████████▎               | 1.1 MB 7.0 MB/s eta 0:00:01
[K     |████████████████▌               | 1.1 MB 7.0 MB/s eta 0:00:01
[K     |████████████████▋               | 1.1 MB 7.0 MB/s eta 0:00:01
[K     |████████████████▉               | 1.1 MB 7.0 MB/s eta 0:00:01
[K     |█████████████████               | 1.1 MB 7.0 MB/s eta 0:00:01
[K     |█████████████████               | 1.1 MB 7.0 MB/s eta 0:00:01
[K     |█████████████████▎              | 1.1 MB 7.0 MB/s eta 0:00:01
[K     |█████████████████▍              | 1.1 MB 7.0 MB/s eta 0:00:01
[K     |█████████████████▋              | 1.2 MB 7.0 MB/s eta 0:00:01
[K     |█████████████████▊              | 1.2 MB 7.0 MB/s eta 0:00:01
[K     |█████████████████▉              | 1.2 MB 7.0 MB/s eta 0:00:01
[K     |██████████████████              | 1.2 MB 7.0 MB/s eta 0:00:01
[K     |██████████████████▏             | 1.2 MB 7.0 MB/s eta 0:00:01
[K     |██████████████████▍             | 1.2 MB 7.0 MB/s eta 0:00:01
[K     |██████████████████▌             | 1.2 MB 7.0 MB/s eta 0:00:01
[K     |██████████████████▋             | 1.2 MB 7.0 MB/s eta 0:00:01
[K     |██████████████████▉             | 1.2 MB 7.0 MB/s eta 0:00:01
[K     |███████████████████             | 1.2 MB 7.0 MB/s eta 0:00:01
[K     |███████████████████▏            | 1.3 MB 7.0 MB/s eta 0:00:01
[K     |███████████████████▎            | 1.3 MB 7.0 MB/s eta 0:00:01
[K     |███████████████████▍            | 1.3 MB 7.0 MB/s eta 0:00:01
[K     |███████████████████▋            | 1.3 MB 7.0 MB/s eta 0:00:01
[K     |███████████████████▊            | 1.3 MB 7.0 MB/s eta 0:00:01
[K     |████████████████████            | 1.3 MB 7.0 MB/s eta 0:00:01
[K     |████████████████████            | 1.3 MB 7.0 MB/s eta 0:00:01
[K     |████████████████████▏           | 1.3 MB 7.0 MB/s eta 0:00:01
[K     |████████████████████▍           | 1.3 MB 7.0 MB/s eta 0:00:01
[K     |████████████████████▌           | 1.4 MB 7.0 MB/s eta 0:00:01
[K     |████████████████████▊           | 1.4 MB 7.0 MB/s eta 0:00:01
[K     |████████████████████▉           | 1.4 MB 7.0 MB/s eta 0:00:01
[K     |█████████████████████           | 1.4 MB 7.0 MB/s eta 0:00:01
[K     |█████████████████████▏          | 1.4 MB 7.0 MB/s eta 0:00:01
[K     |█████████████████████▎          | 1.4 MB 7.0 MB/s eta 0:00:01
[K     |█████████████████████▌          | 1.4 MB 7.0 MB/s eta 0:00:01
[K     |█████████████████████▋          | 1.4 MB 7.0 MB/s eta 0:00:01
[K     |█████████████████████▊          | 1.4 MB 7.0 MB/s eta 0:00:01
[K     |██████████████████████          | 1.4 MB 7.0 MB/s eta 0:00:01
[K     |██████████████████████          | 1.5 MB 7.0 MB/s eta 0:00:01
[K     |██████████████████████▎         | 1.5 MB 7.0 MB/s eta 0:00:01
[K     |██████████████████████▍         | 1.5 MB 7.0 MB/s eta 0:00:01
[K     |██████████████████████▌         | 1.5 MB 7.0 MB/s eta 0:00:01
[K     |██████████████████████▊         | 1.5 MB 7.0 MB/s eta 0:00:01
[K     |██████████████████████▉         | 1.5 MB 7.0 MB/s eta 0:00:01
[K     |███████████████████████         | 1.5 MB 7.0 MB/s eta 0:00:01
[K     |███████████████████████▏        | 1.5 MB 7.0 MB/s eta 0:00:01
[K     |███████████████████████▎        | 1.5 MB 7.0 MB/s eta 0:00:01
[K     |███████████████████████▌        | 1.5 MB 7.0 MB/s eta 0:00:01
[K     |███████████████████████▋        | 1.6 MB 7.0 MB/s eta 0:00:01
[K     |███████████████████████▉        | 1.6 MB 7.0 MB/s eta 0:00:01
[K     |████████████████████████        | 1.6 MB 7.0 MB/s eta 0:00:01
[K     |████████████████████████        | 1.6 MB 7.0 MB/s eta 0:00:01
[K     |████████████████████████▎       | 1.6 MB 7.0 MB/s eta 0:00:01
[K     |████████████████████████▍       | 1.6 MB 7.0 MB/s eta 0:00:01
[K     |████████████████████████▋       | 1.6 MB 7.0 MB/s eta 0:00:01
[K     |████████████████████████▊       | 1.6 MB 7.0 MB/s eta 0:00:01
[K     |████████████████████████▉       | 1.6 MB 7.0 MB/s eta 0:00:01
[K     |█████████████████████████       | 1.6 MB 7.0 MB/s eta 0:00:01
[K     |█████████████████████████▏      | 1.7 MB 7.0 MB/s eta 0:00:01
[K     |█████████████████████████▍      | 1.7 MB 7.0 MB/s eta 0:00:01
[K     |█████████████████████████▌      | 1.7 MB 7.0 MB/s eta 0:00:01
[K     |█████████████████████████▋      | 1.7 MB 7.0 MB/s eta 0:00:01
[K     |█████████████████████████▉      | 1.7 MB 7.0 MB/s eta 0:00:01
[K     |██████████████████████████      | 1.7 MB 7.0 MB/s eta 0:00:01
[K     |██████████████████████████▏     | 1.7 MB 7.0 MB/s eta 0:00:01
[K     |██████████████████████████▎     | 1.7 MB 7.0 MB/s eta 0:00:01
[K     |██████████████████████████▍     | 1.7 MB 7.0 MB/s eta 0:00:01
[K     |██████████████████████████▋     | 1.8 MB 7.0 MB/s eta 0:00:01
[K     |██████████████████████████▊     | 1.8 MB 7.0 MB/s eta 0:00:01
[K     |███████████████████████████     | 1.8 MB 7.0 MB/s eta 0:00:01
[K     |███████████████████████████     | 1.8 MB 7.0 MB/s eta 0:00:01
[K     |███████████████████████████▏    | 1.8 MB 7.0 MB/s eta 0:00:01
[K     |███████████████████████████▍    | 1.8 MB 7.0 MB/s eta 0:00:01
[K     |███████████████████████████▌    | 1.8 MB 7.0 MB/s eta 0:00:01
[K     |███████████████████████████▊    | 1.8 MB 7.0 MB/s eta 0:00:01
[K     |███████████████████████████▉    | 1.8 MB 7.0 MB/s eta 0:00:01
[K     |████████████████████████████    | 1.8 MB 7.0 MB/s eta 0:00:01
[K     |████████████████████████████▏   | 1.9 MB 7.0 MB/s eta 0:00:01
[K     |████████████████████████████▎   | 1.9 MB 7.0 MB/s eta 0:00:01
[K     |████████████████████████████▌   | 1.9 MB 7.0 MB/s eta 0:00:01
[K     |████████████████████████████▋   | 1.9 MB 7.0 MB/s eta 0:00:01
[K     |████████████████████████████▊   | 1.9 MB 7.0 MB/s eta 0:00:01
[K     |█████████████████████████████   | 1.9 MB 7.0 MB/s eta 0:00:01
[K     |█████████████████████████████   | 1.9 MB 7.0 MB/s eta 0:00:01
[K     |█████████████████████████████▎  | 1.9 MB 7.0 MB/s eta 0:00:01
[K     |█████████████████████████████▍  | 1.9 MB 7.0 MB/s eta 0:00:01
[K     |█████████████████████████████▌  | 1.9 MB 7.0 MB/s eta 0:00:01
[K     |█████████████████████████████▊  | 2.0 MB 7.0 MB/s eta 0:00:01
[K     |█████████████████████████████▉  | 2.0 MB 7.0 MB/s eta 0:00:01
[K     |██████████████████████████████  | 2.0 MB 7.0 MB/s eta 0:00:01
[K     |██████████████████████████████▏ | 2.0 MB 7.0 MB/s eta 0:00:01
[K     |██████████████████████████████▎ | 2.0 MB 7.0 MB/s eta 0:00:01
[K     |██████████████████████████████▌ | 2.0 MB 7.0 MB/s eta 0:00:01
[K     |██████████████████████████████▋ | 2.0 MB 7.0 MB/s eta 0:00:01
[K     |██████████████████████████████▉ | 2.0 MB 7.0 MB/s eta 0:00:01
[K     |███████████████████████████████ | 2.0 MB 7.0 MB/s eta 0:00:01
[K     |███████████████████████████████ | 2.0 MB 7.0 MB/s eta 0:00:01
[K     |███████████████████████████████▎| 2.1 MB 7.0 MB/s eta 0:00:01
[K     |███████████████████████████████▍| 2.1 MB 7.0 MB/s eta 0:00:01
[K     |███████████████████████████████▋| 2.1 MB 7.0 MB/s eta 0:00:01
[K     |███████████████████████████████▊| 2.1 MB 7.0 MB/s eta 0:00:01
[K     |███████████████████████████████▉| 2.1 MB 7.0 MB/s eta 0:00:01
[K     |████████████████████████████████| 2.1 MB 7.0 MB/s 
[?25hInstalling collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.0.2
    Not uninstalling pip at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'pip'. No files were found to uninstall.
Successfully installed pip-23.3.1
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Running /platform/source/s01/v4_enggpt/m11100022/m11100022_q17_t0.sh
/platform/source/s01/v4_enggpt/m11100022/m11100022_q17_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4_enggpt/m11100022/m11100022_q17_t0.sh: line 5: sudo: command not found
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRunning /platform/source/s01/v4_enggpt/m11100022/m11100022_q18_t0.sh

0% [Working]
0% [Connecting to ports.ubuntu.com (185.125.190.39)]
                                                    
Hit:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease

                                                    
0% [Working]
            
Get:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease [114 kB]

0% [2 InRelease 1239 B/114 kB 1%]
0% [2 InRelease 15.7 kB/114 kB 14%]
                                   
0% [Working]
0% [Waiting for headers]
                        
Hit:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease

                        
0% [Working]
0% [Waiting for headers]
                        
Hit:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease

                        
0% [Working]
21% [Waiting for headers]
                         
Get:5 http://ports.ubuntu.com/ubuntu-ports focal-updates/main arm64 Packages [2804 kB]

21% [5 Packages 5581 B/2804 kB 0%]
                                  
74% [Waiting for headers]
                         
Get:6 http://ports.ubuntu.com/ubuntu-ports focal-updates/universe arm64 Packages [1328 kB]

81% [6 Packages 393 kB/1328 kB 30%]
81% [5 Packages store 0 B] [6 Packages 393 kB/1328 kB 30%]
                                                          
99% [5 Packages store 0 B]
                          
99% [Working]
99% [6 Packages store 0 B]
                          
100% [Working]
              
Fetched 4246 kB in 2s (2099 kB/s)

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 60%

Reading package lists... 60%

Reading package lists... 61%

Reading package lists... 61%

Reading package lists... 74%

Reading package lists... 74%

Reading package lists... 75%

Reading package lists... 75%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... Done


Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 60%

Reading package lists... 60%

Reading package lists... 61%

Reading package lists... 61%

Reading package lists... 74%

Reading package lists... 74%

Reading package lists... 75%

Reading package lists... 75%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... Done


Building dependency tree... 0%

Building dependency tree... 0%

Building dependency tree... 50%

Building dependency tree... 50%

Building dependency tree       


Reading state information... 0%

Reading state information... 0%

Reading state information... Done

python3 is already the newest version (3.8.2-0ubuntu2).
python3 set to manually installed.
python3-pip is already the newest version (20.0.2-5ubuntu1.10).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRunning /platform/source/s01/v4_enggpt/m11100022/m11100022_q19_t0.sh

0% [Working]
            
Hit:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease

0% [Waiting for headers]
                        
Hit:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease

0% [Waiting for headers]
0% [Waiting for headers]
0% [Waiting for headers]
                        
Hit:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease

                        
0% [Working]
0% [Waiting for headers]
                        
Hit:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease

                        
0% [Working]
20% [Working]
             

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 60%

Reading package lists... 60%

Reading package lists... 61%

Reading package lists... 61%

Reading package lists... 72%

Reading package lists... 74%

Reading package lists... 74%

Reading package lists... 75%

Reading package lists... 75%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... Done


Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 60%

Reading package lists... 60%

Reading package lists... 61%

Reading package lists... 61%

Reading package lists... 74%

Reading package lists... 74%

Reading package lists... 75%

Reading package lists... 75%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... Done


Building dependency tree... 0%

Building dependency tree... 0%

Building dependency tree... 50%

Building dependency tree... 50%

Building dependency tree       


Reading state information... 0%

Reading state information... 0%

Reading state information... Done

Note, selecting 'python3-pip' instead of 'pip'
python3 is already the newest version (3.8.2-0ubuntu2).
python3-pip is already the newest version (20.0.2-5ubuntu1.10).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRunning /platform/source/s01/v4_enggpt/m11100022/m11100022_q1_t0.sh
Running /platform/source/s01/v4_enggpt/m11100022/m11100022_q20_t0.sh
/platform/source/s01/v4_enggpt/m11100022/m11100022_q20_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4_enggpt/m11100022/m11100022_q20_t0.sh: line 7: sudo: command not found
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: direct-redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct-redis) (3.4.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRunning /platform/source/s01/v4_enggpt/m11100022/m11100022_q21_t0.sh
/platform/source/s01/v4_enggpt/m11100022/m11100022_q21_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4_enggpt/m11100022/m11100022_q21_t0.sh: line 5: sudo: command not found
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRunning /platform/source/s01/v4_enggpt/m11100022/m11100022_q22_t0.sh
/platform/source/s01/v4_enggpt/m11100022/m11100022_q22_t0.sh: line 5: sudo: command not found
/platform/source/s01/v4_enggpt/m11100022/m11100022_q22_t0.sh: line 8: sudo: command not found
/platform/source/s01/v4_enggpt/m11100022/m11100022_q22_t0.sh: line 9: sudo: command not found
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRequirement already satisfied: direct-redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct-redis) (3.4.1)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRequirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRunning /platform/source/s01/v4_enggpt/m11100022/m11100022_q2_t0.sh
/platform/source/s01/v4_enggpt/m11100022/m11100022_q2_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4_enggpt/m11100022/m11100022_q2_t0.sh: line 5: sudo: command not found
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRunning /platform/source/s01/v4_enggpt/m11100022/m11100022_q3_t0.sh
/platform/source/s01/v4_enggpt/m11100022/m11100022_q3_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4_enggpt/m11100022/m11100022_q3_t0.sh: line 5: sudo: command not found
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRunning /platform/source/s01/v4_enggpt/m11100022/m11100022_q4_t0.sh

0% [Working]
            
Hit:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease

0% [Working]
0% [Waiting for headers]
                        
Hit:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease

                        
0% [Working]
0% [Waiting for headers]
                        
Hit:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease

                        
0% [Working]
0% [Waiting for headers]
                        
Hit:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease

                        
0% [Working]
20% [Working]
             

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 60%

Reading package lists... 60%

Reading package lists... 61%

Reading package lists... 61%

Reading package lists... 74%

Reading package lists... 74%

Reading package lists... 75%

Reading package lists... 75%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... Done


Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 60%

Reading package lists... 60%

Reading package lists... 61%

Reading package lists... 61%

Reading package lists... 74%

Reading package lists... 74%

Reading package lists... 75%

Reading package lists... 75%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... Done


Building dependency tree... 0%

Building dependency tree... 0%

Building dependency tree... 50%

Building dependency tree... 50%

Building dependency tree       


Reading state information... 0%

Reading state information... 0%

Reading state information... Done

python3 is already the newest version (3.8.2-0ubuntu2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 60%

Reading package lists... 60%

Reading package lists... 61%

Reading package lists... 61%

Reading package lists... 74%

Reading package lists... 74%

Reading package lists... 75%

Reading package lists... 75%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... Done


Building dependency tree... 0%

Building dependency tree... 0%

Building dependency tree... 50%

Building dependency tree... 50%

Building dependency tree       


Reading state information... 0%

Reading state information... 0%

Reading state information... Done

python3-pip is already the newest version (20.0.2-5ubuntu1.10).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRequirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRunning /platform/source/s01/v4_enggpt/m11100022/m11100022_q5_t0.sh
/platform/source/s01/v4_enggpt/m11100022/m11100022_q5_t0.sh: line 5: sudo: command not found
/platform/source/s01/v4_enggpt/m11100022/m11100022_q5_t0.sh: line 8: sudo: command not found
/platform/source/s01/v4_enggpt/m11100022/m11100022_q5_t0.sh: line 11: sudo: command not found
/platform/source/s01/v4_enggpt/m11100022/m11100022_q5_t0.sh: line 14: sudo: command not found
/platform/source/s01/v4_enggpt/m11100022/m11100022_q5_t0.sh: line 17: sudo: command not found
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt install python3.8-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: ['/venv/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']

/platform/source/s01/v4_enggpt/m11100022/m11100022_q5_t0.sh: line 21: venv/bin/activate: No such file or directory
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0m/platform/source/s01/v4_enggpt/m11100022/m11100022_q5_t0.sh: line 27: deactivate: command not found
Running /platform/source/s01/v4_enggpt/m11100022/m11100022_q6_t0.sh

0% [Working]
            
Hit:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease

0% [Working]
0% [Waiting for headers]
                        
Hit:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease

                        
0% [Working]
0% [Waiting for headers]
                        
Hit:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease

                        
0% [Working]
0% [Waiting for headers]
0% [Waiting for headers]
0% [Waiting for headers]
0% [Waiting for headers]
0% [Waiting for headers]
                        
Hit:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease

                        
0% [Working]
20% [Working]
             

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 60%

Reading package lists... 60%

Reading package lists... 61%

Reading package lists... 61%

Reading package lists... 74%

Reading package lists... 74%

Reading package lists... 75%

Reading package lists... 75%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... Done


Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 60%

Reading package lists... 60%

Reading package lists... 61%

Reading package lists... 61%

Reading package lists... 74%

Reading package lists... 74%

Reading package lists... 75%

Reading package lists... 75%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... Done


Building dependency tree... 0%

Building dependency tree... 0%

Building dependency tree... 50%

Building dependency tree... 50%

Building dependency tree       


Reading state information... 0%

Reading state information... 0%

Reading state information... Done


Calculating upgrade... 0%

Calculating upgrade... 50%

Calculating upgrade... Done

0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mCollecting git+https://github.com/your-repo/direct_redis.git
  Cloning https://github.com/your-repo/direct_redis.git to /tmp/pip-req-build-9z1f5zp_
[31m  ERROR: Error [Errno 2] No such file or directory: 'git' while executing command git version[0m[31m
[0m[31mERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?[0m[31m
[0mRunning /platform/source/s01/v4_enggpt/m11100022/m11100022_q7_t0.sh
/platform/source/s01/v4_enggpt/m11100022/m11100022_q7_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4_enggpt/m11100022/m11100022_q7_t0.sh: line 5: sudo: command not found
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: direct-redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct-redis) (3.4.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRunning /platform/source/s01/v4_enggpt/m11100022/m11100022_q8_t0.sh
/platform/source/s01/v4_enggpt/m11100022/m11100022_q8_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4_enggpt/m11100022/m11100022_q8_t0.sh: line 7: sudo: command not found
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: redis in /usr/local/lib/python3.8/dist-packages (3.4.1)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRunning /platform/source/s01/v4_enggpt/m11100022/m11100022_q9_t0.sh
/platform/source/s01/v4_enggpt/m11100022/m11100022_q9_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4_enggpt/m11100022/m11100022_q9_t0.sh: line 5: sudo: command not found
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: redis<4 in /usr/local/lib/python3.8/dist-packages (3.4.1)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mpython /dbknitter/dbknitter/grader.py /platform/source/s01/v4_enggpt/m11100022/m11100022_q10_t0.py /platform/output/s01/v4_enggpt/m11100022/m11100022_q10_t0.csv /platform/expected/s01/q10.csv
/platform/source/s01/v4_enggpt/m11100022/m11100022_q10_t0.py:19: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  customer_df = pd.read_sql(customer_query, mysql_conn)
Traceback (most recent call last):
  File "/platform/source/s01/v4_enggpt/m11100022/m11100022_q10_t0.py", line 34, in <module>
    orders_df = pd.read_json(redis_conn.get('orders'))
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_enggpt/m11100022/m11100022_q11_t0.py /platform/output/s01/v4_enggpt/m11100022/m11100022_q11_t0.csv /platform/expected/s01/q11.csv
>>> Expected ((2541, 2))
      PS_PARTKEY        VALUE
0          12098  16227681.21
1           5134  15709338.52
2          13334  15023662.41
3          17052  14351644.20
4           3452  14070870.14
...          ...          ...
2536       19870   1007919.36
2537       18564   1007416.20
2538       10179   1004920.00
2539         883   1004650.68
2540        3627   1004461.04

[2541 rows x 2 columns]

>>> Actual ((0, 2))
Empty DataFrame
Columns: [PARTKEY, TOTAL_VALUE]
Index: []

Score.fail_wrong_output
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_enggpt/m11100022/m11100022_q12_t0.py /platform/output/s01/v4_enggpt/m11100022/m11100022_q12_t0.csv /platform/expected/s01/q12.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_enggpt/m11100022/m11100022_q12_t0.py", line 12, in <module>
    orders_df = pd.read_json(redis_connection.get('orders'))
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_enggpt/m11100022/m11100022_q13_t0.py /platform/output/s01/v4_enggpt/m11100022/m11100022_q13_t0.csv /platform/expected/s01/q13.csv
/platform/source/s01/v4_enggpt/m11100022/m11100022_q13_t0.py:16: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  customers_df = pd.read_sql(customer_query, mysql_conn)
Traceback (most recent call last):
  File "/platform/source/s01/v4_enggpt/m11100022/m11100022_q13_t0.py", line 26, in <module>
    orders_df = pd.read_json(orders_df_raw)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_enggpt/m11100022/m11100022_q14_t0.py /platform/output/s01/v4_enggpt/m11100022/m11100022_q14_t0.csv /platform/expected/s01/q14.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_enggpt/m11100022/m11100022_q14_t0.py", line 25, in <module>
    lineitem_df = pd.read_json(redis_client.get('lineitem'), orient='records')
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_enggpt/m11100022/m11100022_q15_t0.py /platform/output/s01/v4_enggpt/m11100022/m11100022_q15_t0.csv /platform/expected/s01/q15.csv
/platform/source/s01/v4_enggpt/m11100022/m11100022_q15_t0.py:16: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_supplier = pd.read_sql(supplier_query, mysql_connection)
Traceback (most recent call last):
  File "/platform/source/s01/v4_enggpt/m11100022/m11100022_q15_t0.py", line 23, in <module>
    df_lineitem = pd.read_json(redis_connection.get('lineitem'), orient='records')
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_enggpt/m11100022/m11100022_q16_t0.py /platform/output/s01/v4_enggpt/m11100022/m11100022_q16_t0.csv /platform/expected/s01/q16.csv
>>> Expected ((2762, 4))
       P_BRAND  P_SIZE                  P_TYPE  SUPPLIER_CNT
0     Brand#14      45   SMALL ANODIZED NICKEL            12
1     Brand#22      19   SMALL BURNISHED BRASS            12
2     Brand#25      14   PROMO POLISHED COPPER            12
3     Brand#35      45    LARGE ANODIZED STEEL            12
4     Brand#35       9    PROMO BRUSHED COPPER            12
...        ...     ...                     ...           ...
2757  Brand#22      19     PROMO BRUSHED BRASS             3
2758  Brand#22      14  PROMO BURNISHED COPPER             3
2759  Brand#43      23  STANDARD BRUSHED BRASS             3
2760  Brand#44       9  MEDIUM ANODIZED NICKEL             3
2761  Brand#53      49  MEDIUM BURNISHED BRASS             3

[2762 rows x 4 columns]

>>> Actual ((2762, 4))
       P_BRAND  P_SIZE                    P_TYPE  SUPPLIER_CNT
0     Brand#14      45     SMALL ANODIZED NICKEL             3
1     Brand#22      19     SMALL BURNISHED BRASS             3
2     Brand#25      14     PROMO POLISHED COPPER             3
3     Brand#35      45      LARGE ANODIZED STEEL             3
4     Brand#35       9      PROMO BRUSHED COPPER             3
...        ...     ...                       ...           ...
2757  Brand#55      19  STANDARD POLISHED COPPER             1
2758  Brand#55      36  STANDARD POLISHED COPPER             1
2759  Brand#55      14  STANDARD POLISHED NICKEL             1
2760  Brand#55       9   STANDARD POLISHED STEEL             1
2761  Brand#55      36   STANDARD POLISHED STEEL             1

[2762 rows x 4 columns]

Head row similarity: 0.48235106213065004
Score.fail_wrong_output
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_enggpt/m11100022/m11100022_q17_t0.py /platform/output/s01/v4_enggpt/m11100022/m11100022_q17_t0.csv /platform/expected/s01/q17.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_enggpt/m11100022/m11100022_q17_t0.py", line 17, in <module>
    lineitem_df = pd.read_json(lineitem_data)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_enggpt/m11100022/m11100022_q18_t0.py /platform/output/s01/v4_enggpt/m11100022/m11100022_q18_t0.csv /platform/expected/s01/q18.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_enggpt/m11100022/m11100022_q18_t0.py", line 25, in <module>
    cursor.execute(orders_query)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 822, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'tpch.orders' doesn't exist")
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_enggpt/m11100022/m11100022_q19_t0.py /platform/output/s01/v4_enggpt/m11100022/m11100022_q19_t0.csv /platform/expected/s01/q19.csv
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/indexes/base.py", line 3653, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'P_BRAND'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/platform/source/s01/v4_enggpt/m11100022/m11100022_q19_t0.py", line 43, in <module>
    (result['P_BRAND'] == 'Brand#12') &
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/frame.py", line 3761, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/indexes/base.py", line 3655, in get_loc
    raise KeyError(key) from err
KeyError: 'P_BRAND'
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_enggpt/m11100022/m11100022_q1_t0.py /platform/output/s01/v4_enggpt/m11100022/m11100022_q1_t0.csv /platform/expected/s01/q1.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_enggpt/m11100022/m11100022_q1_t0.py", line 11, in <module>
    lineitem = pd.read_msgpack(lineitem_df)
AttributeError: module 'pandas' has no attribute 'read_msgpack'
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_enggpt/m11100022/m11100022_q20_t0.py /platform/output/s01/v4_enggpt/m11100022/m11100022_q20_t0.csv /platform/expected/s01/q20.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_enggpt/m11100022/m11100022_q20_t0.py", line 10, in <module>
    cursor.execute("""
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 822, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'tpch.part' doesn't exist")
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_enggpt/m11100022/m11100022_q21_t0.py /platform/output/s01/v4_enggpt/m11100022/m11100022_q21_t0.csv /platform/expected/s01/q21.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_enggpt/m11100022/m11100022_q21_t0.py", line 22, in <module>
    cursor.execute("""
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 822, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'tpch.nation' doesn't exist")
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_enggpt/m11100022/m11100022_q22_t0.py /platform/output/s01/v4_enggpt/m11100022/m11100022_q22_t0.csv /platform/expected/s01/q22.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_enggpt/m11100022/m11100022_q22_t0.py", line 35, in <module>
    cursor.execute(customer_query)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 822, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'tpch.orders' doesn't exist")
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_enggpt/m11100022/m11100022_q2_t0.py /platform/output/s01/v4_enggpt/m11100022/m11100022_q2_t0.csv /platform/expected/s01/q2.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_enggpt/m11100022/m11100022_q2_t0.py", line 20, in <module>
    cursor.execute(
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 822, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'tpch.part' doesn't exist")
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_enggpt/m11100022/m11100022_q3_t0.py /platform/output/s01/v4_enggpt/m11100022/m11100022_q3_t0.csv /platform/expected/s01/q3.csv
/platform/source/s01/v4_enggpt/m11100022/m11100022_q3_t0.py:19: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  customer_df = pd.read_sql(mysql_query, mysql_conn)
/platform/source/s01/v4_enggpt/m11100022/m11100022_q3_t0.py:40: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lineitem_filtered_df['REVENUE'] = lineitem_filtered_df['L_EXTENDEDPRICE'] * (1 - lineitem_filtered_df['L_DISCOUNT'])
>>> Expected ((1216, 4))
      L_ORDERKEY O_ORDERDATE  O_SHIPPRIORITY      REVENUE
0         223140  1995-03-14               0  355369.0698
1         584291  1995-02-21               0  354494.7318
2         405063  1995-03-03               0  353125.4577
3         573861  1995-03-09               0  351238.2770
4         554757  1995-03-14               0  349181.7426
...          ...         ...             ...          ...
1211      152096  1995-01-25               0    1113.2000
1212      521728  1994-12-14               0    1013.7761
1213      445159  1994-12-06               0     949.6260
1214      598597  1994-12-03               0     939.0182
1215      135490  1994-12-20               0     934.9592

[1216 rows x 4 columns]

>>> Actual ((1216, 4))
     O_ORDERDATE  O_ORDERKEY  O_SHIPPRIORITY      REVENUE
0     1995-03-14      223140               0  355369.0698
1     1995-02-21      584291               0  354494.7318
2     1995-03-03      405063               0  353125.4577
3     1995-03-09      573861               0  351238.2770
4     1995-03-14      554757               0  349181.7426
...          ...         ...             ...          ...
1211  1995-01-25      152096               0    1113.2000
1212  1994-12-14      521728               0    1013.7761
1213  1994-12-06      445159               0     949.6260
1214  1994-12-03      598597               0     939.0182
1215  1994-12-20      135490               0     934.9592

[1216 rows x 4 columns]

Head row similarity: 0.008488063660477453
Score.success_approx_manual
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_enggpt/m11100022/m11100022_q4_t0.py /platform/output/s01/v4_enggpt/m11100022/m11100022_q4_t0.csv /platform/expected/s01/q4.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_enggpt/m11100022/m11100022_q4_t0.py", line 38, in <module>
    main()
  File "/platform/source/s01/v4_enggpt/m11100022/m11100022_q4_t0.py", line 9, in main
    orders_df = pd.read_json(connection.get("orders"))
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_enggpt/m11100022/m11100022_q5_t0.py /platform/output/s01/v4_enggpt/m11100022/m11100022_q5_t0.csv /platform/expected/s01/q5.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_enggpt/m11100022/m11100022_q5_t0.py", line 39, in <module>
    nation_region_df = pd.merge(nation_df, region_df, left_on='N_REGIONKEY', right_on='R_REGIONKEY')
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/reshape/merge.py", line 148, in merge
    op = _MergeOperation(
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/reshape/merge.py", line 737, in __init__
    ) = self._get_merge_keys()
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/reshape/merge.py", line 1221, in _get_merge_keys
    left_keys.append(left._get_label_or_level_values(lk))
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/generic.py", line 1778, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'N_REGIONKEY'
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_enggpt/m11100022/m11100022_q6_t0.py /platform/output/s01/v4_enggpt/m11100022/m11100022_q6_t0.csv /platform/expected/s01/q6.csv
/platform/source/s01/v4_enggpt/m11100022/m11100022_q6_t0.py:25: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df['REVENUE'] = filtered_df['L_EXTENDEDPRICE'] * (1 - filtered_df['L_DISCOUNT'])
>>> Expected ((1, 1))
        REVENUE
0  7.115407e+06

>>> Actual ((1, 1))
   Total_Revenue
0   1.845191e+08

Head row similarity: 0.40625
Score.fail_wrong_output
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_enggpt/m11100022/m11100022_q7_t0.py /platform/output/s01/v4_enggpt/m11100022/m11100022_q7_t0.csv /platform/expected/s01/q7.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_enggpt/m11100022/m11100022_q7_t0.py", line 25, in <module>
    cursor.execute("SELECT * FROM supplier WHERE S_NATIONKEY IN (SELECT N_NATIONKEY FROM nation WHERE N_NAME IN ('JAPAN', 'INDIA'));")
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 822, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'tpch.nation' doesn't exist")
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_enggpt/m11100022/m11100022_q8_t0.py /platform/output/s01/v4_enggpt/m11100022/m11100022_q8_t0.csv /platform/expected/s01/q8.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_enggpt/m11100022/m11100022_q8_t0.py", line 36, in <module>
    orders_df = pd.read_json(redis_client.get('orders'))
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_enggpt/m11100022/m11100022_q9_t0.py /platform/output/s01/v4_enggpt/m11100022/m11100022_q9_t0.csv /platform/expected/s01/q9.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_enggpt/m11100022/m11100022_q9_t0.py", line 31, in <module>
    orders_df = pd.read_msgpack(redis_conn.get('orders'))
AttributeError: module 'pandas' has no attribute 'read_msgpack'
Score.fail_execute
