Using MAPPING_STR=00001111, VERSION_DIR=v4_3.5
Running /platform/source/s01/v4_3.5/m00001111/m00001111_q10_t0.sh
Running /platform/source/s01/v4_3.5/m00001111/m00001111_q11_t0.sh

0% [Working]
            
Hit:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease

0% [Working]
0% [Waiting for headers]
                        
Hit:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease

                        
0% [Working]
0% [Waiting for headers]
                        
Hit:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease

                        
0% [Working]
0% [Waiting for headers]
                        
Hit:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease

                        
0% [Working]
20% [Working]
             

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 61%

Reading package lists... 61%

Reading package lists... 61%

Reading package lists... 61%

Reading package lists... 75%

Reading package lists... 75%

Reading package lists... 75%

Reading package lists... 75%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... Done


Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 61%

Reading package lists... 61%

Reading package lists... 61%

Reading package lists... 61%

Reading package lists... 75%

Reading package lists... 75%

Reading package lists... 75%

Reading package lists... 75%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... Done


Building dependency tree... 0%

Building dependency tree... 0%

Building dependency tree... 50%

Building dependency tree... 50%

Building dependency tree       


Reading state information... 0%

Reading state information... 0%

Reading state information... Done

python3 is already the newest version (3.8.2-0ubuntu2).
python3 set to manually installed.
python3-pip is already the newest version (20.0.2-5ubuntu1.10).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Running /platform/source/s01/v4_3.5/m00001111/m00001111_q12_t0.sh
Running /platform/source/s01/v4_3.5/m00001111/m00001111_q13_t0.sh
/platform/source/s01/v4_3.5/m00001111/m00001111_q13_t0.sh: line 6: sudo: command not found
/platform/source/s01/v4_3.5/m00001111/m00001111_q13_t0.sh: line 7: sudo: command not found
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Running /platform/source/s01/v4_3.5/m00001111/m00001111_q14_t0.sh
Running /platform/source/s01/v4_3.5/m00001111/m00001111_q15_t0.sh
Running /platform/source/s01/v4_3.5/m00001111/m00001111_q16_t0.sh
/platform/source/s01/v4_3.5/m00001111/m00001111_q16_t0.sh: line 5: sudo: command not found
/platform/source/s01/v4_3.5/m00001111/m00001111_q16_t0.sh: line 6: sudo: command not found
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Running /platform/source/s01/v4_3.5/m00001111/m00001111_q17_t0.sh
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4_3.5/m00001111/m00001111_q18_t0.sh
Running /platform/source/s01/v4_3.5/m00001111/m00001111_q19_t0.sh
Running /platform/source/s01/v4_3.5/m00001111/m00001111_q1_t0.sh
/platform/source/s01/v4_3.5/m00001111/m00001111_q1_t0.sh: line 3: sudo: command not found
/platform/source/s01/v4_3.5/m00001111/m00001111_q1_t0.sh: line 4: sudo: command not found
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Running /platform/source/s01/v4_3.5/m00001111/m00001111_q20_t0.sh

0% [Working]
            
Hit:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease

0% [Working]
0% [Waiting for headers]
                        
Hit:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease

0% [Waiting for headers]
0% [Waiting for headers]
                        
Hit:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease

                        
0% [Working]
0% [Waiting for headers]
                        
Hit:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease

                        
0% [Working]
20% [Working]
             

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 61%

Reading package lists... 61%

Reading package lists... 61%

Reading package lists... 61%

Reading package lists... 75%

Reading package lists... 75%

Reading package lists... 75%

Reading package lists... 75%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... Done


Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 61%

Reading package lists... 61%

Reading package lists... 61%

Reading package lists... 61%

Reading package lists... 75%

Reading package lists... 75%

Reading package lists... 75%

Reading package lists... 75%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... Done


Building dependency tree... 0%

Building dependency tree... 0%

Building dependency tree... 50%

Building dependency tree... 50%

Building dependency tree       


Reading state information... 0%

Reading state information... 0%

Reading state information... Done

The following NEW packages will be installed:
  default-mysql-client
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 3700 B of archives.
After this operation, 10.2 kB of additional disk space will be used.

0% [Working]
            
Get:1 http://ports.ubuntu.com/ubuntu-ports focal/universe arm64 default-mysql-client all 1.0.5ubuntu2 [3700 B]

0% [1 default-mysql-client 0 B/3700 B 0%]
                                         
100% [Working]
              
Fetched 3700 B in 0s (15.9 kB/s)
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package default-mysql-client.
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 14446 files and directories currently installed.)
Preparing to unpack .../default-mysql-client_1.0.5ubuntu2_all.deb ...
Unpacking default-mysql-client (1.0.5ubuntu2) ...
Setting up default-mysql-client (1.0.5ubuntu2) ...

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 61%

Reading package lists... 61%

Reading package lists... 61%

Reading package lists... 61%

Reading package lists... 75%

Reading package lists... 75%

Reading package lists... 75%

Reading package lists... 75%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... Done


Building dependency tree... 0%

Building dependency tree... 0%

Building dependency tree... 50%

Building dependency tree... 50%

Building dependency tree       


Reading state information... 0%

Reading state information... 0%

Reading state information... Done

python3 is already the newest version (3.8.2-0ubuntu2).
python3-pip is already the newest version (20.0.2-5ubuntu1.10).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Running /platform/source/s01/v4_3.5/m00001111/m00001111_q21_t0.sh
Running /platform/source/s01/v4_3.5/m00001111/m00001111_q22_t0.sh
Running /platform/source/s01/v4_3.5/m00001111/m00001111_q2_t0.sh
Running /platform/source/s01/v4_3.5/m00001111/m00001111_q3_t0.sh
/platform/source/s01/v4_3.5/m00001111/m00001111_q3_t0.sh: line 5: sudo: command not found
/platform/source/s01/v4_3.5/m00001111/m00001111_q3_t0.sh: line 8: sudo: command not found
/platform/source/s01/v4_3.5/m00001111/m00001111_q3_t0.sh: line 11: sudo: command not found
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Running /platform/source/s01/v4_3.5/m00001111/m00001111_q4_t0.sh
Running /platform/source/s01/v4_3.5/m00001111/m00001111_q5_t0.sh
/platform/source/s01/v4_3.5/m00001111/m00001111_q5_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4_3.5/m00001111/m00001111_q5_t0.sh: line 5: sudo: command not found
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4_3.5/m00001111/m00001111_q6_t0.sh
/platform/source/s01/v4_3.5/m00001111/m00001111_q6_t0.sh: line 7: sudo: command not found
/platform/source/s01/v4_3.5/m00001111/m00001111_q6_t0.sh: line 10: sudo: command not found
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Running /platform/source/s01/v4_3.5/m00001111/m00001111_q7_t0.sh
/platform/source/s01/v4_3.5/m00001111/m00001111_q7_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4_3.5/m00001111/m00001111_q7_t0.sh: line 5: sudo: command not found
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Running /platform/source/s01/v4_3.5/m00001111/m00001111_q8_t0.sh
Running /platform/source/s01/v4_3.5/m00001111/m00001111_q9_t0.sh
/platform/source/s01/v4_3.5/m00001111/m00001111_q9_t0.sh: line 6: sudo: command not found
/platform/source/s01/v4_3.5/m00001111/m00001111_q9_t0.sh: line 9: sudo: command not found
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_3.5/m00001111/m00001111_q10_t0.py /platform/output/s01/v4_3.5/m00001111/m00001111_q10_t0.csv /platform/expected/s01/q10.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_3.5/m00001111/m00001111_q10_t0.py", line 27, in <module>
    mongodb = mongo_client[tpch_mongodb_conn_info["database"]]
NameError: name 'tpch_mongodb_conn_info' is not defined
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_3.5/m00001111/m00001111_q11_t0.py /platform/output/s01/v4_3.5/m00001111/m00001111_q11_t0.csv /platform/expected/s01/q11.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_3.5/m00001111/m00001111_q11_t0.py", line 60, in <module>
    cursor.execute(
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 822, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'tpch.partsupp' doesn't exist")
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_3.5/m00001111/m00001111_q12_t0.py /platform/output/s01/v4_3.5/m00001111/m00001111_q12_t0.csv /platform/expected/s01/q12.csv
Score.fail_timeout
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_3.5/m00001111/m00001111_q13_t0.py /platform/output/s01/v4_3.5/m00001111/m00001111_q13_t0.csv /platform/expected/s01/q13.csv
  File "/platform/source/s01/v4_3.5/m00001111/m00001111_q13_t0.py", line 12
    orders = list(db.orders.find({'O_COMMENT': {'$not': /.*pending.*deposits.*/}}, {'_id': 0}))
                                                        ^
SyntaxError: invalid syntax
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_3.5/m00001111/m00001111_q14_t0.py /platform/output/s01/v4_3.5/m00001111/m00001111_q14_t0.csv /platform/expected/s01/q14.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_3.5/m00001111/m00001111_q14_t0.py", line 43, in <module>
    mysql_cursor.execute(mysql_query, part_keys)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 151, in execute
    query = self.mogrify(query, args)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 129, in mogrify
    query = query % self._escape_args(args, conn)
TypeError: not enough arguments for format string
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_3.5/m00001111/m00001111_q15_t0.py /platform/output/s01/v4_3.5/m00001111/m00001111_q15_t0.csv /platform/expected/s01/q15.csv
>>> Expected ((1, 5))
               S_ADDRESS              S_NAME          S_PHONE  S_SUPPKEY  TOTAL_REVENUE
0  8mhrffG7D2WJBSQbOGstQ  Supplier#000000677  23-290-639-3315        677   1.614410e+06

>>> Actual ((1, 5))
               S_ADDRESS              S_NAME          S_PHONE  S_SUPPKEY  TOTAL_REVENUE
0  8mhrffG7D2WJBSQbOGstQ  Supplier#000000677  23-290-639-3315        677   1.614410e+06

Score.success
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_3.5/m00001111/m00001111_q16_t0.py /platform/output/s01/v4_3.5/m00001111/m00001111_q16_t0.csv /platform/expected/s01/q16.csv
>>> Expected ((2762, 4))
       P_BRAND  P_SIZE                  P_TYPE  SUPPLIER_CNT
0     Brand#14      45   SMALL ANODIZED NICKEL            12
1     Brand#22      19   SMALL BURNISHED BRASS            12
2     Brand#25      14   PROMO POLISHED COPPER            12
3     Brand#35      45    LARGE ANODIZED STEEL            12
4     Brand#35       9    PROMO BRUSHED COPPER            12
...        ...     ...                     ...           ...
2757  Brand#22      19     PROMO BRUSHED BRASS             3
2758  Brand#22      14  PROMO BURNISHED COPPER             3
2759  Brand#43      23  STANDARD BRUSHED BRASS             3
2760  Brand#44       9  MEDIUM ANODIZED NICKEL             3
2761  Brand#53      49  MEDIUM BURNISHED BRASS             3

[2762 rows x 4 columns]

>>> Actual ((0, 4))
Empty DataFrame
Columns: [P_BRAND, P_SIZE, P_TYPE, SUPPLIER_CNT]
Index: []

Score.fail_wrong_output
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_3.5/m00001111/m00001111_q17_t0.py /platform/output/s01/v4_3.5/m00001111/m00001111_q17_t0.csv /platform/expected/s01/q17.csv
>>> Expected ((1, 1))
     AVG_YEARLY
0  31865.742857

>>> Actual ((1, 1))
     AVG_YEARLY
0  31865.742857

Head row similarity: 1.0
Score.success_approx
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_3.5/m00001111/m00001111_q18_t0.py /platform/output/s01/v4_3.5/m00001111/m00001111_q18_t0.csv /platform/expected/s01/q18.csv
Score.fail_timeout
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_3.5/m00001111/m00001111_q19_t0.py /platform/output/s01/v4_3.5/m00001111/m00001111_q19_t0.csv /platform/expected/s01/q19.csv
>>> Expected ((1, 1))
      REVENUE
0  168597.286

>>> Actual ((1, 1))
   REVENUE
0        0

Head row similarity: 0.5833333333333334
Score.fail_wrong_output
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_3.5/m00001111/m00001111_q1_t0.py /platform/output/s01/v4_3.5/m00001111/m00001111_q1_t0.csv /platform/expected/s01/q1.csv
>>> Expected ((4, 10))
   AVG_DISC     AVG_PRICE    AVG_QTY  COUNT_ORDER L_LINESTATUS L_RETURNFLAG  SUM_BASE_PRICE    SUM_CHARGE  SUM_DISC_PRICE  SUM_QTY
0  0.050145  36002.123829  25.537587       147790            F            A    5.320754e+09  5.256751e+09    5.054096e+09  3774200
1  0.049394  35521.326916  25.300664         3765            F            N    1.337378e+08  1.322863e+08    1.271324e+08    95257
2  0.050096  36000.924688  25.545538       292000            O            N    1.051227e+10  1.038558e+10    9.986238e+09  7459297
3  0.049989  35994.029214  25.525944       148301            F            R    5.337951e+09  5.274406e+09    5.071819e+09  3785523

>>> Actual ((0, 10))
Empty DataFrame
Columns: [AVG_DISC, AVG_PRICE, AVG_QTY, COUNT_ORDER, L_LINESTATUS, L_RETURNFLAG, SUM_BASE_PRICE, SUM_CHARGE, SUM_DISC_PRICE, SUM_QTY]
Index: []

Score.fail_wrong_output
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_3.5/m00001111/m00001111_q20_t0.py /platform/output/s01/v4_3.5/m00001111/m00001111_q20_t0.csv /platform/expected/s01/q20.csv
>>> Expected ((9, 2))
                            S_ADDRESS              S_NAME
0                         ,mEGorBfVIm  Supplier#000000157
1    YC2Acon6kjY3zj3Fbxs2k4Vdf7X0cd2F  Supplier#000000197
2                   7a9SP7qW5Yku5PvSg  Supplier#000000287
3                  FfbhyCxWvcPrO8ltp9  Supplier#000000378
4     0qwCMwobKY OcmLyfRXlagA8ukENJv,  Supplier#000000530
5       TfB,a5bfl3Ah 3Z 74GqnNs6zKVGM  Supplier#000000555
6            jj0wUYh9K3fG5Jhdhrkuy ,4  Supplier#000000557
7  pqck2ppy758TQpZCUAjPvlU55K3QjfL7Bi  Supplier#000000729
8     ij98czM 2KzWe7dDTOxB8sq0UfCdvrX  Supplier#000000935

>>> Actual ((0, 2))
Empty DataFrame
Columns: [S_ADDRESS, S_NAME]
Index: []

Score.fail_wrong_output
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_3.5/m00001111/m00001111_q21_t0.py /platform/output/s01/v4_3.5/m00001111/m00001111_q21_t0.csv /platform/expected/s01/q21.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_3.5/m00001111/m00001111_q21_t0.py", line 22, in <module>
    supplier_data = {row[1]: row[0] for row in mysql_cursor.fetchall() if row[2] in supplier_data}
  File "/platform/source/s01/v4_3.5/m00001111/m00001111_q21_t0.py", line 22, in <dictcomp>
    supplier_data = {row[1]: row[0] for row in mysql_cursor.fetchall() if row[2] in supplier_data}
NameError: name 'supplier_data' is not defined
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_3.5/m00001111/m00001111_q22_t0.py /platform/output/s01/v4_3.5/m00001111/m00001111_q22_t0.csv /platform/expected/s01/q22.csv
>>> Expected ((4, 3))
   CNTRYCODE  NUMCUST  TOTACCTBAL
0         20       91   666158.10
1         21      101   760953.55
2         22      106   759804.81
3         30       87   646748.02

>>> Actual ((4, 3))
   CNTRYCODE  NUMCUST  TOTACCTBAL
0         20       91   666158.10
1         21      101   760953.55
2         22      106   759804.81
3         30       87   646748.02

Head row similarity: 1.0
Score.success_approx
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_3.5/m00001111/m00001111_q2_t0.py /platform/output/s01/v4_3.5/m00001111/m00001111_q2_t0.csv /platform/expected/s01/q2.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_3.5/m00001111/m00001111_q2_t0.py", line 19, in <module>
    cursor.execute("""
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 822, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'tpch.partsupp' doesn't exist")
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_3.5/m00001111/m00001111_q3_t0.py /platform/output/s01/v4_3.5/m00001111/m00001111_q3_t0.csv /platform/expected/s01/q3.csv
Score.fail_timeout
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_3.5/m00001111/m00001111_q4_t0.py /platform/output/s01/v4_3.5/m00001111/m00001111_q4_t0.csv /platform/expected/s01/q4.csv
Score.fail_timeout
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_3.5/m00001111/m00001111_q5_t0.py /platform/output/s01/v4_3.5/m00001111/m00001111_q5_t0.csv /platform/expected/s01/q5.csv
/platform/source/s01/v4_3.5/m00001111/m00001111_q5_t0.py:36: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  mysql_df = pd.read_sql(mysql_query, mysql_conn)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/sql.py", line 2202, in execute
    cur.execute(sql, *args)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 822, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'l_extendedprice' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/platform/source/s01/v4_3.5/m00001111/m00001111_q5_t0.py", line 36, in <module>
    mysql_df = pd.read_sql(mysql_query, mysql_conn)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/sql.py", line 635, in read_sql
    return pandas_sql.read_query(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/sql.py", line 2266, in read_query
    cursor = self.execute(sql, params)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/sql.py", line 2214, in execute
    raise ex from exc
pandas.errors.DatabaseError: Execution failed on sql '
SELECT
    n.N_NAME,
    s.S_NATIONKEY,
    SUM(l_extendedprice * (1 - l_discount)) AS revenue
FROM
    nation n JOIN region r ON n.N_REGIONKEY = r.R_REGIONKEY
             JOIN supplier s ON s.S_NATIONKEY = n.N_NATIONKEY
WHERE
    r.R_NAME = 'ASIA'
GROUP BY
    n.N_NAME, s.S_NATIONKEY
ORDER BY
    revenue DESC
': (1054, "Unknown column 'l_extendedprice' in 'field list'")
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_3.5/m00001111/m00001111_q6_t0.py /platform/output/s01/v4_3.5/m00001111/m00001111_q6_t0.csv /platform/expected/s01/q6.csv
>>> Expected ((1, 1))
        REVENUE
0  7.115407e+06

>>> Actual ((1, 1))
        REVENUE
0  1.180342e+07

Head row similarity: 0.8064516129032258
Score.success_approx_manual
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_3.5/m00001111/m00001111_q7_t0.py /platform/output/s01/v4_3.5/m00001111/m00001111_q7_t0.csv /platform/expected/s01/q7.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_3.5/m00001111/m00001111_q7_t0.py", line 48, in <module>
    'C_NATIONKEY': {'$in': [sn[1] for sn in suppliers_nations.values()]},
  File "/platform/source/s01/v4_3.5/m00001111/m00001111_q7_t0.py", line 48, in <listcomp>
    'C_NATIONKEY': {'$in': [sn[1] for sn in suppliers_nations.values()]},
TypeError: 'int' object is not subscriptable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_3.5/m00001111/m00001111_q8_t0.py /platform/output/s01/v4_3.5/m00001111/m00001111_q8_t0.csv /platform/expected/s01/q8.csv
/platform/source/s01/v4_3.5/m00001111/m00001111_q8_t0.py:10: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(query, connection)
/platform/source/s01/v4_3.5/m00001111/m00001111_q8_t0.py:75: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_data['VOLUME'] = filtered_data['L_EXTENDEDPRICE'] * (1 - filtered_data['L_DISCOUNT'])
/platform/source/s01/v4_3.5/m00001111/m00001111_q8_t0.py:76: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_data['O_YEAR'] = filtered_data['O_ORDERDATE'].apply(lambda x: datetime.strptime(x, "%Y-%m-%d").strftime('%Y'))
>>> Expected ((2, 2))
   MKT_SHARE  O_YEAR
0   0.035052    1995
1   0.051395    1996

>>> Actual ((2, 2))
   MKT_SHARE  O_YEAR
0   0.136792    1995
1   0.152652    1996

Head row similarity: 0.8709677419354839
Score.success_approx
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_3.5/m00001111/m00001111_q9_t0.py /platform/output/s01/v4_3.5/m00001111/m00001111_q9_t0.csv /platform/expected/s01/q9.csv
>>> Expected ((175, 3))
      NATION  O_YEAR    SUM_PROFIT
0    ALGERIA    1998  1.906845e+06
1    ALGERIA    1997  3.613876e+06
2    ALGERIA    1996  3.288633e+06
3    ALGERIA    1995  4.044612e+06
4    ALGERIA    1994  3.872129e+06
..       ...     ...           ...
170  VIETNAM    1996  4.439577e+06
171  VIETNAM    1995  4.029092e+06
172  VIETNAM    1994  5.010489e+06
173  VIETNAM    1993  3.517661e+06
174  VIETNAM    1992  4.200779e+06

[175 rows x 3 columns]

>>> Actual ((175, 3))
      NATION  O_YEAR    SUM_PROFIT
0    ALGERIA    1992  4.215275e+06
1    ALGERIA    1993  3.405270e+06
2    ALGERIA    1994  3.872129e+06
3    ALGERIA    1995  4.044612e+06
4    ALGERIA    1996  3.288633e+06
..       ...     ...           ...
170  VIETNAM    1994  5.010489e+06
171  VIETNAM    1995  4.029092e+06
172  VIETNAM    1996  4.439577e+06
173  VIETNAM    1997  5.110349e+06
174  VIETNAM    1998  2.483165e+06

[175 rows x 3 columns]

Head row similarity: 0.6891334250343879
Score.success_approx_manual
